/**
 * Generated Box SDK operation wrappers.
 *
 * @packageDocumentation
 * @since 0.0.0
 */

// This file is generated by @beep/box/scripts/generate.ts. Do not edit manually.

import { Effect, Result } from "effect";
import { dual } from "effect/Function";
import * as P from "effect/Predicate";
import type * as S from "effect/Schema";
import type { BoxError } from "../Box.errors.ts";
import * as M from "./Box.models.gen.ts";

/**
 * Shared generated operation runner supplied by {@link Box}.
 *
 * **Example** (Reference the BoxRunSdkCall type)
 *
 * ```ts
 * import type { BoxRunSdkCall } from "@beep/box/Box.operations.gen"
 *
 * type Runner = BoxRunSdkCall
 * ```
 *
 * @category services
 * @since 0.0.0
 */
export type BoxRunSdkCall = <Payload, Success>(
  manager: string,
  method: string,
  methodName: M.BoxMethodName,
  payloadSchema: S.ConstraintDecoder<Payload>,
  successSchema: S.ConstraintDecoder<Success>,
  payload: Payload,
  invoke: (decoded: Payload, signal: AbortSignal | undefined) => Promise<unknown>
) => Effect.Effect<Success, BoxError>;

/**
 * Generated JSON operation groups for the Box SDK.
 *
 * **Example** (Reference the BoxGeneratedOperations type)
 *
 * ```ts
 * import type { BoxGeneratedOperations } from "@beep/box/Box.operations.gen"
 *
 * type Managers = keyof BoxGeneratedOperations
 * ```
 *
 * @category services
 * @since 0.0.0
 */
export type BoxGeneratedOperations = {
  readonly avatars: {
    readonly deleteUserAvatar: (payload: M.AvatarsDeleteUserAvatarPayload) => Effect.Effect<M.AvatarsDeleteUserAvatarSuccess, BoxError>;
  };
  readonly chunkedUploads: {
    readonly createFileUploadSession: (payload: M.ChunkedUploadsCreateFileUploadSessionPayload) => Effect.Effect<M.ChunkedUploadsCreateFileUploadSessionSuccess, BoxError>;
    readonly createFileUploadSessionCommit: (payload: M.ChunkedUploadsCreateFileUploadSessionCommitPayload) => Effect.Effect<M.ChunkedUploadsCreateFileUploadSessionCommitSuccess, BoxError>;
    readonly createFileUploadSessionCommitByUrl: (payload: M.ChunkedUploadsCreateFileUploadSessionCommitByUrlPayload) => Effect.Effect<M.ChunkedUploadsCreateFileUploadSessionCommitByUrlSuccess, BoxError>;
    readonly createFileUploadSessionForExistingFile: (payload: M.ChunkedUploadsCreateFileUploadSessionForExistingFilePayload) => Effect.Effect<M.ChunkedUploadsCreateFileUploadSessionForExistingFileSuccess, BoxError>;
    readonly deleteFileUploadSessionById: (payload: M.ChunkedUploadsDeleteFileUploadSessionByIdPayload) => Effect.Effect<M.ChunkedUploadsDeleteFileUploadSessionByIdSuccess, BoxError>;
    readonly deleteFileUploadSessionByUrl: (payload: M.ChunkedUploadsDeleteFileUploadSessionByUrlPayload) => Effect.Effect<M.ChunkedUploadsDeleteFileUploadSessionByUrlSuccess, BoxError>;
    readonly getFileUploadSessionById: (payload: M.ChunkedUploadsGetFileUploadSessionByIdPayload) => Effect.Effect<M.ChunkedUploadsGetFileUploadSessionByIdSuccess, BoxError>;
    readonly getFileUploadSessionByUrl: (payload: M.ChunkedUploadsGetFileUploadSessionByUrlPayload) => Effect.Effect<M.ChunkedUploadsGetFileUploadSessionByUrlSuccess, BoxError>;
    readonly getFileUploadSessionParts: (payload: M.ChunkedUploadsGetFileUploadSessionPartsPayload) => Effect.Effect<M.ChunkedUploadsGetFileUploadSessionPartsSuccess, BoxError>;
    readonly getFileUploadSessionPartsByUrl: (payload: M.ChunkedUploadsGetFileUploadSessionPartsByUrlPayload) => Effect.Effect<M.ChunkedUploadsGetFileUploadSessionPartsByUrlSuccess, BoxError>;
  };
  readonly downloads: {
    readonly getDownloadFileUrl: (payload: M.DownloadsGetDownloadFileUrlPayload) => Effect.Effect<M.DownloadsGetDownloadFileUrlSuccess, BoxError>;
  };
  readonly events: {
    readonly getEvents: (payload: M.EventsGetEventsPayload) => Effect.Effect<M.EventsGetEventsSuccess, BoxError>;
    readonly getEventsWithLongPolling: (payload: M.EventsGetEventsWithLongPollingPayload) => Effect.Effect<M.EventsGetEventsWithLongPollingSuccess, BoxError>;
  };
  readonly files: {
    readonly copyFile: (payload: M.FilesCopyFilePayload) => Effect.Effect<M.FilesCopyFileSuccess, BoxError>;
    readonly deleteFileById: (payload: M.FilesDeleteFileByIdPayload) => Effect.Effect<M.FilesDeleteFileByIdSuccess, BoxError>;
    readonly getFileById: (payload: M.FilesGetFileByIdPayload) => Effect.Effect<M.FilesGetFileByIdSuccess, BoxError>;
    readonly getFileThumbnailUrl: (payload: M.FilesGetFileThumbnailUrlPayload) => Effect.Effect<M.FilesGetFileThumbnailUrlSuccess, BoxError>;
    readonly updateFileById: (payload: M.FilesUpdateFileByIdPayload) => Effect.Effect<M.FilesUpdateFileByIdSuccess, BoxError>;
  };
  readonly folderMetadata: {
    readonly getFolderMetadata: (payload: M.FolderMetadataGetFolderMetadataPayload) => Effect.Effect<M.FolderMetadataGetFolderMetadataSuccess, BoxError>;
    readonly getFolderMetadataById: (payload: M.FolderMetadataGetFolderMetadataByIdPayload) => Effect.Effect<M.FolderMetadataGetFolderMetadataByIdSuccess, BoxError>;
  };
  readonly folders: {
    readonly copyFolder: (payload: M.FoldersCopyFolderPayload) => Effect.Effect<M.FoldersCopyFolderSuccess, BoxError>;
    readonly createFolder: (payload: M.FoldersCreateFolderPayload) => Effect.Effect<M.FoldersCreateFolderSuccess, BoxError>;
    readonly deleteFolderById: (payload: M.FoldersDeleteFolderByIdPayload) => Effect.Effect<M.FoldersDeleteFolderByIdSuccess, BoxError>;
    readonly getFolderById: (payload: M.FoldersGetFolderByIdPayload) => Effect.Effect<M.FoldersGetFolderByIdSuccess, BoxError>;
    readonly getFolderItems: (payload: M.FoldersGetFolderItemsPayload) => Effect.Effect<M.FoldersGetFolderItemsSuccess, BoxError>;
    readonly updateFolderById: (payload: M.FoldersUpdateFolderByIdPayload) => Effect.Effect<M.FoldersUpdateFolderByIdSuccess, BoxError>;
  };
  readonly listCollaborations: {
    readonly getCollaborations: (payload: M.ListCollaborationsGetCollaborationsPayload) => Effect.Effect<M.ListCollaborationsGetCollaborationsSuccess, BoxError>;
    readonly getFileCollaborations: (payload: M.ListCollaborationsGetFileCollaborationsPayload) => Effect.Effect<M.ListCollaborationsGetFileCollaborationsSuccess, BoxError>;
    readonly getFolderCollaborations: (payload: M.ListCollaborationsGetFolderCollaborationsPayload) => Effect.Effect<M.ListCollaborationsGetFolderCollaborationsSuccess, BoxError>;
    readonly getGroupCollaborations: (payload: M.ListCollaborationsGetGroupCollaborationsPayload) => Effect.Effect<M.ListCollaborationsGetGroupCollaborationsSuccess, BoxError>;
  };
  readonly metadataCascadePolicies: {
    readonly getMetadataCascadePolicies: (payload: M.MetadataCascadePoliciesGetMetadataCascadePoliciesPayload) => Effect.Effect<M.MetadataCascadePoliciesGetMetadataCascadePoliciesSuccess, BoxError>;
    readonly getMetadataCascadePolicyById: (payload: M.MetadataCascadePoliciesGetMetadataCascadePolicyByIdPayload) => Effect.Effect<M.MetadataCascadePoliciesGetMetadataCascadePolicyByIdSuccess, BoxError>;
  };
  readonly metadataTemplates: {
    readonly getEnterpriseMetadataTemplates: (payload: M.MetadataTemplatesGetEnterpriseMetadataTemplatesPayload) => Effect.Effect<M.MetadataTemplatesGetEnterpriseMetadataTemplatesSuccess, BoxError>;
    readonly getGlobalMetadataTemplates: (payload: M.MetadataTemplatesGetGlobalMetadataTemplatesPayload) => Effect.Effect<M.MetadataTemplatesGetGlobalMetadataTemplatesSuccess, BoxError>;
    readonly getMetadataTemplate: (payload: M.MetadataTemplatesGetMetadataTemplatePayload) => Effect.Effect<M.MetadataTemplatesGetMetadataTemplateSuccess, BoxError>;
    readonly getMetadataTemplateById: (payload: M.MetadataTemplatesGetMetadataTemplateByIdPayload) => Effect.Effect<M.MetadataTemplatesGetMetadataTemplateByIdSuccess, BoxError>;
    readonly getMetadataTemplatesByInstanceId: (payload: M.MetadataTemplatesGetMetadataTemplatesByInstanceIdPayload) => Effect.Effect<M.MetadataTemplatesGetMetadataTemplatesByInstanceIdSuccess, BoxError>;
  };
  readonly retentionPolicies: {
    readonly getRetentionPolicies: (payload: M.RetentionPoliciesGetRetentionPoliciesPayload) => Effect.Effect<M.RetentionPoliciesGetRetentionPoliciesSuccess, BoxError>;
    readonly getRetentionPolicyById: (payload: M.RetentionPoliciesGetRetentionPolicyByIdPayload) => Effect.Effect<M.RetentionPoliciesGetRetentionPolicyByIdSuccess, BoxError>;
  };
  readonly retentionPolicyAssignments: {
    readonly getFilesUnderRetentionPolicyAssignment: (payload: M.RetentionPolicyAssignmentsGetFilesUnderRetentionPolicyAssignmentPayload) => Effect.Effect<M.RetentionPolicyAssignmentsGetFilesUnderRetentionPolicyAssignmentSuccess, BoxError>;
    readonly getRetentionPolicyAssignmentById: (payload: M.RetentionPolicyAssignmentsGetRetentionPolicyAssignmentByIdPayload) => Effect.Effect<M.RetentionPolicyAssignmentsGetRetentionPolicyAssignmentByIdSuccess, BoxError>;
    readonly getRetentionPolicyAssignments: (payload: M.RetentionPolicyAssignmentsGetRetentionPolicyAssignmentsPayload) => Effect.Effect<M.RetentionPolicyAssignmentsGetRetentionPolicyAssignmentsSuccess, BoxError>;
  };
  readonly signRequests: {
    readonly cancelSignRequest: (payload: M.SignRequestsCancelSignRequestPayload) => Effect.Effect<M.SignRequestsCancelSignRequestSuccess, BoxError>;
    readonly createSignRequest: (payload: M.SignRequestsCreateSignRequestPayload) => Effect.Effect<M.SignRequestsCreateSignRequestSuccess, BoxError>;
    readonly getSignRequestById: (payload: M.SignRequestsGetSignRequestByIdPayload) => Effect.Effect<M.SignRequestsGetSignRequestByIdSuccess, BoxError>;
    readonly getSignRequests: (payload: M.SignRequestsGetSignRequestsPayload) => Effect.Effect<M.SignRequestsGetSignRequestsSuccess, BoxError>;
    readonly resendSignRequest: (payload: M.SignRequestsResendSignRequestPayload) => Effect.Effect<M.SignRequestsResendSignRequestSuccess, BoxError>;
  };
  readonly signTemplates: {
    readonly getSignTemplateById: (payload: M.SignTemplatesGetSignTemplateByIdPayload) => Effect.Effect<M.SignTemplatesGetSignTemplateByIdSuccess, BoxError>;
    readonly getSignTemplates: (payload: M.SignTemplatesGetSignTemplatesPayload) => Effect.Effect<M.SignTemplatesGetSignTemplatesSuccess, BoxError>;
  };
  readonly uploads: {
    readonly preflightFileUploadCheck: (payload: M.UploadsPreflightFileUploadCheckPayload) => Effect.Effect<M.UploadsPreflightFileUploadCheckSuccess, BoxError>;
  };
  readonly userCollaborations: {
    readonly createCollaboration: (payload: M.UserCollaborationsCreateCollaborationPayload) => Effect.Effect<M.UserCollaborationsCreateCollaborationSuccess, BoxError>;
    readonly deleteCollaborationById: (payload: M.UserCollaborationsDeleteCollaborationByIdPayload) => Effect.Effect<M.UserCollaborationsDeleteCollaborationByIdSuccess, BoxError>;
    readonly getCollaborationById: (payload: M.UserCollaborationsGetCollaborationByIdPayload) => Effect.Effect<M.UserCollaborationsGetCollaborationByIdSuccess, BoxError>;
    readonly updateCollaborationById: (payload: M.UserCollaborationsUpdateCollaborationByIdPayload) => Effect.Effect<M.UserCollaborationsUpdateCollaborationByIdSuccess, BoxError>;
  };
  readonly users: {
    readonly createUser: (payload: M.UsersCreateUserPayload) => Effect.Effect<M.UsersCreateUserSuccess, BoxError>;
    readonly deleteUserById: (payload: M.UsersDeleteUserByIdPayload) => Effect.Effect<M.UsersDeleteUserByIdSuccess, BoxError>;
    readonly getUserById: (payload: M.UsersGetUserByIdPayload) => Effect.Effect<M.UsersGetUserByIdSuccess, BoxError>;
    readonly getUserMe: (payload: M.UsersGetUserMePayload) => Effect.Effect<M.UsersGetUserMeSuccess, BoxError>;
    readonly getUsers: (payload: M.UsersGetUsersPayload) => Effect.Effect<M.UsersGetUsersSuccess, BoxError>;
    readonly updateUserById: (payload: M.UsersUpdateUserByIdPayload) => Effect.Effect<M.UsersUpdateUserByIdSuccess, BoxError>;
  };
  readonly webhooks: {
    readonly createWebhook: (payload: M.WebhooksCreateWebhookPayload) => Effect.Effect<M.WebhooksCreateWebhookSuccess, BoxError>;
    readonly deleteWebhookById: (payload: M.WebhooksDeleteWebhookByIdPayload) => Effect.Effect<M.WebhooksDeleteWebhookByIdSuccess, BoxError>;
    readonly getWebhookById: (payload: M.WebhooksGetWebhookByIdPayload) => Effect.Effect<M.WebhooksGetWebhookByIdSuccess, BoxError>;
    readonly getWebhooks: (payload: M.WebhooksGetWebhooksPayload) => Effect.Effect<M.WebhooksGetWebhooksSuccess, BoxError>;
    readonly updateWebhookById: (payload: M.WebhooksUpdateWebhookByIdPayload) => Effect.Effect<M.WebhooksUpdateWebhookByIdSuccess, BoxError>;
    readonly validateMessage: (payload: M.WebhooksValidateMessagePayload) => Effect.Effect<M.WebhooksValidateMessageSuccess, BoxError>;
  };
  readonly zipDownloads: {
    readonly createZipDownload: (payload: M.ZipDownloadsCreateZipDownloadPayload) => Effect.Effect<M.ZipDownloadsCreateZipDownloadSuccess, BoxError>;
    readonly getZipDownloadStatus: (payload: M.ZipDownloadsGetZipDownloadStatusPayload) => Effect.Effect<M.ZipDownloadsGetZipDownloadStatusSuccess, BoxError>;
  };
};

const readProperty = (value: unknown, key: PropertyKey): unknown => (P.isObject(value) ? Reflect.get(value, key) : undefined);

const readCancellationToken = (value: unknown): AbortSignal | undefined => {
  const token = readProperty(value, "cancellationToken");
  return token instanceof AbortSignal ? token : undefined;
};

const combineCancellationToken = (
  callerSignal: AbortSignal | undefined,
  driverSignal: AbortSignal | undefined
): AbortSignal | undefined => {
  if (callerSignal === undefined) {
    return driverSignal;
  }
  if (driverSignal === undefined || callerSignal === driverSignal) {
    return callerSignal;
  }
  return AbortSignal.any([callerSignal, driverSignal]);
};

const mergeCancellation = <A>(
  input: A | undefined,
  signal: AbortSignal | undefined
): A | { readonly cancellationToken: AbortSignal } | undefined => {
  const cancellationToken = combineCancellationToken(readCancellationToken(input), signal);
  if (cancellationToken === undefined) {
    return input;
  }
  if (P.isObject(input)) {
    return { ...input, cancellationToken };
  }
  return { cancellationToken };
};

const sdkShapeFailure = (manager: string, method: string): Promise<never> =>
  Promise.reject({
    _tag: "BoxSdkShapeError",
    manager,
    method
  });

const invokeSdkMethod = (
  client: unknown,
  manager: string,
  method: string,
  args: ReadonlyArray<unknown>
): Promise<unknown> => {
  const managerValue = readProperty(client, manager);
  const methodValue = readProperty(managerValue, method);

  if (!P.isFunction(methodValue)) {
    return sdkShapeFailure(manager, method);
  }

  const result = Result.try(() => Reflect.apply(methodValue, managerValue, args));
  return Result.match(result, {
    onFailure: (cause) => Promise.reject(cause),
    onSuccess: (value) => Promise.resolve(value)
  });
};

/**
 * Build generated Box SDK operation groups from a SDK client and shared runner.
 *
 * **Example** (Inspect the generated operations factory)
 *
 * ```ts
 * import { makeGeneratedOperations } from "@beep/box/Box.operations.gen"
 *
 * console.log(makeGeneratedOperations)
 * ```
 *
 * @category constructors
 * @since 0.0.0
 */
export const makeGeneratedOperations: {
  (runSdkCall: BoxRunSdkCall): (client: unknown) => BoxGeneratedOperations;
  (client: unknown, runSdkCall: BoxRunSdkCall): BoxGeneratedOperations;
} = dual(2, (client: unknown, runSdkCall: BoxRunSdkCall): BoxGeneratedOperations => ({
  avatars: {
    deleteUserAvatar: (payload) =>
      runSdkCall(
        "avatars",
        "deleteUserAvatar",
        "avatars.deleteUserAvatar",
        M.AvatarsDeleteUserAvatarPayload,
        M.AvatarsDeleteUserAvatarSuccess,
        payload,
        (decoded, signal) =>
          invokeSdkMethod(client, "avatars", "deleteUserAvatar", [
            decoded.userId,
            mergeCancellation(decoded.optionalsInput, signal)
          ])
      ),
  },
  chunkedUploads: {
    createFileUploadSession: (payload) =>
      runSdkCall(
        "chunkedUploads",
        "createFileUploadSession",
        "chunkedUploads.createFileUploadSession",
        M.ChunkedUploadsCreateFileUploadSessionPayload,
        M.ChunkedUploadsCreateFileUploadSessionSuccess,
        payload,
        (decoded, signal) =>
          invokeSdkMethod(client, "chunkedUploads", "createFileUploadSession", [
            decoded.requestBody,
            mergeCancellation(decoded.optionalsInput, signal)
          ])
      ),
    createFileUploadSessionCommit: (payload) =>
      runSdkCall(
        "chunkedUploads",
        "createFileUploadSessionCommit",
        "chunkedUploads.createFileUploadSessionCommit",
        M.ChunkedUploadsCreateFileUploadSessionCommitPayload,
        M.ChunkedUploadsCreateFileUploadSessionCommitSuccess,
        payload,
        (decoded, signal) =>
          invokeSdkMethod(client, "chunkedUploads", "createFileUploadSessionCommit", [
            decoded.uploadSessionId,
            decoded.requestBody,
            decoded.headersInput,
            mergeCancellation(decoded.optionalsInput, signal)
          ])
      ),
    createFileUploadSessionCommitByUrl: (payload) =>
      runSdkCall(
        "chunkedUploads",
        "createFileUploadSessionCommitByUrl",
        "chunkedUploads.createFileUploadSessionCommitByUrl",
        M.ChunkedUploadsCreateFileUploadSessionCommitByUrlPayload,
        M.ChunkedUploadsCreateFileUploadSessionCommitByUrlSuccess,
        payload,
        (decoded, signal) =>
          invokeSdkMethod(client, "chunkedUploads", "createFileUploadSessionCommitByUrl", [
            decoded.url,
            decoded.requestBody,
            decoded.headersInput,
            mergeCancellation(decoded.optionalsInput, signal)
          ])
      ),
    createFileUploadSessionForExistingFile: (payload) =>
      runSdkCall(
        "chunkedUploads",
        "createFileUploadSessionForExistingFile",
        "chunkedUploads.createFileUploadSessionForExistingFile",
        M.ChunkedUploadsCreateFileUploadSessionForExistingFilePayload,
        M.ChunkedUploadsCreateFileUploadSessionForExistingFileSuccess,
        payload,
        (decoded, signal) =>
          invokeSdkMethod(client, "chunkedUploads", "createFileUploadSessionForExistingFile", [
            decoded.fileId,
            decoded.requestBody,
            mergeCancellation(decoded.optionalsInput, signal)
          ])
      ),
    deleteFileUploadSessionById: (payload) =>
      runSdkCall(
        "chunkedUploads",
        "deleteFileUploadSessionById",
        "chunkedUploads.deleteFileUploadSessionById",
        M.ChunkedUploadsDeleteFileUploadSessionByIdPayload,
        M.ChunkedUploadsDeleteFileUploadSessionByIdSuccess,
        payload,
        (decoded, signal) =>
          invokeSdkMethod(client, "chunkedUploads", "deleteFileUploadSessionById", [
            decoded.uploadSessionId,
            mergeCancellation(decoded.optionalsInput, signal)
          ])
      ),
    deleteFileUploadSessionByUrl: (payload) =>
      runSdkCall(
        "chunkedUploads",
        "deleteFileUploadSessionByUrl",
        "chunkedUploads.deleteFileUploadSessionByUrl",
        M.ChunkedUploadsDeleteFileUploadSessionByUrlPayload,
        M.ChunkedUploadsDeleteFileUploadSessionByUrlSuccess,
        payload,
        (decoded, signal) =>
          invokeSdkMethod(client, "chunkedUploads", "deleteFileUploadSessionByUrl", [
            decoded.url,
            mergeCancellation(decoded.optionalsInput, signal)
          ])
      ),
    getFileUploadSessionById: (payload) =>
      runSdkCall(
        "chunkedUploads",
        "getFileUploadSessionById",
        "chunkedUploads.getFileUploadSessionById",
        M.ChunkedUploadsGetFileUploadSessionByIdPayload,
        M.ChunkedUploadsGetFileUploadSessionByIdSuccess,
        payload,
        (decoded, signal) =>
          invokeSdkMethod(client, "chunkedUploads", "getFileUploadSessionById", [
            decoded.uploadSessionId,
            mergeCancellation(decoded.optionalsInput, signal)
          ])
      ),
    getFileUploadSessionByUrl: (payload) =>
      runSdkCall(
        "chunkedUploads",
        "getFileUploadSessionByUrl",
        "chunkedUploads.getFileUploadSessionByUrl",
        M.ChunkedUploadsGetFileUploadSessionByUrlPayload,
        M.ChunkedUploadsGetFileUploadSessionByUrlSuccess,
        payload,
        (decoded, signal) =>
          invokeSdkMethod(client, "chunkedUploads", "getFileUploadSessionByUrl", [
            decoded.url,
            mergeCancellation(decoded.optionalsInput, signal)
          ])
      ),
    getFileUploadSessionParts: (payload) =>
      runSdkCall(
        "chunkedUploads",
        "getFileUploadSessionParts",
        "chunkedUploads.getFileUploadSessionParts",
        M.ChunkedUploadsGetFileUploadSessionPartsPayload,
        M.ChunkedUploadsGetFileUploadSessionPartsSuccess,
        payload,
        (decoded, signal) =>
          invokeSdkMethod(client, "chunkedUploads", "getFileUploadSessionParts", [
            decoded.uploadSessionId,
            mergeCancellation(decoded.optionalsInput, signal)
          ])
      ),
    getFileUploadSessionPartsByUrl: (payload) =>
      runSdkCall(
        "chunkedUploads",
        "getFileUploadSessionPartsByUrl",
        "chunkedUploads.getFileUploadSessionPartsByUrl",
        M.ChunkedUploadsGetFileUploadSessionPartsByUrlPayload,
        M.ChunkedUploadsGetFileUploadSessionPartsByUrlSuccess,
        payload,
        (decoded, signal) =>
          invokeSdkMethod(client, "chunkedUploads", "getFileUploadSessionPartsByUrl", [
            decoded.url,
            mergeCancellation(decoded.optionalsInput, signal)
          ])
      ),
  },
  downloads: {
    getDownloadFileUrl: (payload) =>
      runSdkCall(
        "downloads",
        "getDownloadFileUrl",
        "downloads.getDownloadFileUrl",
        M.DownloadsGetDownloadFileUrlPayload,
        M.DownloadsGetDownloadFileUrlSuccess,
        payload,
        (decoded, signal) =>
          invokeSdkMethod(client, "downloads", "getDownloadFileUrl", [
            decoded.fileId,
            mergeCancellation(decoded.optionalsInput, signal)
          ])
      ),
  },
  events: {
    getEvents: (payload) =>
      runSdkCall(
        "events",
        "getEvents",
        "events.getEvents",
        M.EventsGetEventsPayload,
        M.EventsGetEventsSuccess,
        payload,
        (decoded, signal) =>
          invokeSdkMethod(client, "events", "getEvents", [
            decoded.queryParams,
            decoded.headersInput,
            combineCancellationToken(decoded.cancellationToken, signal)
          ])
      ),
    getEventsWithLongPolling: (payload) =>
      runSdkCall(
        "events",
        "getEventsWithLongPolling",
        "events.getEventsWithLongPolling",
        M.EventsGetEventsWithLongPollingPayload,
        M.EventsGetEventsWithLongPollingSuccess,
        payload,
        (decoded, signal) =>
          invokeSdkMethod(client, "events", "getEventsWithLongPolling", [
            decoded.headersInput,
            combineCancellationToken(decoded.cancellationToken, signal)
          ])
      ),
  },
  files: {
    copyFile: (payload) =>
      runSdkCall(
        "files",
        "copyFile",
        "files.copyFile",
        M.FilesCopyFilePayload,
        M.FilesCopyFileSuccess,
        payload,
        (decoded, signal) =>
          invokeSdkMethod(client, "files", "copyFile", [
            decoded.fileId,
            decoded.requestBody,
            mergeCancellation(decoded.optionalsInput, signal)
          ])
      ),
    deleteFileById: (payload) =>
      runSdkCall(
        "files",
        "deleteFileById",
        "files.deleteFileById",
        M.FilesDeleteFileByIdPayload,
        M.FilesDeleteFileByIdSuccess,
        payload,
        (decoded, signal) =>
          invokeSdkMethod(client, "files", "deleteFileById", [
            decoded.fileId,
            mergeCancellation(decoded.optionalsInput, signal)
          ])
      ),
    getFileById: (payload) =>
      runSdkCall(
        "files",
        "getFileById",
        "files.getFileById",
        M.FilesGetFileByIdPayload,
        M.FilesGetFileByIdSuccess,
        payload,
        (decoded, signal) =>
          invokeSdkMethod(client, "files", "getFileById", [
            decoded.fileId,
            mergeCancellation(decoded.optionalsInput, signal)
          ])
      ),
    getFileThumbnailUrl: (payload) =>
      runSdkCall(
        "files",
        "getFileThumbnailUrl",
        "files.getFileThumbnailUrl",
        M.FilesGetFileThumbnailUrlPayload,
        M.FilesGetFileThumbnailUrlSuccess,
        payload,
        (decoded, signal) =>
          invokeSdkMethod(client, "files", "getFileThumbnailUrl", [
            decoded.fileId,
            decoded.extension,
            mergeCancellation(decoded.optionalsInput, signal)
          ])
      ),
    updateFileById: (payload) =>
      runSdkCall(
        "files",
        "updateFileById",
        "files.updateFileById",
        M.FilesUpdateFileByIdPayload,
        M.FilesUpdateFileByIdSuccess,
        payload,
        (decoded, signal) =>
          invokeSdkMethod(client, "files", "updateFileById", [
            decoded.fileId,
            mergeCancellation(decoded.optionalsInput, signal)
          ])
      ),
  },
  folderMetadata: {
    getFolderMetadata: (payload) =>
      runSdkCall(
        "folderMetadata",
        "getFolderMetadata",
        "folderMetadata.getFolderMetadata",
        M.FolderMetadataGetFolderMetadataPayload,
        M.FolderMetadataGetFolderMetadataSuccess,
        payload,
        (decoded, signal) =>
          invokeSdkMethod(client, "folderMetadata", "getFolderMetadata", [
            decoded.folderId,
            mergeCancellation(decoded.optionalsInput, signal)
          ])
      ),
    getFolderMetadataById: (payload) =>
      runSdkCall(
        "folderMetadata",
        "getFolderMetadataById",
        "folderMetadata.getFolderMetadataById",
        M.FolderMetadataGetFolderMetadataByIdPayload,
        M.FolderMetadataGetFolderMetadataByIdSuccess,
        payload,
        (decoded, signal) =>
          invokeSdkMethod(client, "folderMetadata", "getFolderMetadataById", [
            decoded.folderId,
            decoded.scope,
            decoded.templateKey,
            mergeCancellation(decoded.optionalsInput, signal)
          ])
      ),
  },
  folders: {
    copyFolder: (payload) =>
      runSdkCall(
        "folders",
        "copyFolder",
        "folders.copyFolder",
        M.FoldersCopyFolderPayload,
        M.FoldersCopyFolderSuccess,
        payload,
        (decoded, signal) =>
          invokeSdkMethod(client, "folders", "copyFolder", [
            decoded.folderId,
            decoded.requestBody,
            mergeCancellation(decoded.optionalsInput, signal)
          ])
      ),
    createFolder: (payload) =>
      runSdkCall(
        "folders",
        "createFolder",
        "folders.createFolder",
        M.FoldersCreateFolderPayload,
        M.FoldersCreateFolderSuccess,
        payload,
        (decoded, signal) =>
          invokeSdkMethod(client, "folders", "createFolder", [
            decoded.requestBody,
            mergeCancellation(decoded.optionalsInput, signal)
          ])
      ),
    deleteFolderById: (payload) =>
      runSdkCall(
        "folders",
        "deleteFolderById",
        "folders.deleteFolderById",
        M.FoldersDeleteFolderByIdPayload,
        M.FoldersDeleteFolderByIdSuccess,
        payload,
        (decoded, signal) =>
          invokeSdkMethod(client, "folders", "deleteFolderById", [
            decoded.folderId,
            mergeCancellation(decoded.optionalsInput, signal)
          ])
      ),
    getFolderById: (payload) =>
      runSdkCall(
        "folders",
        "getFolderById",
        "folders.getFolderById",
        M.FoldersGetFolderByIdPayload,
        M.FoldersGetFolderByIdSuccess,
        payload,
        (decoded, signal) =>
          invokeSdkMethod(client, "folders", "getFolderById", [
            decoded.folderId,
            mergeCancellation(decoded.optionalsInput, signal)
          ])
      ),
    getFolderItems: (payload) =>
      runSdkCall(
        "folders",
        "getFolderItems",
        "folders.getFolderItems",
        M.FoldersGetFolderItemsPayload,
        M.FoldersGetFolderItemsSuccess,
        payload,
        (decoded, signal) =>
          invokeSdkMethod(client, "folders", "getFolderItems", [
            decoded.folderId,
            mergeCancellation(decoded.optionalsInput, signal)
          ])
      ),
    updateFolderById: (payload) =>
      runSdkCall(
        "folders",
        "updateFolderById",
        "folders.updateFolderById",
        M.FoldersUpdateFolderByIdPayload,
        M.FoldersUpdateFolderByIdSuccess,
        payload,
        (decoded, signal) =>
          invokeSdkMethod(client, "folders", "updateFolderById", [
            decoded.folderId,
            mergeCancellation(decoded.optionalsInput, signal)
          ])
      ),
  },
  listCollaborations: {
    getCollaborations: (payload) =>
      runSdkCall(
        "listCollaborations",
        "getCollaborations",
        "listCollaborations.getCollaborations",
        M.ListCollaborationsGetCollaborationsPayload,
        M.ListCollaborationsGetCollaborationsSuccess,
        payload,
        (decoded, signal) =>
          invokeSdkMethod(client, "listCollaborations", "getCollaborations", [
            decoded.queryParams,
            mergeCancellation(decoded.optionalsInput, signal)
          ])
      ),
    getFileCollaborations: (payload) =>
      runSdkCall(
        "listCollaborations",
        "getFileCollaborations",
        "listCollaborations.getFileCollaborations",
        M.ListCollaborationsGetFileCollaborationsPayload,
        M.ListCollaborationsGetFileCollaborationsSuccess,
        payload,
        (decoded, signal) =>
          invokeSdkMethod(client, "listCollaborations", "getFileCollaborations", [
            decoded.fileId,
            mergeCancellation(decoded.optionalsInput, signal)
          ])
      ),
    getFolderCollaborations: (payload) =>
      runSdkCall(
        "listCollaborations",
        "getFolderCollaborations",
        "listCollaborations.getFolderCollaborations",
        M.ListCollaborationsGetFolderCollaborationsPayload,
        M.ListCollaborationsGetFolderCollaborationsSuccess,
        payload,
        (decoded, signal) =>
          invokeSdkMethod(client, "listCollaborations", "getFolderCollaborations", [
            decoded.folderId,
            mergeCancellation(decoded.optionalsInput, signal)
          ])
      ),
    getGroupCollaborations: (payload) =>
      runSdkCall(
        "listCollaborations",
        "getGroupCollaborations",
        "listCollaborations.getGroupCollaborations",
        M.ListCollaborationsGetGroupCollaborationsPayload,
        M.ListCollaborationsGetGroupCollaborationsSuccess,
        payload,
        (decoded, signal) =>
          invokeSdkMethod(client, "listCollaborations", "getGroupCollaborations", [
            decoded.groupId,
            mergeCancellation(decoded.optionalsInput, signal)
          ])
      ),
  },
  metadataCascadePolicies: {
    getMetadataCascadePolicies: (payload) =>
      runSdkCall(
        "metadataCascadePolicies",
        "getMetadataCascadePolicies",
        "metadataCascadePolicies.getMetadataCascadePolicies",
        M.MetadataCascadePoliciesGetMetadataCascadePoliciesPayload,
        M.MetadataCascadePoliciesGetMetadataCascadePoliciesSuccess,
        payload,
        (decoded, signal) =>
          invokeSdkMethod(client, "metadataCascadePolicies", "getMetadataCascadePolicies", [
            decoded.queryParams,
            mergeCancellation(decoded.optionalsInput, signal)
          ])
      ),
    getMetadataCascadePolicyById: (payload) =>
      runSdkCall(
        "metadataCascadePolicies",
        "getMetadataCascadePolicyById",
        "metadataCascadePolicies.getMetadataCascadePolicyById",
        M.MetadataCascadePoliciesGetMetadataCascadePolicyByIdPayload,
        M.MetadataCascadePoliciesGetMetadataCascadePolicyByIdSuccess,
        payload,
        (decoded, signal) =>
          invokeSdkMethod(client, "metadataCascadePolicies", "getMetadataCascadePolicyById", [
            decoded.metadataCascadePolicyId,
            mergeCancellation(decoded.optionalsInput, signal)
          ])
      ),
  },
  metadataTemplates: {
    getEnterpriseMetadataTemplates: (payload) =>
      runSdkCall(
        "metadataTemplates",
        "getEnterpriseMetadataTemplates",
        "metadataTemplates.getEnterpriseMetadataTemplates",
        M.MetadataTemplatesGetEnterpriseMetadataTemplatesPayload,
        M.MetadataTemplatesGetEnterpriseMetadataTemplatesSuccess,
        payload,
        (decoded, signal) =>
          invokeSdkMethod(client, "metadataTemplates", "getEnterpriseMetadataTemplates", [
            decoded.queryParams,
            decoded.headersInput,
            combineCancellationToken(decoded.cancellationToken, signal)
          ])
      ),
    getGlobalMetadataTemplates: (payload) =>
      runSdkCall(
        "metadataTemplates",
        "getGlobalMetadataTemplates",
        "metadataTemplates.getGlobalMetadataTemplates",
        M.MetadataTemplatesGetGlobalMetadataTemplatesPayload,
        M.MetadataTemplatesGetGlobalMetadataTemplatesSuccess,
        payload,
        (decoded, signal) =>
          invokeSdkMethod(client, "metadataTemplates", "getGlobalMetadataTemplates", [
            decoded.queryParams,
            decoded.headersInput,
            combineCancellationToken(decoded.cancellationToken, signal)
          ])
      ),
    getMetadataTemplate: (payload) =>
      runSdkCall(
        "metadataTemplates",
        "getMetadataTemplate",
        "metadataTemplates.getMetadataTemplate",
        M.MetadataTemplatesGetMetadataTemplatePayload,
        M.MetadataTemplatesGetMetadataTemplateSuccess,
        payload,
        (decoded, signal) =>
          invokeSdkMethod(client, "metadataTemplates", "getMetadataTemplate", [
            decoded.scope,
            decoded.templateKey,
            mergeCancellation(decoded.optionalsInput, signal)
          ])
      ),
    getMetadataTemplateById: (payload) =>
      runSdkCall(
        "metadataTemplates",
        "getMetadataTemplateById",
        "metadataTemplates.getMetadataTemplateById",
        M.MetadataTemplatesGetMetadataTemplateByIdPayload,
        M.MetadataTemplatesGetMetadataTemplateByIdSuccess,
        payload,
        (decoded, signal) =>
          invokeSdkMethod(client, "metadataTemplates", "getMetadataTemplateById", [
            decoded.templateId,
            mergeCancellation(decoded.optionalsInput, signal)
          ])
      ),
    getMetadataTemplatesByInstanceId: (payload) =>
      runSdkCall(
        "metadataTemplates",
        "getMetadataTemplatesByInstanceId",
        "metadataTemplates.getMetadataTemplatesByInstanceId",
        M.MetadataTemplatesGetMetadataTemplatesByInstanceIdPayload,
        M.MetadataTemplatesGetMetadataTemplatesByInstanceIdSuccess,
        payload,
        (decoded, signal) =>
          invokeSdkMethod(client, "metadataTemplates", "getMetadataTemplatesByInstanceId", [
            decoded.queryParams,
            mergeCancellation(decoded.optionalsInput, signal)
          ])
      ),
  },
  retentionPolicies: {
    getRetentionPolicies: (payload) =>
      runSdkCall(
        "retentionPolicies",
        "getRetentionPolicies",
        "retentionPolicies.getRetentionPolicies",
        M.RetentionPoliciesGetRetentionPoliciesPayload,
        M.RetentionPoliciesGetRetentionPoliciesSuccess,
        payload,
        (decoded, signal) =>
          invokeSdkMethod(client, "retentionPolicies", "getRetentionPolicies", [
            decoded.queryParams,
            decoded.headersInput,
            combineCancellationToken(decoded.cancellationToken, signal)
          ])
      ),
    getRetentionPolicyById: (payload) =>
      runSdkCall(
        "retentionPolicies",
        "getRetentionPolicyById",
        "retentionPolicies.getRetentionPolicyById",
        M.RetentionPoliciesGetRetentionPolicyByIdPayload,
        M.RetentionPoliciesGetRetentionPolicyByIdSuccess,
        payload,
        (decoded, signal) =>
          invokeSdkMethod(client, "retentionPolicies", "getRetentionPolicyById", [
            decoded.retentionPolicyId,
            mergeCancellation(decoded.optionalsInput, signal)
          ])
      ),
  },
  retentionPolicyAssignments: {
    getFilesUnderRetentionPolicyAssignment: (payload) =>
      runSdkCall(
        "retentionPolicyAssignments",
        "getFilesUnderRetentionPolicyAssignment",
        "retentionPolicyAssignments.getFilesUnderRetentionPolicyAssignment",
        M.RetentionPolicyAssignmentsGetFilesUnderRetentionPolicyAssignmentPayload,
        M.RetentionPolicyAssignmentsGetFilesUnderRetentionPolicyAssignmentSuccess,
        payload,
        (decoded, signal) =>
          invokeSdkMethod(client, "retentionPolicyAssignments", "getFilesUnderRetentionPolicyAssignment", [
            decoded.retentionPolicyAssignmentId,
            mergeCancellation(decoded.optionalsInput, signal)
          ])
      ),
    getRetentionPolicyAssignmentById: (payload) =>
      runSdkCall(
        "retentionPolicyAssignments",
        "getRetentionPolicyAssignmentById",
        "retentionPolicyAssignments.getRetentionPolicyAssignmentById",
        M.RetentionPolicyAssignmentsGetRetentionPolicyAssignmentByIdPayload,
        M.RetentionPolicyAssignmentsGetRetentionPolicyAssignmentByIdSuccess,
        payload,
        (decoded, signal) =>
          invokeSdkMethod(client, "retentionPolicyAssignments", "getRetentionPolicyAssignmentById", [
            decoded.retentionPolicyAssignmentId,
            mergeCancellation(decoded.optionalsInput, signal)
          ])
      ),
    getRetentionPolicyAssignments: (payload) =>
      runSdkCall(
        "retentionPolicyAssignments",
        "getRetentionPolicyAssignments",
        "retentionPolicyAssignments.getRetentionPolicyAssignments",
        M.RetentionPolicyAssignmentsGetRetentionPolicyAssignmentsPayload,
        M.RetentionPolicyAssignmentsGetRetentionPolicyAssignmentsSuccess,
        payload,
        (decoded, signal) =>
          invokeSdkMethod(client, "retentionPolicyAssignments", "getRetentionPolicyAssignments", [
            decoded.retentionPolicyId,
            mergeCancellation(decoded.optionalsInput, signal)
          ])
      ),
  },
  signRequests: {
    cancelSignRequest: (payload) =>
      runSdkCall(
        "signRequests",
        "cancelSignRequest",
        "signRequests.cancelSignRequest",
        M.SignRequestsCancelSignRequestPayload,
        M.SignRequestsCancelSignRequestSuccess,
        payload,
        (decoded, signal) =>
          invokeSdkMethod(client, "signRequests", "cancelSignRequest", [
            decoded.signRequestId,
            mergeCancellation(decoded.optionalsInput, signal)
          ])
      ),
    createSignRequest: (payload) =>
      runSdkCall(
        "signRequests",
        "createSignRequest",
        "signRequests.createSignRequest",
        M.SignRequestsCreateSignRequestPayload,
        M.SignRequestsCreateSignRequestSuccess,
        payload,
        (decoded, signal) =>
          invokeSdkMethod(client, "signRequests", "createSignRequest", [
            decoded.requestBody,
            mergeCancellation(decoded.optionalsInput, signal)
          ])
      ),
    getSignRequestById: (payload) =>
      runSdkCall(
        "signRequests",
        "getSignRequestById",
        "signRequests.getSignRequestById",
        M.SignRequestsGetSignRequestByIdPayload,
        M.SignRequestsGetSignRequestByIdSuccess,
        payload,
        (decoded, signal) =>
          invokeSdkMethod(client, "signRequests", "getSignRequestById", [
            decoded.signRequestId,
            mergeCancellation(decoded.optionalsInput, signal)
          ])
      ),
    getSignRequests: (payload) =>
      runSdkCall(
        "signRequests",
        "getSignRequests",
        "signRequests.getSignRequests",
        M.SignRequestsGetSignRequestsPayload,
        M.SignRequestsGetSignRequestsSuccess,
        payload,
        (decoded, signal) =>
          invokeSdkMethod(client, "signRequests", "getSignRequests", [
            decoded.queryParams,
            decoded.headersInput,
            combineCancellationToken(decoded.cancellationToken, signal)
          ])
      ),
    resendSignRequest: (payload) =>
      runSdkCall(
        "signRequests",
        "resendSignRequest",
        "signRequests.resendSignRequest",
        M.SignRequestsResendSignRequestPayload,
        M.SignRequestsResendSignRequestSuccess,
        payload,
        (decoded, signal) =>
          invokeSdkMethod(client, "signRequests", "resendSignRequest", [
            decoded.signRequestId,
            mergeCancellation(decoded.optionalsInput, signal)
          ])
      ),
  },
  signTemplates: {
    getSignTemplateById: (payload) =>
      runSdkCall(
        "signTemplates",
        "getSignTemplateById",
        "signTemplates.getSignTemplateById",
        M.SignTemplatesGetSignTemplateByIdPayload,
        M.SignTemplatesGetSignTemplateByIdSuccess,
        payload,
        (decoded, signal) =>
          invokeSdkMethod(client, "signTemplates", "getSignTemplateById", [
            decoded.templateId,
            mergeCancellation(decoded.optionalsInput, signal)
          ])
      ),
    getSignTemplates: (payload) =>
      runSdkCall(
        "signTemplates",
        "getSignTemplates",
        "signTemplates.getSignTemplates",
        M.SignTemplatesGetSignTemplatesPayload,
        M.SignTemplatesGetSignTemplatesSuccess,
        payload,
        (decoded, signal) =>
          invokeSdkMethod(client, "signTemplates", "getSignTemplates", [
            decoded.queryParams,
            decoded.headersInput,
            combineCancellationToken(decoded.cancellationToken, signal)
          ])
      ),
  },
  uploads: {
    preflightFileUploadCheck: (payload) =>
      runSdkCall(
        "uploads",
        "preflightFileUploadCheck",
        "uploads.preflightFileUploadCheck",
        M.UploadsPreflightFileUploadCheckPayload,
        M.UploadsPreflightFileUploadCheckSuccess,
        payload,
        (decoded, signal) =>
          invokeSdkMethod(client, "uploads", "preflightFileUploadCheck", [
            decoded.requestBody,
            decoded.headersInput,
            combineCancellationToken(decoded.cancellationToken, signal)
          ])
      ),
  },
  userCollaborations: {
    createCollaboration: (payload) =>
      runSdkCall(
        "userCollaborations",
        "createCollaboration",
        "userCollaborations.createCollaboration",
        M.UserCollaborationsCreateCollaborationPayload,
        M.UserCollaborationsCreateCollaborationSuccess,
        payload,
        (decoded, signal) =>
          invokeSdkMethod(client, "userCollaborations", "createCollaboration", [
            decoded.requestBody,
            mergeCancellation(decoded.optionalsInput, signal)
          ])
      ),
    deleteCollaborationById: (payload) =>
      runSdkCall(
        "userCollaborations",
        "deleteCollaborationById",
        "userCollaborations.deleteCollaborationById",
        M.UserCollaborationsDeleteCollaborationByIdPayload,
        M.UserCollaborationsDeleteCollaborationByIdSuccess,
        payload,
        (decoded, signal) =>
          invokeSdkMethod(client, "userCollaborations", "deleteCollaborationById", [
            decoded.collaborationId,
            mergeCancellation(decoded.optionalsInput, signal)
          ])
      ),
    getCollaborationById: (payload) =>
      runSdkCall(
        "userCollaborations",
        "getCollaborationById",
        "userCollaborations.getCollaborationById",
        M.UserCollaborationsGetCollaborationByIdPayload,
        M.UserCollaborationsGetCollaborationByIdSuccess,
        payload,
        (decoded, signal) =>
          invokeSdkMethod(client, "userCollaborations", "getCollaborationById", [
            decoded.collaborationId,
            mergeCancellation(decoded.optionalsInput, signal)
          ])
      ),
    updateCollaborationById: (payload) =>
      runSdkCall(
        "userCollaborations",
        "updateCollaborationById",
        "userCollaborations.updateCollaborationById",
        M.UserCollaborationsUpdateCollaborationByIdPayload,
        M.UserCollaborationsUpdateCollaborationByIdSuccess,
        payload,
        (decoded, signal) =>
          invokeSdkMethod(client, "userCollaborations", "updateCollaborationById", [
            decoded.collaborationId,
            mergeCancellation(decoded.optionalsInput, signal)
          ])
      ),
  },
  users: {
    createUser: (payload) =>
      runSdkCall(
        "users",
        "createUser",
        "users.createUser",
        M.UsersCreateUserPayload,
        M.UsersCreateUserSuccess,
        payload,
        (decoded, signal) =>
          invokeSdkMethod(client, "users", "createUser", [
            decoded.requestBody,
            mergeCancellation(decoded.optionalsInput, signal)
          ])
      ),
    deleteUserById: (payload) =>
      runSdkCall(
        "users",
        "deleteUserById",
        "users.deleteUserById",
        M.UsersDeleteUserByIdPayload,
        M.UsersDeleteUserByIdSuccess,
        payload,
        (decoded, signal) =>
          invokeSdkMethod(client, "users", "deleteUserById", [
            decoded.userId,
            mergeCancellation(decoded.optionalsInput, signal)
          ])
      ),
    getUserById: (payload) =>
      runSdkCall(
        "users",
        "getUserById",
        "users.getUserById",
        M.UsersGetUserByIdPayload,
        M.UsersGetUserByIdSuccess,
        payload,
        (decoded, signal) =>
          invokeSdkMethod(client, "users", "getUserById", [
            decoded.userId,
            mergeCancellation(decoded.optionalsInput, signal)
          ])
      ),
    getUserMe: (payload) =>
      runSdkCall(
        "users",
        "getUserMe",
        "users.getUserMe",
        M.UsersGetUserMePayload,
        M.UsersGetUserMeSuccess,
        payload,
        (decoded, signal) =>
          invokeSdkMethod(client, "users", "getUserMe", [
            decoded.queryParams,
            decoded.headersInput,
            combineCancellationToken(decoded.cancellationToken, signal)
          ])
      ),
    getUsers: (payload) =>
      runSdkCall(
        "users",
        "getUsers",
        "users.getUsers",
        M.UsersGetUsersPayload,
        M.UsersGetUsersSuccess,
        payload,
        (decoded, signal) =>
          invokeSdkMethod(client, "users", "getUsers", [
            decoded.queryParams,
            decoded.headersInput,
            combineCancellationToken(decoded.cancellationToken, signal)
          ])
      ),
    updateUserById: (payload) =>
      runSdkCall(
        "users",
        "updateUserById",
        "users.updateUserById",
        M.UsersUpdateUserByIdPayload,
        M.UsersUpdateUserByIdSuccess,
        payload,
        (decoded, signal) =>
          invokeSdkMethod(client, "users", "updateUserById", [
            decoded.userId,
            mergeCancellation(decoded.optionalsInput, signal)
          ])
      ),
  },
  webhooks: {
    createWebhook: (payload) =>
      runSdkCall(
        "webhooks",
        "createWebhook",
        "webhooks.createWebhook",
        M.WebhooksCreateWebhookPayload,
        M.WebhooksCreateWebhookSuccess,
        payload,
        (decoded, signal) =>
          invokeSdkMethod(client, "webhooks", "createWebhook", [
            decoded.requestBody,
            mergeCancellation(decoded.optionalsInput, signal)
          ])
      ),
    deleteWebhookById: (payload) =>
      runSdkCall(
        "webhooks",
        "deleteWebhookById",
        "webhooks.deleteWebhookById",
        M.WebhooksDeleteWebhookByIdPayload,
        M.WebhooksDeleteWebhookByIdSuccess,
        payload,
        (decoded, signal) =>
          invokeSdkMethod(client, "webhooks", "deleteWebhookById", [
            decoded.webhookId,
            mergeCancellation(decoded.optionalsInput, signal)
          ])
      ),
    getWebhookById: (payload) =>
      runSdkCall(
        "webhooks",
        "getWebhookById",
        "webhooks.getWebhookById",
        M.WebhooksGetWebhookByIdPayload,
        M.WebhooksGetWebhookByIdSuccess,
        payload,
        (decoded, signal) =>
          invokeSdkMethod(client, "webhooks", "getWebhookById", [
            decoded.webhookId,
            mergeCancellation(decoded.optionalsInput, signal)
          ])
      ),
    getWebhooks: (payload) =>
      runSdkCall(
        "webhooks",
        "getWebhooks",
        "webhooks.getWebhooks",
        M.WebhooksGetWebhooksPayload,
        M.WebhooksGetWebhooksSuccess,
        payload,
        (decoded, signal) =>
          invokeSdkMethod(client, "webhooks", "getWebhooks", [
            decoded.queryParams,
            decoded.headersInput,
            combineCancellationToken(decoded.cancellationToken, signal)
          ])
      ),
    updateWebhookById: (payload) =>
      runSdkCall(
        "webhooks",
        "updateWebhookById",
        "webhooks.updateWebhookById",
        M.WebhooksUpdateWebhookByIdPayload,
        M.WebhooksUpdateWebhookByIdSuccess,
        payload,
        (decoded, signal) =>
          invokeSdkMethod(client, "webhooks", "updateWebhookById", [
            decoded.webhookId,
            mergeCancellation(decoded.optionalsInput, signal)
          ])
      ),
    validateMessage: (payload) =>
      runSdkCall(
        "webhooks",
        "validateMessage",
        "webhooks.validateMessage",
        M.WebhooksValidateMessagePayload,
        M.WebhooksValidateMessageSuccess,
        payload,
        (decoded, signal) =>
          invokeSdkMethod(client, "webhooks", "validateMessage", [
            decoded.body,
            decoded.headers,
            decoded.primaryKey,
            mergeCancellation(decoded.optionalsInput, signal)
          ])
      ),
  },
  zipDownloads: {
    createZipDownload: (payload) =>
      runSdkCall(
        "zipDownloads",
        "createZipDownload",
        "zipDownloads.createZipDownload",
        M.ZipDownloadsCreateZipDownloadPayload,
        M.ZipDownloadsCreateZipDownloadSuccess,
        payload,
        (decoded, signal) =>
          invokeSdkMethod(client, "zipDownloads", "createZipDownload", [
            decoded.requestBody,
            mergeCancellation(decoded.optionalsInput, signal)
          ])
      ),
    getZipDownloadStatus: (payload) =>
      runSdkCall(
        "zipDownloads",
        "getZipDownloadStatus",
        "zipDownloads.getZipDownloadStatus",
        M.ZipDownloadsGetZipDownloadStatusPayload,
        M.ZipDownloadsGetZipDownloadStatusSuccess,
        payload,
        (decoded, signal) =>
          invokeSdkMethod(client, "zipDownloads", "getZipDownloadStatus", [
            decoded.statusUrl,
            mergeCancellation(decoded.optionalsInput, signal)
          ])
      ),
  },
}));
