/**
 * Generated Box SDK operation wrappers.
 *
 * @packageDocumentation
 * @since 0.0.0
 */

// This file is generated by @beep/box/scripts/generate.ts. Do not edit manually.

import { Effect, Result } from "effect";
import * as P from "effect/Predicate";
import type * as S from "effect/Schema";
import type { BoxError } from "../Box.errors.ts";
import * as M from "./Box.models.gen.ts";

/**
 * Shared generated operation runner supplied by {@link Box}.
 *
 * @example
 * ```ts
 * import type { BoxRunSdkCall } from "@beep/box/Box.operations.gen"
 *
 * type Runner = BoxRunSdkCall
 * ```
 *
 * @category services
 * @since 0.0.0
 */
export type BoxRunSdkCall = <Payload, Success>(
  manager: string,
  method: string,
  methodName: M.BoxMethodName,
  payloadSchema: S.ConstraintDecoder<Payload>,
  successSchema: S.ConstraintDecoder<Success>,
  payload: Payload,
  invoke: (decoded: Payload, signal: AbortSignal | undefined) => Promise<unknown>
) => Effect.Effect<Success, BoxError>;

/**
 * Generated JSON operation groups for the Box SDK.
 *
 * @example
 * ```ts
 * import type { BoxGeneratedOperations } from "@beep/box/Box.operations.gen"
 *
 * type Managers = keyof BoxGeneratedOperations
 * ```
 *
 * @category services
 * @since 0.0.0
 */
export type BoxGeneratedOperations = {
  readonly avatars: {
    readonly deleteUserAvatar: (payload: M.AvatarsDeleteUserAvatarPayload) => Effect.Effect<M.AvatarsDeleteUserAvatarSuccess, BoxError>;
  };
  readonly chunkedUploads: {
    readonly createFileUploadSession: (payload: M.ChunkedUploadsCreateFileUploadSessionPayload) => Effect.Effect<M.ChunkedUploadsCreateFileUploadSessionSuccess, BoxError>;
    readonly createFileUploadSessionCommit: (payload: M.ChunkedUploadsCreateFileUploadSessionCommitPayload) => Effect.Effect<M.ChunkedUploadsCreateFileUploadSessionCommitSuccess, BoxError>;
    readonly createFileUploadSessionCommitByUrl: (payload: M.ChunkedUploadsCreateFileUploadSessionCommitByUrlPayload) => Effect.Effect<M.ChunkedUploadsCreateFileUploadSessionCommitByUrlSuccess, BoxError>;
    readonly createFileUploadSessionForExistingFile: (payload: M.ChunkedUploadsCreateFileUploadSessionForExistingFilePayload) => Effect.Effect<M.ChunkedUploadsCreateFileUploadSessionForExistingFileSuccess, BoxError>;
    readonly deleteFileUploadSessionById: (payload: M.ChunkedUploadsDeleteFileUploadSessionByIdPayload) => Effect.Effect<M.ChunkedUploadsDeleteFileUploadSessionByIdSuccess, BoxError>;
    readonly deleteFileUploadSessionByUrl: (payload: M.ChunkedUploadsDeleteFileUploadSessionByUrlPayload) => Effect.Effect<M.ChunkedUploadsDeleteFileUploadSessionByUrlSuccess, BoxError>;
    readonly getFileUploadSessionById: (payload: M.ChunkedUploadsGetFileUploadSessionByIdPayload) => Effect.Effect<M.ChunkedUploadsGetFileUploadSessionByIdSuccess, BoxError>;
    readonly getFileUploadSessionByUrl: (payload: M.ChunkedUploadsGetFileUploadSessionByUrlPayload) => Effect.Effect<M.ChunkedUploadsGetFileUploadSessionByUrlSuccess, BoxError>;
    readonly getFileUploadSessionParts: (payload: M.ChunkedUploadsGetFileUploadSessionPartsPayload) => Effect.Effect<M.ChunkedUploadsGetFileUploadSessionPartsSuccess, BoxError>;
    readonly getFileUploadSessionPartsByUrl: (payload: M.ChunkedUploadsGetFileUploadSessionPartsByUrlPayload) => Effect.Effect<M.ChunkedUploadsGetFileUploadSessionPartsByUrlSuccess, BoxError>;
  };
  readonly downloads: {
    readonly getDownloadFileUrl: (payload: M.DownloadsGetDownloadFileUrlPayload) => Effect.Effect<M.DownloadsGetDownloadFileUrlSuccess, BoxError>;
  };
  readonly events: {
    readonly getEvents: (payload: M.EventsGetEventsPayload) => Effect.Effect<M.EventsGetEventsSuccess, BoxError>;
    readonly getEventsWithLongPolling: (payload: M.EventsGetEventsWithLongPollingPayload) => Effect.Effect<M.EventsGetEventsWithLongPollingSuccess, BoxError>;
  };
  readonly files: {
    readonly copyFile: (payload: M.FilesCopyFilePayload) => Effect.Effect<M.FilesCopyFileSuccess, BoxError>;
    readonly deleteFileById: (payload: M.FilesDeleteFileByIdPayload) => Effect.Effect<M.FilesDeleteFileByIdSuccess, BoxError>;
    readonly getFileById: (payload: M.FilesGetFileByIdPayload) => Effect.Effect<M.FilesGetFileByIdSuccess, BoxError>;
    readonly getFileThumbnailUrl: (payload: M.FilesGetFileThumbnailUrlPayload) => Effect.Effect<M.FilesGetFileThumbnailUrlSuccess, BoxError>;
    readonly updateFileById: (payload: M.FilesUpdateFileByIdPayload) => Effect.Effect<M.FilesUpdateFileByIdSuccess, BoxError>;
  };
  readonly folders: {
    readonly copyFolder: (payload: M.FoldersCopyFolderPayload) => Effect.Effect<M.FoldersCopyFolderSuccess, BoxError>;
    readonly createFolder: (payload: M.FoldersCreateFolderPayload) => Effect.Effect<M.FoldersCreateFolderSuccess, BoxError>;
    readonly deleteFolderById: (payload: M.FoldersDeleteFolderByIdPayload) => Effect.Effect<M.FoldersDeleteFolderByIdSuccess, BoxError>;
    readonly getFolderById: (payload: M.FoldersGetFolderByIdPayload) => Effect.Effect<M.FoldersGetFolderByIdSuccess, BoxError>;
    readonly getFolderItems: (payload: M.FoldersGetFolderItemsPayload) => Effect.Effect<M.FoldersGetFolderItemsSuccess, BoxError>;
    readonly updateFolderById: (payload: M.FoldersUpdateFolderByIdPayload) => Effect.Effect<M.FoldersUpdateFolderByIdSuccess, BoxError>;
  };
  readonly uploads: {
    readonly preflightFileUploadCheck: (payload: M.UploadsPreflightFileUploadCheckPayload) => Effect.Effect<M.UploadsPreflightFileUploadCheckSuccess, BoxError>;
  };
  readonly users: {
    readonly createUser: (payload: M.UsersCreateUserPayload) => Effect.Effect<M.UsersCreateUserSuccess, BoxError>;
    readonly deleteUserById: (payload: M.UsersDeleteUserByIdPayload) => Effect.Effect<M.UsersDeleteUserByIdSuccess, BoxError>;
    readonly getUserById: (payload: M.UsersGetUserByIdPayload) => Effect.Effect<M.UsersGetUserByIdSuccess, BoxError>;
    readonly getUserMe: (payload: M.UsersGetUserMePayload) => Effect.Effect<M.UsersGetUserMeSuccess, BoxError>;
    readonly getUsers: (payload: M.UsersGetUsersPayload) => Effect.Effect<M.UsersGetUsersSuccess, BoxError>;
    readonly updateUserById: (payload: M.UsersUpdateUserByIdPayload) => Effect.Effect<M.UsersUpdateUserByIdSuccess, BoxError>;
  };
  readonly zipDownloads: {
    readonly createZipDownload: (payload: M.ZipDownloadsCreateZipDownloadPayload) => Effect.Effect<M.ZipDownloadsCreateZipDownloadSuccess, BoxError>;
    readonly getZipDownloadStatus: (payload: M.ZipDownloadsGetZipDownloadStatusPayload) => Effect.Effect<M.ZipDownloadsGetZipDownloadStatusSuccess, BoxError>;
  };
};

const readProperty = (value: unknown, key: PropertyKey): unknown => (P.isObject(value) ? Reflect.get(value, key) : undefined);

const readCancellationToken = (value: unknown): AbortSignal | undefined => {
  const token = readProperty(value, "cancellationToken");
  return token instanceof AbortSignal ? token : undefined;
};

const combineCancellationToken = (
  callerSignal: AbortSignal | undefined,
  driverSignal: AbortSignal | undefined
): AbortSignal | undefined => {
  if (callerSignal === undefined) {
    return driverSignal;
  }
  if (driverSignal === undefined || callerSignal === driverSignal) {
    return callerSignal;
  }
  return AbortSignal.any([callerSignal, driverSignal]);
};

const mergeCancellation = <A>(
  input: A | undefined,
  signal: AbortSignal | undefined
): A | { readonly cancellationToken: AbortSignal } | undefined => {
  const cancellationToken = combineCancellationToken(readCancellationToken(input), signal);
  if (cancellationToken === undefined) {
    return input;
  }
  if (P.isObject(input)) {
    return { ...input, cancellationToken };
  }
  return { cancellationToken };
};

const sdkShapeFailure = (manager: string, method: string): Promise<never> =>
  Promise.reject({
    _tag: "BoxSdkShapeError",
    manager,
    method
  });

const invokeSdkMethod = (
  client: unknown,
  manager: string,
  method: string,
  args: ReadonlyArray<unknown>
): Promise<unknown> => {
  const managerValue = readProperty(client, manager);
  const methodValue = readProperty(managerValue, method);

  if (!P.isFunction(methodValue)) {
    return sdkShapeFailure(manager, method);
  }

  const result = Result.try(() => Reflect.apply(methodValue, managerValue, args));
  return Result.match(result, {
    onFailure: (cause) => Promise.reject(cause),
    onSuccess: (value) => Promise.resolve(value)
  });
};

/**
 * Build generated Box SDK operation groups from a SDK client and shared runner.
 *
 * @example
 * ```ts
 * import { makeGeneratedOperations } from "@beep/box/Box.operations.gen"
 *
 * console.log(makeGeneratedOperations)
 * ```
 *
 * @category constructors
 * @since 0.0.0
 */
export const makeGeneratedOperations = (client: unknown, runSdkCall: BoxRunSdkCall): BoxGeneratedOperations => ({
  avatars: {
    deleteUserAvatar: (payload) =>
      runSdkCall(
        "avatars",
        "deleteUserAvatar",
        "avatars.deleteUserAvatar",
        M.AvatarsDeleteUserAvatarPayload,
        M.AvatarsDeleteUserAvatarSuccess,
        payload,
        (decoded, signal) =>
          invokeSdkMethod(client, "avatars", "deleteUserAvatar", [
            decoded.userId,
            mergeCancellation(decoded.optionalsInput, signal)
          ])
      ),
  },
  chunkedUploads: {
    createFileUploadSession: (payload) =>
      runSdkCall(
        "chunkedUploads",
        "createFileUploadSession",
        "chunkedUploads.createFileUploadSession",
        M.ChunkedUploadsCreateFileUploadSessionPayload,
        M.ChunkedUploadsCreateFileUploadSessionSuccess,
        payload,
        (decoded, signal) =>
          invokeSdkMethod(client, "chunkedUploads", "createFileUploadSession", [
            decoded.requestBody,
            mergeCancellation(decoded.optionalsInput, signal)
          ])
      ),
    createFileUploadSessionCommit: (payload) =>
      runSdkCall(
        "chunkedUploads",
        "createFileUploadSessionCommit",
        "chunkedUploads.createFileUploadSessionCommit",
        M.ChunkedUploadsCreateFileUploadSessionCommitPayload,
        M.ChunkedUploadsCreateFileUploadSessionCommitSuccess,
        payload,
        (decoded, signal) =>
          invokeSdkMethod(client, "chunkedUploads", "createFileUploadSessionCommit", [
            decoded.uploadSessionId,
            decoded.requestBody,
            decoded.headersInput,
            mergeCancellation(decoded.optionalsInput, signal)
          ])
      ),
    createFileUploadSessionCommitByUrl: (payload) =>
      runSdkCall(
        "chunkedUploads",
        "createFileUploadSessionCommitByUrl",
        "chunkedUploads.createFileUploadSessionCommitByUrl",
        M.ChunkedUploadsCreateFileUploadSessionCommitByUrlPayload,
        M.ChunkedUploadsCreateFileUploadSessionCommitByUrlSuccess,
        payload,
        (decoded, signal) =>
          invokeSdkMethod(client, "chunkedUploads", "createFileUploadSessionCommitByUrl", [
            decoded.url,
            decoded.requestBody,
            decoded.headersInput,
            mergeCancellation(decoded.optionalsInput, signal)
          ])
      ),
    createFileUploadSessionForExistingFile: (payload) =>
      runSdkCall(
        "chunkedUploads",
        "createFileUploadSessionForExistingFile",
        "chunkedUploads.createFileUploadSessionForExistingFile",
        M.ChunkedUploadsCreateFileUploadSessionForExistingFilePayload,
        M.ChunkedUploadsCreateFileUploadSessionForExistingFileSuccess,
        payload,
        (decoded, signal) =>
          invokeSdkMethod(client, "chunkedUploads", "createFileUploadSessionForExistingFile", [
            decoded.fileId,
            decoded.requestBody,
            mergeCancellation(decoded.optionalsInput, signal)
          ])
      ),
    deleteFileUploadSessionById: (payload) =>
      runSdkCall(
        "chunkedUploads",
        "deleteFileUploadSessionById",
        "chunkedUploads.deleteFileUploadSessionById",
        M.ChunkedUploadsDeleteFileUploadSessionByIdPayload,
        M.ChunkedUploadsDeleteFileUploadSessionByIdSuccess,
        payload,
        (decoded, signal) =>
          invokeSdkMethod(client, "chunkedUploads", "deleteFileUploadSessionById", [
            decoded.uploadSessionId,
            mergeCancellation(decoded.optionalsInput, signal)
          ])
      ),
    deleteFileUploadSessionByUrl: (payload) =>
      runSdkCall(
        "chunkedUploads",
        "deleteFileUploadSessionByUrl",
        "chunkedUploads.deleteFileUploadSessionByUrl",
        M.ChunkedUploadsDeleteFileUploadSessionByUrlPayload,
        M.ChunkedUploadsDeleteFileUploadSessionByUrlSuccess,
        payload,
        (decoded, signal) =>
          invokeSdkMethod(client, "chunkedUploads", "deleteFileUploadSessionByUrl", [
            decoded.url,
            mergeCancellation(decoded.optionalsInput, signal)
          ])
      ),
    getFileUploadSessionById: (payload) =>
      runSdkCall(
        "chunkedUploads",
        "getFileUploadSessionById",
        "chunkedUploads.getFileUploadSessionById",
        M.ChunkedUploadsGetFileUploadSessionByIdPayload,
        M.ChunkedUploadsGetFileUploadSessionByIdSuccess,
        payload,
        (decoded, signal) =>
          invokeSdkMethod(client, "chunkedUploads", "getFileUploadSessionById", [
            decoded.uploadSessionId,
            mergeCancellation(decoded.optionalsInput, signal)
          ])
      ),
    getFileUploadSessionByUrl: (payload) =>
      runSdkCall(
        "chunkedUploads",
        "getFileUploadSessionByUrl",
        "chunkedUploads.getFileUploadSessionByUrl",
        M.ChunkedUploadsGetFileUploadSessionByUrlPayload,
        M.ChunkedUploadsGetFileUploadSessionByUrlSuccess,
        payload,
        (decoded, signal) =>
          invokeSdkMethod(client, "chunkedUploads", "getFileUploadSessionByUrl", [
            decoded.url,
            mergeCancellation(decoded.optionalsInput, signal)
          ])
      ),
    getFileUploadSessionParts: (payload) =>
      runSdkCall(
        "chunkedUploads",
        "getFileUploadSessionParts",
        "chunkedUploads.getFileUploadSessionParts",
        M.ChunkedUploadsGetFileUploadSessionPartsPayload,
        M.ChunkedUploadsGetFileUploadSessionPartsSuccess,
        payload,
        (decoded, signal) =>
          invokeSdkMethod(client, "chunkedUploads", "getFileUploadSessionParts", [
            decoded.uploadSessionId,
            mergeCancellation(decoded.optionalsInput, signal)
          ])
      ),
    getFileUploadSessionPartsByUrl: (payload) =>
      runSdkCall(
        "chunkedUploads",
        "getFileUploadSessionPartsByUrl",
        "chunkedUploads.getFileUploadSessionPartsByUrl",
        M.ChunkedUploadsGetFileUploadSessionPartsByUrlPayload,
        M.ChunkedUploadsGetFileUploadSessionPartsByUrlSuccess,
        payload,
        (decoded, signal) =>
          invokeSdkMethod(client, "chunkedUploads", "getFileUploadSessionPartsByUrl", [
            decoded.url,
            mergeCancellation(decoded.optionalsInput, signal)
          ])
      ),
  },
  downloads: {
    getDownloadFileUrl: (payload) =>
      runSdkCall(
        "downloads",
        "getDownloadFileUrl",
        "downloads.getDownloadFileUrl",
        M.DownloadsGetDownloadFileUrlPayload,
        M.DownloadsGetDownloadFileUrlSuccess,
        payload,
        (decoded, signal) =>
          invokeSdkMethod(client, "downloads", "getDownloadFileUrl", [
            decoded.fileId,
            mergeCancellation(decoded.optionalsInput, signal)
          ])
      ),
  },
  events: {
    getEvents: (payload) =>
      runSdkCall(
        "events",
        "getEvents",
        "events.getEvents",
        M.EventsGetEventsPayload,
        M.EventsGetEventsSuccess,
        payload,
        (decoded, signal) =>
          invokeSdkMethod(client, "events", "getEvents", [
            decoded.queryParams,
            decoded.headersInput,
            combineCancellationToken(decoded.cancellationToken, signal)
          ])
      ),
    getEventsWithLongPolling: (payload) =>
      runSdkCall(
        "events",
        "getEventsWithLongPolling",
        "events.getEventsWithLongPolling",
        M.EventsGetEventsWithLongPollingPayload,
        M.EventsGetEventsWithLongPollingSuccess,
        payload,
        (decoded, signal) =>
          invokeSdkMethod(client, "events", "getEventsWithLongPolling", [
            decoded.headersInput,
            combineCancellationToken(decoded.cancellationToken, signal)
          ])
      ),
  },
  files: {
    copyFile: (payload) =>
      runSdkCall(
        "files",
        "copyFile",
        "files.copyFile",
        M.FilesCopyFilePayload,
        M.FilesCopyFileSuccess,
        payload,
        (decoded, signal) =>
          invokeSdkMethod(client, "files", "copyFile", [
            decoded.fileId,
            decoded.requestBody,
            mergeCancellation(decoded.optionalsInput, signal)
          ])
      ),
    deleteFileById: (payload) =>
      runSdkCall(
        "files",
        "deleteFileById",
        "files.deleteFileById",
        M.FilesDeleteFileByIdPayload,
        M.FilesDeleteFileByIdSuccess,
        payload,
        (decoded, signal) =>
          invokeSdkMethod(client, "files", "deleteFileById", [
            decoded.fileId,
            mergeCancellation(decoded.optionalsInput, signal)
          ])
      ),
    getFileById: (payload) =>
      runSdkCall(
        "files",
        "getFileById",
        "files.getFileById",
        M.FilesGetFileByIdPayload,
        M.FilesGetFileByIdSuccess,
        payload,
        (decoded, signal) =>
          invokeSdkMethod(client, "files", "getFileById", [
            decoded.fileId,
            mergeCancellation(decoded.optionalsInput, signal)
          ])
      ),
    getFileThumbnailUrl: (payload) =>
      runSdkCall(
        "files",
        "getFileThumbnailUrl",
        "files.getFileThumbnailUrl",
        M.FilesGetFileThumbnailUrlPayload,
        M.FilesGetFileThumbnailUrlSuccess,
        payload,
        (decoded, signal) =>
          invokeSdkMethod(client, "files", "getFileThumbnailUrl", [
            decoded.fileId,
            decoded.extension,
            mergeCancellation(decoded.optionalsInput, signal)
          ])
      ),
    updateFileById: (payload) =>
      runSdkCall(
        "files",
        "updateFileById",
        "files.updateFileById",
        M.FilesUpdateFileByIdPayload,
        M.FilesUpdateFileByIdSuccess,
        payload,
        (decoded, signal) =>
          invokeSdkMethod(client, "files", "updateFileById", [
            decoded.fileId,
            mergeCancellation(decoded.optionalsInput, signal)
          ])
      ),
  },
  folders: {
    copyFolder: (payload) =>
      runSdkCall(
        "folders",
        "copyFolder",
        "folders.copyFolder",
        M.FoldersCopyFolderPayload,
        M.FoldersCopyFolderSuccess,
        payload,
        (decoded, signal) =>
          invokeSdkMethod(client, "folders", "copyFolder", [
            decoded.folderId,
            decoded.requestBody,
            mergeCancellation(decoded.optionalsInput, signal)
          ])
      ),
    createFolder: (payload) =>
      runSdkCall(
        "folders",
        "createFolder",
        "folders.createFolder",
        M.FoldersCreateFolderPayload,
        M.FoldersCreateFolderSuccess,
        payload,
        (decoded, signal) =>
          invokeSdkMethod(client, "folders", "createFolder", [
            decoded.requestBody,
            mergeCancellation(decoded.optionalsInput, signal)
          ])
      ),
    deleteFolderById: (payload) =>
      runSdkCall(
        "folders",
        "deleteFolderById",
        "folders.deleteFolderById",
        M.FoldersDeleteFolderByIdPayload,
        M.FoldersDeleteFolderByIdSuccess,
        payload,
        (decoded, signal) =>
          invokeSdkMethod(client, "folders", "deleteFolderById", [
            decoded.folderId,
            mergeCancellation(decoded.optionalsInput, signal)
          ])
      ),
    getFolderById: (payload) =>
      runSdkCall(
        "folders",
        "getFolderById",
        "folders.getFolderById",
        M.FoldersGetFolderByIdPayload,
        M.FoldersGetFolderByIdSuccess,
        payload,
        (decoded, signal) =>
          invokeSdkMethod(client, "folders", "getFolderById", [
            decoded.folderId,
            mergeCancellation(decoded.optionalsInput, signal)
          ])
      ),
    getFolderItems: (payload) =>
      runSdkCall(
        "folders",
        "getFolderItems",
        "folders.getFolderItems",
        M.FoldersGetFolderItemsPayload,
        M.FoldersGetFolderItemsSuccess,
        payload,
        (decoded, signal) =>
          invokeSdkMethod(client, "folders", "getFolderItems", [
            decoded.folderId,
            mergeCancellation(decoded.optionalsInput, signal)
          ])
      ),
    updateFolderById: (payload) =>
      runSdkCall(
        "folders",
        "updateFolderById",
        "folders.updateFolderById",
        M.FoldersUpdateFolderByIdPayload,
        M.FoldersUpdateFolderByIdSuccess,
        payload,
        (decoded, signal) =>
          invokeSdkMethod(client, "folders", "updateFolderById", [
            decoded.folderId,
            mergeCancellation(decoded.optionalsInput, signal)
          ])
      ),
  },
  uploads: {
    preflightFileUploadCheck: (payload) =>
      runSdkCall(
        "uploads",
        "preflightFileUploadCheck",
        "uploads.preflightFileUploadCheck",
        M.UploadsPreflightFileUploadCheckPayload,
        M.UploadsPreflightFileUploadCheckSuccess,
        payload,
        (decoded, signal) =>
          invokeSdkMethod(client, "uploads", "preflightFileUploadCheck", [
            decoded.requestBody,
            decoded.headersInput,
            combineCancellationToken(decoded.cancellationToken, signal)
          ])
      ),
  },
  users: {
    createUser: (payload) =>
      runSdkCall(
        "users",
        "createUser",
        "users.createUser",
        M.UsersCreateUserPayload,
        M.UsersCreateUserSuccess,
        payload,
        (decoded, signal) =>
          invokeSdkMethod(client, "users", "createUser", [
            decoded.requestBody,
            mergeCancellation(decoded.optionalsInput, signal)
          ])
      ),
    deleteUserById: (payload) =>
      runSdkCall(
        "users",
        "deleteUserById",
        "users.deleteUserById",
        M.UsersDeleteUserByIdPayload,
        M.UsersDeleteUserByIdSuccess,
        payload,
        (decoded, signal) =>
          invokeSdkMethod(client, "users", "deleteUserById", [
            decoded.userId,
            mergeCancellation(decoded.optionalsInput, signal)
          ])
      ),
    getUserById: (payload) =>
      runSdkCall(
        "users",
        "getUserById",
        "users.getUserById",
        M.UsersGetUserByIdPayload,
        M.UsersGetUserByIdSuccess,
        payload,
        (decoded, signal) =>
          invokeSdkMethod(client, "users", "getUserById", [
            decoded.userId,
            mergeCancellation(decoded.optionalsInput, signal)
          ])
      ),
    getUserMe: (payload) =>
      runSdkCall(
        "users",
        "getUserMe",
        "users.getUserMe",
        M.UsersGetUserMePayload,
        M.UsersGetUserMeSuccess,
        payload,
        (decoded, signal) =>
          invokeSdkMethod(client, "users", "getUserMe", [
            decoded.queryParams,
            decoded.headersInput,
            combineCancellationToken(decoded.cancellationToken, signal)
          ])
      ),
    getUsers: (payload) =>
      runSdkCall(
        "users",
        "getUsers",
        "users.getUsers",
        M.UsersGetUsersPayload,
        M.UsersGetUsersSuccess,
        payload,
        (decoded, signal) =>
          invokeSdkMethod(client, "users", "getUsers", [
            decoded.queryParams,
            decoded.headersInput,
            combineCancellationToken(decoded.cancellationToken, signal)
          ])
      ),
    updateUserById: (payload) =>
      runSdkCall(
        "users",
        "updateUserById",
        "users.updateUserById",
        M.UsersUpdateUserByIdPayload,
        M.UsersUpdateUserByIdSuccess,
        payload,
        (decoded, signal) =>
          invokeSdkMethod(client, "users", "updateUserById", [
            decoded.userId,
            mergeCancellation(decoded.optionalsInput, signal)
          ])
      ),
  },
  zipDownloads: {
    createZipDownload: (payload) =>
      runSdkCall(
        "zipDownloads",
        "createZipDownload",
        "zipDownloads.createZipDownload",
        M.ZipDownloadsCreateZipDownloadPayload,
        M.ZipDownloadsCreateZipDownloadSuccess,
        payload,
        (decoded, signal) =>
          invokeSdkMethod(client, "zipDownloads", "createZipDownload", [
            decoded.requestBody,
            mergeCancellation(decoded.optionalsInput, signal)
          ])
      ),
    getZipDownloadStatus: (payload) =>
      runSdkCall(
        "zipDownloads",
        "getZipDownloadStatus",
        "zipDownloads.getZipDownloadStatus",
        M.ZipDownloadsGetZipDownloadStatusPayload,
        M.ZipDownloadsGetZipDownloadStatusSuccess,
        payload,
        (decoded, signal) =>
          invokeSdkMethod(client, "zipDownloads", "getZipDownloadStatus", [
            decoded.statusUrl,
            mergeCancellation(decoded.optionalsInput, signal)
          ])
      ),
  },
});
