/**
 * Path-aware changeset status wrapper (lab-apps-lifecycle P2, ratified row 8).
 *
 * **Details**
 *
 * Lab apps under `apps/labs/**` are changeset-ceremony exempt: a lab-only
 * change set succeeds without consulting changesets, a change set with zero
 * lab paths runs stock `changeset status --since` for byte-parity, and a
 * mixed lab+product change set reimplements the stock requirement in-process
 * (every changed, versioned, non-ignored product workspace must be named by a
 * pending changeset) because the stock CLI cannot exclude lab packages
 * (P2-D12, mixed-PR policy Option B).
 *
 * @packageDocumentation
 * @since 0.0.0
 */

import { $RepoCliId } from "@beep/identity/packages";
import { findRepoRoot } from "@beep/repo-utils";
import { LiteralKit } from "@beep/schema";
import { A, Str, thunkFalse } from "@beep/utils";
import { Console, Effect, FileSystem, flow, Order, Path, pipe } from "effect";
import { dual } from "effect/Function";
import * as O from "effect/Option";
import * as P from "effect/Predicate";
import * as S from "effect/Schema";
import { Command, Flag } from "effect/unstable/cli";
import { failWithReportedExit } from "../../internal/cli/ExitCodeError.ts";
import { isLabsWorkspacePath } from "../../internal/cli/Labs/index.ts";
import { formatCommandLine, QualityTaskStep, runCaptured, runToExit } from "../../internal/process/index.ts";
import { changesetPackageReferencesFromText, collectWorkspacePackageJsonFiles } from "./ChangesetGraph.ts";
import { ChangesetStatusError } from "./Quality.errors.ts";
import type { ChildProcessSpawner } from "effect/unstable/process";
import type { CliReportedExit } from "../../internal/cli/ExitCodeError.ts";
import type { ChangesetGraphPackageReference } from "./ChangesetGraph.ts";

/**
 * Public changeset status error export.
 *
 * @category errors
 * @since 0.0.0
 */
export { ChangesetStatusError } from "./Quality.errors.ts";

const $I = $RepoCliId.create("commands/Quality/ChangesetStatus");

const nulSeparator = "\u0000";
const changesetDirName = ".changeset";
const changesetConfigPath = ".changeset/config.json";
const changesetReadmeFilename = "README.md";
const stockChangesetStatusLabel = "changeset-status:stock";

/**
 * Repo-relative path prefixes that neither block nor grant the lab-only
 * changeset exemption (P2-D13).
 *
 * **Example** (Inspect the neutral prefixes)
 *
 * ```ts
 * import { CHANGESET_STATUS_NEUTRAL_PATH_PREFIXES } from "@beep/repo-cli/commands/Quality/ChangesetStatus"
 *
 * console.log(CHANGESET_STATUS_NEUTRAL_PATH_PREFIXES.length)
 * ```
 *
 * @category configuration
 * @since 0.0.0
 */
export const CHANGESET_STATUS_NEUTRAL_PATH_PREFIXES: ReadonlyArray<string> = [
  "docs/",
  "goals/",
  "research/",
  "explorations/",
  ".changeset/",
];

/**
 * Exact repo-relative companion files regenerated by lab lifecycle tooling.
 *
 * **Details**
 *
 * The identity `packages.ts` carries the generated lab composer group, so a
 * lab create/delete rewrites it alongside the lab tree. It classifies neutral
 * even though it lives inside the identity workspace — otherwise every
 * lab-only change set would false-positive as a product change (P2-D13).
 *
 * **Example** (Inspect the companion files)
 *
 * ```ts
 * import { LAB_EXEMPT_COMPANION_PATHS } from "@beep/repo-cli/commands/Quality/ChangesetStatus"
 *
 * console.log(LAB_EXEMPT_COMPANION_PATHS[0])
 * ```
 *
 * @category configuration
 * @since 0.0.0
 */
export const LAB_EXEMPT_COMPANION_PATHS: ReadonlyArray<string> = [
  "packages/foundation/modeling/identity/src/packages.ts",
  // Minting or deleting a lab always refreshes the lockfile. Without this the
  // repo-root `bun.lock` classifies as a blocking path (no workspace owns a
  // path with no `/`), so `lab-exempt` is unreachable for every real lab PR
  // and the ratified D2 ceremony exemption never applies in practice.
  "bun.lock",
  // Same class: `fallow:boundaries:write` adds or removes a workspace's entries
  // in this generated registry on every lab create/delete, so leaving it
  // blocking would keep `lab-exempt` unreachable for exactly the PRs the
  // exemption exists for.
  "standards/fallow.boundaries.generated.jsonc",
];

/**
 * Changed-file partition computed from a merge-base diff (P2-D12).
 *
 * **Example** (Make a partition)
 *
 * ```ts
 * import { ChangesetStatusPartition } from "@beep/repo-cli/commands/Quality/ChangesetStatus"
 *
 * const partition = ChangesetStatusPartition.make({
 *   labPaths: ["apps/labs/cognee/src/main.ts"],
 *   productWorkspaceDirs: [],
 *   neutralPaths: [],
 *   blockingPaths: []
 * })
 * console.log(partition.labPaths)
 * ```
 *
 * @category models
 * @since 0.0.0
 */
export class ChangesetStatusPartition extends S.Class<ChangesetStatusPartition>($I`ChangesetStatusPartition`)(
  {
    labPaths: S.Array(S.String),
    productWorkspaceDirs: S.Array(S.String),
    neutralPaths: S.Array(S.String),
    blockingPaths: S.Array(S.String),
  },
  $I.annote("ChangesetStatusPartition", {
    description: "Changed-file partition used by the path-aware changeset status wrapper.",
  })
) {}

/**
 * Closed verdict domain of the path-aware changeset status wrapper
 * (P2-D12, mixed-PR policy Option B).
 *
 * **Example** (Use a verdict literal)
 *
 * ```ts
 * import { ChangesetStatusVerdict } from "@beep/repo-cli/commands/Quality/ChangesetStatus"
 *
 * const verdict: ChangesetStatusVerdict = "lab-exempt"
 * console.log(verdict)
 * ```
 *
 * @category schemas
 * @since 0.0.0
 */
export const ChangesetStatusVerdict = LiteralKit(["lab-exempt", "stock-parity", "mixed-reimplemented"]).pipe(
  $I.annoteSchema("ChangesetStatusVerdict", {
    description:
      "Path-aware changeset status verdict: lab-only exemption, stock parity, or the reimplemented mixed check.",
  })
);

/**
 * Decoded {@link ChangesetStatusVerdict} type.
 *
 * @category models
 * @since 0.0.0
 */
export type ChangesetStatusVerdict = typeof ChangesetStatusVerdict.Type;

/**
 * One changed product workspace considered by the reimplemented mixed check.
 *
 * **Example** (Make a workspace package)
 *
 * ```ts
 * import * as O from "effect/Option"
 * import { ChangesetStatusWorkspacePackage } from "@beep/repo-cli/commands/Quality/ChangesetStatus"
 *
 * const workspace = ChangesetStatusWorkspacePackage.make({
 *   dir: "packages/demo",
 *   name: "@beep/demo",
 *   version: O.some("0.0.0")
 * })
 * console.log(workspace.name)
 * ```
 *
 * @category models
 * @since 0.0.0
 */
export class ChangesetStatusWorkspacePackage extends S.Class<ChangesetStatusWorkspacePackage>(
  $I`ChangesetStatusWorkspacePackage`
)(
  {
    dir: S.String,
    name: S.String,
    version: S.OptionFromOptionalKey(S.String),
  },
  $I.annote("ChangesetStatusWorkspacePackage", {
    description: "A changed product workspace considered by the reimplemented mixed changeset check.",
  })
) {}

class ChangesetStatusPackageJson extends S.Class<ChangesetStatusPackageJson>($I`ChangesetStatusPackageJson`)(
  {
    name: S.optionalKey(S.String),
    version: S.optionalKey(S.String),
  },
  $I.annote("ChangesetStatusPackageJson", {
    description: "Minimal package.json shape read by the path-aware changeset status wrapper.",
  })
) {}

class ChangesetStatusChangesetConfig extends S.Class<ChangesetStatusChangesetConfig>(
  $I`ChangesetStatusChangesetConfig`
)(
  {
    ignore: S.Array(S.String).pipe(S.optionalKey),
  },
  $I.annote("ChangesetStatusChangesetConfig", {
    description: "Minimal .changeset/config.json shape read for the ignored package-name list.",
  })
) {}

const decodePackageJson = S.decodeUnknownEffect(S.fromJsonString(ChangesetStatusPackageJson));
const decodeChangesetConfig = S.decodeUnknownEffect(S.fromJsonString(ChangesetStatusChangesetConfig));

const toNulSeparatedPaths: (output: string) => ReadonlyArray<string> = flow(
  Str.split(nulSeparator),
  A.filter(Str.isNonEmpty),
  A.dedupe,
  A.sort(Order.String)
);

const workspaceDirFromPackageJsonPath = Str.replace(/\/package\.json$/, "");

const isChangesetStatusNeutralPath = (filePath: string): boolean =>
  A.contains(LAB_EXEMPT_COMPANION_PATHS, filePath) ||
  A.some(CHANGESET_STATUS_NEUTRAL_PATH_PREFIXES, (prefix) => Str.startsWith(prefix)(filePath));

const ownerWorkspaceDir =
  (workspaceDirs: ReadonlyArray<string>) =>
  (filePath: string): O.Option<string> =>
    A.findFirst(workspaceDirs, (dir) => Str.startsWith(`${dir}/`)(filePath));

const partitionImpl = (
  changedFiles: ReadonlyArray<string>,
  workspaceDirs: ReadonlyArray<string>
): ChangesetStatusPartition => {
  const files = pipe(changedFiles, A.dedupe, A.sort(Order.String));
  // Labs classify FIRST by path prefix so deleted/renamed lab paths with no
  // live workspace owner still classify as lab (P2-D12).
  const labPaths = A.filter(files, isLabsWorkspacePath);
  const nonLabFiles = A.filter(files, (filePath) => !isLabsWorkspacePath(filePath));
  // Neutral (incl. the companion file carve-out) precedes workspace ownership
  // so the regenerated identity packages.ts never blocks the exemption.
  const neutralPaths = A.filter(nonLabFiles, isChangesetStatusNeutralPath);
  const ownedCandidates = A.filter(nonLabFiles, (filePath) => !isChangesetStatusNeutralPath(filePath));
  const ownerFor = ownerWorkspaceDir(workspaceDirs);
  const productWorkspaceDirs = pipe(ownedCandidates, A.map(ownerFor), A.getSomes, A.dedupe, A.sort(Order.String));
  const blockingPaths = A.filter(ownedCandidates, flow(ownerFor, O.isNone));

  return ChangesetStatusPartition.make({
    labPaths,
    productWorkspaceDirs,
    neutralPaths,
    blockingPaths,
  });
};

/**
 * Partition merge-base changed files against the live workspace catalog.
 *
 * **Details**
 *
 * Classification order (P2-D12/P2-D13): labs path prefix first (so deleted or
 * renamed-away lab paths with no live owner still classify as lab), then the
 * neutral allowlist (prefixes plus exact companion files), then live
 * workspace-directory ownership, else blocking.
 *
 * **Example** (Partition a lab-only diff)
 *
 * ```ts
 * import { partitionChangedFilesForStatus } from "@beep/repo-cli/commands/Quality/ChangesetStatus"
 *
 * const partition = partitionChangedFilesForStatus(
 *   ["apps/labs/cognee/src/main.ts"],
 *   ["packages/demo", "apps/labs/cognee"]
 * )
 * console.log(partition.labPaths)
 * ```
 *
 * @param changedFiles - Repo-relative changed file paths from the merge-base diff.
 * @param workspaceDirs - Repo-relative live workspace directories.
 * @returns The changed-file partition.
 * @category utilities
 * @since 0.0.0
 */
export const partitionChangedFilesForStatus: {
  (workspaceDirs: ReadonlyArray<string>): (changedFiles: ReadonlyArray<string>) => ChangesetStatusPartition;
  (changedFiles: ReadonlyArray<string>, workspaceDirs: ReadonlyArray<string>): ChangesetStatusPartition;
} = dual(2, partitionImpl);

/**
 * Derive the wrapper verdict from a changed-file partition (P2-D12).
 *
 * **Details**
 *
 * Zero lab paths (including an empty diff) is `stock-parity`; a lab-only
 * change set (neutral paths do not block) is `lab-exempt`; lab paths plus any
 * product workspace or blocking path is `mixed-reimplemented`.
 *
 * **Example** (Judge an empty diff)
 *
 * ```ts
 * import { changesetStatusVerdict, partitionChangedFilesForStatus } from "@beep/repo-cli/commands/Quality/ChangesetStatus"
 *
 * console.log(changesetStatusVerdict(partitionChangedFilesForStatus([], ["packages/demo"])))
 * ```
 *
 * @param partition - Changed-file partition.
 * @returns The wrapper verdict.
 * @category utilities
 * @since 0.0.0
 */
export const changesetStatusVerdict = (partition: ChangesetStatusPartition): ChangesetStatusVerdict =>
  A.isReadonlyArrayEmpty(partition.labPaths)
    ? "stock-parity"
    : A.isReadonlyArrayEmpty(partition.productWorkspaceDirs) && A.isReadonlyArrayEmpty(partition.blockingPaths)
      ? "lab-exempt"
      : "mixed-reimplemented";

const stockChangesetStatusStep = (repoRoot: string, sinceArgs: ReadonlyArray<string>): QualityTaskStep =>
  QualityTaskStep.make({
    label: stockChangesetStatusLabel,
    command: "bunx",
    args: ["changeset", "status", ...sinceArgs],
    cwd: repoRoot,
  });

/**
 * Plan the stock passthrough invocation used when `--since` is absent.
 *
 * **Details**
 *
 * Passthrough mode preserves interactive stock semantics: one
 * `bunx changeset status` step with no `--since` and no partition (P2-D12).
 *
 * **Example** (Plan the passthrough step)
 *
 * ```ts
 * import { changesetStatusPassthroughSteps } from "@beep/repo-cli/commands/Quality/ChangesetStatus"
 *
 * console.log(changesetStatusPassthroughSteps("/repo")[0]?.args)
 * ```
 *
 * @param repoRoot - Repository root used as the subprocess working directory.
 * @returns The single stock passthrough step.
 * @category utilities
 * @since 0.0.0
 */
export const changesetStatusPassthroughSteps = (repoRoot: string): ReadonlyArray<QualityTaskStep> =>
  A.of(stockChangesetStatusStep(repoRoot, A.empty()));

const planStepsImpl = (
  repoRoot: string,
  verdict: ChangesetStatusVerdict,
  since: string
): ReadonlyArray<QualityTaskStep> =>
  ChangesetStatusVerdict.$match(verdict, {
    "lab-exempt": A.empty<QualityTaskStep>,
    "mixed-reimplemented": A.empty<QualityTaskStep>,
    "stock-parity": () => A.of(stockChangesetStatusStep(repoRoot, A.of(`--since=${since}`))),
  });

/**
 * Plan the subprocess steps for a `--since` run: the spawn seam for tests.
 *
 * **Details**
 *
 * `stock-parity` plans exactly one stock `changeset status --since` step;
 * `lab-exempt` and `mixed-reimplemented` plan none — the exemption succeeds
 * in-process and the mixed check is reimplemented rather than spawned
 * (P2-D12, Option B).
 *
 * **Example** (Plan a stock-parity run)
 *
 * ```ts
 * import { changesetStatusPlanSteps } from "@beep/repo-cli/commands/Quality/ChangesetStatus"
 *
 * console.log(changesetStatusPlanSteps("/repo", "stock-parity", "origin/main")[0]?.args)
 * ```
 *
 * @param repoRoot - Repository root used as the subprocess working directory.
 * @param verdict - Wrapper verdict for the change set.
 * @param since - Base ref forwarded to stock `changeset status`.
 * @returns Planned subprocess steps for the verdict.
 * @category utilities
 * @since 0.0.0
 */
export const changesetStatusPlanSteps: {
  (verdict: ChangesetStatusVerdict, since: string): (repoRoot: string) => ReadonlyArray<QualityTaskStep>;
  (repoRoot: string, verdict: ChangesetStatusVerdict, since: string): ReadonlyArray<QualityTaskStep>;
} = dual(3, planStepsImpl);

const uncoveredImpl = (
  workspaces: ReadonlyArray<ChangesetStatusWorkspacePackage>,
  ignoredPackageNames: ReadonlyArray<string>,
  references: ReadonlyArray<ChangesetGraphPackageReference>
): ReadonlyArray<string> =>
  pipe(
    workspaces,
    A.filter((workspace) => O.isSome(workspace.version)),
    A.filter((workspace) => !A.contains(ignoredPackageNames, workspace.name)),
    A.filter((workspace) => !A.some(references, (reference) => reference.packageName === workspace.name)),
    A.map((workspace) => workspace.name),
    A.dedupe,
    A.sort(Order.String)
  );

/**
 * Find changed product workspaces not named by any pending changeset.
 *
 * **Details**
 *
 * The reimplemented stock requirement (P2-D12, Option B): every changed
 * non-lab workspace that declares a version and is not in the
 * `.changeset/config.json` ignore list must be named by at least one pending
 * changeset. Versionless and ignored workspaces never require coverage.
 *
 * **Example** (Find uncovered workspaces)
 *
 * ```ts
 * import * as O from "effect/Option"
 * import { ChangesetStatusWorkspacePackage, uncoveredWorkspacePackageNames } from "@beep/repo-cli/commands/Quality/ChangesetStatus"
 *
 * const demo = ChangesetStatusWorkspacePackage.make({
 *   dir: "packages/demo",
 *   name: "@beep/demo",
 *   version: O.some("0.0.0")
 * })
 * console.log(uncoveredWorkspacePackageNames([demo], [], []))
 * ```
 *
 * @param workspaces - Changed product workspaces with their manifest facts.
 * @param ignoredPackageNames - Package names ignored by changesets config.
 * @param references - Package references parsed from pending changesets.
 * @returns Sorted package names missing changeset coverage.
 * @category utilities
 * @since 0.0.0
 */
export const uncoveredWorkspacePackageNames: {
  (
    ignoredPackageNames: ReadonlyArray<string>,
    references: ReadonlyArray<ChangesetGraphPackageReference>
  ): (workspaces: ReadonlyArray<ChangesetStatusWorkspacePackage>) => ReadonlyArray<string>;
  (
    workspaces: ReadonlyArray<ChangesetStatusWorkspacePackage>,
    ignoredPackageNames: ReadonlyArray<string>,
    references: ReadonlyArray<ChangesetGraphPackageReference>
  ): ReadonlyArray<string>;
} = dual(3, uncoveredImpl);

const collectChangedFilesSince = Effect.fn("ChangesetStatus.collectChangedFilesSince")(function* (
  repoRoot: string,
  since: string
): Effect.fn.Return<ReadonlyArray<string>, ChangesetStatusError, ChildProcessSpawner.ChildProcessSpawner> {
  const args = ["diff", "--name-only", "-z", "--no-renames", "--diff-filter=ACMRTUXBD", `${since}...HEAD`] as const;
  const result = yield* runCaptured({
    command: "git",
    args,
    cwd: repoRoot,
    source: "stdout",
  }).pipe(ChangesetStatusError.mapError(`Failed to run git ${A.join(args, " ")}.`));
  if (result.exitCode !== 0) {
    return yield* ChangesetStatusError.make({
      message: `git ${A.join(args, " ")} failed with exit code ${result.exitCode}.`,
    });
  }
  return toNulSeparatedPaths(result.output);
});

const readChangesetIgnoredPackageNames = Effect.fn("ChangesetStatus.readChangesetIgnoredPackageNames")(function* (
  repoRoot: string
): Effect.fn.Return<ReadonlyArray<string>, ChangesetStatusError, FileSystem.FileSystem | Path.Path> {
  const fs = yield* FileSystem.FileSystem;
  const path = yield* Path.Path;
  const configPath = path.join(repoRoot, changesetConfigPath);
  const exists = yield* fs.exists(configPath).pipe(Effect.orElseSucceed(thunkFalse));
  if (!exists) {
    return A.empty<string>();
  }
  const content = yield* fs
    .readFileString(configPath)
    .pipe(ChangesetStatusError.mapError(`Failed to read ${changesetConfigPath}.`, changesetConfigPath));
  const config = yield* decodeChangesetConfig(content).pipe(
    ChangesetStatusError.mapError(`Failed to parse ${changesetConfigPath}.`, changesetConfigPath)
  );
  return config.ignore ?? A.empty<string>();
});

const collectPendingChangesetReferences = Effect.fn("ChangesetStatus.collectPendingChangesetReferences")(function* (
  repoRoot: string
): Effect.fn.Return<
  ReadonlyArray<ChangesetGraphPackageReference>,
  ChangesetStatusError,
  FileSystem.FileSystem | Path.Path
> {
  const fs = yield* FileSystem.FileSystem;
  const path = yield* Path.Path;
  const changesetDir = path.join(repoRoot, changesetDirName);
  const exists = yield* fs.exists(changesetDir).pipe(Effect.orElseSucceed(thunkFalse));
  if (!exists) {
    return A.empty<ChangesetGraphPackageReference>();
  }
  const entries = yield* fs
    .readDirectory(changesetDir)
    .pipe(ChangesetStatusError.mapError(`Failed to list ${changesetDirName}.`));
  const changesetFiles = pipe(
    entries,
    A.filter((entry) => Str.endsWith(".md")(entry) && !Str.equivalence(entry, changesetReadmeFilename)),
    A.sort(Order.String)
  );
  const references = yield* Effect.forEach(
    changesetFiles,
    Effect.fn(function* (entry) {
      const file = `${changesetDirName}/${entry}`;
      const content = yield* fs
        .readFileString(path.join(changesetDir, entry))
        .pipe(ChangesetStatusError.mapError(`Failed to read changeset file ${file}.`, file));
      return yield* changesetPackageReferencesFromText(file, content).pipe(
        ChangesetStatusError.mapError(`Failed to parse changeset file ${file}.`, file)
      );
    }),
    { concurrency: 8 }
  );
  return A.flatten(references);
});

const collectChangedWorkspacePackages = Effect.fn("ChangesetStatus.collectChangedWorkspacePackages")(function* (
  repoRoot: string,
  workspaceDirs: ReadonlyArray<string>
): Effect.fn.Return<
  ReadonlyArray<ChangesetStatusWorkspacePackage>,
  ChangesetStatusError,
  FileSystem.FileSystem | Path.Path
> {
  const fs = yield* FileSystem.FileSystem;
  const path = yield* Path.Path;
  return yield* Effect.forEach(
    workspaceDirs,
    Effect.fn(function* (dir) {
      const manifestFile = `${dir}/package.json`;
      const content = yield* fs
        .readFileString(path.join(repoRoot, manifestFile))
        .pipe(ChangesetStatusError.mapError(`Failed to read package manifest ${manifestFile}.`, manifestFile));
      const document = yield* decodePackageJson(content).pipe(
        ChangesetStatusError.mapError(`Failed to parse package manifest ${manifestFile}.`, manifestFile)
      );
      if (P.isUndefined(document.name)) {
        return yield* ChangesetStatusError.make({
          message: `Workspace package manifest ${manifestFile} does not declare a package name.`,
          file: manifestFile,
        });
      }
      return ChangesetStatusWorkspacePackage.make({
        dir,
        name: document.name,
        version: O.fromUndefinedOr(document.version),
      });
    }),
    { concurrency: 8 }
  );
});

const runPlannedStep = Effect.fn("ChangesetStatus.runPlannedStep")(function* (
  step: QualityTaskStep
): Effect.fn.Return<void, ChangesetStatusError | CliReportedExit, ChildProcessSpawner.ChildProcessSpawner> {
  const exitCode = yield* runToExit({
    command: step.command,
    args: step.args,
    cwd: step.cwd,
    stdio: "inherit",
  }).pipe(ChangesetStatusError.mapError(`Failed to spawn ${formatCommandLine(step.command, step.args)}.`));
  if (exitCode !== 0) {
    return yield* failWithReportedExit(`${step.label} failed with exit code ${exitCode}.`, exitCode);
  }
});

const runPlannedSteps = Effect.fn("ChangesetStatus.runPlannedSteps")(function* (
  steps: ReadonlyArray<QualityTaskStep>
): Effect.fn.Return<void, ChangesetStatusError | CliReportedExit, ChildProcessSpawner.ChildProcessSpawner> {
  for (const step of steps) {
    yield* runPlannedStep(step);
  }
});

const runMixedReimplementedCheck = Effect.fn("ChangesetStatus.runMixedReimplementedCheck")(function* (
  repoRoot: string,
  partition: ChangesetStatusPartition
): Effect.fn.Return<void, ChangesetStatusError | CliReportedExit, FileSystem.FileSystem | Path.Path> {
  const workspaces = yield* collectChangedWorkspacePackages(repoRoot, partition.productWorkspaceDirs);
  const ignoredPackageNames = yield* readChangesetIgnoredPackageNames(repoRoot);
  const references = yield* collectPendingChangesetReferences(repoRoot);
  const uncovered = uncoveredWorkspacePackageNames(workspaces, ignoredPackageNames, references);

  if (A.isReadonlyArrayEmpty(uncovered)) {
    return yield* Console.log(
      "[changeset-status] mixed change set: every changed product workspace is named by a pending changeset."
    );
  }

  yield* Console.error("[changeset-status] changed product workspaces missing a pending changeset:");
  for (const packageName of uncovered) {
    yield* Console.error(`- ${packageName}`);
  }
  return yield* failWithReportedExit(
    "Changeset status validation failed: changed product workspaces lack pending changesets.",
    1
  );
});

/**
 * Run the path-aware changeset status wrapper.
 *
 * **Details**
 *
 * Without `--since` this is a stock passthrough: it spawns stock
 * `bunx changeset status` unchanged and propagates its exit. With `--since`
 * it partitions the
 * merge-base diff and applies the P2-D12 verdicts: `lab-exempt` succeeds
 * without spawning, `stock-parity` spawns stock `changeset status --since`,
 * and `mixed-reimplemented` verifies changeset coverage in-process, failing
 * through the reported-exit sentinel when product workspaces are uncovered.
 *
 * **Example** (Run the wrapper)
 *
 * ```ts
 * import * as O from "effect/Option"
 * import { runChangesetStatus } from "@beep/repo-cli/commands/Quality/ChangesetStatus"
 *
 * const program = runChangesetStatus(process.cwd(), O.some("origin/main"))
 * console.log(program) // example value
 * ```
 *
 * @param repoRoot - Repository root used for git and subprocess execution.
 * @param since - Optional base ref; absent selects stock passthrough mode.
 * @returns Effect completing when the change set passes changeset policy.
 * @category use-cases
 * @since 0.0.0
 */
export const runChangesetStatus = Effect.fn("ChangesetStatus.runChangesetStatus")(function* (
  repoRoot: string,
  since: O.Option<string>
): Effect.fn.Return<
  void,
  ChangesetStatusError | CliReportedExit,
  FileSystem.FileSystem | Path.Path | ChildProcessSpawner.ChildProcessSpawner
> {
  if (O.isNone(since)) {
    return yield* runPlannedSteps(changesetStatusPassthroughSteps(repoRoot));
  }

  const changedFiles = yield* collectChangedFilesSince(repoRoot, since.value);
  const workspacePackageJsonFiles = yield* collectWorkspacePackageJsonFiles(repoRoot).pipe(
    ChangesetStatusError.mapError("Failed to collect workspace package manifests.")
  );
  const workspaceDirs = A.map(workspacePackageJsonFiles, workspaceDirFromPackageJsonPath);
  const partition = partitionChangedFilesForStatus(changedFiles, workspaceDirs);
  const verdict = changesetStatusVerdict(partition);

  yield* Console.log(
    `[changeset-status] lab_paths=${A.length(partition.labPaths)} product_workspaces=${A.length(partition.productWorkspaceDirs)} neutral_paths=${A.length(partition.neutralPaths)} blocking_paths=${A.length(partition.blockingPaths)} verdict=${verdict}`
  );

  return yield* ChangesetStatusVerdict.$match(verdict, {
    "lab-exempt": () => Console.log("[changeset-status] changeset ceremony exempt: lab-only change set"),
    "stock-parity": () => runPlannedSteps(changesetStatusPlanSteps(repoRoot, verdict, since.value)),
    "mixed-reimplemented": () => runMixedReimplementedCheck(repoRoot, partition),
  });
});

/**
 * The `beep quality changeset-status` subcommand value.
 *
 * **Details**
 *
 * Built here and registered by `Quality.command.ts`. `--since` is optional
 * with no default: absent selects stock passthrough mode, present selects the
 * path-aware partition (P2-D12).
 *
 * **Example** (Inspect the command)
 *
 * ```ts
 * import { changesetStatusCommand } from "@beep/repo-cli/commands/Quality/ChangesetStatus"
 *
 * console.log(changesetStatusCommand)
 * ```
 *
 * @category cli-commands
 * @since 0.0.0
 */
export const changesetStatusCommand = Command.make(
  "changeset-status",
  {
    since: Flag.string("since").pipe(
      Flag.withDescription(
        "Base ref for the merge-base changed-file partition; omit to run stock `changeset status` unchanged"
      ),
      Flag.optional
    ),
  },
  ({ since }) =>
    findRepoRoot().pipe(
      ChangesetStatusError.mapError("Failed to locate repository root."),
      Effect.flatMap((repoRoot) => runChangesetStatus(repoRoot, since)),
      Effect.asVoid
    )
).pipe(
  Command.withDescription(
    "Path-aware changeset status: lab-only changes are ceremony-exempt, product changes keep stock changesets semantics"
  )
);
