/**
 * Generated eCFR value models and operation descriptors.
 *
 * Do not edit this file by hand. Run `bun run generate` to regenerate from
 * `openapi.json`. Transport stays hand-authored (see `Ecfr.service.ts`).
 *
 * @packageDocumentation
 * @since 0.0.0
 */

import { $EcfrId } from "@beep/identity";
import * as S from "effect/Schema";

const $I = $EcfrId.create("_generated/Ecfr.generated");

/**
 * A single agency represented in the CFR, with the naming and slug metadata the eCFR versioner reports for it.
 *
 * @example
 * ```ts
 * import { Agency } from "@beep/ecfr"
 *
 * const value = Agency.make({ "name": "example-name", "slug": "example-slug" })
 * console.log(value.name)
 * ```
 *
 * @category models
 * @since 0.0.0
 */
export class Agency extends S.Class<Agency>($I`Agency`)(
  {
    name: S.String.annotateKey({ description: "The full, official name of the agency." }),
    short_name: S.optionalKey(S.String).annotateKey({
      description: "Abbreviated form of the agency name, when eCFR provides one.",
    }),
    display_name: S.optionalKey(S.String).annotateKey({
      description: "Human-readable agency name intended for presentation in UI.",
    }),
    sortable_name: S.optionalKey(S.String).annotateKey({
      description: "Agency name normalized for alphabetical sorting (e.g. leading articles removed).",
    }),
    slug: S.String.annotateKey({
      description: "URL-safe identifier for the agency, used as its key in eCFR API paths.",
    }),
  },
  $I.annote("Agency", {
    description:
      "A single agency represented in the CFR, with the naming and slug metadata the eCFR versioner reports for it.",
  })
) {
  static readonly is = S.is(Agency);
}

/**
 * Response envelope for the eCFR agencies listing endpoint, wrapping the full roster of agencies represented in the CFR.
 *
 * @example
 * ```ts
 * import { AgenciesResponse, Agency } from "@beep/ecfr"
 *
 * const value = AgenciesResponse.make({ "agencies": [Agency.make({ "name": "example-name", "slug": "example-slug" })] })
 * console.log(value.agencies)
 * ```
 *
 * @category models
 * @since 0.0.0
 */
export class AgenciesResponse extends S.Class<AgenciesResponse>($I`AgenciesResponse`)(
  {
    agencies: S.Array(Agency).annotateKey({
      description: "The roster of agencies represented in the CFR, each with its naming and slug metadata.",
    }),
  },
  $I.annote("AgenciesResponse", {
    description:
      "Response envelope for the eCFR agencies listing endpoint, wrapping the full roster of agencies represented in the CFR.",
  })
) {
  static readonly is = S.is(AgenciesResponse);
}

/**
 * A single CFR title with the currency metadata the eCFR versioner reports for it (identity plus the dates that describe how current the published content is).
 *
 * @example
 * ```ts
 * import { Title } from "@beep/ecfr"
 *
 * const value = Title.make({ "number": 1, "name": "example-name", "reserved": true })
 * console.log(value.number)
 * ```
 *
 * @category models
 * @since 0.0.0
 */
export class Title extends S.Class<Title>($I`Title`)(
  {
    number: S.Int.annotateKey({
      description: "The CFR title number (1 through 50) that uniquely identifies the title.",
    }),
    name: S.String.annotateKey({ description: "The official name of the CFR title." }),
    latest_amended_on: S.optionalKey(S.String).annotateKey({
      description: "Date on which the title's regulatory content was most recently amended (ISO YYYY-MM-DD).",
    }), // date (YYYY-MM-DD)
    latest_issue_date: S.optionalKey(S.String).annotateKey({
      description: "Date of the most recent published issue of the title in eCFR (ISO YYYY-MM-DD).",
    }), // date (YYYY-MM-DD)
    up_to_date_as_of: S.optionalKey(S.String).annotateKey({
      description: "Date through which the title's content is confirmed current in eCFR (ISO YYYY-MM-DD).",
    }), // date (YYYY-MM-DD)
    reserved: S.Boolean.annotateKey({
      description: "Whether the title number is reserved, meaning it carries no current regulatory content.",
    }),
  },
  $I.annote("Title", {
    description:
      "A single CFR title with the currency metadata the eCFR versioner reports for it (identity plus the dates that describe how current the published content is).",
  })
) {
  static readonly is = S.is(Title);
}

/**
 * Response envelope for the eCFR titles listing endpoint, wrapping the full catalog of CFR titles.
 *
 * @example
 * ```ts
 * import { Title, TitlesResponse } from "@beep/ecfr"
 *
 * const value = TitlesResponse.make({ "titles": [Title.make({ "number": 1, "name": "example-name", "reserved": true })] })
 * console.log(value.titles)
 * ```
 *
 * @category models
 * @since 0.0.0
 */
export class TitlesResponse extends S.Class<TitlesResponse>($I`TitlesResponse`)(
  {
    titles: S.Array(Title).annotateKey({ description: "The catalog of CFR titles, each with its currency metadata." }),
  },
  $I.annote("TitlesResponse", {
    description: "Response envelope for the eCFR titles listing endpoint, wrapping the full catalog of CFR titles.",
  })
) {
  static readonly is = S.is(TitlesResponse);
}

/**
 * Descriptor for a single eCFR REST operation.
 *
 * @example
 * ```ts
 * import { EcfrOperationDescriptor } from "@beep/ecfr"
 *
 * const descriptor = EcfrOperationDescriptor.make({ method: "GET", operationId: "example", path: "/example.json" })
 * console.log(descriptor.path)
 * ```
 *
 * @category endpoints
 * @since 0.0.0
 */
export class EcfrOperationDescriptor extends S.Class<EcfrOperationDescriptor>($I`EcfrOperationDescriptor`)(
  {
    method: S.String,
    operationId: S.String,
    path: S.String,
  },
  $I.annote("EcfrOperationDescriptor", {
    description: "Descriptor for a single eCFR REST operation.",
  })
) {}

/**
 * The `listAgencies` eCFR operation descriptor.
 *
 * @example
 * ```ts
 * import { listAgenciesOperation } from "@beep/ecfr"
 *
 * console.log(listAgenciesOperation.path)
 * ```
 *
 * @category endpoints
 * @since 0.0.0
 */
export const listAgenciesOperation = EcfrOperationDescriptor.make({
  method: "GET",
  operationId: "listAgencies",
  path: "/agencies.json",
});

/**
 * The `listTitles` eCFR operation descriptor.
 *
 * @example
 * ```ts
 * import { listTitlesOperation } from "@beep/ecfr"
 *
 * console.log(listTitlesOperation.path)
 * ```
 *
 * @category endpoints
 * @since 0.0.0
 */
export const listTitlesOperation = EcfrOperationDescriptor.make({
  method: "GET",
  operationId: "listTitles",
  path: "/titles.json",
});

/**
 * All generated eCFR operation descriptors keyed by operation id.
 *
 * @example
 * ```ts
 * import { ECFR_OPERATIONS } from "@beep/ecfr"
 *
 * console.log(ECFR_OPERATIONS.listAgencies.descriptor.path)
 * ```
 *
 * @category endpoints
 * @since 0.0.0
 */
export const ECFR_OPERATIONS = {
  listAgencies: { descriptor: listAgenciesOperation, response: AgenciesResponse },
  listTitles: { descriptor: listTitlesOperation, response: TitlesResponse },
} as const;
