/**
 * Generated eCFR HttpApi contract. Do not edit this file by hand.
 *
 * Run `bun run generate` after changing `openapi.json`.
 *
 * @packageDocumentation
 * @since 0.0.0
 */

import * as Schema from "effect/Schema";
import { HttpApi, HttpApiEndpoint, HttpApiGroup, HttpApiSchema, OpenApi } from "effect/unstable/httpapi";
// non-recursive definitions
export type AgenciesResponse = {
  readonly agencies: ReadonlyArray<{
    readonly name: string;
    readonly short_name?: string;
    readonly display_name?: string;
    readonly sortable_name?: string;
    readonly slug: string;
    readonly children?: ReadonlyArray<{
      readonly name: string;
      readonly short_name?: string;
      readonly display_name?: string;
      readonly sortable_name?: string;
      readonly slug: string;
      readonly cfr_references?: ReadonlyArray<{ readonly title: number; readonly chapter: string }>;
    }>;
    readonly cfr_references?: ReadonlyArray<{ readonly title: number; readonly chapter: string }>;
  }>;
};
export const AgenciesResponse = Schema.Struct({
  agencies: Schema.Array(
    Schema.Struct({
      name: Schema.String.annotate({ description: "Full official agency name." }),
      short_name: Schema.optionalKey(Schema.String.annotate({ description: "Agency abbreviation when supplied." })),
      display_name: Schema.optionalKey(Schema.String.annotate({ description: "Human-readable agency display name." })),
      sortable_name: Schema.optionalKey(
        Schema.String.annotate({ description: "Agency name normalized for alphabetical sorting." })
      ),
      slug: Schema.String.annotate({ description: "URL-safe agency identifier." }),
      children: Schema.optionalKey(
        Schema.Array(
          Schema.Struct({
            name: Schema.String.annotate({ description: "Full official agency name." }),
            short_name: Schema.optionalKey(
              Schema.String.annotate({ description: "Agency abbreviation when supplied." })
            ),
            display_name: Schema.optionalKey(
              Schema.String.annotate({ description: "Human-readable agency display name." })
            ),
            sortable_name: Schema.optionalKey(
              Schema.String.annotate({ description: "Agency name normalized for alphabetical sorting." })
            ),
            slug: Schema.String.annotate({ description: "URL-safe agency identifier." }),
            cfr_references: Schema.optionalKey(
              Schema.Array(
                Schema.Struct({
                  title: Schema.Int.annotate({ description: "CFR title number." }),
                  chapter: Schema.String.annotate({ description: "Chapter identifier within the title." }),
                }).annotate({ description: "A CFR title and chapter reference associated with an agency." })
              ).annotate({ description: "CFR chapters assigned to the child agency." })
            ),
          }).annotate({ description: "A child agency represented in the CFR agency roster." })
        ).annotate({ description: "Child agencies in name order." })
      ),
      cfr_references: Schema.optionalKey(
        Schema.Array(
          Schema.Struct({
            title: Schema.Int.annotate({ description: "CFR title number." }),
            chapter: Schema.String.annotate({ description: "Chapter identifier within the title." }),
          }).annotate({ description: "A CFR title and chapter reference associated with an agency." })
        ).annotate({ description: "CFR chapters assigned directly to the agency." })
      ),
    }).annotate({
      description: "A top-level agency represented in the CFR, including child agencies and CFR references.",
    })
  ).annotate({ description: "Top-level agencies in name order." }),
}).annotate({ description: "Response envelope containing the agency roster.", identifier: "AgenciesResponse" });
export type CorrectionsResponse = {
  readonly ecfr_corrections: ReadonlyArray<{
    readonly id: number;
    readonly cfr_references?: ReadonlyArray<{
      readonly cfr_reference: string;
      readonly hierarchy: {
        readonly title?: string;
        readonly subtitle?: string;
        readonly chapter?: string;
        readonly subchapter?: string;
        readonly part?: string;
        readonly subpart?: string;
        readonly section?: string;
        readonly appendix?: string;
      };
    }>;
    readonly corrective_action?: string;
    readonly error_corrected?: string;
    readonly error_occurred?: string;
    readonly fr_citation?: string;
    readonly position?: number;
    readonly display_in_toc?: boolean;
    readonly title: number;
    readonly year?: number;
    readonly last_modified?: string;
  }>;
};
export const CorrectionsResponse = Schema.Struct({
  ecfr_corrections: Schema.Array(
    Schema.Struct({
      id: Schema.Int.annotate({ description: "Stable correction record identifier." }),
      cfr_references: Schema.optionalKey(
        Schema.Array(
          Schema.Struct({
            cfr_reference: Schema.String.annotate({
              description: "Human-readable CFR citation for the corrected content.",
            }),
            hierarchy: Schema.Struct({
              title: Schema.optionalKey(Schema.String.annotate({ description: "CFR title identifier." })),
              subtitle: Schema.optionalKey(
                Schema.String.annotate({ description: "Subtitle identifier when present." })
              ),
              chapter: Schema.optionalKey(Schema.String.annotate({ description: "Chapter identifier when present." })),
              subchapter: Schema.optionalKey(
                Schema.String.annotate({ description: "Subchapter identifier when present." })
              ),
              part: Schema.optionalKey(Schema.String.annotate({ description: "Part identifier when present." })),
              subpart: Schema.optionalKey(Schema.String.annotate({ description: "Subpart identifier when present." })),
              section: Schema.optionalKey(Schema.String.annotate({ description: "Section identifier when present." })),
              appendix: Schema.optionalKey(
                Schema.String.annotate({ description: "Appendix identifier when present." })
              ),
            }).annotate({ description: "Known CFR hierarchy identifiers locating corrected content." }),
          }).annotate({ description: "Human-readable and structured CFR location for a correction." })
        ).annotate({ description: "CFR locations affected by the correction." })
      ),
      corrective_action: Schema.optionalKey(
        Schema.String.annotate({ description: "Description of the corrective editorial action." })
      ),
      error_corrected: Schema.optionalKey(
        Schema.String.annotate({ description: "Date the error was corrected.", format: "date" })
      ),
      error_occurred: Schema.optionalKey(
        Schema.String.annotate({ description: "Date the error entered the eCFR material.", format: "date" })
      ),
      fr_citation: Schema.optionalKey(
        Schema.String.annotate({ description: "Federal Register citation associated with the correction." })
      ),
      position: Schema.optionalKey(
        Schema.Int.annotate({ description: "Display order among corrections for the same source." })
      ),
      display_in_toc: Schema.optionalKey(
        Schema.Boolean.annotate({ description: "Whether the correction is displayed in the table of contents." })
      ),
      title: Schema.Int.annotate({ description: "Affected CFR title number." }),
      year: Schema.optionalKey(Schema.Int.annotate({ description: "Calendar year associated with the correction." })),
      last_modified: Schema.optionalKey(
        Schema.String.annotate({ description: "Date the correction record was last modified.", format: "date" })
      ),
    }).annotate({ description: "An eCFR editorial correction and its affected CFR locations." })
  ).annotate({ description: "Correction records matching the request." }),
}).annotate({
  description: "Response envelope containing eCFR correction records.",
  identifier: "CorrectionsResponse",
});
export type SearchResultsResponse = {
  readonly results: ReadonlyArray<{
    readonly title?: number;
    readonly type?: string;
    readonly hierarchy_headings?: ReadonlyArray<string>;
    readonly headings?: ReadonlyArray<string>;
    readonly full_text_excerpt?: string;
    readonly score?: number;
  }>;
  readonly meta: {
    readonly description?: string;
    readonly current_page: number;
    readonly total_count: number;
    readonly total_pages: number;
    readonly max_score?: number;
    readonly min_date?: string;
    readonly max_date?: string;
  };
};
export const SearchResultsResponse = Schema.Struct({
  results: Schema.Array(
    Schema.Struct({
      title: Schema.optionalKey(Schema.Int.annotate({ description: "CFR title number containing the match." })),
      type: Schema.optionalKey(Schema.String.annotate({ description: "Hierarchy node type of the matching content." })),
      hierarchy_headings: Schema.optionalKey(
        Schema.Array(Schema.String).annotate({
          description: "Ordered headings locating the match in the CFR hierarchy.",
        })
      ),
      headings: Schema.optionalKey(
        Schema.Array(Schema.String).annotate({ description: "Headings associated with the matching content." })
      ),
      full_text_excerpt: Schema.optionalKey(
        Schema.String.annotate({ description: "Highlighted excerpt surrounding the matching text." })
      ),
      score: Schema.optionalKey(
        Schema.Int.annotate({ description: "Search relevance score when supplied." }).check(
          Schema.isFinite().annotate({ expected: "a finite number" })
        )
      ),
    }).annotate({ description: "A section or appendix matching an eCFR search." })
  ).annotate({ description: "Sections and appendices matching the request." }),
  meta: Schema.Struct({
    description: Schema.optionalKey(
      Schema.String.annotate({ description: "Human-readable description of the search results." })
    ),
    current_page: Schema.Finite.annotate({ description: "One-based current result page." }),
    total_count: Schema.Int.annotate({ description: "Total number of matching results across all pages." }),
    total_pages: Schema.Int.annotate({ description: "Total number of result pages." }),
    max_score: Schema.optionalKey(
      Schema.Finite.annotate({ description: "Maximum relevance score among matches." }).check(
        Schema.isFinite().annotate({ expected: "a finite number" })
      )
    ),
    min_date: Schema.optionalKey(
      Schema.String.annotate({ description: "Minimum result date when paginating by date.", format: "date" })
    ),
    max_date: Schema.optionalKey(
      Schema.String.annotate({ description: "Maximum result date when paginating by date.", format: "date" })
    ),
  }).annotate({ description: "Pagination and score metadata for eCFR search results." }),
}).annotate({ description: "Paginated eCFR search-results envelope.", identifier: "SearchResultsResponse" });
export type SearchCountResponse = { readonly count?: number; readonly total_count?: number };
export const SearchCountResponse = Schema.Struct({
  count: Schema.optionalKey(
    Schema.Int.annotate({ description: "Number of matching search results when supplied by the service." })
  ),
  total_count: Schema.optionalKey(
    Schema.Int.annotate({
      description: "Total matching result count when supplied under the paginated-result field name.",
    })
  ),
}).annotate({
  description: "Conservative envelope for the eCFR search count endpoint.",
  identifier: "SearchCountResponse",
});
export type SearchSummaryResponse = { readonly description?: string; readonly count?: number };
export const SearchSummaryResponse = Schema.Struct({
  description: Schema.optionalKey(Schema.String.annotate({ description: "Human-readable search summary." })),
  count: Schema.optionalKey(Schema.Int.annotate({ description: "Matching result count when included." })),
}).annotate({
  description:
    "Conservative envelope for eCFR search summary details; all known fields remain optional because the official spec leaves the response schema unspecified.",
  identifier: "SearchSummaryResponse",
});
export type SearchDailyCountsResponse = {
  readonly counts?: ReadonlyArray<{ readonly date?: string; readonly count?: number }>;
};
export const SearchDailyCountsResponse = Schema.Struct({
  counts: Schema.optionalKey(
    Schema.Array(
      Schema.Struct({
        date: Schema.optionalKey(
          Schema.String.annotate({ description: "ISO date represented by the bucket.", format: "date" })
        ),
        count: Schema.optionalKey(Schema.Int.annotate({ description: "Number of matches in the date bucket." })),
      }).annotate({ description: "Search-result count associated with one date." })
    ).annotate({ description: "Daily result-count buckets when supplied." })
  ),
}).annotate({
  description: "Conservative envelope for daily eCFR search counts.",
  identifier: "SearchDailyCountsResponse",
});
export type SearchTitleCountsResponse = {
  readonly counts?: ReadonlyArray<{ readonly title?: number; readonly count?: number }>;
};
export const SearchTitleCountsResponse = Schema.Struct({
  counts: Schema.optionalKey(
    Schema.Array(
      Schema.Struct({
        title: Schema.optionalKey(Schema.Int.annotate({ description: "CFR title number represented by the bucket." })),
        count: Schema.optionalKey(Schema.Int.annotate({ description: "Number of matches in the title bucket." })),
      }).annotate({ description: "Search-result count associated with one CFR title." })
    ).annotate({ description: "Per-title result-count buckets when supplied." })
  ),
}).annotate({
  description: "Conservative envelope for per-title eCFR search counts.",
  identifier: "SearchTitleCountsResponse",
});
export type SearchHierarchyCountsResponse = {
  readonly counts?: ReadonlyArray<{ readonly label?: string; readonly identifier?: string; readonly count?: number }>;
};
export const SearchHierarchyCountsResponse = Schema.Struct({
  counts: Schema.optionalKey(
    Schema.Array(
      Schema.Struct({
        label: Schema.optionalKey(Schema.String.annotate({ description: "Human-readable hierarchy label." })),
        identifier: Schema.optionalKey(Schema.String.annotate({ description: "Hierarchy node identifier." })),
        count: Schema.optionalKey(Schema.Int.annotate({ description: "Number of matches in the hierarchy bucket." })),
      }).annotate({ description: "Search-result count associated with one CFR hierarchy node." })
    ).annotate({ description: "Hierarchy result-count buckets when supplied." })
  ),
}).annotate({
  description: "Conservative envelope for hierarchy-level eCFR search counts.",
  identifier: "SearchHierarchyCountsResponse",
});
export type SearchSuggestionsResponse = { readonly suggestions?: ReadonlyArray<string> };
export const SearchSuggestionsResponse = Schema.Struct({
  suggestions: Schema.optionalKey(
    Schema.Array(Schema.String).annotate({ description: "Suggested search strings when supplied." })
  ),
}).annotate({
  description: "Conservative envelope for eCFR search suggestions.",
  identifier: "SearchSuggestionsResponse",
});
export type AncestryResponse = ReadonlyArray<{
  readonly type: string;
  readonly label: string;
  readonly label_level?: string;
  readonly label_description?: string;
  readonly identifier: string;
  readonly reserved?: boolean;
  readonly section_range?: string;
}>;
export const AncestryResponse = Schema.Array(
  Schema.Struct({
    type: Schema.String.annotate({ description: "Hierarchy level such as title, chapter, part, or section." }),
    label: Schema.String.annotate({ description: "Complete human-readable node label." }),
    label_level: Schema.optionalKey(Schema.String.annotate({ description: "Hierarchy level portion of the label." })),
    label_description: Schema.optionalKey(Schema.String.annotate({ description: "Descriptive portion of the label." })),
    identifier: Schema.String.annotate({ description: "Identifier within the node's hierarchy level." }),
    reserved: Schema.optionalKey(Schema.Boolean.annotate({ description: "Whether the hierarchy node is reserved." })),
    section_range: Schema.optionalKey(
      Schema.String.annotate({ description: "Section range covered by the node when supplied." })
    ),
  }).annotate({ description: "A CFR hierarchy node returned in an ancestry response." })
).annotate({
  description: "Ordered CFR hierarchy nodes from title through the requested leaf.",
  identifier: "AncestryResponse",
});
export type StructureNode = {
  readonly type: string;
  readonly label: string;
  readonly label_level?: string;
  readonly label_description?: string;
  readonly identifier: string;
  readonly reserved?: boolean;
  readonly section_range?: string;
  readonly children?: ReadonlyArray<{
    readonly type: string;
    readonly label: string;
    readonly label_level?: string;
    readonly label_description?: string;
    readonly identifier: string;
    readonly reserved?: boolean;
    readonly section_range?: string;
  }>;
};
export const StructureNode = Schema.Struct({
  type: Schema.String.annotate({ description: "Hierarchy level of the root node." }),
  label: Schema.String.annotate({ description: "Complete human-readable root label." }),
  label_level: Schema.optionalKey(
    Schema.String.annotate({ description: "Hierarchy level portion of the root label." })
  ),
  label_description: Schema.optionalKey(
    Schema.String.annotate({ description: "Descriptive portion of the root label." })
  ),
  identifier: Schema.String.annotate({ description: "Identifier within the hierarchy level." }),
  reserved: Schema.optionalKey(Schema.Boolean.annotate({ description: "Whether the root node is reserved." })),
  section_range: Schema.optionalKey(Schema.String.annotate({ description: "Section range covered by the root node." })),
  children: Schema.optionalKey(
    Schema.Array(
      Schema.Struct({
        type: Schema.String.annotate({ description: "Hierarchy level of the child node." }),
        label: Schema.String.annotate({ description: "Complete human-readable child label." }),
        label_level: Schema.optionalKey(
          Schema.String.annotate({ description: "Hierarchy level portion of the child label." })
        ),
        label_description: Schema.optionalKey(
          Schema.String.annotate({ description: "Descriptive portion of the child label." })
        ),
        identifier: Schema.String.annotate({ description: "Identifier within the hierarchy level." }),
        reserved: Schema.optionalKey(Schema.Boolean.annotate({ description: "Whether the child node is reserved." })),
        section_range: Schema.optionalKey(
          Schema.String.annotate({ description: "Section range covered by the child node." })
        ),
      }).annotate({ description: "A direct child in an eCFR structure tree." })
    ).annotate({ description: "Direct child nodes. Deeper tree parsing is intentionally conservative in v1." })
  ),
}).annotate({
  description: "Root of a CFR title structure tree without regulation text.",
  identifier: "StructureNode",
});
export type TitlesResponse = {
  readonly titles: ReadonlyArray<{
    readonly number: number;
    readonly name: string;
    readonly latest_amended_on?: string;
    readonly latest_issue_date?: string;
    readonly up_to_date_as_of?: string;
    readonly reserved: boolean;
    readonly processing_in_progress?: boolean;
  }>;
  readonly meta?: { readonly date?: string; readonly import_in_progress?: boolean };
};
export const TitlesResponse = Schema.Struct({
  titles: Schema.Array(
    Schema.Struct({
      number: Schema.Int.annotate({ description: "CFR title number, from 1 through 50." }),
      name: Schema.String.annotate({ description: "Official CFR title name." }),
      latest_amended_on: Schema.optionalKey(
        Schema.String.annotate({ description: "Most recent amendment date.", format: "date" })
      ),
      latest_issue_date: Schema.optionalKey(
        Schema.String.annotate({ description: "Most recent published issue date.", format: "date" })
      ),
      up_to_date_as_of: Schema.optionalKey(
        Schema.String.annotate({ description: "Date through which the title is confirmed current.", format: "date" })
      ),
      reserved: Schema.Boolean.annotate({ description: "Whether the title number is reserved." }),
      processing_in_progress: Schema.optionalKey(
        Schema.Boolean.annotate({ description: "Whether title processing is currently in progress." })
      ),
    }).annotate({ description: "A CFR title with currency and processing metadata." })
  ).annotate({ description: "CFR titles and their currency metadata." }),
  meta: Schema.optionalKey(
    Schema.Struct({
      date: Schema.optionalKey(Schema.String.annotate({ description: "Metadata snapshot date.", format: "date" })),
      import_in_progress: Schema.optionalKey(
        Schema.Boolean.annotate({ description: "Whether an eCFR title import is in progress." })
      ),
    }).annotate({ description: "Import status metadata accompanying the CFR titles catalog." })
  ),
}).annotate({
  description: "Response envelope containing the CFR titles catalog and import metadata.",
  identifier: "TitlesResponse",
});
export type VersionsResponse = {
  readonly content_versions: ReadonlyArray<{
    readonly date?: string;
    readonly amendment_date?: string;
    readonly issue_date?: string;
    readonly identifier: string;
    readonly name?: string;
    readonly part?: string;
    readonly substantive?: boolean;
    readonly removed?: boolean;
    readonly subpart?: string;
    readonly title: string;
    readonly type: string;
  }>;
  readonly meta: {
    readonly title?: string;
    readonly result_count?: string;
    readonly latest_amendment_date?: string;
    readonly latest_issue_date?: string;
  };
};
export const VersionsResponse = Schema.Struct({
  content_versions: Schema.Array(
    Schema.Struct({
      date: Schema.optionalKey(
        Schema.String.annotate({
          description: "Deprecated alias of amendment_date retained by the API.",
          format: "date",
        })
      ),
      amendment_date: Schema.optionalKey(
        Schema.String.annotate({ description: "Date the content was amended.", format: "date" })
      ),
      issue_date: Schema.optionalKey(
        Schema.String.annotate({ description: "Issue date on which this content version appeared.", format: "date" })
      ),
      identifier: Schema.String.annotate({ description: "Section or appendix identifier." }),
      name: Schema.optionalKey(Schema.String.annotate({ description: "Human-readable content name." })),
      part: Schema.optionalKey(Schema.String.annotate({ description: "Containing CFR part identifier." })),
      substantive: Schema.optionalKey(Schema.Boolean.annotate({ description: "Whether the change is substantive." })),
      removed: Schema.optionalKey(
        Schema.Boolean.annotate({ description: "Whether the content was removed in this version." })
      ),
      subpart: Schema.optionalKey(
        Schema.String.annotate({ description: "Containing subpart identifier when present." })
      ),
      title: Schema.String.annotate({ description: "Containing CFR title identifier." }),
      type: Schema.String.annotate({ description: "Content type, normally section or appendix." }),
    }).annotate({ description: "A dated version of one CFR section or appendix." })
  ).annotate({ description: "Content versions matching the request." }),
  meta: Schema.Struct({
    title: Schema.optionalKey(Schema.String.annotate({ description: "Requested CFR title identifier." })),
    result_count: Schema.optionalKey(
      Schema.String.annotate({ description: "Number of content versions returned, as encoded by the upstream API." })
    ),
    latest_amendment_date: Schema.optionalKey(
      Schema.String.annotate({ description: "Latest amendment date among returned versions.", format: "date" })
    ),
    latest_issue_date: Schema.optionalKey(
      Schema.String.annotate({ description: "Latest issue date among returned versions.", format: "date" })
    ),
  }).annotate({ description: "Query and currency metadata for a content-version response." }),
}).annotate({
  description: "Response envelope containing CFR content versions and query metadata.",
  identifier: "VersionsResponse",
});
// schemas
export type ListAgencies200 = AgenciesResponse;
export const ListAgencies200 = AgenciesResponse;
export type ListCorrectionsParams = {
  readonly date?: string;
  readonly title?: string;
  readonly error_corrected_date?: string;
};
export const ListCorrectionsParams = Schema.Struct({
  date: Schema.optionalKey(Schema.String.annotate({ format: "date" })),
  title: Schema.optionalKey(Schema.String),
  error_corrected_date: Schema.optionalKey(Schema.String.annotate({ format: "date" })),
});
export type ListCorrectionsQuery = {
  readonly date?: string;
  readonly title?: string;
  readonly error_corrected_date?: string;
};
export const ListCorrectionsQuery = Schema.Struct({
  date: Schema.optionalKey(Schema.String.annotate({ format: "date" })),
  title: Schema.optionalKey(Schema.String),
  error_corrected_date: Schema.optionalKey(Schema.String.annotate({ format: "date" })),
});
export type ListCorrections200 = CorrectionsResponse;
export const ListCorrections200 = CorrectionsResponse;
export type ListTitleCorrectionsPathParams = { readonly title: string };
export const ListTitleCorrectionsPathParams = Schema.Struct({ title: Schema.String });
export type ListTitleCorrections200 = CorrectionsResponse;
export const ListTitleCorrections200 = CorrectionsResponse;
export type SearchResultsParams = {
  readonly query?: string;
  readonly "agency_slugs[]"?: ReadonlyArray<string>;
  readonly date?: string;
  readonly order?: "citations" | "hierarchy" | "newest_first" | "oldest_first" | "relevance" | "suggestions";
  readonly paginate_by?: "date" | "results";
  readonly page?: number;
  readonly per_page?: number;
  readonly last_modified_after?: string;
  readonly last_modified_before?: string;
  readonly last_modified_on_or_after?: string;
  readonly last_modified_on_or_before?: string;
};
export const SearchResultsParams = Schema.Struct({
  query: Schema.optionalKey(Schema.String),
  "agency_slugs[]": Schema.Array(Schema.String).pipe(Schema.optionalKey),
  date: Schema.optionalKey(Schema.String.annotate({ format: "date" })),
  order: Schema.optionalKey(
    Schema.Literals(["citations", "hierarchy", "newest_first", "oldest_first", "relevance", "suggestions"])
  ),
  paginate_by: Schema.optionalKey(Schema.Literals(["date", "results"])),
  page: Schema.optionalKey(Schema.Int.annotate({ default: 1 })),
  per_page: Schema.optionalKey(Schema.Int.annotate({ default: 20 })),
  last_modified_after: Schema.optionalKey(Schema.String),
  last_modified_before: Schema.optionalKey(Schema.String),
  last_modified_on_or_after: Schema.optionalKey(Schema.String),
  last_modified_on_or_before: Schema.optionalKey(Schema.String),
});
export type SearchResultsQuery = {
  readonly query?: string;
  readonly "agency_slugs[]"?: ReadonlyArray<string>;
  readonly date?: string;
  readonly order?: "citations" | "hierarchy" | "newest_first" | "oldest_first" | "relevance" | "suggestions";
  readonly paginate_by?: "date" | "results";
  readonly page?: number;
  readonly per_page?: number;
  readonly last_modified_after?: string;
  readonly last_modified_before?: string;
  readonly last_modified_on_or_after?: string;
  readonly last_modified_on_or_before?: string;
};
export const SearchResultsQuery = Schema.Struct({
  query: Schema.optionalKey(Schema.String),
  "agency_slugs[]": Schema.Array(Schema.String).pipe(Schema.optionalKey),
  date: Schema.optionalKey(Schema.String.annotate({ format: "date" })),
  order: Schema.optionalKey(
    Schema.Literals(["citations", "hierarchy", "newest_first", "oldest_first", "relevance", "suggestions"])
  ),
  paginate_by: Schema.optionalKey(Schema.Literals(["date", "results"])),
  page: Schema.optionalKey(Schema.Int.annotate({ default: 1 })),
  per_page: Schema.optionalKey(Schema.Int.annotate({ default: 20 })),
  last_modified_after: Schema.optionalKey(Schema.String),
  last_modified_before: Schema.optionalKey(Schema.String),
  last_modified_on_or_after: Schema.optionalKey(Schema.String),
  last_modified_on_or_before: Schema.optionalKey(Schema.String),
});
export type SearchResults200 = SearchResultsResponse;
export const SearchResults200 = SearchResultsResponse;
export type SearchCountParams = {
  readonly query?: string;
  readonly "agency_slugs[]"?: ReadonlyArray<string>;
  readonly date?: string;
  readonly order?: "citations" | "hierarchy" | "newest_first" | "oldest_first" | "relevance" | "suggestions";
  readonly paginate_by?: "date" | "results";
  readonly page?: number;
  readonly per_page?: number;
  readonly last_modified_after?: string;
  readonly last_modified_before?: string;
  readonly last_modified_on_or_after?: string;
  readonly last_modified_on_or_before?: string;
};
export const SearchCountParams = Schema.Struct({
  query: Schema.optionalKey(Schema.String),
  "agency_slugs[]": Schema.Array(Schema.String).pipe(Schema.optionalKey),
  date: Schema.optionalKey(Schema.String.annotate({ format: "date" })),
  order: Schema.optionalKey(
    Schema.Literals(["citations", "hierarchy", "newest_first", "oldest_first", "relevance", "suggestions"])
  ),
  paginate_by: Schema.optionalKey(Schema.Literals(["date", "results"])),
  page: Schema.optionalKey(Schema.Int.annotate({ default: 1 })),
  per_page: Schema.optionalKey(Schema.Int.annotate({ default: 20 })),
  last_modified_after: Schema.optionalKey(Schema.String),
  last_modified_before: Schema.optionalKey(Schema.String),
  last_modified_on_or_after: Schema.optionalKey(Schema.String),
  last_modified_on_or_before: Schema.optionalKey(Schema.String),
});
export type SearchCountQuery = {
  readonly query?: string;
  readonly "agency_slugs[]"?: ReadonlyArray<string>;
  readonly date?: string;
  readonly order?: "citations" | "hierarchy" | "newest_first" | "oldest_first" | "relevance" | "suggestions";
  readonly paginate_by?: "date" | "results";
  readonly page?: number;
  readonly per_page?: number;
  readonly last_modified_after?: string;
  readonly last_modified_before?: string;
  readonly last_modified_on_or_after?: string;
  readonly last_modified_on_or_before?: string;
};
export const SearchCountQuery = Schema.Struct({
  query: Schema.optionalKey(Schema.String),
  "agency_slugs[]": Schema.Array(Schema.String).pipe(Schema.optionalKey),
  date: Schema.optionalKey(Schema.String.annotate({ format: "date" })),
  order: Schema.optionalKey(
    Schema.Literals(["citations", "hierarchy", "newest_first", "oldest_first", "relevance", "suggestions"])
  ),
  paginate_by: Schema.optionalKey(Schema.Literals(["date", "results"])),
  page: Schema.optionalKey(Schema.Int.annotate({ default: 1 })),
  per_page: Schema.optionalKey(Schema.Int.annotate({ default: 20 })),
  last_modified_after: Schema.optionalKey(Schema.String),
  last_modified_before: Schema.optionalKey(Schema.String),
  last_modified_on_or_after: Schema.optionalKey(Schema.String),
  last_modified_on_or_before: Schema.optionalKey(Schema.String),
});
export type SearchCount200 = SearchCountResponse;
export const SearchCount200 = SearchCountResponse;
export type SearchSummaryParams = {
  readonly query?: string;
  readonly "agency_slugs[]"?: ReadonlyArray<string>;
  readonly date?: string;
  readonly order?: "citations" | "hierarchy" | "newest_first" | "oldest_first" | "relevance" | "suggestions";
  readonly paginate_by?: "date" | "results";
  readonly page?: number;
  readonly per_page?: number;
  readonly last_modified_after?: string;
  readonly last_modified_before?: string;
  readonly last_modified_on_or_after?: string;
  readonly last_modified_on_or_before?: string;
};
export const SearchSummaryParams = Schema.Struct({
  query: Schema.optionalKey(Schema.String),
  "agency_slugs[]": Schema.Array(Schema.String).pipe(Schema.optionalKey),
  date: Schema.optionalKey(Schema.String.annotate({ format: "date" })),
  order: Schema.optionalKey(
    Schema.Literals(["citations", "hierarchy", "newest_first", "oldest_first", "relevance", "suggestions"])
  ),
  paginate_by: Schema.optionalKey(Schema.Literals(["date", "results"])),
  page: Schema.optionalKey(Schema.Int.annotate({ default: 1 })),
  per_page: Schema.optionalKey(Schema.Int.annotate({ default: 20 })),
  last_modified_after: Schema.optionalKey(Schema.String),
  last_modified_before: Schema.optionalKey(Schema.String),
  last_modified_on_or_after: Schema.optionalKey(Schema.String),
  last_modified_on_or_before: Schema.optionalKey(Schema.String),
});
export type SearchSummaryQuery = {
  readonly query?: string;
  readonly "agency_slugs[]"?: ReadonlyArray<string>;
  readonly date?: string;
  readonly order?: "citations" | "hierarchy" | "newest_first" | "oldest_first" | "relevance" | "suggestions";
  readonly paginate_by?: "date" | "results";
  readonly page?: number;
  readonly per_page?: number;
  readonly last_modified_after?: string;
  readonly last_modified_before?: string;
  readonly last_modified_on_or_after?: string;
  readonly last_modified_on_or_before?: string;
};
export const SearchSummaryQuery = Schema.Struct({
  query: Schema.optionalKey(Schema.String),
  "agency_slugs[]": Schema.Array(Schema.String).pipe(Schema.optionalKey),
  date: Schema.optionalKey(Schema.String.annotate({ format: "date" })),
  order: Schema.optionalKey(
    Schema.Literals(["citations", "hierarchy", "newest_first", "oldest_first", "relevance", "suggestions"])
  ),
  paginate_by: Schema.optionalKey(Schema.Literals(["date", "results"])),
  page: Schema.optionalKey(Schema.Int.annotate({ default: 1 })),
  per_page: Schema.optionalKey(Schema.Int.annotate({ default: 20 })),
  last_modified_after: Schema.optionalKey(Schema.String),
  last_modified_before: Schema.optionalKey(Schema.String),
  last_modified_on_or_after: Schema.optionalKey(Schema.String),
  last_modified_on_or_before: Schema.optionalKey(Schema.String),
});
export type SearchSummary200 = SearchSummaryResponse;
export const SearchSummary200 = SearchSummaryResponse;
export type SearchDailyCountsParams = {
  readonly query?: string;
  readonly "agency_slugs[]"?: ReadonlyArray<string>;
  readonly date?: string;
  readonly order?: "citations" | "hierarchy" | "newest_first" | "oldest_first" | "relevance" | "suggestions";
  readonly paginate_by?: "date" | "results";
  readonly page?: number;
  readonly per_page?: number;
  readonly last_modified_after?: string;
  readonly last_modified_before?: string;
  readonly last_modified_on_or_after?: string;
  readonly last_modified_on_or_before?: string;
};
export const SearchDailyCountsParams = Schema.Struct({
  query: Schema.optionalKey(Schema.String),
  "agency_slugs[]": Schema.Array(Schema.String).pipe(Schema.optionalKey),
  date: Schema.optionalKey(Schema.String.annotate({ format: "date" })),
  order: Schema.optionalKey(
    Schema.Literals(["citations", "hierarchy", "newest_first", "oldest_first", "relevance", "suggestions"])
  ),
  paginate_by: Schema.optionalKey(Schema.Literals(["date", "results"])),
  page: Schema.optionalKey(Schema.Int.annotate({ default: 1 })),
  per_page: Schema.optionalKey(Schema.Int.annotate({ default: 20 })),
  last_modified_after: Schema.optionalKey(Schema.String),
  last_modified_before: Schema.optionalKey(Schema.String),
  last_modified_on_or_after: Schema.optionalKey(Schema.String),
  last_modified_on_or_before: Schema.optionalKey(Schema.String),
});
export type SearchDailyCountsQuery = {
  readonly query?: string;
  readonly "agency_slugs[]"?: ReadonlyArray<string>;
  readonly date?: string;
  readonly order?: "citations" | "hierarchy" | "newest_first" | "oldest_first" | "relevance" | "suggestions";
  readonly paginate_by?: "date" | "results";
  readonly page?: number;
  readonly per_page?: number;
  readonly last_modified_after?: string;
  readonly last_modified_before?: string;
  readonly last_modified_on_or_after?: string;
  readonly last_modified_on_or_before?: string;
};
export const SearchDailyCountsQuery = Schema.Struct({
  query: Schema.optionalKey(Schema.String),
  "agency_slugs[]": Schema.Array(Schema.String).pipe(Schema.optionalKey),
  date: Schema.optionalKey(Schema.String.annotate({ format: "date" })),
  order: Schema.optionalKey(
    Schema.Literals(["citations", "hierarchy", "newest_first", "oldest_first", "relevance", "suggestions"])
  ),
  paginate_by: Schema.optionalKey(Schema.Literals(["date", "results"])),
  page: Schema.optionalKey(Schema.Int.annotate({ default: 1 })),
  per_page: Schema.optionalKey(Schema.Int.annotate({ default: 20 })),
  last_modified_after: Schema.optionalKey(Schema.String),
  last_modified_before: Schema.optionalKey(Schema.String),
  last_modified_on_or_after: Schema.optionalKey(Schema.String),
  last_modified_on_or_before: Schema.optionalKey(Schema.String),
});
export type SearchDailyCounts200 = SearchDailyCountsResponse;
export const SearchDailyCounts200 = SearchDailyCountsResponse;
export type SearchTitleCountsParams = {
  readonly query?: string;
  readonly "agency_slugs[]"?: ReadonlyArray<string>;
  readonly date?: string;
  readonly order?: "citations" | "hierarchy" | "newest_first" | "oldest_first" | "relevance" | "suggestions";
  readonly paginate_by?: "date" | "results";
  readonly page?: number;
  readonly per_page?: number;
  readonly last_modified_after?: string;
  readonly last_modified_before?: string;
  readonly last_modified_on_or_after?: string;
  readonly last_modified_on_or_before?: string;
};
export const SearchTitleCountsParams = Schema.Struct({
  query: Schema.optionalKey(Schema.String),
  "agency_slugs[]": Schema.Array(Schema.String).pipe(Schema.optionalKey),
  date: Schema.optionalKey(Schema.String.annotate({ format: "date" })),
  order: Schema.optionalKey(
    Schema.Literals(["citations", "hierarchy", "newest_first", "oldest_first", "relevance", "suggestions"])
  ),
  paginate_by: Schema.optionalKey(Schema.Literals(["date", "results"])),
  page: Schema.optionalKey(Schema.Int.annotate({ default: 1 })),
  per_page: Schema.optionalKey(Schema.Int.annotate({ default: 20 })),
  last_modified_after: Schema.optionalKey(Schema.String),
  last_modified_before: Schema.optionalKey(Schema.String),
  last_modified_on_or_after: Schema.optionalKey(Schema.String),
  last_modified_on_or_before: Schema.optionalKey(Schema.String),
});
export type SearchTitleCountsQuery = {
  readonly query?: string;
  readonly "agency_slugs[]"?: ReadonlyArray<string>;
  readonly date?: string;
  readonly order?: "citations" | "hierarchy" | "newest_first" | "oldest_first" | "relevance" | "suggestions";
  readonly paginate_by?: "date" | "results";
  readonly page?: number;
  readonly per_page?: number;
  readonly last_modified_after?: string;
  readonly last_modified_before?: string;
  readonly last_modified_on_or_after?: string;
  readonly last_modified_on_or_before?: string;
};
export const SearchTitleCountsQuery = Schema.Struct({
  query: Schema.optionalKey(Schema.String),
  "agency_slugs[]": Schema.Array(Schema.String).pipe(Schema.optionalKey),
  date: Schema.optionalKey(Schema.String.annotate({ format: "date" })),
  order: Schema.optionalKey(
    Schema.Literals(["citations", "hierarchy", "newest_first", "oldest_first", "relevance", "suggestions"])
  ),
  paginate_by: Schema.optionalKey(Schema.Literals(["date", "results"])),
  page: Schema.optionalKey(Schema.Int.annotate({ default: 1 })),
  per_page: Schema.optionalKey(Schema.Int.annotate({ default: 20 })),
  last_modified_after: Schema.optionalKey(Schema.String),
  last_modified_before: Schema.optionalKey(Schema.String),
  last_modified_on_or_after: Schema.optionalKey(Schema.String),
  last_modified_on_or_before: Schema.optionalKey(Schema.String),
});
export type SearchTitleCounts200 = SearchTitleCountsResponse;
export const SearchTitleCounts200 = SearchTitleCountsResponse;
export type SearchHierarchyCountsParams = {
  readonly query?: string;
  readonly "agency_slugs[]"?: ReadonlyArray<string>;
  readonly date?: string;
  readonly order?: "citations" | "hierarchy" | "newest_first" | "oldest_first" | "relevance" | "suggestions";
  readonly paginate_by?: "date" | "results";
  readonly page?: number;
  readonly per_page?: number;
  readonly last_modified_after?: string;
  readonly last_modified_before?: string;
  readonly last_modified_on_or_after?: string;
  readonly last_modified_on_or_before?: string;
};
export const SearchHierarchyCountsParams = Schema.Struct({
  query: Schema.optionalKey(Schema.String),
  "agency_slugs[]": Schema.Array(Schema.String).pipe(Schema.optionalKey),
  date: Schema.optionalKey(Schema.String.annotate({ format: "date" })),
  order: Schema.optionalKey(
    Schema.Literals(["citations", "hierarchy", "newest_first", "oldest_first", "relevance", "suggestions"])
  ),
  paginate_by: Schema.optionalKey(Schema.Literals(["date", "results"])),
  page: Schema.optionalKey(Schema.Int.annotate({ default: 1 })),
  per_page: Schema.optionalKey(Schema.Int.annotate({ default: 20 })),
  last_modified_after: Schema.optionalKey(Schema.String),
  last_modified_before: Schema.optionalKey(Schema.String),
  last_modified_on_or_after: Schema.optionalKey(Schema.String),
  last_modified_on_or_before: Schema.optionalKey(Schema.String),
});
export type SearchHierarchyCountsQuery = {
  readonly query?: string;
  readonly "agency_slugs[]"?: ReadonlyArray<string>;
  readonly date?: string;
  readonly order?: "citations" | "hierarchy" | "newest_first" | "oldest_first" | "relevance" | "suggestions";
  readonly paginate_by?: "date" | "results";
  readonly page?: number;
  readonly per_page?: number;
  readonly last_modified_after?: string;
  readonly last_modified_before?: string;
  readonly last_modified_on_or_after?: string;
  readonly last_modified_on_or_before?: string;
};
export const SearchHierarchyCountsQuery = Schema.Struct({
  query: Schema.optionalKey(Schema.String),
  "agency_slugs[]": Schema.Array(Schema.String).pipe(Schema.optionalKey),
  date: Schema.optionalKey(Schema.String.annotate({ format: "date" })),
  order: Schema.optionalKey(
    Schema.Literals(["citations", "hierarchy", "newest_first", "oldest_first", "relevance", "suggestions"])
  ),
  paginate_by: Schema.optionalKey(Schema.Literals(["date", "results"])),
  page: Schema.optionalKey(Schema.Int.annotate({ default: 1 })),
  per_page: Schema.optionalKey(Schema.Int.annotate({ default: 20 })),
  last_modified_after: Schema.optionalKey(Schema.String),
  last_modified_before: Schema.optionalKey(Schema.String),
  last_modified_on_or_after: Schema.optionalKey(Schema.String),
  last_modified_on_or_before: Schema.optionalKey(Schema.String),
});
export type SearchHierarchyCounts200 = SearchHierarchyCountsResponse;
export const SearchHierarchyCounts200 = SearchHierarchyCountsResponse;
export type SearchSuggestionsParams = {
  readonly query?: string;
  readonly "agency_slugs[]"?: ReadonlyArray<string>;
  readonly date?: string;
  readonly order?: "citations" | "hierarchy" | "newest_first" | "oldest_first" | "relevance" | "suggestions";
  readonly paginate_by?: "date" | "results";
  readonly page?: number;
  readonly per_page?: number;
  readonly last_modified_after?: string;
  readonly last_modified_before?: string;
  readonly last_modified_on_or_after?: string;
  readonly last_modified_on_or_before?: string;
};
export const SearchSuggestionsParams = Schema.Struct({
  query: Schema.optionalKey(Schema.String),
  "agency_slugs[]": Schema.Array(Schema.String).pipe(Schema.optionalKey),
  date: Schema.optionalKey(Schema.String.annotate({ format: "date" })),
  order: Schema.optionalKey(
    Schema.Literals(["citations", "hierarchy", "newest_first", "oldest_first", "relevance", "suggestions"])
  ),
  paginate_by: Schema.optionalKey(Schema.Literals(["date", "results"])),
  page: Schema.optionalKey(Schema.Int.annotate({ default: 1 })),
  per_page: Schema.optionalKey(Schema.Int.annotate({ default: 20 })),
  last_modified_after: Schema.optionalKey(Schema.String),
  last_modified_before: Schema.optionalKey(Schema.String),
  last_modified_on_or_after: Schema.optionalKey(Schema.String),
  last_modified_on_or_before: Schema.optionalKey(Schema.String),
});
export type SearchSuggestionsQuery = {
  readonly query?: string;
  readonly "agency_slugs[]"?: ReadonlyArray<string>;
  readonly date?: string;
  readonly order?: "citations" | "hierarchy" | "newest_first" | "oldest_first" | "relevance" | "suggestions";
  readonly paginate_by?: "date" | "results";
  readonly page?: number;
  readonly per_page?: number;
  readonly last_modified_after?: string;
  readonly last_modified_before?: string;
  readonly last_modified_on_or_after?: string;
  readonly last_modified_on_or_before?: string;
};
export const SearchSuggestionsQuery = Schema.Struct({
  query: Schema.optionalKey(Schema.String),
  "agency_slugs[]": Schema.Array(Schema.String).pipe(Schema.optionalKey),
  date: Schema.optionalKey(Schema.String.annotate({ format: "date" })),
  order: Schema.optionalKey(
    Schema.Literals(["citations", "hierarchy", "newest_first", "oldest_first", "relevance", "suggestions"])
  ),
  paginate_by: Schema.optionalKey(Schema.Literals(["date", "results"])),
  page: Schema.optionalKey(Schema.Int.annotate({ default: 1 })),
  per_page: Schema.optionalKey(Schema.Int.annotate({ default: 20 })),
  last_modified_after: Schema.optionalKey(Schema.String),
  last_modified_before: Schema.optionalKey(Schema.String),
  last_modified_on_or_after: Schema.optionalKey(Schema.String),
  last_modified_on_or_before: Schema.optionalKey(Schema.String),
});
export type SearchSuggestions200 = SearchSuggestionsResponse;
export const SearchSuggestions200 = SearchSuggestionsResponse;
export type GetAncestryParams = {
  readonly subtitle?: string;
  readonly chapter?: string;
  readonly subchapter?: string;
  readonly part?: string;
  readonly subpart?: string;
  readonly section?: string;
  readonly appendix?: string;
};
export const GetAncestryParams = Schema.Struct({
  subtitle: Schema.optionalKey(Schema.String),
  chapter: Schema.optionalKey(Schema.String),
  subchapter: Schema.optionalKey(Schema.String),
  part: Schema.optionalKey(Schema.String),
  subpart: Schema.optionalKey(Schema.String),
  section: Schema.optionalKey(Schema.String),
  appendix: Schema.optionalKey(Schema.String),
});
export type GetAncestryPathParams = { readonly date: string; readonly title: string };
export const GetAncestryPathParams = Schema.Struct({
  date: Schema.String.annotate({ format: "date" }),
  title: Schema.String,
});
export type GetAncestryQuery = {
  readonly subtitle?: string;
  readonly chapter?: string;
  readonly subchapter?: string;
  readonly part?: string;
  readonly subpart?: string;
  readonly section?: string;
  readonly appendix?: string;
};
export const GetAncestryQuery = Schema.Struct({
  subtitle: Schema.optionalKey(Schema.String),
  chapter: Schema.optionalKey(Schema.String),
  subchapter: Schema.optionalKey(Schema.String),
  part: Schema.optionalKey(Schema.String),
  subpart: Schema.optionalKey(Schema.String),
  section: Schema.optionalKey(Schema.String),
  appendix: Schema.optionalKey(Schema.String),
});
export type GetAncestry200 = AncestryResponse;
export const GetAncestry200 = AncestryResponse;
export type GetFullTitleXmlParams = {
  readonly subtitle?: string;
  readonly chapter?: string;
  readonly subchapter?: string;
  readonly part?: string;
  readonly subpart?: string;
  readonly section?: string;
  readonly appendix?: string;
};
export const GetFullTitleXmlParams = Schema.Struct({
  subtitle: Schema.optionalKey(Schema.String),
  chapter: Schema.optionalKey(Schema.String),
  subchapter: Schema.optionalKey(Schema.String),
  part: Schema.optionalKey(Schema.String),
  subpart: Schema.optionalKey(Schema.String),
  section: Schema.optionalKey(Schema.String),
  appendix: Schema.optionalKey(Schema.String),
});
export type GetFullTitleXmlPathParams = { readonly date: string; readonly title: string };
export const GetFullTitleXmlPathParams = Schema.Struct({
  date: Schema.String.annotate({ format: "date" }),
  title: Schema.String,
});
export type GetFullTitleXmlQuery = {
  readonly subtitle?: string;
  readonly chapter?: string;
  readonly subchapter?: string;
  readonly part?: string;
  readonly subpart?: string;
  readonly section?: string;
  readonly appendix?: string;
};
export const GetFullTitleXmlQuery = Schema.Struct({
  subtitle: Schema.optionalKey(Schema.String),
  chapter: Schema.optionalKey(Schema.String),
  subchapter: Schema.optionalKey(Schema.String),
  part: Schema.optionalKey(Schema.String),
  subpart: Schema.optionalKey(Schema.String),
  section: Schema.optionalKey(Schema.String),
  appendix: Schema.optionalKey(Schema.String),
});
export type GetFullTitleXml200TextXml = string;
export const GetFullTitleXml200TextXml = Schema.String.annotate({ description: "Raw XML payload." });
export type GetStructureParams = {
  readonly subtitle?: string;
  readonly chapter?: string;
  readonly subchapter?: string;
  readonly part?: string;
  readonly subpart?: string;
  readonly section?: string;
  readonly appendix?: string;
};
export const GetStructureParams = Schema.Struct({
  subtitle: Schema.optionalKey(Schema.String),
  chapter: Schema.optionalKey(Schema.String),
  subchapter: Schema.optionalKey(Schema.String),
  part: Schema.optionalKey(Schema.String),
  subpart: Schema.optionalKey(Schema.String),
  section: Schema.optionalKey(Schema.String),
  appendix: Schema.optionalKey(Schema.String),
});
export type GetStructurePathParams = { readonly date: string; readonly title: string };
export const GetStructurePathParams = Schema.Struct({
  date: Schema.String.annotate({ format: "date" }),
  title: Schema.String,
});
export type GetStructureQuery = {
  readonly subtitle?: string;
  readonly chapter?: string;
  readonly subchapter?: string;
  readonly part?: string;
  readonly subpart?: string;
  readonly section?: string;
  readonly appendix?: string;
};
export const GetStructureQuery = Schema.Struct({
  subtitle: Schema.optionalKey(Schema.String),
  chapter: Schema.optionalKey(Schema.String),
  subchapter: Schema.optionalKey(Schema.String),
  part: Schema.optionalKey(Schema.String),
  subpart: Schema.optionalKey(Schema.String),
  section: Schema.optionalKey(Schema.String),
  appendix: Schema.optionalKey(Schema.String),
});
export type GetStructure200 = StructureNode;
export const GetStructure200 = StructureNode;
export type ListTitles200 = TitlesResponse;
export const ListTitles200 = TitlesResponse;
export type ListVersionsParams = {
  readonly subtitle?: string;
  readonly chapter?: string;
  readonly subchapter?: string;
  readonly part?: string;
  readonly subpart?: string;
  readonly section?: string;
  readonly appendix?: string;
  readonly "issue_date[on]"?: string;
  readonly "issue_date[lte]"?: string;
  readonly "issue_date[gte]"?: string;
  readonly page?: number;
};
export const ListVersionsParams = Schema.Struct({
  subtitle: Schema.optionalKey(Schema.String),
  chapter: Schema.optionalKey(Schema.String),
  subchapter: Schema.optionalKey(Schema.String),
  part: Schema.optionalKey(Schema.String),
  subpart: Schema.optionalKey(Schema.String),
  section: Schema.optionalKey(Schema.String),
  appendix: Schema.optionalKey(Schema.String),
  "issue_date[on]": Schema.optionalKey(Schema.String.annotate({ format: "date" })),
  "issue_date[lte]": Schema.optionalKey(Schema.String.annotate({ format: "date" })),
  "issue_date[gte]": Schema.optionalKey(Schema.String.annotate({ format: "date" })),
  page: Schema.optionalKey(Schema.Int),
});
export type ListVersionsPathParams = { readonly title: string };
export const ListVersionsPathParams = Schema.Struct({ title: Schema.String });
export type ListVersionsQuery = {
  readonly subtitle?: string;
  readonly chapter?: string;
  readonly subchapter?: string;
  readonly part?: string;
  readonly subpart?: string;
  readonly section?: string;
  readonly appendix?: string;
  readonly "issue_date[on]"?: string;
  readonly "issue_date[lte]"?: string;
  readonly "issue_date[gte]"?: string;
  readonly page?: number;
};
export const ListVersionsQuery = Schema.Struct({
  subtitle: Schema.optionalKey(Schema.String),
  chapter: Schema.optionalKey(Schema.String),
  subchapter: Schema.optionalKey(Schema.String),
  part: Schema.optionalKey(Schema.String),
  subpart: Schema.optionalKey(Schema.String),
  section: Schema.optionalKey(Schema.String),
  appendix: Schema.optionalKey(Schema.String),
  "issue_date[on]": Schema.optionalKey(Schema.String.annotate({ format: "date" })),
  "issue_date[lte]": Schema.optionalKey(Schema.String.annotate({ format: "date" })),
  "issue_date[gte]": Schema.optionalKey(Schema.String.annotate({ format: "date" })),
  page: Schema.optionalKey(Schema.Int),
});
export type ListVersions200 = VersionsResponse;
export const ListVersions200 = VersionsResponse;

class DefaultGroup extends HttpApiGroup.make("default", { topLevel: true }).add(
  HttpApiEndpoint.get("listAgencies", "/api/admin/v1/agencies.json", { success: ListAgencies200 })
    .annotate(OpenApi.Identifier, "listAgencies")
    .annotate(OpenApi.Summary, "List all top-level eCFR agencies and their children in name order."),
  HttpApiEndpoint.get("listCorrections", "/api/admin/v1/corrections.json", {
    query: ListCorrectionsQuery,
    success: ListCorrections200,
  })
    .annotate(OpenApi.Identifier, "listCorrections")
    .annotate(OpenApi.Summary, "List eCFR corrections, optionally filtered by title or date."),
  HttpApiEndpoint.get("listTitleCorrections", "/api/admin/v1/corrections/title/:title.json", {
    params: ListTitleCorrectionsPathParams,
    success: ListTitleCorrections200,
  })
    .annotate(OpenApi.Identifier, "listTitleCorrections")
    .annotate(OpenApi.Summary, "List all eCFR corrections for a CFR title."),
  HttpApiEndpoint.get("searchResults", "/api/search/v1/results", {
    query: SearchResultsQuery,
    success: SearchResults200,
  })
    .annotate(OpenApi.Identifier, "searchResults")
    .annotate(OpenApi.Summary, "Search eCFR headings and full text."),
  HttpApiEndpoint.get("searchCount", "/api/search/v1/count", { query: SearchCountQuery, success: SearchCount200 })
    .annotate(OpenApi.Identifier, "searchCount")
    .annotate(OpenApi.Summary, "Count eCFR search matches."),
  HttpApiEndpoint.get("searchSummary", "/api/search/v1/summary", {
    query: SearchSummaryQuery,
    success: SearchSummary200,
  })
    .annotate(OpenApi.Identifier, "searchSummary")
    .annotate(OpenApi.Summary, "Return summary details for an eCFR search."),
  HttpApiEndpoint.get("searchDailyCounts", "/api/search/v1/counts/daily", {
    query: SearchDailyCountsQuery,
    success: SearchDailyCounts200,
  })
    .annotate(OpenApi.Identifier, "searchDailyCounts")
    .annotate(OpenApi.Summary, "Return eCFR search-result counts by date."),
  HttpApiEndpoint.get("searchTitleCounts", "/api/search/v1/counts/titles", {
    query: SearchTitleCountsQuery,
    success: SearchTitleCounts200,
  })
    .annotate(OpenApi.Identifier, "searchTitleCounts")
    .annotate(OpenApi.Summary, "Return eCFR search-result counts by CFR title."),
  HttpApiEndpoint.get("searchHierarchyCounts", "/api/search/v1/counts/hierarchy", {
    query: SearchHierarchyCountsQuery,
    success: SearchHierarchyCounts200,
  })
    .annotate(OpenApi.Identifier, "searchHierarchyCounts")
    .annotate(OpenApi.Summary, "Return eCFR search-result counts by hierarchy node."),
  HttpApiEndpoint.get("searchSuggestions", "/api/search/v1/suggestions", {
    query: SearchSuggestionsQuery,
    success: SearchSuggestions200,
  })
    .annotate(OpenApi.Identifier, "searchSuggestions")
    .annotate(OpenApi.Summary, "Return eCFR search suggestions."),
  HttpApiEndpoint.get("getAncestry", "/api/versioner/v1/ancestry/:date/title-:title.json", {
    params: GetAncestryPathParams,
    query: GetAncestryQuery,
    success: GetAncestry200,
  })
    .annotate(OpenApi.Identifier, "getAncestry")
    .annotate(OpenApi.Summary, "Return the ancestry of a CFR hierarchy node on a date."),
  HttpApiEndpoint.get("getFullTitleXml", "/api/versioner/v1/full/:date/title-:title.xml", {
    params: GetFullTitleXmlPathParams,
    query: GetFullTitleXmlQuery,
    success: GetFullTitleXml200TextXml.pipe(HttpApiSchema.asText({ contentType: "text/xml" })),
  })
    .annotate(OpenApi.Identifier, "getFullTitleXml")
    .annotate(OpenApi.Summary, "Return source XML for a complete CFR title or hierarchy subset."),
  HttpApiEndpoint.get("getStructure", "/api/versioner/v1/structure/:date/title-:title.json", {
    params: GetStructurePathParams,
    query: GetStructureQuery,
    success: GetStructure200,
  })
    .annotate(OpenApi.Identifier, "getStructure")
    .annotate(OpenApi.Summary, "Return the complete structure tree for a CFR title on a date."),
  HttpApiEndpoint.get("listTitles", "/api/versioner/v1/titles.json", { success: ListTitles200 })
    .annotate(OpenApi.Identifier, "listTitles")
    .annotate(OpenApi.Summary, "List CFR titles and currency metadata."),
  HttpApiEndpoint.get("listVersions", "/api/versioner/v1/versions/title-:title.json", {
    params: ListVersionsPathParams,
    query: ListVersionsQuery,
    success: ListVersions200,
  })
    .annotate(OpenApi.Identifier, "listVersions")
    .annotate(OpenApi.Summary, "List content versions within a CFR title.")
) {}

export class Ecfr extends HttpApi.make("Ecfr")
  .annotate(OpenApi.Title, "eCFR API")
  .annotate(OpenApi.Version, "v1")
  .annotate(
    OpenApi.Description,
    "Hand-maintained Swagger 2.0 description of the 15-operation public, keyless eCFR API surface. Paths span the admin, search, and versioner service families, so basePath is empty and every operation records its full /api/<family>/v1 path. The official eCFR Swagger document is the authority; response definitions preserve stable documented envelope fields conservatively where the official response schema is unspecified."
  )
  .annotate(OpenApi.Servers, [{ url: "https://www.ecfr.gov" }])
  .add(DefaultGroup) {}
