/**
 * Generated eCFR value models and operation descriptors.
 *
 * Do not edit this file by hand. Run `bun run generate` to regenerate from
 * `openapi.json`. Transport stays hand-authored (see `Ecfr.service.ts`).
 *
 * @packageDocumentation
 * @since 0.0.0
 */

import { $EcfrId } from "@beep/identity";
import * as S from "effect/Schema";

const $I = $EcfrId.create("_generated/Ecfr.generated");

/**
 * A CFR title and chapter reference associated with an agency.
 *
 * **Example** (Construct the CfrReference)
 *
 * ```ts
 * import { CfrReference } from "@beep/ecfr"
 *
 * const value = CfrReference.make({ "title": 1, "chapter": "example-chapter" })
 * console.log(value.title)
 * ```
 *
 * @category models
 * @since 0.0.0
 */
export class CfrReference extends S.Class<CfrReference>($I`CfrReference`)(
  {
    title: S.Int.annotateKey({ description: "CFR title number." }),
    chapter: S.String.annotateKey({ description: "Chapter identifier within the title." }),
  },
  $I.annote("CfrReference", {
    description: "A CFR title and chapter reference associated with an agency.",
  })
) {
  static readonly is = S.is(CfrReference);
}

/**
 * A child agency represented in the CFR agency roster.
 *
 * **Example** (Construct the AgencyChild)
 *
 * ```ts
 * import { AgencyChild } from "@beep/ecfr"
 *
 * const value = AgencyChild.make({ "name": "example-name", "slug": "example-slug" })
 * console.log(value.name)
 * ```
 *
 * @category models
 * @since 0.0.0
 */
export class AgencyChild extends S.Class<AgencyChild>($I`AgencyChild`)(
  {
    name: S.String.annotateKey({ description: "Full official agency name." }),
    short_name: S.optionalKey(S.String).annotateKey({ description: "Agency abbreviation when supplied." }),
    display_name: S.optionalKey(S.String).annotateKey({ description: "Human-readable agency display name." }),
    sortable_name: S.optionalKey(S.String).annotateKey({
      description: "Agency name normalized for alphabetical sorting.",
    }),
    slug: S.String.annotateKey({ description: "URL-safe agency identifier." }),
    cfr_references: S.optionalKey(CfrReference.pipe(S.Array)).annotateKey({
      description: "CFR chapters assigned to the child agency.",
    }),
  },
  $I.annote("AgencyChild", {
    description: "A child agency represented in the CFR agency roster.",
  })
) {
  static readonly is = S.is(AgencyChild);
}

/**
 * A top-level agency represented in the CFR, including child agencies and CFR references.
 *
 * **Example** (Construct the Agency)
 *
 * ```ts
 * import { Agency } from "@beep/ecfr"
 *
 * const value = Agency.make({ "name": "example-name", "slug": "example-slug" })
 * console.log(value.name)
 * ```
 *
 * @category models
 * @since 0.0.0
 */
export class Agency extends S.Class<Agency>($I`Agency`)(
  {
    name: S.String.annotateKey({ description: "Full official agency name." }),
    short_name: S.optionalKey(S.String).annotateKey({ description: "Agency abbreviation when supplied." }),
    display_name: S.optionalKey(S.String).annotateKey({ description: "Human-readable agency display name." }),
    sortable_name: S.optionalKey(S.String).annotateKey({
      description: "Agency name normalized for alphabetical sorting.",
    }),
    slug: S.String.annotateKey({ description: "URL-safe agency identifier." }),
    children: S.optionalKey(AgencyChild.pipe(S.Array)).annotateKey({ description: "Child agencies in name order." }),
    cfr_references: S.optionalKey(CfrReference.pipe(S.Array)).annotateKey({
      description: "CFR chapters assigned directly to the agency.",
    }),
  },
  $I.annote("Agency", {
    description: "A top-level agency represented in the CFR, including child agencies and CFR references.",
  })
) {
  static readonly is = S.is(Agency);
}

/**
 * Response envelope containing the agency roster.
 *
 * **Example** (Construct the AgenciesResponse)
 *
 * ```ts
 * import { AgenciesResponse, Agency } from "@beep/ecfr"
 *
 * const value = AgenciesResponse.make({ "agencies": [Agency.make({ "name": "example-name", "slug": "example-slug" })] })
 * console.log(value.agencies)
 * ```
 *
 * @category models
 * @since 0.0.0
 */
export class AgenciesResponse extends S.Class<AgenciesResponse>($I`AgenciesResponse`)(
  {
    agencies: Agency.pipe(S.Array).annotateKey({ description: "Top-level agencies in name order." }),
  },
  $I.annote("AgenciesResponse", {
    description: "Response envelope containing the agency roster.",
  })
) {
  static readonly is = S.is(AgenciesResponse);
}

/**
 * A CFR hierarchy node returned in an ancestry response.
 *
 * **Example** (Construct the HierarchyNode)
 *
 * ```ts
 * import { HierarchyNode } from "@beep/ecfr"
 *
 * const value = HierarchyNode.make({ "type": "example-type", "label": "example-label", "identifier": "example-identifier" })
 * console.log(value.type)
 * ```
 *
 * @category models
 * @since 0.0.0
 */
export class HierarchyNode extends S.Class<HierarchyNode>($I`HierarchyNode`)(
  {
    type: S.String.annotateKey({ description: "Hierarchy level such as title, chapter, part, or section." }),
    label: S.String.annotateKey({ description: "Complete human-readable node label." }),
    label_level: S.optionalKey(S.String).annotateKey({ description: "Hierarchy level portion of the label." }),
    label_description: S.optionalKey(S.String).annotateKey({ description: "Descriptive portion of the label." }),
    identifier: S.String.annotateKey({ description: "Identifier within the node's hierarchy level." }),
    reserved: S.optionalKey(S.Boolean).annotateKey({ description: "Whether the hierarchy node is reserved." }),
    section_range: S.optionalKey(S.String).annotateKey({
      description: "Section range covered by the node when supplied.",
    }),
  },
  $I.annote("HierarchyNode", {
    description: "A CFR hierarchy node returned in an ancestry response.",
  })
) {
  static readonly is = S.is(HierarchyNode);
}

/**
 * Ordered CFR hierarchy nodes from title through the requested leaf.
 *
 * **Example** (Decode a AncestryResponse)
 *
 * ```ts
 * import { AncestryResponse, HierarchyNode } from "@beep/ecfr"
 * import * as S from "effect/Schema"
 *
 * const value = S.decodeUnknownEffect(AncestryResponse)([HierarchyNode.make({ "type": "example-type", "label": "example-label", "identifier": "example-identifier" })])
 * console.log(value)
 * ```
 *
 * @category models
 * @since 0.0.0
 */
export const AncestryResponse = HierarchyNode.pipe(
  S.Array,
  $I.annoteSchema("AncestryResponse", {
    description: "Ordered CFR hierarchy nodes from title through the requested leaf.",
  })
);

/**
 * Type for {@link AncestryResponse}.
 *
 * **Example** (Type a AncestryResponse value)
 *
 * ```ts
 * import type { AncestryResponse } from "@beep/ecfr"
 *
 * const value: AncestryResponse = []
 * console.log(value.length)
 * ```
 *
 * @category models
 * @since 0.0.0
 */
export type AncestryResponse = typeof AncestryResponse.Type;

/**
 * A dated version of one CFR section or appendix.
 *
 * **Example** (Construct the ContentVersion)
 *
 * ```ts
 * import { ContentVersion } from "@beep/ecfr"
 *
 * const value = ContentVersion.make({ "identifier": "example-identifier", "title": "example-title", "type": "example-type" })
 * console.log(value.identifier)
 * ```
 *
 * @category models
 * @since 0.0.0
 */
export class ContentVersion extends S.Class<ContentVersion>($I`ContentVersion`)(
  {
    date: S.optionalKey(S.String).annotateKey({
      description: "Deprecated alias of amendment_date retained by the API.",
    }), // date (YYYY-MM-DD)
    amendment_date: S.optionalKey(S.String).annotateKey({ description: "Date the content was amended." }), // date (YYYY-MM-DD)
    issue_date: S.optionalKey(S.String).annotateKey({
      description: "Issue date on which this content version appeared.",
    }), // date (YYYY-MM-DD)
    identifier: S.String.annotateKey({ description: "Section or appendix identifier." }),
    name: S.optionalKey(S.String).annotateKey({ description: "Human-readable content name." }),
    part: S.optionalKey(S.String).annotateKey({ description: "Containing CFR part identifier." }),
    substantive: S.optionalKey(S.Boolean).annotateKey({ description: "Whether the change is substantive." }),
    removed: S.optionalKey(S.Boolean).annotateKey({ description: "Whether the content was removed in this version." }),
    subpart: S.optionalKey(S.String).annotateKey({ description: "Containing subpart identifier when present." }),
    title: S.String.annotateKey({ description: "Containing CFR title identifier." }),
    type: S.String.annotateKey({ description: "Content type, normally section or appendix." }),
  },
  $I.annote("ContentVersion", {
    description: "A dated version of one CFR section or appendix.",
  })
) {
  static readonly is = S.is(ContentVersion);
}

/**
 * Known CFR hierarchy identifiers locating corrected content.
 *
 * **Example** (Construct the CorrectionHierarchy)
 *
 * ```ts
 * import { CorrectionHierarchy } from "@beep/ecfr"
 *
 * const value = CorrectionHierarchy.make({  })
 * console.log(value)
 * ```
 *
 * @category models
 * @since 0.0.0
 */
export class CorrectionHierarchy extends S.Class<CorrectionHierarchy>($I`CorrectionHierarchy`)(
  {
    title: S.optionalKey(S.String).annotateKey({ description: "CFR title identifier." }),
    subtitle: S.optionalKey(S.String).annotateKey({ description: "Subtitle identifier when present." }),
    chapter: S.optionalKey(S.String).annotateKey({ description: "Chapter identifier when present." }),
    subchapter: S.optionalKey(S.String).annotateKey({ description: "Subchapter identifier when present." }),
    part: S.optionalKey(S.String).annotateKey({ description: "Part identifier when present." }),
    subpart: S.optionalKey(S.String).annotateKey({ description: "Subpart identifier when present." }),
    section: S.optionalKey(S.String).annotateKey({ description: "Section identifier when present." }),
    appendix: S.optionalKey(S.String).annotateKey({ description: "Appendix identifier when present." }),
  },
  $I.annote("CorrectionHierarchy", {
    description: "Known CFR hierarchy identifiers locating corrected content.",
  })
) {
  static readonly is = S.is(CorrectionHierarchy);
}

/**
 * Human-readable and structured CFR location for a correction.
 *
 * **Example** (Construct the CorrectionReference)
 *
 * ```ts
 * import { CorrectionHierarchy, CorrectionReference } from "@beep/ecfr"
 *
 * const value = CorrectionReference.make({ "cfr_reference": "example-cfr_reference", "hierarchy": CorrectionHierarchy.make({  }) })
 * console.log(value.cfr_reference)
 * ```
 *
 * @category models
 * @since 0.0.0
 */
export class CorrectionReference extends S.Class<CorrectionReference>($I`CorrectionReference`)(
  {
    cfr_reference: S.String.annotateKey({ description: "Human-readable CFR citation for the corrected content." }),
    hierarchy: CorrectionHierarchy.annotateKey({
      description: "Structured hierarchy identifiers for the corrected content.",
    }),
  },
  $I.annote("CorrectionReference", {
    description: "Human-readable and structured CFR location for a correction.",
  })
) {
  static readonly is = S.is(CorrectionReference);
}

/**
 * An eCFR editorial correction and its affected CFR locations.
 *
 * **Example** (Construct the Correction)
 *
 * ```ts
 * import { Correction } from "@beep/ecfr"
 *
 * const value = Correction.make({ "id": 1, "title": 1 })
 * console.log(value.id)
 * ```
 *
 * @category models
 * @since 0.0.0
 */
export class Correction extends S.Class<Correction>($I`Correction`)(
  {
    id: S.Int.annotateKey({ description: "Stable correction record identifier." }),
    cfr_references: S.optionalKey(CorrectionReference.pipe(S.Array)).annotateKey({
      description: "CFR locations affected by the correction.",
    }),
    corrective_action: S.optionalKey(S.String).annotateKey({
      description: "Description of the corrective editorial action.",
    }),
    error_corrected: S.optionalKey(S.String).annotateKey({ description: "Date the error was corrected." }), // date (YYYY-MM-DD)
    error_occurred: S.optionalKey(S.String).annotateKey({ description: "Date the error entered the eCFR material." }), // date (YYYY-MM-DD)
    fr_citation: S.optionalKey(S.String).annotateKey({
      description: "Federal Register citation associated with the correction.",
    }),
    position: S.optionalKey(S.Int).annotateKey({ description: "Display order among corrections for the same source." }),
    display_in_toc: S.optionalKey(S.Boolean).annotateKey({
      description: "Whether the correction is displayed in the table of contents.",
    }),
    title: S.Int.annotateKey({ description: "Affected CFR title number." }),
    year: S.optionalKey(S.Int).annotateKey({ description: "Calendar year associated with the correction." }),
    last_modified: S.optionalKey(S.String).annotateKey({
      description: "Date the correction record was last modified.",
    }), // date (YYYY-MM-DD)
  },
  $I.annote("Correction", {
    description: "An eCFR editorial correction and its affected CFR locations.",
  })
) {
  static readonly is = S.is(Correction);
}

/**
 * Response envelope containing eCFR correction records.
 *
 * **Example** (Construct the CorrectionsResponse)
 *
 * ```ts
 * import { Correction, CorrectionsResponse } from "@beep/ecfr"
 *
 * const value = CorrectionsResponse.make({ "ecfr_corrections": [Correction.make({ "id": 1, "title": 1 })] })
 * console.log(value.ecfr_corrections)
 * ```
 *
 * @category models
 * @since 0.0.0
 */
export class CorrectionsResponse extends S.Class<CorrectionsResponse>($I`CorrectionsResponse`)(
  {
    ecfr_corrections: Correction.pipe(S.Array).annotateKey({ description: "Correction records matching the request." }),
  },
  $I.annote("CorrectionsResponse", {
    description: "Response envelope containing eCFR correction records.",
  })
) {
  static readonly is = S.is(CorrectionsResponse);
}

/**
 * Search-result count associated with one date.
 *
 * **Example** (Construct the DailyCount)
 *
 * ```ts
 * import { DailyCount } from "@beep/ecfr"
 *
 * const value = DailyCount.make({  })
 * console.log(value)
 * ```
 *
 * @category models
 * @since 0.0.0
 */
export class DailyCount extends S.Class<DailyCount>($I`DailyCount`)(
  {
    date: S.optionalKey(S.String).annotateKey({ description: "ISO date represented by the bucket." }), // date (YYYY-MM-DD)
    count: S.optionalKey(S.Int).annotateKey({ description: "Number of matches in the date bucket." }),
  },
  $I.annote("DailyCount", {
    description: "Search-result count associated with one date.",
  })
) {
  static readonly is = S.is(DailyCount);
}

/**
 * Search-result count associated with one CFR hierarchy node.
 *
 * **Example** (Construct the HierarchyCount)
 *
 * ```ts
 * import { HierarchyCount } from "@beep/ecfr"
 *
 * const value = HierarchyCount.make({  })
 * console.log(value)
 * ```
 *
 * @category models
 * @since 0.0.0
 */
export class HierarchyCount extends S.Class<HierarchyCount>($I`HierarchyCount`)(
  {
    label: S.optionalKey(S.String).annotateKey({ description: "Human-readable hierarchy label." }),
    identifier: S.optionalKey(S.String).annotateKey({ description: "Hierarchy node identifier." }),
    count: S.optionalKey(S.Int).annotateKey({ description: "Number of matches in the hierarchy bucket." }),
  },
  $I.annote("HierarchyCount", {
    description: "Search-result count associated with one CFR hierarchy node.",
  })
) {
  static readonly is = S.is(HierarchyCount);
}

/**
 * Conservative envelope for the eCFR search count endpoint.
 *
 * **Example** (Construct the SearchCountResponse)
 *
 * ```ts
 * import { SearchCountResponse } from "@beep/ecfr"
 *
 * const value = SearchCountResponse.make({  })
 * console.log(value)
 * ```
 *
 * @category models
 * @since 0.0.0
 */
export class SearchCountResponse extends S.Class<SearchCountResponse>($I`SearchCountResponse`)(
  {
    count: S.optionalKey(S.Int).annotateKey({
      description: "Number of matching search results when supplied by the service.",
    }),
    total_count: S.optionalKey(S.Int).annotateKey({
      description: "Total matching result count when supplied under the paginated-result field name.",
    }),
  },
  $I.annote("SearchCountResponse", {
    description: "Conservative envelope for the eCFR search count endpoint.",
  })
) {
  static readonly is = S.is(SearchCountResponse);
}

/**
 * Conservative envelope for daily eCFR search counts.
 *
 * **Example** (Construct the SearchDailyCountsResponse)
 *
 * ```ts
 * import { SearchDailyCountsResponse } from "@beep/ecfr"
 *
 * const value = SearchDailyCountsResponse.make({  })
 * console.log(value)
 * ```
 *
 * @category models
 * @since 0.0.0
 */
export class SearchDailyCountsResponse extends S.Class<SearchDailyCountsResponse>($I`SearchDailyCountsResponse`)(
  {
    counts: S.optionalKey(DailyCount.pipe(S.Array)).annotateKey({
      description: "Daily result-count buckets when supplied.",
    }),
  },
  $I.annote("SearchDailyCountsResponse", {
    description: "Conservative envelope for daily eCFR search counts.",
  })
) {
  static readonly is = S.is(SearchDailyCountsResponse);
}

/**
 * Conservative envelope for hierarchy-level eCFR search counts.
 *
 * **Example** (Construct the SearchHierarchyCountsResponse)
 *
 * ```ts
 * import { SearchHierarchyCountsResponse } from "@beep/ecfr"
 *
 * const value = SearchHierarchyCountsResponse.make({  })
 * console.log(value)
 * ```
 *
 * @category models
 * @since 0.0.0
 */
export class SearchHierarchyCountsResponse extends S.Class<SearchHierarchyCountsResponse>(
  $I`SearchHierarchyCountsResponse`
)(
  {
    counts: S.optionalKey(HierarchyCount.pipe(S.Array)).annotateKey({
      description: "Hierarchy result-count buckets when supplied.",
    }),
  },
  $I.annote("SearchHierarchyCountsResponse", {
    description: "Conservative envelope for hierarchy-level eCFR search counts.",
  })
) {
  static readonly is = S.is(SearchHierarchyCountsResponse);
}

/**
 * Pagination and score metadata for eCFR search results.
 *
 * **Example** (Construct the SearchMeta)
 *
 * ```ts
 * import { SearchMeta } from "@beep/ecfr"
 *
 * const value = SearchMeta.make({ "current_page": 1, "total_count": 1, "total_pages": 1 })
 * console.log(value.current_page)
 * ```
 *
 * @category models
 * @since 0.0.0
 */
export class SearchMeta extends S.Class<SearchMeta>($I`SearchMeta`)(
  {
    description: S.optionalKey(S.String).annotateKey({
      description: "Human-readable description of the search results.",
    }),
    current_page: S.Int.annotateKey({ description: "One-based current result page." }),
    total_count: S.Int.annotateKey({ description: "Total number of matching results across all pages." }),
    total_pages: S.Int.annotateKey({ description: "Total number of result pages." }),
    max_score: S.optionalKey(S.Finite).annotateKey({ description: "Maximum relevance score among matches." }),
    min_date: S.optionalKey(S.String).annotateKey({ description: "Minimum result date when paginating by date." }), // date (YYYY-MM-DD)
    max_date: S.optionalKey(S.String).annotateKey({ description: "Maximum result date when paginating by date." }), // date (YYYY-MM-DD)
  },
  $I.annote("SearchMeta", {
    description: "Pagination and score metadata for eCFR search results.",
  })
) {
  static readonly is = S.is(SearchMeta);
}

/**
 * A section or appendix matching an eCFR search.
 *
 * **Example** (Construct the SearchResult)
 *
 * ```ts
 * import { SearchResult } from "@beep/ecfr"
 *
 * const value = SearchResult.make({  })
 * console.log(value)
 * ```
 *
 * @category models
 * @since 0.0.0
 */
export class SearchResult extends S.Class<SearchResult>($I`SearchResult`)(
  {
    title: S.optionalKey(S.Int).annotateKey({ description: "CFR title number containing the match." }),
    type: S.optionalKey(S.String).annotateKey({ description: "Hierarchy node type of the matching content." }),
    hierarchy_headings: S.optionalKey(S.String.pipe(S.Array)).annotateKey({
      description: "Ordered headings locating the match in the CFR hierarchy.",
    }),
    headings: S.optionalKey(S.String.pipe(S.Array)).annotateKey({
      description: "Headings associated with the matching content.",
    }),
    full_text_excerpt: S.optionalKey(S.String).annotateKey({
      description: "Highlighted excerpt surrounding the matching text.",
    }),
    score: S.optionalKey(S.Finite).annotateKey({ description: "Search relevance score when supplied." }),
  },
  $I.annote("SearchResult", {
    description: "A section or appendix matching an eCFR search.",
  })
) {
  static readonly is = S.is(SearchResult);
}

/**
 * Paginated eCFR search-results envelope.
 *
 * **Example** (Construct the SearchResultsResponse)
 *
 * ```ts
 * import { SearchMeta, SearchResult, SearchResultsResponse } from "@beep/ecfr"
 *
 * const value = SearchResultsResponse.make({ "results": [SearchResult.make({  })], "meta": SearchMeta.make({ "current_page": 1, "total_count": 1, "total_pages": 1 }) })
 * console.log(value.results)
 * ```
 *
 * @category models
 * @since 0.0.0
 */
export class SearchResultsResponse extends S.Class<SearchResultsResponse>($I`SearchResultsResponse`)(
  {
    results: SearchResult.pipe(S.Array).annotateKey({ description: "Sections and appendices matching the request." }),
    meta: SearchMeta.annotateKey({ description: "Pagination metadata for the result set." }),
  },
  $I.annote("SearchResultsResponse", {
    description: "Paginated eCFR search-results envelope.",
  })
) {
  static readonly is = S.is(SearchResultsResponse);
}

/**
 * Conservative envelope for eCFR search suggestions.
 *
 * **Example** (Construct the SearchSuggestionsResponse)
 *
 * ```ts
 * import { SearchSuggestionsResponse } from "@beep/ecfr"
 *
 * const value = SearchSuggestionsResponse.make({  })
 * console.log(value)
 * ```
 *
 * @category models
 * @since 0.0.0
 */
export class SearchSuggestionsResponse extends S.Class<SearchSuggestionsResponse>($I`SearchSuggestionsResponse`)(
  {
    suggestions: S.optionalKey(S.String.pipe(S.Array)).annotateKey({
      description: "Suggested search strings when supplied.",
    }),
  },
  $I.annote("SearchSuggestionsResponse", {
    description: "Conservative envelope for eCFR search suggestions.",
  })
) {
  static readonly is = S.is(SearchSuggestionsResponse);
}

/**
 * Conservative envelope for eCFR search summary details; all known fields remain optional because the official spec leaves the response schema unspecified.
 *
 * **Example** (Construct the SearchSummaryResponse)
 *
 * ```ts
 * import { SearchSummaryResponse } from "@beep/ecfr"
 *
 * const value = SearchSummaryResponse.make({  })
 * console.log(value)
 * ```
 *
 * @category models
 * @since 0.0.0
 */
export class SearchSummaryResponse extends S.Class<SearchSummaryResponse>($I`SearchSummaryResponse`)(
  {
    description: S.optionalKey(S.String).annotateKey({ description: "Human-readable search summary." }),
    count: S.optionalKey(S.Int).annotateKey({ description: "Matching result count when included." }),
  },
  $I.annote("SearchSummaryResponse", {
    description:
      "Conservative envelope for eCFR search summary details; all known fields remain optional because the official spec leaves the response schema unspecified.",
  })
) {
  static readonly is = S.is(SearchSummaryResponse);
}

/**
 * Search-result count associated with one CFR title.
 *
 * **Example** (Construct the TitleCount)
 *
 * ```ts
 * import { TitleCount } from "@beep/ecfr"
 *
 * const value = TitleCount.make({  })
 * console.log(value)
 * ```
 *
 * @category models
 * @since 0.0.0
 */
export class TitleCount extends S.Class<TitleCount>($I`TitleCount`)(
  {
    title: S.optionalKey(S.Int).annotateKey({ description: "CFR title number represented by the bucket." }),
    count: S.optionalKey(S.Int).annotateKey({ description: "Number of matches in the title bucket." }),
  },
  $I.annote("TitleCount", {
    description: "Search-result count associated with one CFR title.",
  })
) {
  static readonly is = S.is(TitleCount);
}

/**
 * Conservative envelope for per-title eCFR search counts.
 *
 * **Example** (Construct the SearchTitleCountsResponse)
 *
 * ```ts
 * import { SearchTitleCountsResponse } from "@beep/ecfr"
 *
 * const value = SearchTitleCountsResponse.make({  })
 * console.log(value)
 * ```
 *
 * @category models
 * @since 0.0.0
 */
export class SearchTitleCountsResponse extends S.Class<SearchTitleCountsResponse>($I`SearchTitleCountsResponse`)(
  {
    counts: S.optionalKey(TitleCount.pipe(S.Array)).annotateKey({
      description: "Per-title result-count buckets when supplied.",
    }),
  },
  $I.annote("SearchTitleCountsResponse", {
    description: "Conservative envelope for per-title eCFR search counts.",
  })
) {
  static readonly is = S.is(SearchTitleCountsResponse);
}

/**
 * A direct child in an eCFR structure tree.
 *
 * **Example** (Construct the StructureChild)
 *
 * ```ts
 * import { StructureChild } from "@beep/ecfr"
 *
 * const value = StructureChild.make({ "type": "example-type", "label": "example-label", "identifier": "example-identifier" })
 * console.log(value.type)
 * ```
 *
 * @category models
 * @since 0.0.0
 */
export class StructureChild extends S.Class<StructureChild>($I`StructureChild`)(
  {
    type: S.String.annotateKey({ description: "Hierarchy level of the child node." }),
    label: S.String.annotateKey({ description: "Complete human-readable child label." }),
    label_level: S.optionalKey(S.String).annotateKey({ description: "Hierarchy level portion of the child label." }),
    label_description: S.optionalKey(S.String).annotateKey({ description: "Descriptive portion of the child label." }),
    identifier: S.String.annotateKey({ description: "Identifier within the hierarchy level." }),
    reserved: S.optionalKey(S.Boolean).annotateKey({ description: "Whether the child node is reserved." }),
    section_range: S.optionalKey(S.String).annotateKey({ description: "Section range covered by the child node." }),
  },
  $I.annote("StructureChild", {
    description: "A direct child in an eCFR structure tree.",
  })
) {
  static readonly is = S.is(StructureChild);
}

/**
 * Root of a CFR title structure tree without regulation text.
 *
 * **Example** (Construct the StructureNode)
 *
 * ```ts
 * import { StructureNode } from "@beep/ecfr"
 *
 * const value = StructureNode.make({ "type": "example-type", "label": "example-label", "identifier": "example-identifier" })
 * console.log(value.type)
 * ```
 *
 * @category models
 * @since 0.0.0
 */
export class StructureNode extends S.Class<StructureNode>($I`StructureNode`)(
  {
    type: S.String.annotateKey({ description: "Hierarchy level of the root node." }),
    label: S.String.annotateKey({ description: "Complete human-readable root label." }),
    label_level: S.optionalKey(S.String).annotateKey({ description: "Hierarchy level portion of the root label." }),
    label_description: S.optionalKey(S.String).annotateKey({ description: "Descriptive portion of the root label." }),
    identifier: S.String.annotateKey({ description: "Identifier within the hierarchy level." }),
    reserved: S.optionalKey(S.Boolean).annotateKey({ description: "Whether the root node is reserved." }),
    section_range: S.optionalKey(S.String).annotateKey({ description: "Section range covered by the root node." }),
    children: S.optionalKey(StructureChild.pipe(S.Array)).annotateKey({
      description: "Direct child nodes. Deeper tree parsing is intentionally conservative in v1.",
    }),
  },
  $I.annote("StructureNode", {
    description: "Root of a CFR title structure tree without regulation text.",
  })
) {
  static readonly is = S.is(StructureNode);
}

/**
 * A CFR title with currency and processing metadata.
 *
 * **Example** (Construct the Title)
 *
 * ```ts
 * import { Title } from "@beep/ecfr"
 *
 * const value = Title.make({ "number": 1, "name": "example-name", "reserved": true })
 * console.log(value.number)
 * ```
 *
 * @category models
 * @since 0.0.0
 */
export class Title extends S.Class<Title>($I`Title`)(
  {
    number: S.Int.annotateKey({ description: "CFR title number, from 1 through 50." }),
    name: S.String.annotateKey({ description: "Official CFR title name." }),
    latest_amended_on: S.optionalKey(S.String).annotateKey({ description: "Most recent amendment date." }), // date (YYYY-MM-DD)
    latest_issue_date: S.optionalKey(S.String).annotateKey({ description: "Most recent published issue date." }), // date (YYYY-MM-DD)
    up_to_date_as_of: S.optionalKey(S.String).annotateKey({
      description: "Date through which the title is confirmed current.",
    }), // date (YYYY-MM-DD)
    reserved: S.Boolean.annotateKey({ description: "Whether the title number is reserved." }),
    processing_in_progress: S.optionalKey(S.Boolean).annotateKey({
      description: "Whether title processing is currently in progress.",
    }),
  },
  $I.annote("Title", {
    description: "A CFR title with currency and processing metadata.",
  })
) {
  static readonly is = S.is(Title);
}

/**
 * Import status metadata accompanying the CFR titles catalog.
 *
 * **Example** (Construct the TitlesMeta)
 *
 * ```ts
 * import { TitlesMeta } from "@beep/ecfr"
 *
 * const value = TitlesMeta.make({  })
 * console.log(value)
 * ```
 *
 * @category models
 * @since 0.0.0
 */
export class TitlesMeta extends S.Class<TitlesMeta>($I`TitlesMeta`)(
  {
    date: S.optionalKey(S.String).annotateKey({ description: "Metadata snapshot date." }), // date (YYYY-MM-DD)
    import_in_progress: S.optionalKey(S.Boolean).annotateKey({
      description: "Whether an eCFR title import is in progress.",
    }),
  },
  $I.annote("TitlesMeta", {
    description: "Import status metadata accompanying the CFR titles catalog.",
  })
) {
  static readonly is = S.is(TitlesMeta);
}

/**
 * Response envelope containing the CFR titles catalog and import metadata.
 *
 * **Example** (Construct the TitlesResponse)
 *
 * ```ts
 * import { Title, TitlesResponse } from "@beep/ecfr"
 *
 * const value = TitlesResponse.make({ "titles": [Title.make({ "number": 1, "name": "example-name", "reserved": true })] })
 * console.log(value.titles)
 * ```
 *
 * @category models
 * @since 0.0.0
 */
export class TitlesResponse extends S.Class<TitlesResponse>($I`TitlesResponse`)(
  {
    titles: Title.pipe(S.Array).annotateKey({ description: "CFR titles and their currency metadata." }),
    meta: S.optionalKey(TitlesMeta).annotateKey({ description: "Catalog import status when supplied." }),
  },
  $I.annote("TitlesResponse", {
    description: "Response envelope containing the CFR titles catalog and import metadata.",
  })
) {
  static readonly is = S.is(TitlesResponse);
}

/**
 * Query and currency metadata for a content-version response.
 *
 * **Example** (Construct the VersionsMeta)
 *
 * ```ts
 * import { VersionsMeta } from "@beep/ecfr"
 *
 * const value = VersionsMeta.make({  })
 * console.log(value)
 * ```
 *
 * @category models
 * @since 0.0.0
 */
export class VersionsMeta extends S.Class<VersionsMeta>($I`VersionsMeta`)(
  {
    title: S.optionalKey(S.String).annotateKey({ description: "Requested CFR title identifier." }),
    result_count: S.optionalKey(S.String).annotateKey({
      description: "Number of content versions returned, as encoded by the upstream API.",
    }),
    latest_amendment_date: S.optionalKey(S.String).annotateKey({
      description: "Latest amendment date among returned versions.",
    }), // date (YYYY-MM-DD)
    latest_issue_date: S.optionalKey(S.String).annotateKey({
      description: "Latest issue date among returned versions.",
    }), // date (YYYY-MM-DD)
  },
  $I.annote("VersionsMeta", {
    description: "Query and currency metadata for a content-version response.",
  })
) {
  static readonly is = S.is(VersionsMeta);
}

/**
 * Response envelope containing CFR content versions and query metadata.
 *
 * **Example** (Construct the VersionsResponse)
 *
 * ```ts
 * import { ContentVersion, VersionsMeta, VersionsResponse } from "@beep/ecfr"
 *
 * const value = VersionsResponse.make({ "content_versions": [ContentVersion.make({ "identifier": "example-identifier", "title": "example-title", "type": "example-type" })], "meta": VersionsMeta.make({  }) })
 * console.log(value.content_versions)
 * ```
 *
 * @category models
 * @since 0.0.0
 */
export class VersionsResponse extends S.Class<VersionsResponse>($I`VersionsResponse`)(
  {
    content_versions: ContentVersion.pipe(S.Array).annotateKey({
      description: "Content versions matching the request.",
    }),
    meta: VersionsMeta.annotateKey({ description: "Query and currency metadata." }),
  },
  $I.annote("VersionsResponse", {
    description: "Response envelope containing CFR content versions and query metadata.",
  })
) {
  static readonly is = S.is(VersionsResponse);
}

/**
 * Descriptor for a single eCFR REST operation.
 *
 * **Example** (Build an operation descriptor)
 *
 * ```ts
 * import { EcfrOperationDescriptor } from "@beep/ecfr"
 *
 * const descriptor = EcfrOperationDescriptor.make({ method: "GET", operationId: "example", path: "/example.json" })
 * console.log(descriptor.path)
 * ```
 *
 * @category endpoints
 * @since 0.0.0
 */
export class EcfrOperationDescriptor extends S.Class<EcfrOperationDescriptor>($I`EcfrOperationDescriptor`)(
  {
    method: S.String,
    operationId: S.String,
    path: S.String,
  },
  $I.annote("EcfrOperationDescriptor", {
    description: "Descriptor for a single eCFR REST operation.",
  })
) {}

/**
 * The `getAncestry` eCFR operation descriptor.
 *
 * **Example** (Read the getAncestry operation path)
 *
 * ```ts
 * import { getAncestryOperation } from "@beep/ecfr"
 *
 * console.log(getAncestryOperation.path)
 * ```
 *
 * @category endpoints
 * @since 0.0.0
 */
export const getAncestryOperation = EcfrOperationDescriptor.make({
  method: "GET",
  operationId: "getAncestry",
  path: "/api/versioner/v1/ancestry/{date}/title-{title}.json",
});

/**
 * The `getFullTitleXml` eCFR operation descriptor.
 *
 * **Example** (Read the getFullTitleXml operation path)
 *
 * ```ts
 * import { getFullTitleXmlOperation } from "@beep/ecfr"
 *
 * console.log(getFullTitleXmlOperation.path)
 * ```
 *
 * @category endpoints
 * @since 0.0.0
 */
export const getFullTitleXmlOperation = EcfrOperationDescriptor.make({
  method: "GET",
  operationId: "getFullTitleXml",
  path: "/api/versioner/v1/full/{date}/title-{title}.xml",
});

/**
 * The `getStructure` eCFR operation descriptor.
 *
 * **Example** (Read the getStructure operation path)
 *
 * ```ts
 * import { getStructureOperation } from "@beep/ecfr"
 *
 * console.log(getStructureOperation.path)
 * ```
 *
 * @category endpoints
 * @since 0.0.0
 */
export const getStructureOperation = EcfrOperationDescriptor.make({
  method: "GET",
  operationId: "getStructure",
  path: "/api/versioner/v1/structure/{date}/title-{title}.json",
});

/**
 * The `listAgencies` eCFR operation descriptor.
 *
 * **Example** (Read the listAgencies operation path)
 *
 * ```ts
 * import { listAgenciesOperation } from "@beep/ecfr"
 *
 * console.log(listAgenciesOperation.path)
 * ```
 *
 * @category endpoints
 * @since 0.0.0
 */
export const listAgenciesOperation = EcfrOperationDescriptor.make({
  method: "GET",
  operationId: "listAgencies",
  path: "/api/admin/v1/agencies.json",
});

/**
 * The `listCorrections` eCFR operation descriptor.
 *
 * **Example** (Read the listCorrections operation path)
 *
 * ```ts
 * import { listCorrectionsOperation } from "@beep/ecfr"
 *
 * console.log(listCorrectionsOperation.path)
 * ```
 *
 * @category endpoints
 * @since 0.0.0
 */
export const listCorrectionsOperation = EcfrOperationDescriptor.make({
  method: "GET",
  operationId: "listCorrections",
  path: "/api/admin/v1/corrections.json",
});

/**
 * The `listTitleCorrections` eCFR operation descriptor.
 *
 * **Example** (Read the listTitleCorrections operation path)
 *
 * ```ts
 * import { listTitleCorrectionsOperation } from "@beep/ecfr"
 *
 * console.log(listTitleCorrectionsOperation.path)
 * ```
 *
 * @category endpoints
 * @since 0.0.0
 */
export const listTitleCorrectionsOperation = EcfrOperationDescriptor.make({
  method: "GET",
  operationId: "listTitleCorrections",
  path: "/api/admin/v1/corrections/title/{title}.json",
});

/**
 * The `listTitles` eCFR operation descriptor.
 *
 * **Example** (Read the listTitles operation path)
 *
 * ```ts
 * import { listTitlesOperation } from "@beep/ecfr"
 *
 * console.log(listTitlesOperation.path)
 * ```
 *
 * @category endpoints
 * @since 0.0.0
 */
export const listTitlesOperation = EcfrOperationDescriptor.make({
  method: "GET",
  operationId: "listTitles",
  path: "/api/versioner/v1/titles.json",
});

/**
 * The `listVersions` eCFR operation descriptor.
 *
 * **Example** (Read the listVersions operation path)
 *
 * ```ts
 * import { listVersionsOperation } from "@beep/ecfr"
 *
 * console.log(listVersionsOperation.path)
 * ```
 *
 * @category endpoints
 * @since 0.0.0
 */
export const listVersionsOperation = EcfrOperationDescriptor.make({
  method: "GET",
  operationId: "listVersions",
  path: "/api/versioner/v1/versions/title-{title}.json",
});

/**
 * The `searchCount` eCFR operation descriptor.
 *
 * **Example** (Read the searchCount operation path)
 *
 * ```ts
 * import { searchCountOperation } from "@beep/ecfr"
 *
 * console.log(searchCountOperation.path)
 * ```
 *
 * @category endpoints
 * @since 0.0.0
 */
export const searchCountOperation = EcfrOperationDescriptor.make({
  method: "GET",
  operationId: "searchCount",
  path: "/api/search/v1/count",
});

/**
 * The `searchDailyCounts` eCFR operation descriptor.
 *
 * **Example** (Read the searchDailyCounts operation path)
 *
 * ```ts
 * import { searchDailyCountsOperation } from "@beep/ecfr"
 *
 * console.log(searchDailyCountsOperation.path)
 * ```
 *
 * @category endpoints
 * @since 0.0.0
 */
export const searchDailyCountsOperation = EcfrOperationDescriptor.make({
  method: "GET",
  operationId: "searchDailyCounts",
  path: "/api/search/v1/counts/daily",
});

/**
 * The `searchHierarchyCounts` eCFR operation descriptor.
 *
 * **Example** (Read the searchHierarchyCounts operation path)
 *
 * ```ts
 * import { searchHierarchyCountsOperation } from "@beep/ecfr"
 *
 * console.log(searchHierarchyCountsOperation.path)
 * ```
 *
 * @category endpoints
 * @since 0.0.0
 */
export const searchHierarchyCountsOperation = EcfrOperationDescriptor.make({
  method: "GET",
  operationId: "searchHierarchyCounts",
  path: "/api/search/v1/counts/hierarchy",
});

/**
 * The `searchResults` eCFR operation descriptor.
 *
 * **Example** (Read the searchResults operation path)
 *
 * ```ts
 * import { searchResultsOperation } from "@beep/ecfr"
 *
 * console.log(searchResultsOperation.path)
 * ```
 *
 * @category endpoints
 * @since 0.0.0
 */
export const searchResultsOperation = EcfrOperationDescriptor.make({
  method: "GET",
  operationId: "searchResults",
  path: "/api/search/v1/results",
});

/**
 * The `searchSuggestions` eCFR operation descriptor.
 *
 * **Example** (Read the searchSuggestions operation path)
 *
 * ```ts
 * import { searchSuggestionsOperation } from "@beep/ecfr"
 *
 * console.log(searchSuggestionsOperation.path)
 * ```
 *
 * @category endpoints
 * @since 0.0.0
 */
export const searchSuggestionsOperation = EcfrOperationDescriptor.make({
  method: "GET",
  operationId: "searchSuggestions",
  path: "/api/search/v1/suggestions",
});

/**
 * The `searchSummary` eCFR operation descriptor.
 *
 * **Example** (Read the searchSummary operation path)
 *
 * ```ts
 * import { searchSummaryOperation } from "@beep/ecfr"
 *
 * console.log(searchSummaryOperation.path)
 * ```
 *
 * @category endpoints
 * @since 0.0.0
 */
export const searchSummaryOperation = EcfrOperationDescriptor.make({
  method: "GET",
  operationId: "searchSummary",
  path: "/api/search/v1/summary",
});

/**
 * The `searchTitleCounts` eCFR operation descriptor.
 *
 * **Example** (Read the searchTitleCounts operation path)
 *
 * ```ts
 * import { searchTitleCountsOperation } from "@beep/ecfr"
 *
 * console.log(searchTitleCountsOperation.path)
 * ```
 *
 * @category endpoints
 * @since 0.0.0
 */
export const searchTitleCountsOperation = EcfrOperationDescriptor.make({
  method: "GET",
  operationId: "searchTitleCounts",
  path: "/api/search/v1/counts/titles",
});

/**
 * All generated eCFR operation descriptors keyed by operation id.
 *
 * **Example** (Look up an operation descriptor)
 *
 * ```ts
 * import { ECFR_OPERATIONS } from "@beep/ecfr"
 *
 * console.log(ECFR_OPERATIONS.getAncestry.descriptor.path)
 * ```
 *
 * @category endpoints
 * @since 0.0.0
 */
export const ECFR_OPERATIONS = {
  getAncestry: { descriptor: getAncestryOperation, response: AncestryResponse },
  getFullTitleXml: { descriptor: getFullTitleXmlOperation, response: S.String },
  getStructure: { descriptor: getStructureOperation, response: StructureNode },
  listAgencies: { descriptor: listAgenciesOperation, response: AgenciesResponse },
  listCorrections: { descriptor: listCorrectionsOperation, response: CorrectionsResponse },
  listTitleCorrections: { descriptor: listTitleCorrectionsOperation, response: CorrectionsResponse },
  listTitles: { descriptor: listTitlesOperation, response: TitlesResponse },
  listVersions: { descriptor: listVersionsOperation, response: VersionsResponse },
  searchCount: { descriptor: searchCountOperation, response: SearchCountResponse },
  searchDailyCounts: { descriptor: searchDailyCountsOperation, response: SearchDailyCountsResponse },
  searchHierarchyCounts: { descriptor: searchHierarchyCountsOperation, response: SearchHierarchyCountsResponse },
  searchResults: { descriptor: searchResultsOperation, response: SearchResultsResponse },
  searchSuggestions: { descriptor: searchSuggestionsOperation, response: SearchSuggestionsResponse },
  searchSummary: { descriptor: searchSummaryOperation, response: SearchSummaryResponse },
  searchTitleCounts: { descriptor: searchTitleCountsOperation, response: SearchTitleCountsResponse },
} as const;
