import { generateSchemaCatalogDocument, lintCommand } from "@beep/repo-cli/commands/Lint";
import { FsUtilsLive } from "@beep/repo-utils/FsUtils";
import { A } from "@beep/utils";
import { NodeServices } from "@effect/platform-node";
import { describe, expect, layer } from "@effect/vitest";
import { Effect, Layer } from "effect";
import * as O from "effect/Option";
import * as TestConsole from "effect/testing/TestConsole";
import { Command } from "effect/unstable/cli";
import {
  expectReportedExit,
  readProjectFile,
  withTempWorkingDirectory,
  writeProjectFile,
} from "./support/CommandTest.js";

const runLintCommand = Command.runWith(lintCommand, { version: "0.0.0" });
const testLayer = Layer.mergeAll(
  NodeServices.layer,
  TestConsole.layer,
  FsUtilsLive.pipe(Layer.provide(NodeServices.layer))
);

const writeSchemaCatalogFixture = Effect.fn("SchemaCatalogTest.writeFixture")(function* () {
  // Root marker so findRepoRoot resolves the temp fixture as the repo root.
  yield* writeProjectFile("bun.lock", "");
  yield* writeProjectFile(
    "package.json",
    A.join(
      [
        "{",
        '  "name": "@beep/test-root",',
        '  "private": true,',
        '  "type": "module",',
        '  "workspaces": ["packages/*"]',
        "}",
        "",
      ],
      "\n"
    )
  );
  yield* writeProjectFile(
    "tsconfig.json",
    A.join(
      [
        "{",
        '  "compilerOptions": {',
        '    "target": "ES2022",',
        '    "module": "ESNext",',
        '    "moduleResolution": "Bundler"',
        "  }",
        "}",
        "",
      ],
      "\n"
    )
  );
  yield* writeProjectFile(
    "packages/example/package.json",
    A.join(["{", '  "name": "@beep/example",', '  "version": "0.0.0",', '  "type": "module"', "}", ""], "\n")
  );
  yield* writeProjectFile(
    "packages/example/src/Example.ts",
    A.join(
      [
        'import { $RepoCliId } from "@beep/identity/packages";',
        'import { LiteralKit } from "@beep/schema";',
        'import * as S from "effect/Schema";',
        "",
        'const $I = $RepoCliId.create("schema-catalog-fixture");',
        "",
        "export class FixtureModel extends S.Class<FixtureModel>($I`FixtureModel`)(",
        "  { id: S.String },",
        '  $I.annote("FixtureModel", { description: "Fixture model schema." })',
        ") {}",
        "",
        'export const FixtureStatus = LiteralKit(["open", "closed"]).pipe(',
        '  $I.annoteSchema("FixtureStatus", { description: "Fixture status values." })',
        ");",
        "",
        "class PrivateModel extends S.Class<PrivateModel>($I`PrivateModel`)(",
        "  { id: S.String },",
        '  $I.annote("PrivateModel", { description: "Module-local helper schema." })',
        ") {}",
        "",
        'const PrivateStatus = LiteralKit(["a", "b"]);',
        "",
        "export const usePrivates = (): ReadonlyArray<unknown> => [PrivateModel, PrivateStatus];",
        "",
      ],
      "\n"
    )
  );
});

layer(testLayer)("schema catalog command", (it) => {
  describe("generation", () => {
    it.effect(
      "writes deterministic catalog bytes on repeated runs",
      Effect.fn("SchemaCatalogTest.deterministicWrites")(function* () {
        yield* withTempWorkingDirectory(
          Effect.gen(function* () {
            yield* writeSchemaCatalogFixture();

            yield* runLintCommand(["schema-catalog", "--write"]);
            const first = yield* readProjectFile("standards/schema-catalog.generated.jsonc");
            yield* runLintCommand(["schema-catalog", "--write"]);
            const second = yield* readProjectFile("standards/schema-catalog.generated.jsonc");

            expect(second).toBe(first);
            expect(first).toContain("// Generated by bun run beep lint schema-catalog --write.");
            expect(first).toContain('"schemaVersion": "schema-catalog/v1"');
            expect(first).toContain('"generatedBy": "bun run beep lint schema-catalog --write"');
          })
        );
      })
    );

    it.effect(
      "catalogs a fixture S.Class with kind and owner",
      Effect.fn("SchemaCatalogTest.fixtureEntry")(function* () {
        yield* withTempWorkingDirectory(
          Effect.gen(function* () {
            yield* writeSchemaCatalogFixture();
            const document = yield* generateSchemaCatalogDocument();
            const entry = A.findFirst(
              document.entries,
              (candidate) => candidate.file === "packages/example/src/Example.ts" && candidate.symbol === "FixtureModel"
            );

            expect(O.isSome(entry)).toBe(true);
            if (O.isSome(entry)) {
              expect(entry.value.kind).toBe("schema-class");
              expect(entry.value.owner).toBe("@beep/example");
              expect(entry.value.identity).toBe("FixtureModel");
              expect(entry.value.description).toBe("Fixture model schema.");
            }

            // Non-exported declarations are private helpers, not catalog surface.
            const symbols = A.map(document.entries, (candidate) => candidate.symbol);
            expect(A.contains(symbols, "PrivateModel")).toBe(false);
            expect(A.contains(symbols, "PrivateStatus")).toBe(false);
          })
        );
      })
    );

    it.effect(
      "fails check mode when the tracked catalog is stale",
      Effect.fn("SchemaCatalogTest.staleCheck")(function* () {
        yield* withTempWorkingDirectory(
          Effect.gen(function* () {
            yield* writeSchemaCatalogFixture();
            yield* writeProjectFile("standards/schema-catalog.generated.jsonc", "// stale\n{}\n");

            const exit = yield* Effect.exit(runLintCommand(["schema-catalog"]));
            const errorLines = yield* TestConsole.errorLines;

            expectReportedExit(exit);
            expect(errorLines).toContain("[schema-catalog] stale standards/schema-catalog.generated.jsonc");
          })
        );
      })
    );
  });
});
