/**
 * Deterministic configuration projection for the identity lint candidate.
 *
 * @packageDocumentation
 * @since 0.0.0
 */
import { $RepoCliId } from "@beep/identity/packages";
import { decodeJsoncTextAs } from "@beep/schema/Jsonc";
import { Effect } from "effect";
import * as A from "effect/Array";
import * as R from "effect/Record";
import * as S from "effect/Schema";
import { writeContainedFileString } from "../../internal/cli/FsGuards.ts";
import { JsonStringCodec } from "../../internal/schema/JsonCodec.ts";
import { decodeCacheExperimentText, readCacheExperimentBytes } from "./Cache.evidence.ts";
import { CacheCommandError } from "./Cache.schemas.ts";

const $I = $RepoCliId.create("commands/Cache/Cache.profile");
const SupportedIncludes = S.TupleWithRest(S.Tuple([S.Literal("**")]), [S.String.check(S.isPattern(/^!.+/))]).annotate(
  $I.annote("SupportedIncludes", {
    description: "Reviewed root scanner selection: one universal positive selector followed only by exclusions.",
  })
);
const decodeIncludes = S.decodeUnknownEffect(SupportedIncludes);
const decodeObject = S.decodeUnknownEffect(S.JsonObject);
const decodeRoot = S.decodeUnknownEffect(S.Literal(true));
const profilePath = "biome.identity.jsonc";

/**
 * Project root rules into the reviewed identity/types scanner scope without dropping exclusions.
 *
 * **Details**
 * Rejects inherited configurations and unreviewed positive-selector shapes.
 * The output belongs beside the root config so relative plugin paths retain
 * their meaning. Projection does not grant cache qualification.
 *
 * **Example** (Project an explicitly rooted configuration)
 *
 * ```ts
 * import { renderCacheIdentityLintProfile } from "@beep/repo-cli/test/Cache"
 * import * as Effect from "effect/Effect"
 * const profile = renderCacheIdentityLintProfile('{"root":true,"files":{"includes":["**","!vendor"]}}')
 * console.assert(Effect.isEffect(profile))
 * ```
 *
 * @category mapping
 * @since 0.0.0
 */
export const renderCacheIdentityLintProfile = Effect.fn("CacheProfile.render")(function* (source: string) {
  const config = yield* decodeJsoncTextAs(S.JsonObject)(source);
  yield* decodeRoot(config.root);
  if (R.has(config, "extends"))
    return yield* CacheCommandError.new("Identity lint profile cannot inherit another config.");
  const files = yield* decodeObject(config.files);
  const includes = yield* decodeIncludes(files.includes);
  const projected = R.set(
    config,
    "files",
    R.set(files, "includes", [
      "packages/foundation/modeling/identity/**",
      "packages/foundation/primitive/types/**",
      ...A.drop(includes, 1),
    ])
  );
  return `// biome-ignore format: Generated by beep cache profile; regenerate instead of editing.\n${yield* JsonStringCodec(S.JsonObject).encode(projected)}\n`;
}, CacheCommandError.mapError("Cannot project the reviewed identity lint profile."));

const renderFromRoot = Effect.fn("CacheProfile.renderFromRoot")(function* (root: string) {
  const source = yield* readCacheExperimentBytes(root, "biome.jsonc").pipe(Effect.flatMap(decodeCacheExperimentText));
  return yield* renderCacheIdentityLintProfile(source);
});

/**
 * Reject a missing or stale generated identity lint profile using bounded no-follow reads.
 *
 * **Example** (Require a current generated profile)
 *
 * ```ts
 * import { verifyCacheIdentityLintProfile } from "@beep/repo-cli/test/Cache"
 * import * as Effect from "effect/Effect"
 * console.assert(Effect.isEffect(verifyCacheIdentityLintProfile("/repo")))
 * ```
 *
 * @category validation
 * @since 0.0.0
 */
export const verifyCacheIdentityLintProfile = Effect.fn("CacheProfile.verify")(function* (root: string) {
  const expected = yield* renderFromRoot(root);
  const actual = yield* readCacheExperimentBytes(root, profilePath).pipe(Effect.flatMap(decodeCacheExperimentText));
  if (actual !== expected)
    return yield* CacheCommandError.new("Identity lint profile is stale; regenerate it with cache profile --write.");
}, CacheCommandError.mapError("Cannot verify the generated identity lint profile."));

/**
 * Write the reviewed identity profile beside its root configuration with contained-path guards.
 *
 * **Details**
 * This only prepares a candidate configuration. It does not select it for a
 * task, enable caching, or replace execution-time freshness verification.
 *
 * **Example** (Prepare a candidate profile)
 *
 * ```ts
 * import { writeCacheIdentityLintProfile } from "@beep/repo-cli/test/Cache"
 * import * as Effect from "effect/Effect"
 * console.assert(Effect.isEffect(writeCacheIdentityLintProfile("/repo")))
 * ```
 *
 * @category commands
 * @since 0.0.0
 */
export const writeCacheIdentityLintProfile = Effect.fn("CacheProfile.write")(function* (root: string) {
  yield* writeContainedFileString(root, profilePath, yield* renderFromRoot(root));
}, CacheCommandError.mapError("Cannot write the generated identity lint profile."));
