/**
 * GENERATED FILE — do not edit by hand. Run `bun run generate`.
 *
 * Per-element metadata for the HTML AST: DOM interface, conformance tier, void /
 * raw-text classification, and (advisory) content categories.
 *
 * @packageDocumentation \@beep/html/Html.meta
 * @since 0.0.0
 */
import { $HtmlId } from "@beep/identity";
import { LiteralKit } from "@beep/schema";
import * as S from "effect/Schema";

const $I = $HtmlId.create("Html.meta");

/**
 * Exact generated HTML element-tag domain.
 *
 * @example
 * ```ts
 * import { HtmlTag } from "@beep/html/Html.meta"
 *
 * console.log(HtmlTag.is.div("div")) // true
 * ```
 *
 * @category models
 * @since 0.0.0
 */
export const HtmlTag = LiteralKit([
  "a",
  "abbr",
  "acronym",
  "address",
  "applet",
  "area",
  "article",
  "aside",
  "audio",
  "b",
  "base",
  "basefont",
  "bdi",
  "bdo",
  "bgsound",
  "big",
  "blink",
  "blockquote",
  "body",
  "br",
  "button",
  "canvas",
  "caption",
  "center",
  "cite",
  "code",
  "col",
  "colgroup",
  "data",
  "datalist",
  "dd",
  "del",
  "details",
  "dfn",
  "dialog",
  "dir",
  "div",
  "dl",
  "dt",
  "em",
  "embed",
  "fieldset",
  "figcaption",
  "figure",
  "font",
  "footer",
  "form",
  "frame",
  "frameset",
  "h1",
  "h2",
  "h3",
  "h4",
  "h5",
  "h6",
  "head",
  "header",
  "hgroup",
  "hr",
  "html",
  "i",
  "iframe",
  "img",
  "input",
  "ins",
  "isindex",
  "kbd",
  "keygen",
  "label",
  "legend",
  "li",
  "link",
  "listing",
  "main",
  "map",
  "mark",
  "marquee",
  "menu",
  "menuitem",
  "meta",
  "meter",
  "multicol",
  "nav",
  "nextid",
  "nobr",
  "noembed",
  "noframes",
  "noscript",
  "object",
  "ol",
  "optgroup",
  "option",
  "output",
  "p",
  "param",
  "picture",
  "plaintext",
  "pre",
  "progress",
  "q",
  "rb",
  "rp",
  "rt",
  "rtc",
  "ruby",
  "s",
  "samp",
  "script",
  "search",
  "section",
  "select",
  "selectedcontent",
  "slot",
  "small",
  "source",
  "spacer",
  "span",
  "strike",
  "strong",
  "style",
  "sub",
  "summary",
  "sup",
  "table",
  "tbody",
  "td",
  "template",
  "textarea",
  "tfoot",
  "th",
  "thead",
  "time",
  "title",
  "tr",
  "track",
  "tt",
  "u",
  "ul",
  "var",
  "video",
  "wbr",
  "xmp",
]).pipe($I.annoteSchema("HtmlTag", { description: "Exact generated HTML element-tag domain." }));

/**
 * Decoded HTML element tag.
 *
 * @example
 * ```ts
 * import type { HtmlTag } from "@beep/html/Html.meta"
 *
 * const tag: HtmlTag = "div"
 * console.log(tag)
 * ```
 *
 * @category models
 * @since 0.0.0
 */
export type HtmlTag = typeof HtmlTag.Type;

/**
 * Advisory content-category values emitted by the WHATWG element index.
 *
 * @example
 * ```ts
 * import { HtmlCategory } from "@beep/html/Html.meta"
 *
 * console.log(HtmlCategory.is.flow("flow")) // true
 * ```
 *
 * @category models
 * @since 0.0.0
 */
export const HtmlCategory = LiteralKit([
  "embedded",
  "flow",
  "form-associated",
  "heading",
  "interactive",
  "labelable",
  "listed",
  "metadata",
  "palpable",
  "phrasing",
  "resettable",
  "script-supporting",
  "sectioning",
  "submittable",
]).pipe($I.annoteSchema("HtmlCategory", { description: "Advisory WHATWG content-category value." }));

/**
 * Decoded advisory content category.
 *
 * @example
 * ```ts
 * import type { HtmlCategory } from "@beep/html/Html.meta"
 *
 * const category: HtmlCategory = "flow"
 * console.log(category)
 * ```
 *
 * @category models
 * @since 0.0.0
 */
export type HtmlCategory = typeof HtmlCategory.Type;

/**
 * Content-model tokens emitted by the pinned WHATWG element index.
 *
 * @example
 * ```ts
 * import { HtmlContentToken } from "@beep/html/Html.meta"
 *
 * console.log(HtmlContentToken.is.flow("flow")) // true
 * ```
 *
 * @category models
 * @since 0.0.0
 */
export const HtmlContentToken = LiteralKit([
  "area",
  "body",
  "button",
  "caption",
  "col",
  "colgroup",
  "data",
  "dd",
  "div",
  "dt",
  "empty",
  "figcaption",
  "flow",
  "flow select element inner content elements",
  "h1",
  "h2",
  "h3",
  "h4",
  "h5",
  "h6",
  "head",
  "heading content",
  "legend",
  "li",
  "metadata content",
  "one img",
  "optgroup element inner content elements",
  "option",
  "option element inner content elements",
  "or script documentation",
  "p",
  "phrasing",
  "rp",
  "rt",
  "script",
  "script-supporting elements",
  "select element inner content elements",
  "source",
  "summary",
  "tbody",
  "td",
  "template",
  "text",
  "tfoot",
  "th",
  "thead",
  "tr",
  "track",
  "transparent",
  "varies",
]).pipe($I.annoteSchema("HtmlContentToken", { description: "Pinned HTML content-model token." }));

/**
 * Decoded HTML content-model token.
 *
 * @example
 * ```ts
 * import type { HtmlContentToken } from "@beep/html/Html.meta"
 *
 * const token: HtmlContentToken = "flow"
 * console.log(token)
 * ```
 *
 * @category models
 * @since 0.0.0
 */
export type HtmlContentToken = typeof HtmlContentToken.Type;

/**
 * Text parsing and serialization mode of an HTML element.
 *
 * @example
 * ```ts
 * import { HtmlTextMode } from "@beep/html/Html.meta"
 *
 * console.log(HtmlTextMode.is.rcdata("rcdata")) // true
 * ```
 *
 * @category models
 * @since 0.0.0
 */
export const HtmlTextMode = LiteralKit(["normal", "raw-text", "rcdata", "plaintext"]).pipe(
  $I.annoteSchema("HtmlTextMode", { description: "HTML text parsing and serialization mode." })
);

/**
 * Decoded HTML text mode.
 *
 * @example
 * ```ts
 * import type { HtmlTextMode } from "@beep/html/Html.meta"
 *
 * const mode: HtmlTextMode = "normal"
 * console.log(mode)
 * ```
 *
 * @category models
 * @since 0.0.0
 */
export type HtmlTextMode = typeof HtmlTextMode.Type;

/**
 * Authoritative generated domain of HTML boolean attribute names.
 *
 * @example
 * ```ts
 * import { HtmlBooleanAttributeName } from "@beep/html/Html.meta"
 *
 * console.log(HtmlBooleanAttributeName.is.disabled("disabled")) // true
 * ```
 *
 * @category models
 * @since 0.0.0
 */
export const HtmlBooleanAttributeName = LiteralKit([
  "allowfullscreen",
  "alpha",
  "async",
  "autoplay",
  "checked",
  "compact",
  "controls",
  "declare",
  "default",
  "defer",
  "disabled",
  "formnovalidate",
  "ismap",
  "loop",
  "multiple",
  "muted",
  "nomodule",
  "noresize",
  "noshade",
  "novalidate",
  "nowrap",
  "open",
  "playsinline",
  "pubdate",
  "readonly",
  "required",
  "reversed",
  "scoped",
  "seamless",
  "selected",
  "shadowrootclonable",
  "shadowrootdelegatesfocus",
  "shadowrootserializable",
  "truespeed",
]).pipe(
  $I.annoteSchema("HtmlBooleanAttributeName", {
    description: "Authoritative HTML boolean attribute-name domain used by generation and serialization.",
  })
);

/**
 * Decoded HTML boolean attribute name.
 *
 * @example
 * ```ts
 * import { HtmlBooleanAttributeName } from "@beep/html/Html.meta"
 * import { Result } from "effect"
 * import * as S from "effect/Schema"
 *
 * const decoded = S.decodeUnknownResult(HtmlBooleanAttributeName)("disabled")
 * if (Result.isSuccess(decoded)) {
 *   const name: HtmlBooleanAttributeName = decoded.success
 *   console.log(name) // "disabled"
 * }
 * ```
 *
 * @category models
 * @since 0.0.0
 */
export type HtmlBooleanAttributeName = typeof HtmlBooleanAttributeName.Type;

/**
 * Schema describing one HTML element kind's metadata.
 *
 * @example
 * ```ts
 * import { HtmlElementMeta } from "@beep/html/Html.meta"
 * import * as S from "effect/Schema"
 *
 * console.log(S.is(HtmlElementMeta)({
 *   tag: "div",
 *   interface: "HTMLDivElement",
 *   conformance: "conforming",
 *   void: false,
 *   rawText: false,
 *   categories: ["flow"]
 * })) // true
 * ```
 *
 * @category models
 * @since 0.0.0
 */
export class HtmlElementMeta extends S.Class<HtmlElementMeta>($I`HtmlElementMeta`)(
  {
    tag: HtmlTag,
    interface: S.NonEmptyString,
    conformance: S.Literals(["conforming", "non-conforming"]),
    void: S.Boolean,
    rawText: S.Boolean,
    textMode: HtmlTextMode,
    categories: S.Array(HtmlCategory),
    children: S.Array(HtmlContentToken),
    childSequencePattern: S.String.pipe(S.optionalKey),
  },
  $I.annote("HtmlElementMeta", { description: "Metadata describing one HTML element kind." })
) {}

/**
 * Metadata for every generated HTML element, keyed by tag name.
 *
 * @example
 * ```ts
 * import { ELEMENT_META } from "@beep/html/Html.meta"
 *
 * console.log(ELEMENT_META.div.interface) // "HTMLDivElement"
 * ```
 *
 * @category models
 * @since 0.0.0
 */
export const ELEMENT_META: Readonly<Record<HtmlTag, HtmlElementMeta>> = {
  a: {
    tag: "a",
    interface: "HTMLAnchorElement",
    conformance: "conforming",
    void: false,
    rawText: false,
    textMode: "normal",
    categories: ["flow", "phrasing", "interactive", "palpable"],
    children: ["transparent"],
  },
  abbr: {
    tag: "abbr",
    interface: "HTMLElement",
    conformance: "conforming",
    void: false,
    rawText: false,
    textMode: "normal",
    categories: ["flow", "phrasing", "palpable"],
    children: ["phrasing"],
  },
  acronym: {
    tag: "acronym",
    interface: "HTMLElement",
    conformance: "non-conforming",
    void: false,
    rawText: false,
    textMode: "normal",
    categories: [],
    children: [],
  },
  address: {
    tag: "address",
    interface: "HTMLElement",
    conformance: "conforming",
    void: false,
    rawText: false,
    textMode: "normal",
    categories: ["flow", "palpable"],
    children: ["flow"],
  },
  applet: {
    tag: "applet",
    interface: "HTMLUnknownElement",
    conformance: "non-conforming",
    void: false,
    rawText: false,
    textMode: "normal",
    categories: [],
    children: [],
  },
  area: {
    tag: "area",
    interface: "HTMLAreaElement",
    conformance: "conforming",
    void: true,
    rawText: false,
    textMode: "normal",
    categories: ["flow", "phrasing"],
    children: ["empty"],
  },
  article: {
    tag: "article",
    interface: "HTMLElement",
    conformance: "conforming",
    void: false,
    rawText: false,
    textMode: "normal",
    categories: ["flow", "sectioning", "palpable"],
    children: ["flow"],
  },
  aside: {
    tag: "aside",
    interface: "HTMLElement",
    conformance: "conforming",
    void: false,
    rawText: false,
    textMode: "normal",
    categories: ["flow", "sectioning", "palpable"],
    children: ["flow"],
  },
  audio: {
    tag: "audio",
    interface: "HTMLAudioElement",
    conformance: "conforming",
    void: false,
    rawText: false,
    textMode: "normal",
    categories: ["flow", "phrasing", "embedded", "interactive", "palpable"],
    children: ["source", "track", "transparent"],
  },
  b: {
    tag: "b",
    interface: "HTMLElement",
    conformance: "conforming",
    void: false,
    rawText: false,
    textMode: "normal",
    categories: ["flow", "phrasing", "palpable"],
    children: ["phrasing"],
  },
  base: {
    tag: "base",
    interface: "HTMLBaseElement",
    conformance: "conforming",
    void: true,
    rawText: false,
    textMode: "normal",
    categories: ["metadata"],
    children: ["empty"],
  },
  basefont: {
    tag: "basefont",
    interface: "HTMLElement",
    conformance: "non-conforming",
    void: true,
    rawText: false,
    textMode: "normal",
    categories: [],
    children: [],
  },
  bdi: {
    tag: "bdi",
    interface: "HTMLElement",
    conformance: "conforming",
    void: false,
    rawText: false,
    textMode: "normal",
    categories: ["flow", "phrasing", "palpable"],
    children: ["phrasing"],
  },
  bdo: {
    tag: "bdo",
    interface: "HTMLElement",
    conformance: "conforming",
    void: false,
    rawText: false,
    textMode: "normal",
    categories: ["flow", "phrasing", "palpable"],
    children: ["phrasing"],
  },
  bgsound: {
    tag: "bgsound",
    interface: "HTMLUnknownElement",
    conformance: "non-conforming",
    void: true,
    rawText: false,
    textMode: "normal",
    categories: [],
    children: [],
  },
  big: {
    tag: "big",
    interface: "HTMLElement",
    conformance: "non-conforming",
    void: false,
    rawText: false,
    textMode: "normal",
    categories: [],
    children: [],
  },
  blink: {
    tag: "blink",
    interface: "HTMLUnknownElement",
    conformance: "non-conforming",
    void: false,
    rawText: false,
    textMode: "normal",
    categories: [],
    children: [],
  },
  blockquote: {
    tag: "blockquote",
    interface: "HTMLQuoteElement",
    conformance: "conforming",
    void: false,
    rawText: false,
    textMode: "normal",
    categories: ["flow", "palpable"],
    children: ["flow"],
  },
  body: {
    tag: "body",
    interface: "HTMLBodyElement",
    conformance: "conforming",
    void: false,
    rawText: false,
    textMode: "normal",
    categories: [],
    children: ["flow"],
  },
  br: {
    tag: "br",
    interface: "HTMLBRElement",
    conformance: "conforming",
    void: true,
    rawText: false,
    textMode: "normal",
    categories: ["flow", "phrasing"],
    children: ["empty"],
  },
  button: {
    tag: "button",
    interface: "HTMLButtonElement",
    conformance: "conforming",
    void: false,
    rawText: false,
    textMode: "normal",
    categories: [
      "flow",
      "phrasing",
      "interactive",
      "listed",
      "labelable",
      "submittable",
      "form-associated",
      "palpable",
    ],
    children: ["phrasing"],
  },
  canvas: {
    tag: "canvas",
    interface: "HTMLCanvasElement",
    conformance: "conforming",
    void: false,
    rawText: false,
    textMode: "normal",
    categories: ["flow", "phrasing", "embedded", "palpable"],
    children: ["transparent"],
  },
  caption: {
    tag: "caption",
    interface: "HTMLTableCaptionElement",
    conformance: "conforming",
    void: false,
    rawText: false,
    textMode: "normal",
    categories: [],
    children: ["flow"],
  },
  center: {
    tag: "center",
    interface: "HTMLElement",
    conformance: "non-conforming",
    void: false,
    rawText: false,
    textMode: "normal",
    categories: [],
    children: [],
  },
  cite: {
    tag: "cite",
    interface: "HTMLElement",
    conformance: "conforming",
    void: false,
    rawText: false,
    textMode: "normal",
    categories: ["flow", "phrasing", "palpable"],
    children: ["phrasing"],
  },
  code: {
    tag: "code",
    interface: "HTMLElement",
    conformance: "conforming",
    void: false,
    rawText: false,
    textMode: "normal",
    categories: ["flow", "phrasing", "palpable"],
    children: ["phrasing"],
  },
  col: {
    tag: "col",
    interface: "HTMLTableColElement",
    conformance: "conforming",
    void: true,
    rawText: false,
    textMode: "normal",
    categories: [],
    children: ["empty"],
  },
  colgroup: {
    tag: "colgroup",
    interface: "HTMLTableColElement",
    conformance: "conforming",
    void: false,
    rawText: false,
    textMode: "normal",
    categories: [],
    children: ["col", "template"],
  },
  data: {
    tag: "data",
    interface: "HTMLDataElement",
    conformance: "conforming",
    void: false,
    rawText: false,
    textMode: "normal",
    categories: ["flow", "phrasing", "palpable"],
    children: ["phrasing"],
  },
  datalist: {
    tag: "datalist",
    interface: "HTMLDataListElement",
    conformance: "conforming",
    void: false,
    rawText: false,
    textMode: "normal",
    categories: ["flow", "phrasing"],
    children: ["phrasing", "option", "script-supporting elements"],
  },
  dd: {
    tag: "dd",
    interface: "HTMLElement",
    conformance: "conforming",
    void: false,
    rawText: false,
    textMode: "normal",
    categories: [],
    children: ["flow"],
  },
  del: {
    tag: "del",
    interface: "HTMLModElement",
    conformance: "conforming",
    void: false,
    rawText: false,
    textMode: "normal",
    categories: ["flow", "phrasing", "palpable"],
    children: ["transparent"],
  },
  details: {
    tag: "details",
    interface: "HTMLDetailsElement",
    conformance: "conforming",
    void: false,
    rawText: false,
    textMode: "normal",
    categories: ["flow", "interactive", "palpable"],
    children: ["summary", "flow"],
  },
  dfn: {
    tag: "dfn",
    interface: "HTMLElement",
    conformance: "conforming",
    void: false,
    rawText: false,
    textMode: "normal",
    categories: ["flow", "phrasing", "palpable"],
    children: ["phrasing"],
  },
  dialog: {
    tag: "dialog",
    interface: "HTMLDialogElement",
    conformance: "conforming",
    void: false,
    rawText: false,
    textMode: "normal",
    categories: ["flow"],
    children: ["flow"],
  },
  dir: {
    tag: "dir",
    interface: "HTMLDirectoryElement",
    conformance: "non-conforming",
    void: false,
    rawText: false,
    textMode: "normal",
    categories: [],
    children: [],
  },
  div: {
    tag: "div",
    interface: "HTMLDivElement",
    conformance: "conforming",
    void: false,
    rawText: false,
    textMode: "normal",
    categories: ["flow", "palpable"],
    children: [
      "flow select element inner content elements",
      "optgroup element inner content elements",
      "option element inner content elements",
    ],
  },
  dl: {
    tag: "dl",
    interface: "HTMLDListElement",
    conformance: "conforming",
    void: false,
    rawText: false,
    textMode: "normal",
    categories: ["flow", "palpable"],
    children: ["dt", "dd", "div", "script-supporting elements"],
  },
  dt: {
    tag: "dt",
    interface: "HTMLElement",
    conformance: "conforming",
    void: false,
    rawText: false,
    textMode: "normal",
    categories: [],
    children: ["flow"],
  },
  em: {
    tag: "em",
    interface: "HTMLElement",
    conformance: "conforming",
    void: false,
    rawText: false,
    textMode: "normal",
    categories: ["flow", "phrasing", "palpable"],
    children: ["phrasing"],
  },
  embed: {
    tag: "embed",
    interface: "HTMLEmbedElement",
    conformance: "conforming",
    void: true,
    rawText: false,
    textMode: "normal",
    categories: ["flow", "phrasing", "embedded", "interactive", "palpable"],
    children: ["empty"],
  },
  fieldset: {
    tag: "fieldset",
    interface: "HTMLFieldSetElement",
    conformance: "conforming",
    void: false,
    rawText: false,
    textMode: "normal",
    categories: ["flow", "listed", "form-associated", "palpable"],
    children: ["legend", "flow"],
  },
  figcaption: {
    tag: "figcaption",
    interface: "HTMLElement",
    conformance: "conforming",
    void: false,
    rawText: false,
    textMode: "normal",
    categories: [],
    children: ["flow"],
  },
  figure: {
    tag: "figure",
    interface: "HTMLElement",
    conformance: "conforming",
    void: false,
    rawText: false,
    textMode: "normal",
    categories: ["flow", "palpable"],
    children: ["figcaption", "flow"],
  },
  font: {
    tag: "font",
    interface: "HTMLFontElement",
    conformance: "non-conforming",
    void: false,
    rawText: false,
    textMode: "normal",
    categories: [],
    children: [],
  },
  footer: {
    tag: "footer",
    interface: "HTMLElement",
    conformance: "conforming",
    void: false,
    rawText: false,
    textMode: "normal",
    categories: ["flow", "palpable"],
    children: ["flow"],
  },
  form: {
    tag: "form",
    interface: "HTMLFormElement",
    conformance: "conforming",
    void: false,
    rawText: false,
    textMode: "normal",
    categories: ["flow", "palpable"],
    children: ["flow"],
  },
  frame: {
    tag: "frame",
    interface: "HTMLFrameElement",
    conformance: "non-conforming",
    void: true,
    rawText: false,
    textMode: "normal",
    categories: [],
    children: [],
  },
  frameset: {
    tag: "frameset",
    interface: "HTMLFrameSetElement",
    conformance: "non-conforming",
    void: false,
    rawText: false,
    textMode: "normal",
    categories: [],
    children: [],
  },
  h1: {
    tag: "h1",
    interface: "HTMLHeadingElement",
    conformance: "conforming",
    void: false,
    rawText: false,
    textMode: "normal",
    categories: ["flow", "heading", "palpable"],
    children: ["phrasing"],
  },
  h2: {
    tag: "h2",
    interface: "HTMLHeadingElement",
    conformance: "conforming",
    void: false,
    rawText: false,
    textMode: "normal",
    categories: ["flow", "heading", "palpable"],
    children: ["phrasing"],
  },
  h3: {
    tag: "h3",
    interface: "HTMLHeadingElement",
    conformance: "conforming",
    void: false,
    rawText: false,
    textMode: "normal",
    categories: ["flow", "heading", "palpable"],
    children: ["phrasing"],
  },
  h4: {
    tag: "h4",
    interface: "HTMLHeadingElement",
    conformance: "conforming",
    void: false,
    rawText: false,
    textMode: "normal",
    categories: ["flow", "heading", "palpable"],
    children: ["phrasing"],
  },
  h5: {
    tag: "h5",
    interface: "HTMLHeadingElement",
    conformance: "conforming",
    void: false,
    rawText: false,
    textMode: "normal",
    categories: ["flow", "heading", "palpable"],
    children: ["phrasing"],
  },
  h6: {
    tag: "h6",
    interface: "HTMLHeadingElement",
    conformance: "conforming",
    void: false,
    rawText: false,
    textMode: "normal",
    categories: ["flow", "heading", "palpable"],
    children: ["phrasing"],
  },
  head: {
    tag: "head",
    interface: "HTMLHeadElement",
    conformance: "conforming",
    void: false,
    rawText: false,
    textMode: "normal",
    categories: [],
    children: ["metadata content"],
  },
  header: {
    tag: "header",
    interface: "HTMLElement",
    conformance: "conforming",
    void: false,
    rawText: false,
    textMode: "normal",
    categories: ["flow", "palpable"],
    children: ["flow"],
  },
  hgroup: {
    tag: "hgroup",
    interface: "HTMLElement",
    conformance: "conforming",
    void: false,
    rawText: false,
    textMode: "normal",
    categories: ["flow", "palpable"],
    children: ["h1", "h2", "h3", "h4", "h5", "h6", "p", "script-supporting elements"],
  },
  hr: {
    tag: "hr",
    interface: "HTMLHRElement",
    conformance: "conforming",
    void: true,
    rawText: false,
    textMode: "normal",
    categories: ["flow"],
    children: ["empty"],
  },
  html: {
    tag: "html",
    interface: "HTMLHtmlElement",
    conformance: "conforming",
    void: false,
    rawText: false,
    textMode: "normal",
    categories: [],
    children: ["head", "body"],
  },
  i: {
    tag: "i",
    interface: "HTMLElement",
    conformance: "conforming",
    void: false,
    rawText: false,
    textMode: "normal",
    categories: ["flow", "phrasing", "palpable"],
    children: ["phrasing"],
  },
  iframe: {
    tag: "iframe",
    interface: "HTMLIFrameElement",
    conformance: "conforming",
    void: false,
    rawText: true,
    textMode: "raw-text",
    categories: ["flow", "phrasing", "embedded", "interactive", "palpable"],
    children: ["empty"],
  },
  img: {
    tag: "img",
    interface: "HTMLImageElement",
    conformance: "conforming",
    void: true,
    rawText: false,
    textMode: "normal",
    categories: ["flow", "phrasing", "embedded", "interactive", "form-associated", "palpable"],
    children: ["empty"],
  },
  input: {
    tag: "input",
    interface: "HTMLInputElement",
    conformance: "conforming",
    void: true,
    rawText: false,
    textMode: "normal",
    categories: [
      "flow",
      "phrasing",
      "interactive",
      "listed",
      "labelable",
      "submittable",
      "resettable",
      "form-associated",
      "palpable",
    ],
    children: ["empty"],
  },
  ins: {
    tag: "ins",
    interface: "HTMLModElement",
    conformance: "conforming",
    void: false,
    rawText: false,
    textMode: "normal",
    categories: ["flow", "phrasing", "palpable"],
    children: ["transparent"],
  },
  isindex: {
    tag: "isindex",
    interface: "HTMLUnknownElement",
    conformance: "non-conforming",
    void: true,
    rawText: false,
    textMode: "normal",
    categories: [],
    children: [],
  },
  kbd: {
    tag: "kbd",
    interface: "HTMLElement",
    conformance: "conforming",
    void: false,
    rawText: false,
    textMode: "normal",
    categories: ["flow", "phrasing", "palpable"],
    children: ["phrasing"],
  },
  keygen: {
    tag: "keygen",
    interface: "HTMLUnknownElement",
    conformance: "non-conforming",
    void: true,
    rawText: false,
    textMode: "normal",
    categories: [],
    children: [],
  },
  label: {
    tag: "label",
    interface: "HTMLLabelElement",
    conformance: "conforming",
    void: false,
    rawText: false,
    textMode: "normal",
    categories: ["flow", "phrasing", "interactive", "palpable"],
    children: ["phrasing"],
  },
  legend: {
    tag: "legend",
    interface: "HTMLLegendElement",
    conformance: "conforming",
    void: false,
    rawText: false,
    textMode: "normal",
    categories: [],
    children: ["phrasing", "heading content"],
  },
  li: {
    tag: "li",
    interface: "HTMLLIElement",
    conformance: "conforming",
    void: false,
    rawText: false,
    textMode: "normal",
    categories: [],
    children: ["flow"],
  },
  link: {
    tag: "link",
    interface: "HTMLLinkElement",
    conformance: "conforming",
    void: true,
    rawText: false,
    textMode: "normal",
    categories: ["metadata", "flow", "phrasing"],
    children: ["empty"],
  },
  listing: {
    tag: "listing",
    interface: "HTMLPreElement",
    conformance: "non-conforming",
    void: false,
    rawText: false,
    textMode: "normal",
    categories: [],
    children: [],
  },
  main: {
    tag: "main",
    interface: "HTMLElement",
    conformance: "conforming",
    void: false,
    rawText: false,
    textMode: "normal",
    categories: ["flow", "palpable"],
    children: ["flow"],
  },
  map: {
    tag: "map",
    interface: "HTMLMapElement",
    conformance: "conforming",
    void: false,
    rawText: false,
    textMode: "normal",
    categories: ["flow", "phrasing", "palpable"],
    children: ["transparent", "area"],
  },
  mark: {
    tag: "mark",
    interface: "HTMLElement",
    conformance: "conforming",
    void: false,
    rawText: false,
    textMode: "normal",
    categories: ["flow", "phrasing", "palpable"],
    children: ["phrasing"],
  },
  marquee: {
    tag: "marquee",
    interface: "HTMLMarqueeElement",
    conformance: "non-conforming",
    void: false,
    rawText: false,
    textMode: "normal",
    categories: [],
    children: [],
  },
  menu: {
    tag: "menu",
    interface: "HTMLMenuElement",
    conformance: "conforming",
    void: false,
    rawText: false,
    textMode: "normal",
    categories: ["flow", "palpable"],
    children: ["li", "script-supporting elements"],
  },
  menuitem: {
    tag: "menuitem",
    interface: "HTMLUnknownElement",
    conformance: "non-conforming",
    void: false,
    rawText: false,
    textMode: "normal",
    categories: [],
    children: [],
  },
  meta: {
    tag: "meta",
    interface: "HTMLMetaElement",
    conformance: "conforming",
    void: true,
    rawText: false,
    textMode: "normal",
    categories: ["metadata", "flow", "phrasing"],
    children: ["empty"],
  },
  meter: {
    tag: "meter",
    interface: "HTMLMeterElement",
    conformance: "conforming",
    void: false,
    rawText: false,
    textMode: "normal",
    categories: ["flow", "phrasing", "labelable", "palpable"],
    children: ["phrasing"],
  },
  multicol: {
    tag: "multicol",
    interface: "HTMLUnknownElement",
    conformance: "non-conforming",
    void: false,
    rawText: false,
    textMode: "normal",
    categories: [],
    children: [],
  },
  nav: {
    tag: "nav",
    interface: "HTMLElement",
    conformance: "conforming",
    void: false,
    rawText: false,
    textMode: "normal",
    categories: ["flow", "sectioning", "palpable"],
    children: ["flow"],
  },
  nextid: {
    tag: "nextid",
    interface: "HTMLUnknownElement",
    conformance: "non-conforming",
    void: true,
    rawText: false,
    textMode: "normal",
    categories: [],
    children: [],
  },
  nobr: {
    tag: "nobr",
    interface: "HTMLElement",
    conformance: "non-conforming",
    void: false,
    rawText: false,
    textMode: "normal",
    categories: [],
    children: [],
  },
  noembed: {
    tag: "noembed",
    interface: "HTMLElement",
    conformance: "non-conforming",
    void: false,
    rawText: true,
    textMode: "raw-text",
    categories: [],
    children: [],
  },
  noframes: {
    tag: "noframes",
    interface: "HTMLElement",
    conformance: "non-conforming",
    void: false,
    rawText: true,
    textMode: "raw-text",
    categories: [],
    children: [],
  },
  noscript: {
    tag: "noscript",
    interface: "HTMLElement",
    conformance: "conforming",
    void: false,
    rawText: false,
    textMode: "normal",
    categories: ["metadata", "flow", "phrasing"],
    children: ["varies"],
  },
  object: {
    tag: "object",
    interface: "HTMLObjectElement",
    conformance: "conforming",
    void: false,
    rawText: false,
    textMode: "normal",
    categories: ["flow", "phrasing", "embedded", "interactive", "listed", "form-associated", "palpable"],
    children: ["transparent"],
  },
  ol: {
    tag: "ol",
    interface: "HTMLOListElement",
    conformance: "conforming",
    void: false,
    rawText: false,
    textMode: "normal",
    categories: ["flow", "palpable"],
    children: ["li", "script-supporting elements"],
  },
  optgroup: {
    tag: "optgroup",
    interface: "HTMLOptGroupElement",
    conformance: "conforming",
    void: false,
    rawText: false,
    textMode: "normal",
    categories: [],
    children: ["optgroup element inner content elements", "legend"],
  },
  option: {
    tag: "option",
    interface: "HTMLOptionElement",
    conformance: "conforming",
    void: false,
    rawText: false,
    textMode: "normal",
    categories: [],
    children: ["text", "option element inner content elements"],
  },
  output: {
    tag: "output",
    interface: "HTMLOutputElement",
    conformance: "conforming",
    void: false,
    rawText: false,
    textMode: "normal",
    categories: ["flow", "phrasing", "listed", "labelable", "resettable", "form-associated", "palpable"],
    children: ["phrasing"],
  },
  p: {
    tag: "p",
    interface: "HTMLParagraphElement",
    conformance: "conforming",
    void: false,
    rawText: false,
    textMode: "normal",
    categories: ["flow", "palpable"],
    children: ["phrasing"],
  },
  param: {
    tag: "param",
    interface: "HTMLParamElement",
    conformance: "non-conforming",
    void: true,
    rawText: false,
    textMode: "normal",
    categories: [],
    children: [],
  },
  picture: {
    tag: "picture",
    interface: "HTMLPictureElement",
    conformance: "conforming",
    void: false,
    rawText: false,
    textMode: "normal",
    categories: ["flow", "phrasing", "embedded", "palpable"],
    children: ["source", "one img", "script-supporting elements"],
  },
  plaintext: {
    tag: "plaintext",
    interface: "HTMLElement",
    conformance: "non-conforming",
    void: false,
    rawText: false,
    textMode: "plaintext",
    categories: [],
    children: [],
  },
  pre: {
    tag: "pre",
    interface: "HTMLPreElement",
    conformance: "conforming",
    void: false,
    rawText: false,
    textMode: "normal",
    categories: ["flow", "palpable"],
    children: ["phrasing"],
  },
  progress: {
    tag: "progress",
    interface: "HTMLProgressElement",
    conformance: "conforming",
    void: false,
    rawText: false,
    textMode: "normal",
    categories: ["flow", "phrasing", "labelable", "palpable"],
    children: ["phrasing"],
  },
  q: {
    tag: "q",
    interface: "HTMLQuoteElement",
    conformance: "conforming",
    void: false,
    rawText: false,
    textMode: "normal",
    categories: ["flow", "phrasing", "palpable"],
    children: ["phrasing"],
  },
  rb: {
    tag: "rb",
    interface: "HTMLElement",
    conformance: "non-conforming",
    void: false,
    rawText: false,
    textMode: "normal",
    categories: [],
    children: [],
  },
  rp: {
    tag: "rp",
    interface: "HTMLElement",
    conformance: "conforming",
    void: false,
    rawText: false,
    textMode: "normal",
    categories: [],
    children: ["text"],
  },
  rt: {
    tag: "rt",
    interface: "HTMLElement",
    conformance: "conforming",
    void: false,
    rawText: false,
    textMode: "normal",
    categories: [],
    children: ["phrasing"],
  },
  rtc: {
    tag: "rtc",
    interface: "HTMLElement",
    conformance: "non-conforming",
    void: false,
    rawText: false,
    textMode: "normal",
    categories: [],
    children: [],
  },
  ruby: {
    tag: "ruby",
    interface: "HTMLElement",
    conformance: "conforming",
    void: false,
    rawText: false,
    textMode: "normal",
    categories: ["flow", "phrasing", "palpable"],
    children: ["phrasing", "rt", "rp"],
  },
  s: {
    tag: "s",
    interface: "HTMLElement",
    conformance: "conforming",
    void: false,
    rawText: false,
    textMode: "normal",
    categories: ["flow", "phrasing", "palpable"],
    children: ["phrasing"],
  },
  samp: {
    tag: "samp",
    interface: "HTMLElement",
    conformance: "conforming",
    void: false,
    rawText: false,
    textMode: "normal",
    categories: ["flow", "phrasing", "palpable"],
    children: ["phrasing"],
  },
  script: {
    tag: "script",
    interface: "HTMLScriptElement",
    conformance: "conforming",
    void: false,
    rawText: true,
    textMode: "raw-text",
    categories: ["metadata", "flow", "phrasing", "script-supporting"],
    children: ["script", "data", "or script documentation"],
  },
  search: {
    tag: "search",
    interface: "HTMLElement",
    conformance: "conforming",
    void: false,
    rawText: false,
    textMode: "normal",
    categories: ["flow", "palpable"],
    children: ["flow"],
  },
  section: {
    tag: "section",
    interface: "HTMLElement",
    conformance: "conforming",
    void: false,
    rawText: false,
    textMode: "normal",
    categories: ["flow", "sectioning", "palpable"],
    children: ["flow"],
  },
  select: {
    tag: "select",
    interface: "HTMLSelectElement",
    conformance: "conforming",
    void: false,
    rawText: false,
    textMode: "normal",
    categories: [
      "flow",
      "phrasing",
      "interactive",
      "listed",
      "labelable",
      "submittable",
      "resettable",
      "form-associated",
      "palpable",
    ],
    children: ["select element inner content elements", "button"],
  },
  selectedcontent: {
    tag: "selectedcontent",
    interface: "HTMLSelectedContentElement",
    conformance: "conforming",
    void: false,
    rawText: false,
    textMode: "normal",
    categories: [],
    children: ["empty"],
  },
  slot: {
    tag: "slot",
    interface: "HTMLSlotElement",
    conformance: "conforming",
    void: false,
    rawText: false,
    textMode: "normal",
    categories: ["flow", "phrasing"],
    children: ["transparent"],
  },
  small: {
    tag: "small",
    interface: "HTMLElement",
    conformance: "conforming",
    void: false,
    rawText: false,
    textMode: "normal",
    categories: ["flow", "phrasing", "palpable"],
    children: ["phrasing"],
  },
  source: {
    tag: "source",
    interface: "HTMLSourceElement",
    conformance: "conforming",
    void: true,
    rawText: false,
    textMode: "normal",
    categories: [],
    children: ["empty"],
  },
  spacer: {
    tag: "spacer",
    interface: "HTMLUnknownElement",
    conformance: "non-conforming",
    void: true,
    rawText: false,
    textMode: "normal",
    categories: [],
    children: [],
  },
  span: {
    tag: "span",
    interface: "HTMLSpanElement",
    conformance: "conforming",
    void: false,
    rawText: false,
    textMode: "normal",
    categories: ["flow", "phrasing", "palpable"],
    children: ["phrasing"],
  },
  strike: {
    tag: "strike",
    interface: "HTMLElement",
    conformance: "non-conforming",
    void: false,
    rawText: false,
    textMode: "normal",
    categories: [],
    children: [],
  },
  strong: {
    tag: "strong",
    interface: "HTMLElement",
    conformance: "conforming",
    void: false,
    rawText: false,
    textMode: "normal",
    categories: ["flow", "phrasing", "palpable"],
    children: ["phrasing"],
  },
  style: {
    tag: "style",
    interface: "HTMLStyleElement",
    conformance: "conforming",
    void: false,
    rawText: true,
    textMode: "raw-text",
    categories: ["metadata"],
    children: ["text"],
  },
  sub: {
    tag: "sub",
    interface: "HTMLElement",
    conformance: "conforming",
    void: false,
    rawText: false,
    textMode: "normal",
    categories: ["flow", "phrasing", "palpable"],
    children: ["phrasing"],
  },
  summary: {
    tag: "summary",
    interface: "HTMLElement",
    conformance: "conforming",
    void: false,
    rawText: false,
    textMode: "normal",
    categories: [],
    children: ["phrasing", "heading content"],
  },
  sup: {
    tag: "sup",
    interface: "HTMLElement",
    conformance: "conforming",
    void: false,
    rawText: false,
    textMode: "normal",
    categories: ["flow", "phrasing", "palpable"],
    children: ["phrasing"],
  },
  table: {
    tag: "table",
    interface: "HTMLTableElement",
    conformance: "conforming",
    void: false,
    rawText: false,
    textMode: "normal",
    categories: ["flow", "palpable"],
    children: ["caption", "colgroup", "thead", "tbody", "tfoot", "tr", "script-supporting elements"],
    childSequencePattern: "^(?:caption,)?(?:colgroup,)*(?:thead,)?(?:(?:tbody,)*|(?:tr,)+)(?:tfoot,)?$",
  },
  tbody: {
    tag: "tbody",
    interface: "HTMLTableSectionElement",
    conformance: "conforming",
    void: false,
    rawText: false,
    textMode: "normal",
    categories: [],
    children: ["tr", "script-supporting elements"],
  },
  td: {
    tag: "td",
    interface: "HTMLTableCellElement",
    conformance: "conforming",
    void: false,
    rawText: false,
    textMode: "normal",
    categories: [],
    children: ["flow"],
  },
  template: {
    tag: "template",
    interface: "HTMLTemplateElement",
    conformance: "conforming",
    void: false,
    rawText: false,
    textMode: "normal",
    categories: ["metadata", "flow", "phrasing", "script-supporting"],
    children: ["empty"],
  },
  textarea: {
    tag: "textarea",
    interface: "HTMLTextAreaElement",
    conformance: "conforming",
    void: false,
    rawText: false,
    textMode: "rcdata",
    categories: [
      "flow",
      "phrasing",
      "interactive",
      "listed",
      "labelable",
      "submittable",
      "resettable",
      "form-associated",
      "palpable",
    ],
    children: ["text"],
  },
  tfoot: {
    tag: "tfoot",
    interface: "HTMLTableSectionElement",
    conformance: "conforming",
    void: false,
    rawText: false,
    textMode: "normal",
    categories: [],
    children: ["tr", "script-supporting elements"],
  },
  th: {
    tag: "th",
    interface: "HTMLTableCellElement",
    conformance: "conforming",
    void: false,
    rawText: false,
    textMode: "normal",
    categories: ["interactive"],
    children: ["flow"],
  },
  thead: {
    tag: "thead",
    interface: "HTMLTableSectionElement",
    conformance: "conforming",
    void: false,
    rawText: false,
    textMode: "normal",
    categories: [],
    children: ["tr", "script-supporting elements"],
  },
  time: {
    tag: "time",
    interface: "HTMLTimeElement",
    conformance: "conforming",
    void: false,
    rawText: false,
    textMode: "normal",
    categories: ["flow", "phrasing", "palpable"],
    children: ["phrasing"],
  },
  title: {
    tag: "title",
    interface: "HTMLTitleElement",
    conformance: "conforming",
    void: false,
    rawText: false,
    textMode: "rcdata",
    categories: ["metadata"],
    children: ["text"],
  },
  tr: {
    tag: "tr",
    interface: "HTMLTableRowElement",
    conformance: "conforming",
    void: false,
    rawText: false,
    textMode: "normal",
    categories: [],
    children: ["th", "td", "script-supporting elements"],
  },
  track: {
    tag: "track",
    interface: "HTMLTrackElement",
    conformance: "conforming",
    void: true,
    rawText: false,
    textMode: "normal",
    categories: [],
    children: ["empty"],
  },
  tt: {
    tag: "tt",
    interface: "HTMLElement",
    conformance: "non-conforming",
    void: false,
    rawText: false,
    textMode: "normal",
    categories: [],
    children: [],
  },
  u: {
    tag: "u",
    interface: "HTMLElement",
    conformance: "conforming",
    void: false,
    rawText: false,
    textMode: "normal",
    categories: ["flow", "phrasing", "palpable"],
    children: ["phrasing"],
  },
  ul: {
    tag: "ul",
    interface: "HTMLUListElement",
    conformance: "conforming",
    void: false,
    rawText: false,
    textMode: "normal",
    categories: ["flow", "palpable"],
    children: ["li", "script-supporting elements"],
  },
  var: {
    tag: "var",
    interface: "HTMLElement",
    conformance: "conforming",
    void: false,
    rawText: false,
    textMode: "normal",
    categories: ["flow", "phrasing", "palpable"],
    children: ["phrasing"],
  },
  video: {
    tag: "video",
    interface: "HTMLVideoElement",
    conformance: "conforming",
    void: false,
    rawText: false,
    textMode: "normal",
    categories: ["flow", "phrasing", "embedded", "interactive", "palpable"],
    children: ["source", "track", "transparent"],
  },
  wbr: {
    tag: "wbr",
    interface: "HTMLElement",
    conformance: "conforming",
    void: true,
    rawText: false,
    textMode: "normal",
    categories: ["flow", "phrasing"],
    children: ["empty"],
  },
  xmp: {
    tag: "xmp",
    interface: "HTMLPreElement",
    conformance: "non-conforming",
    void: false,
    rawText: true,
    textMode: "raw-text",
    categories: [],
    children: [],
  },
};
