/**
 * GENERATED FILE — do not edit by hand. Run `bun run generate`.
 *
 * Per-element metadata for the HTML AST: DOM interface, conformance tier, void /
 * raw-text classification, and (advisory) content categories.
 *
 * @packageDocumentation \@beep/html/Html.meta
 * @since 0.0.0
 */
import { $HtmlId } from "@beep/identity";
import { LiteralKit } from "@beep/schema";
import * as A from "effect/Array";
import * as R from "effect/Record";
import * as S from "effect/Schema";

// WHATWG's tokenizer-lowercased attribute and event names are normative.
// cspell:words numoctaves onpagereveal onpageswap pointsatx pointsaty pointsatz refx refy
// cspell:words targetx targety xchannelselector ychannelselector

const $I = $HtmlId.create("Html.meta");

/**
 * Exact generated HTML element-tag domain.
 *
 * @example
 * ```ts
 * import { HtmlTag } from "@beep/html/Html.meta"
 *
 * console.log(HtmlTag.is.div("div")) // true
 * ```
 *
 * @category models
 * @since 0.0.0
 */
export const HtmlTag = LiteralKit([
  "a",
  "abbr",
  "acronym",
  "address",
  "applet",
  "area",
  "article",
  "aside",
  "audio",
  "b",
  "base",
  "basefont",
  "bdi",
  "bdo",
  "bgsound",
  "big",
  "blink",
  "blockquote",
  "body",
  "br",
  "button",
  "canvas",
  "caption",
  "center",
  "cite",
  "code",
  "col",
  "colgroup",
  "data",
  "datalist",
  "dd",
  "del",
  "details",
  "dfn",
  "dialog",
  "dir",
  "div",
  "dl",
  "dt",
  "em",
  "embed",
  "fieldset",
  "figcaption",
  "figure",
  "font",
  "footer",
  "form",
  "frame",
  "frameset",
  "h1",
  "h2",
  "h3",
  "h4",
  "h5",
  "h6",
  "head",
  "header",
  "hgroup",
  "hr",
  "html",
  "i",
  "iframe",
  "img",
  "input",
  "ins",
  "isindex",
  "kbd",
  "keygen",
  "label",
  "legend",
  "li",
  "link",
  "listing",
  "main",
  "map",
  "mark",
  "marquee",
  "menu",
  "menuitem",
  "meta",
  "meter",
  "multicol",
  "nav",
  "nextid",
  "nobr",
  "noembed",
  "noframes",
  "noscript",
  "object",
  "ol",
  "optgroup",
  "option",
  "output",
  "p",
  "param",
  "picture",
  "plaintext",
  "pre",
  "progress",
  "q",
  "rb",
  "rp",
  "rt",
  "rtc",
  "ruby",
  "s",
  "samp",
  "script",
  "search",
  "section",
  "select",
  "selectedcontent",
  "slot",
  "small",
  "source",
  "spacer",
  "span",
  "strike",
  "strong",
  "style",
  "sub",
  "summary",
  "sup",
  "table",
  "tbody",
  "td",
  "template",
  "textarea",
  "tfoot",
  "th",
  "thead",
  "time",
  "title",
  "tr",
  "track",
  "tt",
  "u",
  "ul",
  "var",
  "video",
  "wbr",
  "xmp",
]).pipe($I.annoteSchema("HtmlTag", { description: "Exact generated HTML element-tag domain." }));

/**
 * Decoded HTML element tag.
 *
 * @example
 * ```ts
 * import type { HtmlTag } from "@beep/html/Html.meta"
 *
 * const tag: HtmlTag = "div"
 * console.log(tag)
 * ```
 *
 * @category models
 * @since 0.0.0
 */
export type HtmlTag = typeof HtmlTag.Type;

/**
 * Advisory content-category values emitted by the WHATWG element index.
 *
 * @example
 * ```ts
 * import { HtmlCategory } from "@beep/html/Html.meta"
 *
 * console.log(HtmlCategory.is.flow("flow")) // true
 * ```
 *
 * @category models
 * @since 0.0.0
 */
export const HtmlCategory = LiteralKit([
  "embedded",
  "flow",
  "form-associated",
  "heading",
  "interactive",
  "labelable",
  "listed",
  "metadata",
  "palpable",
  "phrasing",
  "resettable",
  "script-supporting",
  "sectioning",
  "submittable",
]).pipe($I.annoteSchema("HtmlCategory", { description: "Advisory WHATWG content-category value." }));

/**
 * Decoded advisory content category.
 *
 * @example
 * ```ts
 * import type { HtmlCategory } from "@beep/html/Html.meta"
 *
 * const category: HtmlCategory = "flow"
 * console.log(category)
 * ```
 *
 * @category models
 * @since 0.0.0
 */
export type HtmlCategory = typeof HtmlCategory.Type;

/**
 * Content-model tokens emitted by the pinned WHATWG element index.
 *
 * @example
 * ```ts
 * import { HtmlContentToken } from "@beep/html/Html.meta"
 *
 * console.log(HtmlContentToken.is.flow("flow")) // true
 * ```
 *
 * @category models
 * @since 0.0.0
 */
export const HtmlContentToken = LiteralKit([
  "area",
  "body",
  "button",
  "caption",
  "col",
  "colgroup",
  "data",
  "dd",
  "div",
  "dt",
  "empty",
  "figcaption",
  "flow",
  "flow select element inner content elements",
  "h1",
  "h2",
  "h3",
  "h4",
  "h5",
  "h6",
  "head",
  "heading content",
  "legend",
  "li",
  "metadata content",
  "one img",
  "optgroup element inner content elements",
  "option",
  "option element inner content elements",
  "or script documentation",
  "p",
  "phrasing",
  "rp",
  "rt",
  "script",
  "script-supporting elements",
  "select element inner content elements",
  "source",
  "summary",
  "tbody",
  "td",
  "template",
  "text",
  "tfoot",
  "th",
  "thead",
  "tr",
  "track",
  "transparent",
  "varies",
]).pipe($I.annoteSchema("HtmlContentToken", { description: "Pinned HTML content-model token." }));

/**
 * Decoded HTML content-model token.
 *
 * @example
 * ```ts
 * import type { HtmlContentToken } from "@beep/html/Html.meta"
 *
 * const token: HtmlContentToken = "flow"
 * console.log(token)
 * ```
 *
 * @category models
 * @since 0.0.0
 */
export type HtmlContentToken = typeof HtmlContentToken.Type;

/**
 * Reviewed grammar profiles for HTML elements whose child rules include
 * ordering, cardinality, alternatives, or attribute-dependent branches.
 *
 * @example
 * ```ts
 * import { HtmlChildGrammar } from "@beep/html/Html.meta"
 *
 * console.log(HtmlChildGrammar.is.table("table")) // true
 * ```
 *
 * @category models
 * @since 0.0.0
 */
export const HtmlChildGrammar = LiteralKit([
  "colgroup",
  "datalist",
  "description-list",
  "details",
  "document-element",
  "fieldset",
  "figure",
  "head",
  "hgroup",
  "media",
  "optgroup",
  "phrasing-or-heading",
  "picture",
  "ruby",
  "select",
  "table",
]).pipe($I.annoteSchema("HtmlChildGrammar", { description: "Reviewed HTML special-child grammar profile." }));

/**
 * Decoded HTML special-child grammar profile.
 *
 * @example
 * ```ts
 * import type { HtmlChildGrammar } from "@beep/html/Html.meta"
 *
 * const grammar: HtmlChildGrammar = "table"
 * console.log(grammar)
 * ```
 *
 * @category models
 * @since 0.0.0
 */
export type HtmlChildGrammar = typeof HtmlChildGrammar.Type;

/**
 * One attribute-dependent content-category membership rule.
 *
 * @example
 * ```ts
 * import { HtmlConditionalCategoryRule } from "@beep/html/Html.meta"
 *
 * const rule = HtmlConditionalCategoryRule.make({
 *   attribute: "href",
 *   category: "interactive",
 *   condition: "present"
 * })
 * console.log(rule.category) // "interactive"
 * ```
 *
 * @category models
 * @since 0.0.0
 */
export class HtmlConditionalCategoryRule extends S.Class<HtmlConditionalCategoryRule>($I`HtmlConditionalCategoryRule`)(
  {
    attribute: S.String,
    category: HtmlCategory,
    condition: S.Literals(["present", "not-equals"]),
    value: S.String.pipe(S.optionalKey),
  },
  $I.annote("HtmlConditionalCategoryRule", {
    description: "Attribute predicate controlling one element content-category membership.",
  })
) {}

/**
 * WHATWG SVG element-name adjustments keyed by tokenizer-lowercased input.
 *
 * @example
 * ```ts
 * import { SVG_ELEMENT_NAME_ADJUSTMENTS } from "@beep/html/Html.meta"
 *
 * console.log(SVG_ELEMENT_NAME_ADJUSTMENTS.lineargradient) // "linearGradient"
 * ```
 *
 * @category constants
 * @since 0.0.0
 */
export const SVG_ELEMENT_NAME_ADJUSTMENTS: Readonly<Record<string, string>> = Object.freeze({
  altglyph: "altGlyph",
  altglyphdef: "altGlyphDef",
  altglyphitem: "altGlyphItem",
  animatecolor: "animateColor",
  animatemotion: "animateMotion",
  animatetransform: "animateTransform",
  clippath: "clipPath",
  feblend: "feBlend",
  fecolormatrix: "feColorMatrix",
  fecomponenttransfer: "feComponentTransfer",
  fecomposite: "feComposite",
  feconvolvematrix: "feConvolveMatrix",
  fediffuselighting: "feDiffuseLighting",
  fedisplacementmap: "feDisplacementMap",
  fedistantlight: "feDistantLight",
  feflood: "feFlood",
  fefunca: "feFuncA",
  fefuncb: "feFuncB",
  fefuncg: "feFuncG",
  fefuncr: "feFuncR",
  fegaussianblur: "feGaussianBlur",
  feimage: "feImage",
  femerge: "feMerge",
  femergenode: "feMergeNode",
  femorphology: "feMorphology",
  feoffset: "feOffset",
  fepointlight: "fePointLight",
  fespecularlighting: "feSpecularLighting",
  fespotlight: "feSpotLight",
  fetile: "feTile",
  feturbulence: "feTurbulence",
  foreignobject: "foreignObject",
  glyphref: "glyphRef",
  lineargradient: "linearGradient",
  radialgradient: "radialGradient",
  textpath: "textPath",
});

/**
 * WHATWG SVG attribute-name adjustments keyed by tokenizer-lowercased input.
 *
 * @example
 * ```ts
 * import { SVG_ATTRIBUTE_NAME_ADJUSTMENTS } from "@beep/html/Html.meta"
 *
 * console.log(SVG_ATTRIBUTE_NAME_ADJUSTMENTS.viewbox) // "viewBox"
 * ```
 *
 * @category constants
 * @since 0.0.0
 */
export const SVG_ATTRIBUTE_NAME_ADJUSTMENTS: Readonly<Record<string, string>> = Object.freeze({
  attributename: "attributeName",
  attributetype: "attributeType",
  basefrequency: "baseFrequency",
  baseprofile: "baseProfile",
  calcmode: "calcMode",
  clippathunits: "clipPathUnits",
  diffuseconstant: "diffuseConstant",
  edgemode: "edgeMode",
  filterunits: "filterUnits",
  glyphref: "glyphRef",
  gradienttransform: "gradientTransform",
  gradientunits: "gradientUnits",
  kernelmatrix: "kernelMatrix",
  kernelunitlength: "kernelUnitLength",
  keypoints: "keyPoints",
  keysplines: "keySplines",
  keytimes: "keyTimes",
  lengthadjust: "lengthAdjust",
  limitingconeangle: "limitingConeAngle",
  markerheight: "markerHeight",
  markerunits: "markerUnits",
  markerwidth: "markerWidth",
  maskcontentunits: "maskContentUnits",
  maskunits: "maskUnits",
  numoctaves: "numOctaves",
  pathlength: "pathLength",
  patterncontentunits: "patternContentUnits",
  patterntransform: "patternTransform",
  patternunits: "patternUnits",
  pointsatx: "pointsAtX",
  pointsaty: "pointsAtY",
  pointsatz: "pointsAtZ",
  preservealpha: "preserveAlpha",
  preserveaspectratio: "preserveAspectRatio",
  primitiveunits: "primitiveUnits",
  refx: "refX",
  refy: "refY",
  repeatcount: "repeatCount",
  repeatdur: "repeatDur",
  requiredextensions: "requiredExtensions",
  requiredfeatures: "requiredFeatures",
  specularconstant: "specularConstant",
  specularexponent: "specularExponent",
  spreadmethod: "spreadMethod",
  startoffset: "startOffset",
  stddeviation: "stdDeviation",
  stitchtiles: "stitchTiles",
  surfacescale: "surfaceScale",
  systemlanguage: "systemLanguage",
  tablevalues: "tableValues",
  targetx: "targetX",
  targety: "targetY",
  textlength: "textLength",
  viewbox: "viewBox",
  viewtarget: "viewTarget",
  xchannelselector: "xChannelSelector",
  ychannelselector: "yChannelSelector",
  zoomandpan: "zoomAndPan",
});

/**
 * WHATWG MathML attribute-name adjustments keyed by tokenizer-lowercased input.
 *
 * @example
 * ```ts
 * import { MATHML_ATTRIBUTE_NAME_ADJUSTMENTS } from "@beep/html/Html.meta"
 *
 * console.log(MATHML_ATTRIBUTE_NAME_ADJUSTMENTS.definitionurl) // "definitionURL"
 * ```
 *
 * @category constants
 * @since 0.0.0
 */
export const MATHML_ATTRIBUTE_NAME_ADJUSTMENTS: Readonly<Record<string, string>> = Object.freeze({
  definitionurl: "definitionURL",
});

/**
 * Foreign qualified attributes whose HTML parser adjustment assigns an XML,
 * XMLNS, or XLink namespace while preserving this serialized name.
 *
 * @example
 * ```ts
 * import { XML_FOREIGN_ATTRIBUTE_NAMES } from "@beep/html/Html.meta"
 *
 * console.log(XML_FOREIGN_ATTRIBUTE_NAMES.includes("xlink:href")) // true
 * ```
 *
 * @category constants
 * @since 0.0.0
 */
export const XML_FOREIGN_ATTRIBUTE_NAMES: ReadonlyArray<string> = Object.freeze([
  "xlink:actuate",
  "xlink:arcrole",
  "xlink:href",
  "xlink:role",
  "xlink:show",
  "xlink:title",
  "xlink:type",
  "xml:lang",
  "xml:space",
  "xmlns",
  "xmlns:xlink",
]);

/**
 * Shared current attributes permitted on every generated HTML element.
 *
 * Per-element metadata reuses this frozen inventory and appends only its
 * element-specific current attributes.
 *
 * @example
 * ```ts
 * import { HTML_GLOBAL_ATTRIBUTE_NAMES } from "@beep/html/Html.meta"
 *
 * console.log(HTML_GLOBAL_ATTRIBUTE_NAMES.includes("inert")) // true
 * ```
 *
 * @category constants
 * @since 0.0.0
 */
export const HTML_GLOBAL_ATTRIBUTE_NAMES: ReadonlyArray<string> = Object.freeze([
  "accesskey",
  "aria-activedescendant",
  "aria-atomic",
  "aria-autocomplete",
  "aria-braillelabel",
  "aria-brailleroledescription",
  "aria-busy",
  "aria-checked",
  "aria-colcount",
  "aria-colindex",
  "aria-colindextext",
  "aria-colspan",
  "aria-controls",
  "aria-current",
  "aria-describedby",
  "aria-description",
  "aria-details",
  "aria-disabled",
  "aria-dropeffect",
  "aria-errormessage",
  "aria-expanded",
  "aria-flowto",
  "aria-grabbed",
  "aria-haspopup",
  "aria-hidden",
  "aria-invalid",
  "aria-keyshortcuts",
  "aria-label",
  "aria-labelledby",
  "aria-level",
  "aria-live",
  "aria-modal",
  "aria-multiline",
  "aria-multiselectable",
  "aria-orientation",
  "aria-owns",
  "aria-placeholder",
  "aria-posinset",
  "aria-pressed",
  "aria-readonly",
  "aria-relevant",
  "aria-required",
  "aria-roledescription",
  "aria-rowcount",
  "aria-rowindex",
  "aria-rowindextext",
  "aria-rowspan",
  "aria-selected",
  "aria-setsize",
  "aria-sort",
  "aria-valuemax",
  "aria-valuemin",
  "aria-valuenow",
  "aria-valuetext",
  "autocapitalize",
  "autocorrect",
  "autofocus",
  "class",
  "contenteditable",
  "dataset",
  "dir",
  "draggable",
  "enterkeyhint",
  "exportparts",
  "headingoffset",
  "headingreset",
  "hidden",
  "id",
  "inert",
  "inputmode",
  "is",
  "itemid",
  "itemprop",
  "itemref",
  "itemscope",
  "itemtype",
  "lang",
  "nonce",
  "onabort",
  "onauxclick",
  "onbeforeinput",
  "onbeforematch",
  "onbeforetoggle",
  "onblur",
  "oncancel",
  "oncanplay",
  "oncanplaythrough",
  "onchange",
  "onclick",
  "onclose",
  "oncommand",
  "oncontextlost",
  "oncontextmenu",
  "oncontextrestored",
  "oncopy",
  "oncuechange",
  "oncut",
  "ondblclick",
  "ondrag",
  "ondragend",
  "ondragenter",
  "ondragleave",
  "ondragover",
  "ondragstart",
  "ondrop",
  "ondurationchange",
  "onemptied",
  "onended",
  "onerror",
  "onfocus",
  "onformdata",
  "oninput",
  "oninvalid",
  "onkeydown",
  "onkeypress",
  "onkeyup",
  "onload",
  "onloadeddata",
  "onloadedmetadata",
  "onloadstart",
  "onmousedown",
  "onmouseenter",
  "onmouseleave",
  "onmousemove",
  "onmouseout",
  "onmouseover",
  "onmouseup",
  "onpaste",
  "onpause",
  "onplay",
  "onplaying",
  "onprogress",
  "onratechange",
  "onreset",
  "onresize",
  "onscroll",
  "onscrollend",
  "onsecuritypolicyviolation",
  "onseeked",
  "onseeking",
  "onselect",
  "onslotchange",
  "onstalled",
  "onsubmit",
  "onsuspend",
  "ontimeupdate",
  "ontoggle",
  "onvolumechange",
  "onwaiting",
  "onwheel",
  "part",
  "popover",
  "role",
  "slot",
  "spellcheck",
  "style",
  "tabindex",
  "title",
  "translate",
  "writingsuggestions",
]);

/**
 * Reviewed expansions for context-sensitive content-model tokens emitted by
 * the non-normative WHATWG element index.
 *
 * @example
 * ```ts
 * import { HTML_CONTENT_TOKEN_EXPANSIONS } from "@beep/html/Html.meta"
 *
 * console.log(HTML_CONTENT_TOKEN_EXPANSIONS["option element inner content elements"]) // ["phrasing"]
 * ```
 *
 * @category constants
 * @since 0.0.0
 */
export const HTML_CONTENT_TOKEN_EXPANSIONS: Readonly<Record<string, ReadonlyArray<string>>> = Object.freeze({
  "flow select element inner content elements": Object.freeze([
    "div",
    "hr",
    "optgroup",
    "option",
    "script-supporting elements",
  ]),
  "optgroup element inner content elements": Object.freeze(["div", "optgroup", "option", "script-supporting elements"]),
  "option element inner content elements": Object.freeze(["phrasing"]),
  "select element inner content elements": Object.freeze([
    "div",
    "hr",
    "optgroup",
    "option",
    "script-supporting elements",
  ]),
});

/**
 * Text parsing and serialization mode of an HTML element.
 *
 * @example
 * ```ts
 * import { HtmlTextMode } from "@beep/html/Html.meta"
 *
 * console.log(HtmlTextMode.is.rcdata("rcdata")) // true
 * ```
 *
 * @category models
 * @since 0.0.0
 */
export const HtmlTextMode = LiteralKit(["normal", "raw-text", "rcdata", "plaintext"]).pipe(
  $I.annoteSchema("HtmlTextMode", { description: "HTML text parsing and serialization mode." })
);

/**
 * Decoded HTML text mode.
 *
 * @example
 * ```ts
 * import type { HtmlTextMode } from "@beep/html/Html.meta"
 *
 * const mode: HtmlTextMode = "normal"
 * console.log(mode)
 * ```
 *
 * @category models
 * @since 0.0.0
 */
export type HtmlTextMode = typeof HtmlTextMode.Type;

/**
 * Authoritative generated domain of HTML boolean attribute names.
 *
 * @example
 * ```ts
 * import { HtmlBooleanAttributeName } from "@beep/html/Html.meta"
 *
 * console.log(HtmlBooleanAttributeName.is.disabled("disabled")) // true
 * ```
 *
 * @category models
 * @since 0.0.0
 */
export const HtmlBooleanAttributeName = LiteralKit([
  "allowfullscreen",
  "alpha",
  "async",
  "autofocus",
  "autoplay",
  "checked",
  "compact",
  "controls",
  "declare",
  "default",
  "defer",
  "disabled",
  "formnovalidate",
  "headingreset",
  "inert",
  "ismap",
  "itemscope",
  "loop",
  "multiple",
  "muted",
  "nomodule",
  "noresize",
  "noshade",
  "novalidate",
  "nowrap",
  "open",
  "playsinline",
  "pubdate",
  "readonly",
  "required",
  "reversed",
  "scoped",
  "seamless",
  "selected",
  "shadowrootclonable",
  "shadowrootdelegatesfocus",
  "shadowrootserializable",
  "truespeed",
]).pipe(
  $I.annoteSchema("HtmlBooleanAttributeName", {
    description: "Authoritative HTML boolean attribute-name domain used by generation and serialization.",
  })
);

/**
 * Decoded HTML boolean attribute name.
 *
 * @example
 * ```ts
 * import { HtmlBooleanAttributeName } from "@beep/html/Html.meta"
 * import { Result } from "effect"
 * import * as S from "effect/Schema"
 *
 * const decoded = S.decodeUnknownResult(HtmlBooleanAttributeName)("disabled")
 * if (Result.isSuccess(decoded)) {
 *   const name: HtmlBooleanAttributeName = decoded.success
 *   console.log(name) // "disabled"
 * }
 * ```
 *
 * @category models
 * @since 0.0.0
 */
export type HtmlBooleanAttributeName = typeof HtmlBooleanAttributeName.Type;

/**
 * Schema describing one HTML element kind's metadata.
 *
 * @example
 * ```ts
 * import { HtmlElementMeta } from "@beep/html/Html.meta"
 * import * as S from "effect/Schema"
 *
 * console.log(S.is(HtmlElementMeta)({
 *   tag: "div",
 *   interface: "HTMLDivElement",
 *   conformance: "conforming",
 *   void: false,
 *   rawText: false,
 *   textMode: "normal",
 *   categories: ["flow"],
 *   children: ["flow"],
 *   currentAttributes: [],
 *   obsoleteAttributes: [],
 *   conditionalCategories: []
 * })) // true
 * ```
 *
 * @category models
 * @since 0.0.0
 */
export class HtmlElementMeta extends S.Class<HtmlElementMeta>($I`HtmlElementMeta`)(
  {
    tag: HtmlTag,
    interface: S.NonEmptyString,
    conformance: S.Literals(["conforming", "non-conforming"]),
    void: S.Boolean,
    rawText: S.Boolean,
    textMode: HtmlTextMode,
    categories: S.Array(HtmlCategory),
    children: S.Array(HtmlContentToken),
    currentAttributes: S.Array(S.String),
    obsoleteAttributes: S.Array(S.String),
    conditionalCategories: S.Array(HtmlConditionalCategoryRule),
    childSequencePattern: S.String.pipe(S.optionalKey),
    childGrammar: HtmlChildGrammar.pipe(S.optionalKey),
  },
  $I.annote("HtmlElementMeta", { description: "Metadata describing one HTML element kind." })
) {}

const freezeElementMeta = (value: HtmlElementMeta): HtmlElementMeta =>
  Object.freeze({
    ...value,
    categories: Object.freeze(value.categories),
    children: Object.freeze(value.children),
    conditionalCategories: Object.freeze(A.map(value.conditionalCategories, (rule) => Object.freeze(rule))),
    currentAttributes: Object.freeze(value.currentAttributes),
    obsoleteAttributes: Object.freeze(value.obsoleteAttributes),
  });

const elementMetaSource: Readonly<Record<HtmlTag, HtmlElementMeta>> = {
  a: {
    tag: "a",
    interface: "HTMLAnchorElement",
    conformance: "conforming",
    void: false,
    rawText: false,
    textMode: "normal",
    categories: ["flow", "phrasing", "interactive", "palpable"],
    children: ["transparent"],
    currentAttributes: [
      ...HTML_GLOBAL_ATTRIBUTE_NAMES,
      ...["download", "href", "hreflang", "ping", "referrerpolicy", "rel", "target", "type"],
    ],
    obsoleteAttributes: ["charset", "coords", "methods", "name", "rev", "shape", "urn"],
    conditionalCategories: [{ attribute: "href", category: "interactive", condition: "present" }],
  },
  abbr: {
    tag: "abbr",
    interface: "HTMLElement",
    conformance: "conforming",
    void: false,
    rawText: false,
    textMode: "normal",
    categories: ["flow", "phrasing", "palpable"],
    children: ["phrasing"],
    currentAttributes: HTML_GLOBAL_ATTRIBUTE_NAMES,
    obsoleteAttributes: [],
    conditionalCategories: [],
  },
  acronym: {
    tag: "acronym",
    interface: "HTMLElement",
    conformance: "non-conforming",
    void: false,
    rawText: false,
    textMode: "normal",
    categories: [],
    children: [],
    currentAttributes: HTML_GLOBAL_ATTRIBUTE_NAMES,
    obsoleteAttributes: [],
    conditionalCategories: [],
  },
  address: {
    tag: "address",
    interface: "HTMLElement",
    conformance: "conforming",
    void: false,
    rawText: false,
    textMode: "normal",
    categories: ["flow", "palpable"],
    children: ["flow"],
    currentAttributes: HTML_GLOBAL_ATTRIBUTE_NAMES,
    obsoleteAttributes: [],
    conditionalCategories: [],
  },
  applet: {
    tag: "applet",
    interface: "HTMLUnknownElement",
    conformance: "non-conforming",
    void: false,
    rawText: false,
    textMode: "normal",
    categories: [],
    children: [],
    currentAttributes: HTML_GLOBAL_ATTRIBUTE_NAMES,
    obsoleteAttributes: [],
    conditionalCategories: [],
  },
  area: {
    tag: "area",
    interface: "HTMLAreaElement",
    conformance: "conforming",
    void: true,
    rawText: false,
    textMode: "normal",
    categories: ["flow", "phrasing"],
    children: ["empty"],
    currentAttributes: [
      ...HTML_GLOBAL_ATTRIBUTE_NAMES,
      ...["alt", "coords", "download", "href", "ping", "referrerpolicy", "rel", "shape", "target"],
    ],
    obsoleteAttributes: ["hreflang", "nohref", "type"],
    conditionalCategories: [],
  },
  article: {
    tag: "article",
    interface: "HTMLElement",
    conformance: "conforming",
    void: false,
    rawText: false,
    textMode: "normal",
    categories: ["flow", "sectioning", "palpable"],
    children: ["flow"],
    currentAttributes: HTML_GLOBAL_ATTRIBUTE_NAMES,
    obsoleteAttributes: [],
    conditionalCategories: [],
  },
  aside: {
    tag: "aside",
    interface: "HTMLElement",
    conformance: "conforming",
    void: false,
    rawText: false,
    textMode: "normal",
    categories: ["flow", "sectioning", "palpable"],
    children: ["flow"],
    currentAttributes: HTML_GLOBAL_ATTRIBUTE_NAMES,
    obsoleteAttributes: [],
    conditionalCategories: [],
  },
  audio: {
    tag: "audio",
    interface: "HTMLAudioElement",
    conformance: "conforming",
    void: false,
    rawText: false,
    textMode: "normal",
    categories: ["flow", "phrasing", "embedded", "interactive", "palpable"],
    children: ["source", "track", "transparent"],
    currentAttributes: [
      ...HTML_GLOBAL_ATTRIBUTE_NAMES,
      ...["autoplay", "controls", "crossorigin", "loading", "loop", "muted", "preload", "src"],
    ],
    obsoleteAttributes: [],
    conditionalCategories: [{ attribute: "controls", category: "interactive", condition: "present" }],
    childGrammar: "media",
  },
  b: {
    tag: "b",
    interface: "HTMLElement",
    conformance: "conforming",
    void: false,
    rawText: false,
    textMode: "normal",
    categories: ["flow", "phrasing", "palpable"],
    children: ["phrasing"],
    currentAttributes: HTML_GLOBAL_ATTRIBUTE_NAMES,
    obsoleteAttributes: [],
    conditionalCategories: [],
  },
  base: {
    tag: "base",
    interface: "HTMLBaseElement",
    conformance: "conforming",
    void: true,
    rawText: false,
    textMode: "normal",
    categories: ["metadata"],
    children: ["empty"],
    currentAttributes: [...HTML_GLOBAL_ATTRIBUTE_NAMES, ...["href", "target"]],
    obsoleteAttributes: [],
    conditionalCategories: [],
  },
  basefont: {
    tag: "basefont",
    interface: "HTMLElement",
    conformance: "non-conforming",
    void: true,
    rawText: false,
    textMode: "normal",
    categories: [],
    children: [],
    currentAttributes: HTML_GLOBAL_ATTRIBUTE_NAMES,
    obsoleteAttributes: [],
    conditionalCategories: [],
  },
  bdi: {
    tag: "bdi",
    interface: "HTMLElement",
    conformance: "conforming",
    void: false,
    rawText: false,
    textMode: "normal",
    categories: ["flow", "phrasing", "palpable"],
    children: ["phrasing"],
    currentAttributes: HTML_GLOBAL_ATTRIBUTE_NAMES,
    obsoleteAttributes: [],
    conditionalCategories: [],
  },
  bdo: {
    tag: "bdo",
    interface: "HTMLElement",
    conformance: "conforming",
    void: false,
    rawText: false,
    textMode: "normal",
    categories: ["flow", "phrasing", "palpable"],
    children: ["phrasing"],
    currentAttributes: HTML_GLOBAL_ATTRIBUTE_NAMES,
    obsoleteAttributes: [],
    conditionalCategories: [],
  },
  bgsound: {
    tag: "bgsound",
    interface: "HTMLUnknownElement",
    conformance: "non-conforming",
    void: true,
    rawText: false,
    textMode: "normal",
    categories: [],
    children: [],
    currentAttributes: HTML_GLOBAL_ATTRIBUTE_NAMES,
    obsoleteAttributes: [],
    conditionalCategories: [],
  },
  big: {
    tag: "big",
    interface: "HTMLElement",
    conformance: "non-conforming",
    void: false,
    rawText: false,
    textMode: "normal",
    categories: [],
    children: [],
    currentAttributes: HTML_GLOBAL_ATTRIBUTE_NAMES,
    obsoleteAttributes: [],
    conditionalCategories: [],
  },
  blink: {
    tag: "blink",
    interface: "HTMLUnknownElement",
    conformance: "non-conforming",
    void: false,
    rawText: false,
    textMode: "normal",
    categories: [],
    children: [],
    currentAttributes: HTML_GLOBAL_ATTRIBUTE_NAMES,
    obsoleteAttributes: [],
    conditionalCategories: [],
  },
  blockquote: {
    tag: "blockquote",
    interface: "HTMLQuoteElement",
    conformance: "conforming",
    void: false,
    rawText: false,
    textMode: "normal",
    categories: ["flow", "palpable"],
    children: ["flow"],
    currentAttributes: [...HTML_GLOBAL_ATTRIBUTE_NAMES, ...["cite"]],
    obsoleteAttributes: [],
    conditionalCategories: [],
  },
  body: {
    tag: "body",
    interface: "HTMLBodyElement",
    conformance: "conforming",
    void: false,
    rawText: false,
    textMode: "normal",
    categories: [],
    children: ["flow"],
    currentAttributes: [
      ...HTML_GLOBAL_ATTRIBUTE_NAMES,
      ...[
        "onafterprint",
        "onbeforeprint",
        "onbeforeunload",
        "onhashchange",
        "onlanguagechange",
        "onmessage",
        "onmessageerror",
        "onoffline",
        "ononline",
        "onpagehide",
        "onpagereveal",
        "onpageshow",
        "onpageswap",
        "onpopstate",
        "onrejectionhandled",
        "onstorage",
        "onunhandledrejection",
        "onunload",
      ],
    ],
    obsoleteAttributes: [
      "alink",
      "bgcolor",
      "bottommargin",
      "leftmargin",
      "link",
      "marginheight",
      "marginwidth",
      "rightmargin",
      "text",
      "topmargin",
      "vlink",
    ],
    conditionalCategories: [],
  },
  br: {
    tag: "br",
    interface: "HTMLBRElement",
    conformance: "conforming",
    void: true,
    rawText: false,
    textMode: "normal",
    categories: ["flow", "phrasing"],
    children: ["empty"],
    currentAttributes: HTML_GLOBAL_ATTRIBUTE_NAMES,
    obsoleteAttributes: ["clear"],
    conditionalCategories: [],
  },
  button: {
    tag: "button",
    interface: "HTMLButtonElement",
    conformance: "conforming",
    void: false,
    rawText: false,
    textMode: "normal",
    categories: [
      "flow",
      "phrasing",
      "interactive",
      "listed",
      "labelable",
      "submittable",
      "form-associated",
      "palpable",
    ],
    children: ["phrasing"],
    currentAttributes: [
      ...HTML_GLOBAL_ATTRIBUTE_NAMES,
      ...[
        "command",
        "commandfor",
        "disabled",
        "form",
        "formaction",
        "formenctype",
        "formmethod",
        "formnovalidate",
        "formtarget",
        "name",
        "popovertarget",
        "popovertargetaction",
        "type",
        "value",
      ],
    ],
    obsoleteAttributes: ["action", "autocomplete", "enctype", "method", "novalidate", "target"],
    conditionalCategories: [],
  },
  canvas: {
    tag: "canvas",
    interface: "HTMLCanvasElement",
    conformance: "conforming",
    void: false,
    rawText: false,
    textMode: "normal",
    categories: ["flow", "phrasing", "embedded", "palpable"],
    children: ["transparent"],
    currentAttributes: [...HTML_GLOBAL_ATTRIBUTE_NAMES, ...["height", "width"]],
    obsoleteAttributes: [],
    conditionalCategories: [],
  },
  caption: {
    tag: "caption",
    interface: "HTMLTableCaptionElement",
    conformance: "conforming",
    void: false,
    rawText: false,
    textMode: "normal",
    categories: [],
    children: ["flow"],
    currentAttributes: HTML_GLOBAL_ATTRIBUTE_NAMES,
    obsoleteAttributes: ["align"],
    conditionalCategories: [],
  },
  center: {
    tag: "center",
    interface: "HTMLElement",
    conformance: "non-conforming",
    void: false,
    rawText: false,
    textMode: "normal",
    categories: [],
    children: [],
    currentAttributes: HTML_GLOBAL_ATTRIBUTE_NAMES,
    obsoleteAttributes: [],
    conditionalCategories: [],
  },
  cite: {
    tag: "cite",
    interface: "HTMLElement",
    conformance: "conforming",
    void: false,
    rawText: false,
    textMode: "normal",
    categories: ["flow", "phrasing", "palpable"],
    children: ["phrasing"],
    currentAttributes: HTML_GLOBAL_ATTRIBUTE_NAMES,
    obsoleteAttributes: [],
    conditionalCategories: [],
  },
  code: {
    tag: "code",
    interface: "HTMLElement",
    conformance: "conforming",
    void: false,
    rawText: false,
    textMode: "normal",
    categories: ["flow", "phrasing", "palpable"],
    children: ["phrasing"],
    currentAttributes: HTML_GLOBAL_ATTRIBUTE_NAMES,
    obsoleteAttributes: [],
    conditionalCategories: [],
  },
  col: {
    tag: "col",
    interface: "HTMLTableColElement",
    conformance: "conforming",
    void: true,
    rawText: false,
    textMode: "normal",
    categories: [],
    children: ["empty"],
    currentAttributes: [...HTML_GLOBAL_ATTRIBUTE_NAMES, ...["span"]],
    obsoleteAttributes: ["align", "char", "charoff", "valign", "width"],
    conditionalCategories: [],
  },
  colgroup: {
    tag: "colgroup",
    interface: "HTMLTableColElement",
    conformance: "conforming",
    void: false,
    rawText: false,
    textMode: "normal",
    categories: [],
    children: ["col", "template"],
    currentAttributes: [...HTML_GLOBAL_ATTRIBUTE_NAMES, ...["span"]],
    obsoleteAttributes: [],
    conditionalCategories: [],
    childGrammar: "colgroup",
  },
  data: {
    tag: "data",
    interface: "HTMLDataElement",
    conformance: "conforming",
    void: false,
    rawText: false,
    textMode: "normal",
    categories: ["flow", "phrasing", "palpable"],
    children: ["phrasing"],
    currentAttributes: [...HTML_GLOBAL_ATTRIBUTE_NAMES, ...["value"]],
    obsoleteAttributes: [],
    conditionalCategories: [],
  },
  datalist: {
    tag: "datalist",
    interface: "HTMLDataListElement",
    conformance: "conforming",
    void: false,
    rawText: false,
    textMode: "normal",
    categories: ["flow", "phrasing"],
    children: ["phrasing", "option", "script-supporting elements"],
    currentAttributes: HTML_GLOBAL_ATTRIBUTE_NAMES,
    obsoleteAttributes: [],
    conditionalCategories: [],
    childGrammar: "datalist",
  },
  dd: {
    tag: "dd",
    interface: "HTMLElement",
    conformance: "conforming",
    void: false,
    rawText: false,
    textMode: "normal",
    categories: [],
    children: ["flow"],
    currentAttributes: HTML_GLOBAL_ATTRIBUTE_NAMES,
    obsoleteAttributes: [],
    conditionalCategories: [],
  },
  del: {
    tag: "del",
    interface: "HTMLModElement",
    conformance: "conforming",
    void: false,
    rawText: false,
    textMode: "normal",
    categories: ["flow", "phrasing", "palpable"],
    children: ["transparent"],
    currentAttributes: [...HTML_GLOBAL_ATTRIBUTE_NAMES, ...["cite", "datetime"]],
    obsoleteAttributes: [],
    conditionalCategories: [],
  },
  details: {
    tag: "details",
    interface: "HTMLDetailsElement",
    conformance: "conforming",
    void: false,
    rawText: false,
    textMode: "normal",
    categories: ["flow", "interactive", "palpable"],
    children: ["summary", "flow"],
    currentAttributes: [...HTML_GLOBAL_ATTRIBUTE_NAMES, ...["name", "open"]],
    obsoleteAttributes: [],
    conditionalCategories: [],
    childGrammar: "details",
  },
  dfn: {
    tag: "dfn",
    interface: "HTMLElement",
    conformance: "conforming",
    void: false,
    rawText: false,
    textMode: "normal",
    categories: ["flow", "phrasing", "palpable"],
    children: ["phrasing"],
    currentAttributes: HTML_GLOBAL_ATTRIBUTE_NAMES,
    obsoleteAttributes: [],
    conditionalCategories: [],
  },
  dialog: {
    tag: "dialog",
    interface: "HTMLDialogElement",
    conformance: "conforming",
    void: false,
    rawText: false,
    textMode: "normal",
    categories: ["flow"],
    children: ["flow"],
    currentAttributes: [...HTML_GLOBAL_ATTRIBUTE_NAMES, ...["open"]],
    obsoleteAttributes: ["closedby"],
    conditionalCategories: [],
  },
  dir: {
    tag: "dir",
    interface: "HTMLDirectoryElement",
    conformance: "non-conforming",
    void: false,
    rawText: false,
    textMode: "normal",
    categories: [],
    children: [],
    currentAttributes: HTML_GLOBAL_ATTRIBUTE_NAMES,
    obsoleteAttributes: [],
    conditionalCategories: [],
  },
  div: {
    tag: "div",
    interface: "HTMLDivElement",
    conformance: "conforming",
    void: false,
    rawText: false,
    textMode: "normal",
    categories: ["flow", "palpable"],
    children: [
      "flow select element inner content elements",
      "optgroup element inner content elements",
      "option element inner content elements",
    ],
    currentAttributes: HTML_GLOBAL_ATTRIBUTE_NAMES,
    obsoleteAttributes: ["align"],
    conditionalCategories: [],
  },
  dl: {
    tag: "dl",
    interface: "HTMLDListElement",
    conformance: "conforming",
    void: false,
    rawText: false,
    textMode: "normal",
    categories: ["flow", "palpable"],
    children: ["dt", "dd", "div", "script-supporting elements"],
    currentAttributes: HTML_GLOBAL_ATTRIBUTE_NAMES,
    obsoleteAttributes: ["compact"],
    conditionalCategories: [],
    childGrammar: "description-list",
  },
  dt: {
    tag: "dt",
    interface: "HTMLElement",
    conformance: "conforming",
    void: false,
    rawText: false,
    textMode: "normal",
    categories: [],
    children: ["flow"],
    currentAttributes: HTML_GLOBAL_ATTRIBUTE_NAMES,
    obsoleteAttributes: [],
    conditionalCategories: [],
  },
  em: {
    tag: "em",
    interface: "HTMLElement",
    conformance: "conforming",
    void: false,
    rawText: false,
    textMode: "normal",
    categories: ["flow", "phrasing", "palpable"],
    children: ["phrasing"],
    currentAttributes: HTML_GLOBAL_ATTRIBUTE_NAMES,
    obsoleteAttributes: [],
    conditionalCategories: [],
  },
  embed: {
    tag: "embed",
    interface: "HTMLEmbedElement",
    conformance: "conforming",
    void: true,
    rawText: false,
    textMode: "normal",
    categories: ["flow", "phrasing", "embedded", "interactive", "palpable"],
    children: ["empty"],
    currentAttributes: [...HTML_GLOBAL_ATTRIBUTE_NAMES, ...["height", "src", "type", "width"]],
    obsoleteAttributes: ["align", "hspace", "name", "vspace"],
    conditionalCategories: [],
  },
  fieldset: {
    tag: "fieldset",
    interface: "HTMLFieldSetElement",
    conformance: "conforming",
    void: false,
    rawText: false,
    textMode: "normal",
    categories: ["flow", "listed", "form-associated", "palpable"],
    children: ["legend", "flow"],
    currentAttributes: [...HTML_GLOBAL_ATTRIBUTE_NAMES, ...["disabled", "form", "name"]],
    obsoleteAttributes: ["autocomplete"],
    conditionalCategories: [],
    childGrammar: "fieldset",
  },
  figcaption: {
    tag: "figcaption",
    interface: "HTMLElement",
    conformance: "conforming",
    void: false,
    rawText: false,
    textMode: "normal",
    categories: [],
    children: ["flow"],
    currentAttributes: HTML_GLOBAL_ATTRIBUTE_NAMES,
    obsoleteAttributes: [],
    conditionalCategories: [],
  },
  figure: {
    tag: "figure",
    interface: "HTMLElement",
    conformance: "conforming",
    void: false,
    rawText: false,
    textMode: "normal",
    categories: ["flow", "palpable"],
    children: ["figcaption", "flow"],
    currentAttributes: HTML_GLOBAL_ATTRIBUTE_NAMES,
    obsoleteAttributes: [],
    conditionalCategories: [],
    childGrammar: "figure",
  },
  font: {
    tag: "font",
    interface: "HTMLFontElement",
    conformance: "non-conforming",
    void: false,
    rawText: false,
    textMode: "normal",
    categories: [],
    children: [],
    currentAttributes: HTML_GLOBAL_ATTRIBUTE_NAMES,
    obsoleteAttributes: [],
    conditionalCategories: [],
  },
  footer: {
    tag: "footer",
    interface: "HTMLElement",
    conformance: "conforming",
    void: false,
    rawText: false,
    textMode: "normal",
    categories: ["flow", "palpable"],
    children: ["flow"],
    currentAttributes: HTML_GLOBAL_ATTRIBUTE_NAMES,
    obsoleteAttributes: [],
    conditionalCategories: [],
  },
  form: {
    tag: "form",
    interface: "HTMLFormElement",
    conformance: "conforming",
    void: false,
    rawText: false,
    textMode: "normal",
    categories: ["flow", "palpable"],
    children: ["flow"],
    currentAttributes: [
      ...HTML_GLOBAL_ATTRIBUTE_NAMES,
      ...["accept-charset", "action", "autocomplete", "enctype", "method", "name", "novalidate", "rel", "target"],
    ],
    obsoleteAttributes: ["accept", "formaction", "formenctype", "formmethod", "formnovalidate", "formtarget"],
    conditionalCategories: [],
  },
  frame: {
    tag: "frame",
    interface: "HTMLFrameElement",
    conformance: "non-conforming",
    void: true,
    rawText: false,
    textMode: "normal",
    categories: [],
    children: [],
    currentAttributes: HTML_GLOBAL_ATTRIBUTE_NAMES,
    obsoleteAttributes: [],
    conditionalCategories: [],
  },
  frameset: {
    tag: "frameset",
    interface: "HTMLFrameSetElement",
    conformance: "non-conforming",
    void: false,
    rawText: false,
    textMode: "normal",
    categories: [],
    children: [],
    currentAttributes: HTML_GLOBAL_ATTRIBUTE_NAMES,
    obsoleteAttributes: [],
    conditionalCategories: [],
  },
  h1: {
    tag: "h1",
    interface: "HTMLHeadingElement",
    conformance: "conforming",
    void: false,
    rawText: false,
    textMode: "normal",
    categories: ["flow", "heading", "palpable"],
    children: ["phrasing"],
    currentAttributes: HTML_GLOBAL_ATTRIBUTE_NAMES,
    obsoleteAttributes: ["align"],
    conditionalCategories: [],
  },
  h2: {
    tag: "h2",
    interface: "HTMLHeadingElement",
    conformance: "conforming",
    void: false,
    rawText: false,
    textMode: "normal",
    categories: ["flow", "heading", "palpable"],
    children: ["phrasing"],
    currentAttributes: HTML_GLOBAL_ATTRIBUTE_NAMES,
    obsoleteAttributes: ["align"],
    conditionalCategories: [],
  },
  h3: {
    tag: "h3",
    interface: "HTMLHeadingElement",
    conformance: "conforming",
    void: false,
    rawText: false,
    textMode: "normal",
    categories: ["flow", "heading", "palpable"],
    children: ["phrasing"],
    currentAttributes: HTML_GLOBAL_ATTRIBUTE_NAMES,
    obsoleteAttributes: ["align"],
    conditionalCategories: [],
  },
  h4: {
    tag: "h4",
    interface: "HTMLHeadingElement",
    conformance: "conforming",
    void: false,
    rawText: false,
    textMode: "normal",
    categories: ["flow", "heading", "palpable"],
    children: ["phrasing"],
    currentAttributes: HTML_GLOBAL_ATTRIBUTE_NAMES,
    obsoleteAttributes: ["align"],
    conditionalCategories: [],
  },
  h5: {
    tag: "h5",
    interface: "HTMLHeadingElement",
    conformance: "conforming",
    void: false,
    rawText: false,
    textMode: "normal",
    categories: ["flow", "heading", "palpable"],
    children: ["phrasing"],
    currentAttributes: HTML_GLOBAL_ATTRIBUTE_NAMES,
    obsoleteAttributes: ["align"],
    conditionalCategories: [],
  },
  h6: {
    tag: "h6",
    interface: "HTMLHeadingElement",
    conformance: "conforming",
    void: false,
    rawText: false,
    textMode: "normal",
    categories: ["flow", "heading", "palpable"],
    children: ["phrasing"],
    currentAttributes: HTML_GLOBAL_ATTRIBUTE_NAMES,
    obsoleteAttributes: ["align"],
    conditionalCategories: [],
  },
  head: {
    tag: "head",
    interface: "HTMLHeadElement",
    conformance: "conforming",
    void: false,
    rawText: false,
    textMode: "normal",
    categories: [],
    children: ["metadata content"],
    currentAttributes: HTML_GLOBAL_ATTRIBUTE_NAMES,
    obsoleteAttributes: ["profile"],
    conditionalCategories: [],
    childGrammar: "head",
  },
  header: {
    tag: "header",
    interface: "HTMLElement",
    conformance: "conforming",
    void: false,
    rawText: false,
    textMode: "normal",
    categories: ["flow", "palpable"],
    children: ["flow"],
    currentAttributes: HTML_GLOBAL_ATTRIBUTE_NAMES,
    obsoleteAttributes: [],
    conditionalCategories: [],
  },
  hgroup: {
    tag: "hgroup",
    interface: "HTMLElement",
    conformance: "conforming",
    void: false,
    rawText: false,
    textMode: "normal",
    categories: ["flow", "palpable"],
    children: ["h1", "h2", "h3", "h4", "h5", "h6", "p", "script-supporting elements"],
    currentAttributes: HTML_GLOBAL_ATTRIBUTE_NAMES,
    obsoleteAttributes: [],
    conditionalCategories: [],
    childGrammar: "hgroup",
  },
  hr: {
    tag: "hr",
    interface: "HTMLHRElement",
    conformance: "conforming",
    void: true,
    rawText: false,
    textMode: "normal",
    categories: ["flow"],
    children: ["empty"],
    currentAttributes: HTML_GLOBAL_ATTRIBUTE_NAMES,
    obsoleteAttributes: ["align", "color", "noshade", "size", "width"],
    conditionalCategories: [],
  },
  html: {
    tag: "html",
    interface: "HTMLHtmlElement",
    conformance: "conforming",
    void: false,
    rawText: false,
    textMode: "normal",
    categories: [],
    children: ["head", "body"],
    currentAttributes: HTML_GLOBAL_ATTRIBUTE_NAMES,
    obsoleteAttributes: ["manifest", "version"],
    conditionalCategories: [],
    childGrammar: "document-element",
  },
  i: {
    tag: "i",
    interface: "HTMLElement",
    conformance: "conforming",
    void: false,
    rawText: false,
    textMode: "normal",
    categories: ["flow", "phrasing", "palpable"],
    children: ["phrasing"],
    currentAttributes: HTML_GLOBAL_ATTRIBUTE_NAMES,
    obsoleteAttributes: [],
    conditionalCategories: [],
  },
  iframe: {
    tag: "iframe",
    interface: "HTMLIFrameElement",
    conformance: "conforming",
    void: false,
    rawText: true,
    textMode: "raw-text",
    categories: ["flow", "phrasing", "embedded", "interactive", "palpable"],
    children: ["empty"],
    currentAttributes: [
      ...HTML_GLOBAL_ATTRIBUTE_NAMES,
      ...[
        "allow",
        "allowfullscreen",
        "height",
        "loading",
        "name",
        "referrerpolicy",
        "sandbox",
        "src",
        "srcdoc",
        "width",
      ],
    ],
    obsoleteAttributes: [
      "align",
      "allowtransparency",
      "frameborder",
      "framespacing",
      "hspace",
      "longdesc",
      "marginheight",
      "marginwidth",
      "scrolling",
      "vspace",
    ],
    conditionalCategories: [],
  },
  img: {
    tag: "img",
    interface: "HTMLImageElement",
    conformance: "conforming",
    void: true,
    rawText: false,
    textMode: "normal",
    categories: ["flow", "phrasing", "embedded", "interactive", "form-associated", "palpable"],
    children: ["empty"],
    currentAttributes: [
      ...HTML_GLOBAL_ATTRIBUTE_NAMES,
      ...[
        "alt",
        "controls",
        "crossorigin",
        "decoding",
        "fetchpriority",
        "height",
        "ismap",
        "loading",
        "referrerpolicy",
        "sizes",
        "src",
        "srcset",
        "usemap",
        "width",
      ],
    ],
    obsoleteAttributes: ["align", "border", "hspace", "longdesc", "lowsrc", "name", "vspace"],
    conditionalCategories: [{ attribute: "usemap", category: "interactive", condition: "present" }],
  },
  input: {
    tag: "input",
    interface: "HTMLInputElement",
    conformance: "conforming",
    void: true,
    rawText: false,
    textMode: "normal",
    categories: [
      "flow",
      "phrasing",
      "interactive",
      "listed",
      "labelable",
      "submittable",
      "resettable",
      "form-associated",
      "palpable",
    ],
    children: ["empty"],
    currentAttributes: [
      ...HTML_GLOBAL_ATTRIBUTE_NAMES,
      ...[
        "accept",
        "alpha",
        "alt",
        "autocomplete",
        "checked",
        "colorspace",
        "dirname",
        "disabled",
        "form",
        "formaction",
        "formenctype",
        "formmethod",
        "formnovalidate",
        "formtarget",
        "height",
        "list",
        "max",
        "maxlength",
        "min",
        "minlength",
        "multiple",
        "name",
        "pattern",
        "placeholder",
        "popovertarget",
        "popovertargetaction",
        "readonly",
        "required",
        "size",
        "src",
        "step",
        "type",
        "value",
        "width",
      ],
    ],
    obsoleteAttributes: ["align", "border", "hspace", "ismap", "usemap", "vspace"],
    conditionalCategories: [{ attribute: "type", category: "interactive", condition: "not-equals", value: "hidden" }],
  },
  ins: {
    tag: "ins",
    interface: "HTMLModElement",
    conformance: "conforming",
    void: false,
    rawText: false,
    textMode: "normal",
    categories: ["flow", "phrasing", "palpable"],
    children: ["transparent"],
    currentAttributes: [...HTML_GLOBAL_ATTRIBUTE_NAMES, ...["cite", "datetime"]],
    obsoleteAttributes: [],
    conditionalCategories: [],
  },
  isindex: {
    tag: "isindex",
    interface: "HTMLUnknownElement",
    conformance: "non-conforming",
    void: true,
    rawText: false,
    textMode: "normal",
    categories: [],
    children: [],
    currentAttributes: HTML_GLOBAL_ATTRIBUTE_NAMES,
    obsoleteAttributes: [],
    conditionalCategories: [],
  },
  kbd: {
    tag: "kbd",
    interface: "HTMLElement",
    conformance: "conforming",
    void: false,
    rawText: false,
    textMode: "normal",
    categories: ["flow", "phrasing", "palpable"],
    children: ["phrasing"],
    currentAttributes: HTML_GLOBAL_ATTRIBUTE_NAMES,
    obsoleteAttributes: [],
    conditionalCategories: [],
  },
  keygen: {
    tag: "keygen",
    interface: "HTMLUnknownElement",
    conformance: "non-conforming",
    void: true,
    rawText: false,
    textMode: "normal",
    categories: [],
    children: [],
    currentAttributes: HTML_GLOBAL_ATTRIBUTE_NAMES,
    obsoleteAttributes: [],
    conditionalCategories: [],
  },
  label: {
    tag: "label",
    interface: "HTMLLabelElement",
    conformance: "conforming",
    void: false,
    rawText: false,
    textMode: "normal",
    categories: ["flow", "phrasing", "interactive", "palpable"],
    children: ["phrasing"],
    currentAttributes: [...HTML_GLOBAL_ATTRIBUTE_NAMES, ...["for"]],
    obsoleteAttributes: [],
    conditionalCategories: [],
  },
  legend: {
    tag: "legend",
    interface: "HTMLLegendElement",
    conformance: "conforming",
    void: false,
    rawText: false,
    textMode: "normal",
    categories: [],
    children: ["phrasing", "heading content"],
    currentAttributes: HTML_GLOBAL_ATTRIBUTE_NAMES,
    obsoleteAttributes: ["align"],
    conditionalCategories: [],
    childGrammar: "phrasing-or-heading",
  },
  li: {
    tag: "li",
    interface: "HTMLLIElement",
    conformance: "conforming",
    void: false,
    rawText: false,
    textMode: "normal",
    categories: [],
    children: ["flow"],
    currentAttributes: [...HTML_GLOBAL_ATTRIBUTE_NAMES, ...["value"]],
    obsoleteAttributes: ["type"],
    conditionalCategories: [],
  },
  link: {
    tag: "link",
    interface: "HTMLLinkElement",
    conformance: "conforming",
    void: true,
    rawText: false,
    textMode: "normal",
    categories: ["metadata", "flow", "phrasing"],
    children: ["empty"],
    currentAttributes: [
      ...HTML_GLOBAL_ATTRIBUTE_NAMES,
      ...[
        "as",
        "blocking",
        "color",
        "crossorigin",
        "disabled",
        "fetchpriority",
        "href",
        "hreflang",
        "imagesizes",
        "imagesrcset",
        "integrity",
        "media",
        "referrerpolicy",
        "rel",
        "sizes",
        "type",
      ],
    ],
    obsoleteAttributes: ["charset", "methods", "rev", "target", "urn"],
    conditionalCategories: [],
  },
  listing: {
    tag: "listing",
    interface: "HTMLPreElement",
    conformance: "non-conforming",
    void: false,
    rawText: false,
    textMode: "normal",
    categories: [],
    children: [],
    currentAttributes: HTML_GLOBAL_ATTRIBUTE_NAMES,
    obsoleteAttributes: [],
    conditionalCategories: [],
  },
  main: {
    tag: "main",
    interface: "HTMLElement",
    conformance: "conforming",
    void: false,
    rawText: false,
    textMode: "normal",
    categories: ["flow", "palpable"],
    children: ["flow"],
    currentAttributes: HTML_GLOBAL_ATTRIBUTE_NAMES,
    obsoleteAttributes: [],
    conditionalCategories: [],
  },
  map: {
    tag: "map",
    interface: "HTMLMapElement",
    conformance: "conforming",
    void: false,
    rawText: false,
    textMode: "normal",
    categories: ["flow", "phrasing", "palpable"],
    children: ["transparent", "area"],
    currentAttributes: [...HTML_GLOBAL_ATTRIBUTE_NAMES, ...["name"]],
    obsoleteAttributes: [],
    conditionalCategories: [],
  },
  mark: {
    tag: "mark",
    interface: "HTMLElement",
    conformance: "conforming",
    void: false,
    rawText: false,
    textMode: "normal",
    categories: ["flow", "phrasing", "palpable"],
    children: ["phrasing"],
    currentAttributes: HTML_GLOBAL_ATTRIBUTE_NAMES,
    obsoleteAttributes: [],
    conditionalCategories: [],
  },
  marquee: {
    tag: "marquee",
    interface: "HTMLMarqueeElement",
    conformance: "non-conforming",
    void: false,
    rawText: false,
    textMode: "normal",
    categories: [],
    children: [],
    currentAttributes: HTML_GLOBAL_ATTRIBUTE_NAMES,
    obsoleteAttributes: ["behavior", "direction", "loop", "truespeed"],
    conditionalCategories: [],
  },
  menu: {
    tag: "menu",
    interface: "HTMLMenuElement",
    conformance: "conforming",
    void: false,
    rawText: false,
    textMode: "normal",
    categories: ["flow", "palpable"],
    children: ["li", "script-supporting elements"],
    currentAttributes: HTML_GLOBAL_ATTRIBUTE_NAMES,
    obsoleteAttributes: ["compact", "label", "type"],
    conditionalCategories: [],
  },
  menuitem: {
    tag: "menuitem",
    interface: "HTMLUnknownElement",
    conformance: "non-conforming",
    void: false,
    rawText: false,
    textMode: "normal",
    categories: [],
    children: [],
    currentAttributes: HTML_GLOBAL_ATTRIBUTE_NAMES,
    obsoleteAttributes: [],
    conditionalCategories: [],
  },
  meta: {
    tag: "meta",
    interface: "HTMLMetaElement",
    conformance: "conforming",
    void: true,
    rawText: false,
    textMode: "normal",
    categories: ["metadata", "flow", "phrasing"],
    children: ["empty"],
    currentAttributes: [...HTML_GLOBAL_ATTRIBUTE_NAMES, ...["charset", "content", "http-equiv", "media", "name"]],
    obsoleteAttributes: ["scheme"],
    conditionalCategories: [],
  },
  meter: {
    tag: "meter",
    interface: "HTMLMeterElement",
    conformance: "conforming",
    void: false,
    rawText: false,
    textMode: "normal",
    categories: ["flow", "phrasing", "labelable", "palpable"],
    children: ["phrasing"],
    currentAttributes: [...HTML_GLOBAL_ATTRIBUTE_NAMES, ...["high", "low", "max", "min", "optimum", "value"]],
    obsoleteAttributes: [],
    conditionalCategories: [],
  },
  multicol: {
    tag: "multicol",
    interface: "HTMLUnknownElement",
    conformance: "non-conforming",
    void: false,
    rawText: false,
    textMode: "normal",
    categories: [],
    children: [],
    currentAttributes: HTML_GLOBAL_ATTRIBUTE_NAMES,
    obsoleteAttributes: [],
    conditionalCategories: [],
  },
  nav: {
    tag: "nav",
    interface: "HTMLElement",
    conformance: "conforming",
    void: false,
    rawText: false,
    textMode: "normal",
    categories: ["flow", "sectioning", "palpable"],
    children: ["flow"],
    currentAttributes: HTML_GLOBAL_ATTRIBUTE_NAMES,
    obsoleteAttributes: [],
    conditionalCategories: [],
  },
  nextid: {
    tag: "nextid",
    interface: "HTMLUnknownElement",
    conformance: "non-conforming",
    void: true,
    rawText: false,
    textMode: "normal",
    categories: [],
    children: [],
    currentAttributes: HTML_GLOBAL_ATTRIBUTE_NAMES,
    obsoleteAttributes: [],
    conditionalCategories: [],
  },
  nobr: {
    tag: "nobr",
    interface: "HTMLElement",
    conformance: "non-conforming",
    void: false,
    rawText: false,
    textMode: "normal",
    categories: [],
    children: [],
    currentAttributes: HTML_GLOBAL_ATTRIBUTE_NAMES,
    obsoleteAttributes: [],
    conditionalCategories: [],
  },
  noembed: {
    tag: "noembed",
    interface: "HTMLElement",
    conformance: "non-conforming",
    void: false,
    rawText: true,
    textMode: "raw-text",
    categories: [],
    children: [],
    currentAttributes: HTML_GLOBAL_ATTRIBUTE_NAMES,
    obsoleteAttributes: [],
    conditionalCategories: [],
  },
  noframes: {
    tag: "noframes",
    interface: "HTMLElement",
    conformance: "non-conforming",
    void: false,
    rawText: true,
    textMode: "raw-text",
    categories: [],
    children: [],
    currentAttributes: HTML_GLOBAL_ATTRIBUTE_NAMES,
    obsoleteAttributes: [],
    conditionalCategories: [],
  },
  noscript: {
    tag: "noscript",
    interface: "HTMLElement",
    conformance: "conforming",
    void: false,
    rawText: false,
    textMode: "normal",
    categories: ["metadata", "flow", "phrasing"],
    children: ["varies"],
    currentAttributes: HTML_GLOBAL_ATTRIBUTE_NAMES,
    obsoleteAttributes: [],
    conditionalCategories: [],
  },
  object: {
    tag: "object",
    interface: "HTMLObjectElement",
    conformance: "conforming",
    void: false,
    rawText: false,
    textMode: "normal",
    categories: ["flow", "phrasing", "embedded", "interactive", "listed", "form-associated", "palpable"],
    children: ["transparent"],
    currentAttributes: [...HTML_GLOBAL_ATTRIBUTE_NAMES, ...["data", "form", "height", "name", "type", "width"]],
    obsoleteAttributes: [
      "align",
      "archive",
      "autocomplete",
      "border",
      "classid",
      "code",
      "codebase",
      "codetype",
      "declare",
      "disabled",
      "hspace",
      "standby",
      "typemustmatch",
      "usemap",
      "vspace",
    ],
    conditionalCategories: [{ attribute: "usemap", category: "interactive", condition: "present" }],
  },
  ol: {
    tag: "ol",
    interface: "HTMLOListElement",
    conformance: "conforming",
    void: false,
    rawText: false,
    textMode: "normal",
    categories: ["flow", "palpable"],
    children: ["li", "script-supporting elements"],
    currentAttributes: [...HTML_GLOBAL_ATTRIBUTE_NAMES, ...["reversed", "start", "type"]],
    obsoleteAttributes: ["compact"],
    conditionalCategories: [],
  },
  optgroup: {
    tag: "optgroup",
    interface: "HTMLOptGroupElement",
    conformance: "conforming",
    void: false,
    rawText: false,
    textMode: "normal",
    categories: [],
    children: ["optgroup element inner content elements", "legend"],
    currentAttributes: [...HTML_GLOBAL_ATTRIBUTE_NAMES, ...["disabled", "label"]],
    obsoleteAttributes: [],
    conditionalCategories: [],
    childGrammar: "optgroup",
  },
  option: {
    tag: "option",
    interface: "HTMLOptionElement",
    conformance: "conforming",
    void: false,
    rawText: false,
    textMode: "normal",
    categories: [],
    children: ["text", "option element inner content elements"],
    currentAttributes: [...HTML_GLOBAL_ATTRIBUTE_NAMES, ...["disabled", "label", "selected", "value"]],
    obsoleteAttributes: ["name"],
    conditionalCategories: [],
  },
  output: {
    tag: "output",
    interface: "HTMLOutputElement",
    conformance: "conforming",
    void: false,
    rawText: false,
    textMode: "normal",
    categories: ["flow", "phrasing", "listed", "labelable", "resettable", "form-associated", "palpable"],
    children: ["phrasing"],
    currentAttributes: [...HTML_GLOBAL_ATTRIBUTE_NAMES, ...["for", "form", "name"]],
    obsoleteAttributes: ["autocomplete", "disabled"],
    conditionalCategories: [],
  },
  p: {
    tag: "p",
    interface: "HTMLParagraphElement",
    conformance: "conforming",
    void: false,
    rawText: false,
    textMode: "normal",
    categories: ["flow", "palpable"],
    children: ["phrasing"],
    currentAttributes: HTML_GLOBAL_ATTRIBUTE_NAMES,
    obsoleteAttributes: ["align"],
    conditionalCategories: [],
  },
  param: {
    tag: "param",
    interface: "HTMLParamElement",
    conformance: "non-conforming",
    void: true,
    rawText: false,
    textMode: "normal",
    categories: [],
    children: [],
    currentAttributes: HTML_GLOBAL_ATTRIBUTE_NAMES,
    obsoleteAttributes: [],
    conditionalCategories: [],
  },
  picture: {
    tag: "picture",
    interface: "HTMLPictureElement",
    conformance: "conforming",
    void: false,
    rawText: false,
    textMode: "normal",
    categories: ["flow", "phrasing", "embedded", "palpable"],
    children: ["source", "one img", "script-supporting elements"],
    currentAttributes: HTML_GLOBAL_ATTRIBUTE_NAMES,
    obsoleteAttributes: [],
    conditionalCategories: [],
    childGrammar: "picture",
  },
  plaintext: {
    tag: "plaintext",
    interface: "HTMLElement",
    conformance: "non-conforming",
    void: false,
    rawText: false,
    textMode: "plaintext",
    categories: [],
    children: [],
    currentAttributes: HTML_GLOBAL_ATTRIBUTE_NAMES,
    obsoleteAttributes: [],
    conditionalCategories: [],
  },
  pre: {
    tag: "pre",
    interface: "HTMLPreElement",
    conformance: "conforming",
    void: false,
    rawText: false,
    textMode: "normal",
    categories: ["flow", "palpable"],
    children: ["phrasing"],
    currentAttributes: HTML_GLOBAL_ATTRIBUTE_NAMES,
    obsoleteAttributes: ["width"],
    conditionalCategories: [],
  },
  progress: {
    tag: "progress",
    interface: "HTMLProgressElement",
    conformance: "conforming",
    void: false,
    rawText: false,
    textMode: "normal",
    categories: ["flow", "phrasing", "labelable", "palpable"],
    children: ["phrasing"],
    currentAttributes: [...HTML_GLOBAL_ATTRIBUTE_NAMES, ...["max", "value"]],
    obsoleteAttributes: [],
    conditionalCategories: [],
  },
  q: {
    tag: "q",
    interface: "HTMLQuoteElement",
    conformance: "conforming",
    void: false,
    rawText: false,
    textMode: "normal",
    categories: ["flow", "phrasing", "palpable"],
    children: ["phrasing"],
    currentAttributes: [...HTML_GLOBAL_ATTRIBUTE_NAMES, ...["cite"]],
    obsoleteAttributes: [],
    conditionalCategories: [],
  },
  rb: {
    tag: "rb",
    interface: "HTMLElement",
    conformance: "non-conforming",
    void: false,
    rawText: false,
    textMode: "normal",
    categories: [],
    children: [],
    currentAttributes: HTML_GLOBAL_ATTRIBUTE_NAMES,
    obsoleteAttributes: [],
    conditionalCategories: [],
  },
  rp: {
    tag: "rp",
    interface: "HTMLElement",
    conformance: "conforming",
    void: false,
    rawText: false,
    textMode: "normal",
    categories: [],
    children: ["text"],
    currentAttributes: HTML_GLOBAL_ATTRIBUTE_NAMES,
    obsoleteAttributes: [],
    conditionalCategories: [],
  },
  rt: {
    tag: "rt",
    interface: "HTMLElement",
    conformance: "conforming",
    void: false,
    rawText: false,
    textMode: "normal",
    categories: [],
    children: ["phrasing"],
    currentAttributes: HTML_GLOBAL_ATTRIBUTE_NAMES,
    obsoleteAttributes: [],
    conditionalCategories: [],
  },
  rtc: {
    tag: "rtc",
    interface: "HTMLElement",
    conformance: "non-conforming",
    void: false,
    rawText: false,
    textMode: "normal",
    categories: [],
    children: [],
    currentAttributes: HTML_GLOBAL_ATTRIBUTE_NAMES,
    obsoleteAttributes: [],
    conditionalCategories: [],
  },
  ruby: {
    tag: "ruby",
    interface: "HTMLElement",
    conformance: "conforming",
    void: false,
    rawText: false,
    textMode: "normal",
    categories: ["flow", "phrasing", "palpable"],
    children: ["phrasing", "rt", "rp"],
    currentAttributes: HTML_GLOBAL_ATTRIBUTE_NAMES,
    obsoleteAttributes: [],
    conditionalCategories: [],
    childGrammar: "ruby",
  },
  s: {
    tag: "s",
    interface: "HTMLElement",
    conformance: "conforming",
    void: false,
    rawText: false,
    textMode: "normal",
    categories: ["flow", "phrasing", "palpable"],
    children: ["phrasing"],
    currentAttributes: HTML_GLOBAL_ATTRIBUTE_NAMES,
    obsoleteAttributes: [],
    conditionalCategories: [],
  },
  samp: {
    tag: "samp",
    interface: "HTMLElement",
    conformance: "conforming",
    void: false,
    rawText: false,
    textMode: "normal",
    categories: ["flow", "phrasing", "palpable"],
    children: ["phrasing"],
    currentAttributes: HTML_GLOBAL_ATTRIBUTE_NAMES,
    obsoleteAttributes: [],
    conditionalCategories: [],
  },
  script: {
    tag: "script",
    interface: "HTMLScriptElement",
    conformance: "conforming",
    void: false,
    rawText: true,
    textMode: "raw-text",
    categories: ["metadata", "flow", "phrasing", "script-supporting"],
    children: ["script", "data", "or script documentation"],
    currentAttributes: [
      ...HTML_GLOBAL_ATTRIBUTE_NAMES,
      ...[
        "async",
        "blocking",
        "crossorigin",
        "defer",
        "fetchpriority",
        "integrity",
        "nomodule",
        "referrerpolicy",
        "src",
        "type",
      ],
    ],
    obsoleteAttributes: ["charset", "event", "for", "language"],
    conditionalCategories: [],
  },
  search: {
    tag: "search",
    interface: "HTMLElement",
    conformance: "conforming",
    void: false,
    rawText: false,
    textMode: "normal",
    categories: ["flow", "palpable"],
    children: ["flow"],
    currentAttributes: HTML_GLOBAL_ATTRIBUTE_NAMES,
    obsoleteAttributes: [],
    conditionalCategories: [],
  },
  section: {
    tag: "section",
    interface: "HTMLElement",
    conformance: "conforming",
    void: false,
    rawText: false,
    textMode: "normal",
    categories: ["flow", "sectioning", "palpable"],
    children: ["flow"],
    currentAttributes: HTML_GLOBAL_ATTRIBUTE_NAMES,
    obsoleteAttributes: [],
    conditionalCategories: [],
  },
  select: {
    tag: "select",
    interface: "HTMLSelectElement",
    conformance: "conforming",
    void: false,
    rawText: false,
    textMode: "normal",
    categories: [
      "flow",
      "phrasing",
      "interactive",
      "listed",
      "labelable",
      "submittable",
      "resettable",
      "form-associated",
      "palpable",
    ],
    children: ["select element inner content elements", "button"],
    currentAttributes: [
      ...HTML_GLOBAL_ATTRIBUTE_NAMES,
      ...["autocomplete", "disabled", "form", "multiple", "name", "required", "size"],
    ],
    obsoleteAttributes: [],
    conditionalCategories: [],
    childGrammar: "select",
  },
  selectedcontent: {
    tag: "selectedcontent",
    interface: "HTMLSelectedContentElement",
    conformance: "conforming",
    void: false,
    rawText: false,
    textMode: "normal",
    categories: [],
    children: ["empty"],
    currentAttributes: HTML_GLOBAL_ATTRIBUTE_NAMES,
    obsoleteAttributes: [],
    conditionalCategories: [],
  },
  slot: {
    tag: "slot",
    interface: "HTMLSlotElement",
    conformance: "conforming",
    void: false,
    rawText: false,
    textMode: "normal",
    categories: ["flow", "phrasing"],
    children: ["transparent"],
    currentAttributes: [...HTML_GLOBAL_ATTRIBUTE_NAMES, ...["name"]],
    obsoleteAttributes: [],
    conditionalCategories: [],
  },
  small: {
    tag: "small",
    interface: "HTMLElement",
    conformance: "conforming",
    void: false,
    rawText: false,
    textMode: "normal",
    categories: ["flow", "phrasing", "palpable"],
    children: ["phrasing"],
    currentAttributes: HTML_GLOBAL_ATTRIBUTE_NAMES,
    obsoleteAttributes: [],
    conditionalCategories: [],
  },
  source: {
    tag: "source",
    interface: "HTMLSourceElement",
    conformance: "conforming",
    void: true,
    rawText: false,
    textMode: "normal",
    categories: [],
    children: ["empty"],
    currentAttributes: [
      ...HTML_GLOBAL_ATTRIBUTE_NAMES,
      ...["height", "media", "sizes", "src", "srcset", "type", "width"],
    ],
    obsoleteAttributes: [],
    conditionalCategories: [],
  },
  spacer: {
    tag: "spacer",
    interface: "HTMLUnknownElement",
    conformance: "non-conforming",
    void: true,
    rawText: false,
    textMode: "normal",
    categories: [],
    children: [],
    currentAttributes: HTML_GLOBAL_ATTRIBUTE_NAMES,
    obsoleteAttributes: [],
    conditionalCategories: [],
  },
  span: {
    tag: "span",
    interface: "HTMLSpanElement",
    conformance: "conforming",
    void: false,
    rawText: false,
    textMode: "normal",
    categories: ["flow", "phrasing", "palpable"],
    children: ["phrasing"],
    currentAttributes: HTML_GLOBAL_ATTRIBUTE_NAMES,
    obsoleteAttributes: [],
    conditionalCategories: [],
  },
  strike: {
    tag: "strike",
    interface: "HTMLElement",
    conformance: "non-conforming",
    void: false,
    rawText: false,
    textMode: "normal",
    categories: [],
    children: [],
    currentAttributes: HTML_GLOBAL_ATTRIBUTE_NAMES,
    obsoleteAttributes: [],
    conditionalCategories: [],
  },
  strong: {
    tag: "strong",
    interface: "HTMLElement",
    conformance: "conforming",
    void: false,
    rawText: false,
    textMode: "normal",
    categories: ["flow", "phrasing", "palpable"],
    children: ["phrasing"],
    currentAttributes: HTML_GLOBAL_ATTRIBUTE_NAMES,
    obsoleteAttributes: [],
    conditionalCategories: [],
  },
  style: {
    tag: "style",
    interface: "HTMLStyleElement",
    conformance: "conforming",
    void: false,
    rawText: true,
    textMode: "raw-text",
    categories: ["metadata"],
    children: ["text"],
    currentAttributes: [...HTML_GLOBAL_ATTRIBUTE_NAMES, ...["blocking", "media"]],
    obsoleteAttributes: ["type"],
    conditionalCategories: [],
  },
  sub: {
    tag: "sub",
    interface: "HTMLElement",
    conformance: "conforming",
    void: false,
    rawText: false,
    textMode: "normal",
    categories: ["flow", "phrasing", "palpable"],
    children: ["phrasing"],
    currentAttributes: HTML_GLOBAL_ATTRIBUTE_NAMES,
    obsoleteAttributes: [],
    conditionalCategories: [],
  },
  summary: {
    tag: "summary",
    interface: "HTMLElement",
    conformance: "conforming",
    void: false,
    rawText: false,
    textMode: "normal",
    categories: [],
    children: ["phrasing", "heading content"],
    currentAttributes: HTML_GLOBAL_ATTRIBUTE_NAMES,
    obsoleteAttributes: [],
    conditionalCategories: [],
    childGrammar: "phrasing-or-heading",
  },
  sup: {
    tag: "sup",
    interface: "HTMLElement",
    conformance: "conforming",
    void: false,
    rawText: false,
    textMode: "normal",
    categories: ["flow", "phrasing", "palpable"],
    children: ["phrasing"],
    currentAttributes: HTML_GLOBAL_ATTRIBUTE_NAMES,
    obsoleteAttributes: [],
    conditionalCategories: [],
  },
  table: {
    tag: "table",
    interface: "HTMLTableElement",
    conformance: "conforming",
    void: false,
    rawText: false,
    textMode: "normal",
    categories: ["flow", "palpable"],
    children: ["caption", "colgroup", "thead", "tbody", "tfoot", "tr", "script-supporting elements"],
    currentAttributes: HTML_GLOBAL_ATTRIBUTE_NAMES,
    obsoleteAttributes: [
      "align",
      "bgcolor",
      "border",
      "bordercolor",
      "cellpadding",
      "cellspacing",
      "datapagesize",
      "frame",
      "height",
      "rules",
      "summary",
      "width",
    ],
    conditionalCategories: [],
    childSequencePattern: "^(?:caption,)?(?:colgroup,)*(?:thead,)?(?:(?:tbody,)*|(?:tr,)+)(?:tfoot,)?$",
    childGrammar: "table",
  },
  tbody: {
    tag: "tbody",
    interface: "HTMLTableSectionElement",
    conformance: "conforming",
    void: false,
    rawText: false,
    textMode: "normal",
    categories: [],
    children: ["tr", "script-supporting elements"],
    currentAttributes: HTML_GLOBAL_ATTRIBUTE_NAMES,
    obsoleteAttributes: ["align", "char", "charoff", "height", "valign"],
    conditionalCategories: [],
  },
  td: {
    tag: "td",
    interface: "HTMLTableCellElement",
    conformance: "conforming",
    void: false,
    rawText: false,
    textMode: "normal",
    categories: [],
    children: ["flow"],
    currentAttributes: [...HTML_GLOBAL_ATTRIBUTE_NAMES, ...["colspan", "headers", "rowspan"]],
    obsoleteAttributes: [
      "abbr",
      "align",
      "axis",
      "bgcolor",
      "char",
      "charoff",
      "height",
      "nowrap",
      "scope",
      "valign",
      "width",
    ],
    conditionalCategories: [],
  },
  template: {
    tag: "template",
    interface: "HTMLTemplateElement",
    conformance: "conforming",
    void: false,
    rawText: false,
    textMode: "normal",
    categories: ["metadata", "flow", "phrasing", "script-supporting"],
    children: ["empty"],
    currentAttributes: [
      ...HTML_GLOBAL_ATTRIBUTE_NAMES,
      ...[
        "shadowrootclonable",
        "shadowrootcustomelementregistry",
        "shadowrootdelegatesfocus",
        "shadowrootmode",
        "shadowrootserializable",
        "shadowrootslotassignment",
      ],
    ],
    obsoleteAttributes: [],
    conditionalCategories: [],
  },
  textarea: {
    tag: "textarea",
    interface: "HTMLTextAreaElement",
    conformance: "conforming",
    void: false,
    rawText: false,
    textMode: "rcdata",
    categories: [
      "flow",
      "phrasing",
      "interactive",
      "listed",
      "labelable",
      "submittable",
      "resettable",
      "form-associated",
      "palpable",
    ],
    children: ["text"],
    currentAttributes: [
      ...HTML_GLOBAL_ATTRIBUTE_NAMES,
      ...[
        "autocomplete",
        "cols",
        "dirname",
        "disabled",
        "form",
        "maxlength",
        "minlength",
        "name",
        "placeholder",
        "readonly",
        "required",
        "rows",
        "wrap",
      ],
    ],
    obsoleteAttributes: [],
    conditionalCategories: [],
  },
  tfoot: {
    tag: "tfoot",
    interface: "HTMLTableSectionElement",
    conformance: "conforming",
    void: false,
    rawText: false,
    textMode: "normal",
    categories: [],
    children: ["tr", "script-supporting elements"],
    currentAttributes: HTML_GLOBAL_ATTRIBUTE_NAMES,
    obsoleteAttributes: [],
    conditionalCategories: [],
  },
  th: {
    tag: "th",
    interface: "HTMLTableCellElement",
    conformance: "conforming",
    void: false,
    rawText: false,
    textMode: "normal",
    categories: ["interactive"],
    children: ["flow"],
    currentAttributes: [...HTML_GLOBAL_ATTRIBUTE_NAMES, ...["abbr", "colspan", "headers", "rowspan", "scope"]],
    obsoleteAttributes: ["align", "axis", "bgcolor", "char", "charoff", "height", "nowrap", "valign", "width"],
    conditionalCategories: [],
  },
  thead: {
    tag: "thead",
    interface: "HTMLTableSectionElement",
    conformance: "conforming",
    void: false,
    rawText: false,
    textMode: "normal",
    categories: [],
    children: ["tr", "script-supporting elements"],
    currentAttributes: HTML_GLOBAL_ATTRIBUTE_NAMES,
    obsoleteAttributes: [],
    conditionalCategories: [],
  },
  time: {
    tag: "time",
    interface: "HTMLTimeElement",
    conformance: "conforming",
    void: false,
    rawText: false,
    textMode: "normal",
    categories: ["flow", "phrasing", "palpable"],
    children: ["phrasing"],
    currentAttributes: [...HTML_GLOBAL_ATTRIBUTE_NAMES, ...["datetime"]],
    obsoleteAttributes: [],
    conditionalCategories: [],
  },
  title: {
    tag: "title",
    interface: "HTMLTitleElement",
    conformance: "conforming",
    void: false,
    rawText: false,
    textMode: "rcdata",
    categories: ["metadata"],
    children: ["text"],
    currentAttributes: HTML_GLOBAL_ATTRIBUTE_NAMES,
    obsoleteAttributes: [],
    conditionalCategories: [],
  },
  tr: {
    tag: "tr",
    interface: "HTMLTableRowElement",
    conformance: "conforming",
    void: false,
    rawText: false,
    textMode: "normal",
    categories: [],
    children: ["th", "td", "script-supporting elements"],
    currentAttributes: HTML_GLOBAL_ATTRIBUTE_NAMES,
    obsoleteAttributes: ["align", "bgcolor", "char", "charoff", "height", "valign"],
    conditionalCategories: [],
  },
  track: {
    tag: "track",
    interface: "HTMLTrackElement",
    conformance: "conforming",
    void: true,
    rawText: false,
    textMode: "normal",
    categories: [],
    children: ["empty"],
    currentAttributes: [...HTML_GLOBAL_ATTRIBUTE_NAMES, ...["default", "kind", "label", "src", "srclang"]],
    obsoleteAttributes: [],
    conditionalCategories: [],
  },
  tt: {
    tag: "tt",
    interface: "HTMLElement",
    conformance: "non-conforming",
    void: false,
    rawText: false,
    textMode: "normal",
    categories: [],
    children: [],
    currentAttributes: HTML_GLOBAL_ATTRIBUTE_NAMES,
    obsoleteAttributes: [],
    conditionalCategories: [],
  },
  u: {
    tag: "u",
    interface: "HTMLElement",
    conformance: "conforming",
    void: false,
    rawText: false,
    textMode: "normal",
    categories: ["flow", "phrasing", "palpable"],
    children: ["phrasing"],
    currentAttributes: HTML_GLOBAL_ATTRIBUTE_NAMES,
    obsoleteAttributes: [],
    conditionalCategories: [],
  },
  ul: {
    tag: "ul",
    interface: "HTMLUListElement",
    conformance: "conforming",
    void: false,
    rawText: false,
    textMode: "normal",
    categories: ["flow", "palpable"],
    children: ["li", "script-supporting elements"],
    currentAttributes: HTML_GLOBAL_ATTRIBUTE_NAMES,
    obsoleteAttributes: ["compact", "type"],
    conditionalCategories: [],
  },
  var: {
    tag: "var",
    interface: "HTMLElement",
    conformance: "conforming",
    void: false,
    rawText: false,
    textMode: "normal",
    categories: ["flow", "phrasing", "palpable"],
    children: ["phrasing"],
    currentAttributes: HTML_GLOBAL_ATTRIBUTE_NAMES,
    obsoleteAttributes: [],
    conditionalCategories: [],
  },
  video: {
    tag: "video",
    interface: "HTMLVideoElement",
    conformance: "conforming",
    void: false,
    rawText: false,
    textMode: "normal",
    categories: ["flow", "phrasing", "embedded", "interactive", "palpable"],
    children: ["source", "track", "transparent"],
    currentAttributes: [
      ...HTML_GLOBAL_ATTRIBUTE_NAMES,
      ...[
        "autoplay",
        "controls",
        "crossorigin",
        "height",
        "loading",
        "loop",
        "muted",
        "playsinline",
        "poster",
        "preload",
        "src",
        "width",
      ],
    ],
    obsoleteAttributes: [],
    conditionalCategories: [{ attribute: "controls", category: "interactive", condition: "present" }],
    childGrammar: "media",
  },
  wbr: {
    tag: "wbr",
    interface: "HTMLElement",
    conformance: "conforming",
    void: true,
    rawText: false,
    textMode: "normal",
    categories: ["flow", "phrasing"],
    children: ["empty"],
    currentAttributes: HTML_GLOBAL_ATTRIBUTE_NAMES,
    obsoleteAttributes: [],
    conditionalCategories: [],
  },
  xmp: {
    tag: "xmp",
    interface: "HTMLPreElement",
    conformance: "non-conforming",
    void: false,
    rawText: true,
    textMode: "raw-text",
    categories: [],
    children: [],
    currentAttributes: HTML_GLOBAL_ATTRIBUTE_NAMES,
    obsoleteAttributes: [],
    conditionalCategories: [],
  },
};

/**
 * Metadata for every generated HTML element, keyed by tag name.
 *
 * @example
 * ```ts
 * import { ELEMENT_META } from "@beep/html/Html.meta"
 *
 * console.log(ELEMENT_META.div.interface) // "HTMLDivElement"
 * ```
 *
 * @category models
 * @since 0.0.0
 */
export const ELEMENT_META: Readonly<Record<HtmlTag, HtmlElementMeta>> = Object.freeze(
  R.map(elementMetaSource, freezeElementMeta)
);
