// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as outputs from "../types/output";
import type * as pulumi from "@pulumi/pulumi";
import type * as inputs from "../types/input";

export interface AmiArgs {
  filter?: pulumi.Input<{ [key: string]: pulumi.Input<pulumi.Input<string>[]> } | undefined>;
  id_ssm_parameter_arn?: pulumi.Input<string | undefined>;
  kms_key_arn?: pulumi.Input<string | undefined>;
  owners?: pulumi.Input<pulumi.Input<string>[] | undefined>;
}

export interface AmiHousekeeperCleanupConfigArgs {
  amiFilters?: pulumi.Input<pulumi.Input<inputs.AmiHousekeeperCleanupConfigAmiFiltersArgs>[] | undefined>;
  dryRun?: pulumi.Input<boolean | undefined>;
  launchTemplateNames?: pulumi.Input<pulumi.Input<string>[] | undefined>;
  maxItems?: pulumi.Input<number | undefined>;
  minimumDaysOld?: pulumi.Input<number | undefined>;
  ssmParameterNames?: pulumi.Input<pulumi.Input<string>[] | undefined>;
}

export interface AmiHousekeeperCleanupConfigAmiFiltersArgs {
  Name?: pulumi.Input<string | undefined>;
  Values?: pulumi.Input<pulumi.Input<string>[] | undefined>;
}

export interface BlockDeviceMappingsArgs {
  delete_on_termination?: pulumi.Input<boolean | undefined>;
  device_name?: pulumi.Input<string | undefined>;
  encrypted?: pulumi.Input<boolean | undefined>;
  iops?: pulumi.Input<number | undefined>;
  kms_key_id?: pulumi.Input<string | undefined>;
  snapshot_id?: pulumi.Input<string | undefined>;
  throughput?: pulumi.Input<number | undefined>;
  volume_initialization_rate?: pulumi.Input<number | undefined>;
  volume_size?: pulumi.Input<number | undefined>;
  volume_type?: pulumi.Input<string | undefined>;
}

export interface EventbridgeArgs {
  accept_events?: pulumi.Input<pulumi.Input<string>[] | undefined>;
  enable?: pulumi.Input<boolean | undefined>;
}

export interface GithubAppArgs {
  id?: pulumi.Input<string | undefined>;
  id_ssm?: pulumi.Input<inputs.GithubAppIdSsmArgs | undefined>;
  key_base64?: pulumi.Input<string | undefined>;
  key_base64_ssm?: pulumi.Input<inputs.GithubAppKeyBase64SsmArgs | undefined>;
  webhook_secret?: pulumi.Input<string | undefined>;
  webhook_secret_ssm?: pulumi.Input<inputs.GithubAppWebhookSecretSsmArgs | undefined>;
}

export interface GithubAppIdSsmArgs {
  arn?: pulumi.Input<string | undefined>;
  name?: pulumi.Input<string | undefined>;
}

export interface GithubAppKeyBase64SsmArgs {
  arn?: pulumi.Input<string | undefined>;
  name?: pulumi.Input<string | undefined>;
}

export interface GithubAppWebhookSecretSsmArgs {
  arn?: pulumi.Input<string | undefined>;
  name?: pulumi.Input<string | undefined>;
}

export interface IamOverridesArgs {
  instance_profile_name?: pulumi.Input<string | undefined>;
  override_instance_profile?: pulumi.Input<boolean | undefined>;
  override_runner_role?: pulumi.Input<boolean | undefined>;
  runner_role_arn?: pulumi.Input<string | undefined>;
}

export interface IdleConfigArgs {
  cron?: pulumi.Input<string | undefined>;
  evictionStrategy?: pulumi.Input<string | undefined>;
  idleCount?: pulumi.Input<number | undefined>;
  timeZone?: pulumi.Input<string | undefined>;
}

export interface InstanceTerminationWatcherArgs {
  enable?: pulumi.Input<boolean | undefined>;
  enable_runner_deregistration?: pulumi.Input<boolean | undefined>;
  features?: pulumi.Input<inputs.InstanceTerminationWatcherFeaturesArgs | undefined>;
  memory_size?: pulumi.Input<number | undefined>;
  s3_key?: pulumi.Input<string | undefined>;
  s3_object_version?: pulumi.Input<string | undefined>;
  timeout?: pulumi.Input<number | undefined>;
  zip?: pulumi.Input<string | undefined>;
}

export interface InstanceTerminationWatcherFeaturesArgs {
  enable_spot_termination_handler?: pulumi.Input<boolean | undefined>;
  enable_spot_termination_notification_watcher?: pulumi.Input<boolean | undefined>;
}

export interface JobRetryArgs {
  delay_backoff?: pulumi.Input<number | undefined>;
  delay_in_seconds?: pulumi.Input<number | undefined>;
  enable?: pulumi.Input<boolean | undefined>;
  lambda_memory_size?: pulumi.Input<number | undefined>;
  lambda_timeout?: pulumi.Input<number | undefined>;
  max_attempts?: pulumi.Input<number | undefined>;
}

export interface LambdaPrincipalsArgs {
  identifiers?: pulumi.Input<pulumi.Input<string>[] | undefined>;
  type?: pulumi.Input<string | undefined>;
}

export interface MetricsArgs {
  enable?: pulumi.Input<boolean | undefined>;
  metric?: pulumi.Input<inputs.MetricsMetricArgs | undefined>;
  namespace?: pulumi.Input<string | undefined>;
}

export interface MetricsMetricArgs {
  enable_github_app_rate_limit?: pulumi.Input<boolean | undefined>;
  enable_job_retry?: pulumi.Input<boolean | undefined>;
  enable_spot_termination_warning?: pulumi.Input<boolean | undefined>;
}

export interface PoolConfigArgs {
  schedule_expression?: pulumi.Input<string | undefined>;
  schedule_expression_timezone?: pulumi.Input<string | undefined>;
  size?: pulumi.Input<number | undefined>;
}

export interface QueueEncryptionArgs {
  kms_data_key_reuse_period_seconds?: pulumi.Input<number | undefined>;
  kms_master_key_id?: pulumi.Input<string | undefined>;
  sqs_managed_sse_enabled?: pulumi.Input<boolean | undefined>;
}

export interface RedriveBuildQueueArgs {
  enabled?: pulumi.Input<boolean | undefined>;
  maxReceiveCount?: pulumi.Input<number | undefined>;
}

export interface RunnerCpuOptionsArgs {
  amd_sev_snp?: pulumi.Input<string | undefined>;
  core_count?: pulumi.Input<number | undefined>;
  nested_virtualization?: pulumi.Input<string | undefined>;
  threads_per_core?: pulumi.Input<number | undefined>;
}

export interface RunnerEgressRulesArgs {
  cidr_blocks?: pulumi.Input<pulumi.Input<string>[] | undefined>;
  description?: pulumi.Input<string | undefined>;
  from_port?: pulumi.Input<number | undefined>;
  ipv6_cidr_blocks?: pulumi.Input<pulumi.Input<string>[] | undefined>;
  prefix_list_ids?: pulumi.Input<pulumi.Input<string>[] | undefined>;
  protocol?: pulumi.Input<string | undefined>;
  security_groups?: pulumi.Input<pulumi.Input<string>[] | undefined>;
  self?: pulumi.Input<boolean | undefined>;
  to_port?: pulumi.Input<number | undefined>;
}

export interface RunnerLicenseSpecificationsArgs {
  license_configuration_arn?: pulumi.Input<string | undefined>;
}

export interface RunnerLogFilesArgs {
  file_path?: pulumi.Input<string | undefined>;
  log_class?: pulumi.Input<string | undefined>;
  log_group_name?: pulumi.Input<string | undefined>;
  log_stream_name?: pulumi.Input<string | undefined>;
  prefix_log_group?: pulumi.Input<boolean | undefined>;
}

export interface RunnerPlacementArgs {
  affinity?: pulumi.Input<string | undefined>;
  availability_zone?: pulumi.Input<string | undefined>;
  group_id?: pulumi.Input<string | undefined>;
  group_name?: pulumi.Input<string | undefined>;
  host_id?: pulumi.Input<string | undefined>;
  host_resource_group_arn?: pulumi.Input<string | undefined>;
  partition_number?: pulumi.Input<number | undefined>;
  spread_domain?: pulumi.Input<string | undefined>;
  tenancy?: pulumi.Input<string | undefined>;
}

export interface RunnersSsmHousekeeperArgs {
  config?: pulumi.Input<inputs.RunnersSsmHousekeeperConfigArgs | undefined>;
  enabled?: pulumi.Input<boolean | undefined>;
  lambda_memory_size?: pulumi.Input<number | undefined>;
  lambda_timeout?: pulumi.Input<number | undefined>;
  schedule_expression?: pulumi.Input<string | undefined>;
}

export interface RunnersSsmHousekeeperConfigArgs {
  dryRun?: pulumi.Input<boolean | undefined>;
  minimumDaysOld?: pulumi.Input<number | undefined>;
  tokenPath?: pulumi.Input<string | undefined>;
}

export interface SsmPathsArgs {
  app?: pulumi.Input<string | undefined>;
  root?: pulumi.Input<string | undefined>;
  runners?: pulumi.Input<string | undefined>;
  use_prefix?: pulumi.Input<boolean | undefined>;
  webhook?: pulumi.Input<string | undefined>;
}

export interface TracingConfigArgs {
  capture_error?: pulumi.Input<boolean | undefined>;
  capture_http_requests?: pulumi.Input<boolean | undefined>;
  mode?: pulumi.Input<string | undefined>;
}

export interface WebhookLambdaApigatewayAccessLogSettingsArgs {
  destination_arn?: pulumi.Input<string | undefined>;
  format?: pulumi.Input<string | undefined>;
}
