/**
 * Vocabulary term-inventory target definition.
 *
 * Generates the shared namespace term inventories
 * (`rdf`/`rdfs`/`skos`/`owl`/`dcterms`/`schema`) in `@beep/rdf` from the
 * `@beep/identity` `CoreVocab` registry, single-sourcing the inventories the
 * CURIE literal types are derived from. Curated named-node constants in the
 * hand-authored Vocab modules stay untouched.
 *
 * @packageDocumentation
 * @since 0.0.0
 */

import { CoreVocab } from "@beep/identity";
import { A, Str } from "@beep/utils";
import { Effect, pipe } from "effect";
import * as R from "effect/Record";
import { formatJson, outputFile } from "../internal/Source.ts";
import { SyncDataTargetMetadata, SyncDataTargetProjection } from "../SyncDataToTs.schemas.ts";
import type { SyncDataTarget } from "../SyncDataToTs.schemas.ts";

const targetId = "vocab-terms" as const;
const outputDir = "packages/foundation/modeling/rdf/src/Vocab/generated" as const;
const canonicalPath = `${outputDir}/vocab-terms.data.json` as const;

const SHARED_PREFIXES = ["rdf", "rdfs", "skos", "owl", "dcterms", "schema"] as const;

type SharedPrefix = (typeof SHARED_PREFIXES)[number];

const moduleNames: Record<SharedPrefix, string> = {
  rdf: "Rdf",
  rdfs: "Rdfs",
  skos: "Skos",
  owl: "Owl",
  dcterms: "Dcterms",
  schema: "SchemaOrg",
};

const displayNames: Record<SharedPrefix, string> = {
  rdf: "RDF",
  rdfs: "RDFS",
  skos: "SKOS",
  owl: "OWL",
  dcterms: "DCMI Terms",
  schema: "Schema.org",
};

const constantPrefixes: Record<SharedPrefix, string> = {
  rdf: "RDF",
  rdfs: "RDFS",
  skos: "SKOS",
  owl: "OWL",
  dcterms: "DCTERMS",
  schema: "SCHEMA_ORG",
};

const sortedTerms = (prefix: SharedPrefix): ReadonlyArray<string> => pipe(CoreVocab[prefix].terms, A.sort(Str.Order));

const renderTermsModule = (prefix: SharedPrefix): string => {
  const moduleName = moduleNames[prefix];
  const display = displayNames[prefix];
  const constant = constantPrefixes[prefix];
  const terms = pipe(
    sortedTerms(prefix),
    A.map((term) => `  "${term}",`),
    A.join("\n")
  );

  return `/**
 * Generated by \`bun run beep sync-data-to-ts --target vocab-terms\`.
 * Source: the \`@beep/identity\` \`CoreVocab\` registry (${prefix} namespace).
 * Do not edit by hand.
 *
 * @packageDocumentation
 * @since 0.0.0
 */

/**
 * ${display} namespace IRI generated from the identity \`CoreVocab\` registry.
 *
 * **Example** (Read the ${display} namespace IRI)
 *
 * \`\`\`ts
 * import { ${constant}_NAMESPACE } from "@beep/rdf/Vocab/generated/${moduleName}.terms"
 *
 * console.log(${constant}_NAMESPACE.length > 0) // true
 * \`\`\`
 *
 * @category constants
 * @since 0.0.0
 */
export const ${constant}_NAMESPACE = "${CoreVocab[prefix].iri}" as const;

/**
 * ${display} local-name inventory generated from the identity \`CoreVocab\` registry.
 *
 * **Example** (Read the ${display} term inventory)
 *
 * \`\`\`ts
 * import { ${constant}_TERMS } from "@beep/rdf/Vocab/generated/${moduleName}.terms"
 *
 * console.log(${constant}_TERMS.length > 0) // true
 * \`\`\`
 *
 * @category constants
 * @since 0.0.0
 */
// fallow-ignore-next-line code-duplication -- generated mirror of the identity CoreVocab registry
export const ${constant}_TERMS = [
${terms}
] as const;
`;
};

const canonicalDocument = (): Record<string, { readonly iri: string; readonly terms: ReadonlyArray<string> }> =>
  pipe(
    SHARED_PREFIXES,
    A.map((prefix) => [prefix, { iri: CoreVocab[prefix].iri, terms: sortedTerms(prefix) }] as const),
    R.fromEntries
  );

/**
 * Vocabulary term-inventory sync target.
 *
 * **Example** (Inspect the vocab-terms sync target)
 *
 * ```ts
 * import { vocabTermsTarget } from "@beep/repo-cli/commands/SyncDataToTs"
 * console.log(vocabTermsTarget.id) // "vocab-terms"
 * ```
 *
 * @category configuration
 * @since 0.0.0
 */
export const vocabTermsTarget: SyncDataTarget = {
  ...SyncDataTargetMetadata.make({
    id: targetId,
    description:
      "Shared vocabulary term inventories in @beep/rdf generated from the @beep/identity CoreVocab registry.",
    access: "public",
    sourceUrls: [],
  }),
  acquire: Effect.sync(() => {
    const canonical = canonicalDocument();
    const files = pipe(
      SHARED_PREFIXES,
      A.map((prefix) => outputFile(`${outputDir}/${moduleNames[prefix]}.terms.ts`, renderTermsModule(prefix)))
    );
    const recordCount = pipe(
      SHARED_PREFIXES,
      A.map((prefix) => A.length(CoreVocab[prefix].terms)),
      A.reduce(0, (total, count) => total + count)
    );

    return SyncDataTargetProjection.make({
      files: [...files, outputFile(canonicalPath, `${formatJson(canonical)}\n`)],
      canonicalPath,
      canonical,
      recordCount,
      summary: `vocab-terms: ${recordCount} terms across ${A.length(SHARED_PREFIXES)} namespaces from CoreVocab`,
      sources: [],
    });
  }),
};
