// @effect-diagnostics nodeBuiltinImport:skip-file
import * as Console from "effect/Console";
import * as DateTime from "effect/DateTime";
import * as Effect from "effect/Effect";
import * as S from "effect/Schema";
import { FetchHttpClient } from "effect/http";
import { writeFileSync } from "node:fs";
import { resolve } from "node:path";

const SOURCE = "https://html.spec.whatwg.org/entities.json";

/** The document's shape: `&name;` keys, each with its replacement string. */
const EntitiesDocument = S.Record(S.String, S.Struct({ characters: S.String }));

const response = await Effect.runSync(Effect.service(FetchHttpClient.Fetch))(SOURCE);
if (!response.ok) {
	throw new Error(`${SOURCE}: ${response.status} ${response.statusText}`);
}
const rawDocument: unknown = await response.json();
const document = await Effect.runPromise(S.decodeUnknownEffect(EntitiesDocument)(rawDocument));

const entries = Object.entries(document)
	.filter(([name]) => name.endsWith(";"))
	.map(([name, { characters }]) => [name.slice(1, -1), characters] as const)
	.sort(([a], [b]) => (a < b ? -1 : a > b ? 1 : 0));

const fetchedOn = DateTime.now.pipe(Effect.runSync, DateTime.formatIsoDateUtc);

const header = `// Generated by __test__/tools/generate-entities.ts — do not edit by hand.
//
// The HTML5 named character references, from the WHATWG HTML standard's
// entity document (${SOURCE}, fetched ${fetchedOn});
// the human-readable table is at
// https://html.spec.whatwg.org/multipage/named-characters.html.
//
// Only the semicolon-terminated names are here: CommonMark's entity grammar
// requires the semicolon, so the legacy unterminated forms cannot match.
//
// Stored as JSON and parsed once at module load — a ${entries.length}-entry
// Map literal costs several times this in source size, and the parse is a
// one-off. Leaf module: imports only Effect codecs.

import * as Result from "effect/Result";
import * as S from "effect/Schema";

const DATA = ${JSON.stringify(JSON.stringify(entries))};

const decodeEntities = S.Tuple([S.String, S.String]).pipe(S.Array, S.fromJsonString, S.decodeResult);

/** The HTML5 named character references, keyed without \`&\` or \`;\`. */
export const ENTITY_MAP: ReadonlyMap<string, string> = new Map(Result.getOrThrow(decodeEntities(DATA)));
`;

const target = resolve(import.meta.dirname, "../../src/internal/entityMap.ts");
writeFileSync(target, header);
Effect.runSync(Console.log(`wrote ${entries.length} entities to ${target}`));
