/**
 * Generated from the checked-in GovInfo OpenAPI document.
 *
 * This package-private module is a drift oracle for the hand-written GovInfo
 * contracts. Do not import it from package source or edit it by hand.
 *
 * @packageDocumentation
 * @since 0.0.0
 */

import * as Schema from "effect/Schema"
import { HttpApi, HttpApiEndpoint, HttpApiGroup, HttpApiMiddleware, HttpApiSchema, HttpApiSecurity, OpenApi } from "effect/unstable/httpapi"
// non-recursive definitions
export type SearchRequest = { readonly "query"?: string, readonly "pageSize"?: number, readonly "offsetMark"?: string, readonly "sorts"?: ReadonlyArray<{ readonly "field"?: string, readonly "sortOrder"?: "ASC" | "DESC" }>, readonly "historical"?: boolean, readonly "resultLevel"?: string }
export const SearchRequest = Schema.Struct({ "query": Schema.optionalKey(Schema.String), "pageSize": Schema.optionalKey(Schema.Int.annotate({ "format": "int32" })), "offsetMark": Schema.optionalKey(Schema.String), "sorts": Schema.Array(Schema.Struct({ "field": Schema.optionalKey(Schema.String), "sortOrder": Schema.optionalKey(Schema.Literals(["ASC", "DESC"])) })).pipe(Schema.optionalKey), "historical": Schema.optionalKey(Schema.Boolean), "resultLevel": Schema.optionalKey(Schema.String) }).annotate({ "identifier": "SearchRequest" })
export type SearchResponse = { readonly "results"?: ReadonlyArray<{ readonly "title"?: string, readonly "packageId"?: string, readonly "granuleId"?: string, readonly "lastModified"?: string, readonly "governmentAuthor"?: ReadonlyArray<string>, readonly "dateIssued"?: string, readonly "collectionCode"?: string, readonly "resultLink"?: string, readonly "dateIngested"?: string, readonly "download"?: { readonly [x: string]: string }, readonly "relatedLink"?: string }>, readonly "offsetMark"?: string, readonly "count"?: number }
export const SearchResponse = Schema.Struct({ "results": Schema.Array(Schema.Struct({ "title": Schema.optionalKey(Schema.String), "packageId": Schema.optionalKey(Schema.String), "granuleId": Schema.optionalKey(Schema.String), "lastModified": Schema.optionalKey(Schema.String), "governmentAuthor": Schema.String.pipe(Schema.Array, Schema.optionalKey), "dateIssued": Schema.optionalKey(Schema.String), "collectionCode": Schema.optionalKey(Schema.String), "resultLink": Schema.optionalKey(Schema.String), "dateIngested": Schema.optionalKey(Schema.String), "download": Schema.Record(Schema.String, Schema.String).pipe(Schema.optionalKey), "relatedLink": Schema.optionalKey(Schema.String) })).pipe(Schema.optionalKey), "offsetMark": Schema.optionalKey(Schema.String), "count": Schema.optionalKey(Schema.Int.annotate({ "format": "int32" })) }).annotate({ "identifier": "SearchResponse" })
export type CollectionContainer = { readonly "count"?: number, readonly "message"?: string, readonly "nextPage"?: string, readonly "previousPage"?: string, readonly "packages"?: ReadonlyArray<{ readonly "packageId"?: string, readonly "lastModified"?: string, readonly "packageLink"?: string, readonly "docClass"?: string, readonly "title"?: string, readonly "congress"?: string, readonly "dateIssued"?: string }> }
export const CollectionContainer = Schema.Struct({ "count": Schema.optionalKey(Schema.Int.annotate({ "format": "int64" })), "message": Schema.optionalKey(Schema.String), "nextPage": Schema.optionalKey(Schema.String), "previousPage": Schema.optionalKey(Schema.String), "packages": Schema.Array(Schema.Struct({ "packageId": Schema.optionalKey(Schema.String), "lastModified": Schema.optionalKey(Schema.String), "packageLink": Schema.optionalKey(Schema.String), "docClass": Schema.optionalKey(Schema.String), "title": Schema.optionalKey(Schema.String), "congress": Schema.optionalKey(Schema.String), "dateIssued": Schema.optionalKey(Schema.String) })).pipe(Schema.optionalKey) }).annotate({ "identifier": "CollectionContainer" })
export type GranuleContainer = { readonly "count"?: number, readonly "offset"?: number, readonly "pageSize"?: number, readonly "nextPage"?: string, readonly "previousPage"?: string, readonly "granules"?: ReadonlyArray<{ readonly "title"?: string, readonly "granuleId"?: string, readonly "granuleLink"?: string, readonly "dateIssued"?: string, readonly "granuleClass"?: string, readonly "md5"?: string }>, readonly "message"?: string }
export const GranuleContainer = Schema.Struct({ "count": Schema.optionalKey(Schema.Int.annotate({ "format": "int32" })), "offset": Schema.optionalKey(Schema.Int.annotate({ "format": "int32" })), "pageSize": Schema.optionalKey(Schema.Int.annotate({ "format": "int32" })), "nextPage": Schema.optionalKey(Schema.String), "previousPage": Schema.optionalKey(Schema.String), "granules": Schema.Array(Schema.Struct({ "title": Schema.optionalKey(Schema.String), "granuleId": Schema.optionalKey(Schema.String), "granuleLink": Schema.optionalKey(Schema.String), "dateIssued": Schema.optionalKey(Schema.String), "granuleClass": Schema.optionalKey(Schema.String), "md5": Schema.optionalKey(Schema.String) })).pipe(Schema.optionalKey), "message": Schema.optionalKey(Schema.String) }).annotate({ "identifier": "GranuleContainer" })
export type CollectionSummary = { readonly "collections"?: ReadonlyArray<{ readonly "collectionCode"?: string, readonly "collectionName"?: string, readonly "packageCount"?: number, readonly "granuleCount"?: number }> }
export const CollectionSummary = Schema.Struct({ "collections": Schema.Array(Schema.Struct({ "collectionCode": Schema.optionalKey(Schema.String), "collectionName": Schema.optionalKey(Schema.String), "packageCount": Schema.optionalKey(Schema.Int.annotate({ "format": "int64" })), "granuleCount": Schema.optionalKey(Schema.Int.annotate({ "format": "int64" })) })).pipe(Schema.optionalKey) }).annotate({ "identifier": "CollectionSummary" })
// schemas
export type SearchRequestJson = SearchRequest
export const SearchRequestJson = SearchRequest
export type Search200 = SearchResponse
export const Search200 = SearchResponse
export type RelatedPackageDetailsPathParams = { readonly "accessId": string }
export const RelatedPackageDetailsPathParams = Schema.Struct({ "accessId": Schema.String })
export type RelatedVersionsDetailsParams = { readonly "granuleClass"?: string, readonly "subGranuleClass"?: string }
export const RelatedVersionsDetailsParams = Schema.Struct({ "granuleClass": Schema.optionalKey(Schema.String), "subGranuleClass": Schema.optionalKey(Schema.String) })
export type RelatedVersionsDetailsPathParams = { readonly "accessId": string, readonly "collection": "BILLS" | "CPD" | "DPCD" | "CPRT" | "CRPT" | "FR" | "HOB" | "PLAW" | "STATUTE" | "USCODE" | "CMR" }
export const RelatedVersionsDetailsPathParams = Schema.Struct({ "accessId": Schema.String, "collection": Schema.Literals(["BILLS", "CPD", "DPCD", "CPRT", "CRPT", "FR", "HOB", "PLAW", "STATUTE", "USCODE", "CMR"]) })
export type RelatedVersionsDetailsQuery = { readonly "granuleClass"?: string, readonly "subGranuleClass"?: string }
export const RelatedVersionsDetailsQuery = Schema.Struct({ "granuleClass": Schema.optionalKey(Schema.String), "subGranuleClass": Schema.optionalKey(Schema.String) })
export type GetPackagesByDateIssuedParams = { readonly "offsetMark"?: string, readonly "offset"?: number, readonly "pageSize": number, readonly "collection": string, readonly "congress"?: string, readonly "docClass"?: string, readonly "billVersion"?: "as" | "ash" | "ath" | "ats" | "cdh" | "cds" | "cph" | "cps" | "eah" | "eas" | "eh" | "enr" | "eph" | "es" | "fah" | "fph" | "fps" | "hdh" | "hds" | "ih" | "iph" | "ips" | "is" | "lth" | "lts" | "nat" | "oph" | "ops" | "pap" | "pav" | "pch" | "pcs" | "pp" | "pwah" | "rah" | "ras" | "rch" | "rcs" | "rdh" | "rds" | "re" | "reah" | "renr" | "res" | "rfh" | "rfs" | "rft" | "rh" | "rhuc" | "rih" | "ris" | "rs" | "rth" | "rts" | "s_p" | "sas" | "sc" | "mostrecent", readonly "modifiedSince"?: string, readonly "courtCode"?: string, readonly "courtType"?: string, readonly "state"?: string, readonly "topic"?: string, readonly "isGLP"?: boolean, readonly "natureSuitCode"?: string, readonly "natureSuit"?: string }
export const GetPackagesByDateIssuedParams = Schema.Struct({ "offsetMark": Schema.optionalKey(Schema.String), "offset": Schema.optionalKey(Schema.Int), "pageSize": Schema.Int.check(Schema.isLessThanOrEqualTo(1000).annotate({ "expected": "a value less than or equal to 1000" })), "collection": Schema.String, "congress": Schema.optionalKey(Schema.String), "docClass": Schema.optionalKey(Schema.String), "billVersion": Schema.optionalKey(Schema.Literals(["as", "ash", "ath", "ats", "cdh", "cds", "cph", "cps", "eah", "eas", "eh", "enr", "eph", "es", "fah", "fph", "fps", "hdh", "hds", "ih", "iph", "ips", "is", "lth", "lts", "nat", "oph", "ops", "pap", "pav", "pch", "pcs", "pp", "pwah", "rah", "ras", "rch", "rcs", "rdh", "rds", "re", "reah", "renr", "res", "rfh", "rfs", "rft", "rh", "rhuc", "rih", "ris", "rs", "rth", "rts", "s_p", "sas", "sc", "mostrecent"])), "modifiedSince": Schema.optionalKey(Schema.String), "courtCode": Schema.optionalKey(Schema.String.check(Schema.isPattern(new RegExp("(?:AL|AK|AS|AZ|AR|CA|CO|CT|DE|DC|FL|GA|GU|HI|ID|IL|IN|IA|KS|KY|LA|ME|MD|MA|MI|MN|MS|MO|MT|NE|NV|NH|NJ|NM|NY|NC|ND|MP|OH|OK|OR|PA|PR|RI|SC|SD|TN|TX|UT|VT|VA|VI|WA|WV|WI|WY)[n|e|w|s]?[d|b|a]|(cofc|jpml)")).annotate({ "expected": "a string matching the RegExp (?:AL|AK|AS|AZ|AR|CA|CO|CT|DE|DC|FL|GA|GU|HI|ID|IL|IN|IA|KS|KY|LA|ME|MD|MA|MI|MN|MS|MO|MT|NE|NV|NH|NJ|NM|NY|NC|ND|MP|OH|OK|OR|PA|PR|RI|SC|SD|TN|TX|UT|VT|VA|VI|WA|WV|WI|WY)[n|e|w|s]?[d|b|a]|(cofc|jpml)" }))), "courtType": Schema.optionalKey(Schema.String.check(Schema.isPattern(new RegExp("District|Bankruptcy|Appellate|National")).annotate({ "expected": "a string matching the RegExp District|Bankruptcy|Appellate|National" }))), "state": Schema.optionalKey(Schema.String.check(Schema.isPattern(new RegExp("AL|AK|AS|AZ|AR|CA|CO|CT|DE|DC|FL|GA|GU|HI|ID|IL|IN|IA|KS|KY|LA|ME|MD|MA|MI|MN|MS|MO|MT|NE|NV|NH|NJ|NM|NY|NC|ND|MP|OH|OK|OR|PA|PR|RI|SC|SD|TN|TX|UT|VT|VA|VI|WA|WV|WI|WY")).annotate({ "expected": "a string matching the RegExp AL|AK|AS|AZ|AR|CA|CO|CT|DE|DC|FL|GA|GU|HI|ID|IL|IN|IA|KS|KY|LA|ME|MD|MA|MI|MN|MS|MO|MT|NE|NV|NH|NJ|NM|NY|NC|ND|MP|OH|OK|OR|PA|PR|RI|SC|SD|TN|TX|UT|VT|VA|VI|WA|WV|WI|WY" }))), "topic": Schema.optionalKey(Schema.String), "isGLP": Schema.optionalKey(Schema.Boolean), "natureSuitCode": Schema.optionalKey(Schema.String), "natureSuit": Schema.optionalKey(Schema.String) })
export type GetPackagesByDateIssuedPathParams = { readonly "dateIssuedStartDate": string }
export const GetPackagesByDateIssuedPathParams = Schema.Struct({ "dateIssuedStartDate": Schema.String.check(Schema.isPattern(new RegExp("\\d{4}-\\d{1,2}-\\d{1,2}")).annotate({ "expected": "a string matching the RegExp \\d{4}-\\d{1,2}-\\d{1,2}" })) })
export type GetPackagesByDateIssuedQuery = { readonly "offsetMark"?: string, readonly "offset"?: number, readonly "pageSize": number, readonly "collection": string, readonly "congress"?: string, readonly "docClass"?: string, readonly "billVersion"?: "as" | "ash" | "ath" | "ats" | "cdh" | "cds" | "cph" | "cps" | "eah" | "eas" | "eh" | "enr" | "eph" | "es" | "fah" | "fph" | "fps" | "hdh" | "hds" | "ih" | "iph" | "ips" | "is" | "lth" | "lts" | "nat" | "oph" | "ops" | "pap" | "pav" | "pch" | "pcs" | "pp" | "pwah" | "rah" | "ras" | "rch" | "rcs" | "rdh" | "rds" | "re" | "reah" | "renr" | "res" | "rfh" | "rfs" | "rft" | "rh" | "rhuc" | "rih" | "ris" | "rs" | "rth" | "rts" | "s_p" | "sas" | "sc" | "mostrecent", readonly "modifiedSince"?: string, readonly "courtCode"?: string, readonly "courtType"?: string, readonly "state"?: string, readonly "topic"?: string, readonly "isGLP"?: boolean, readonly "natureSuitCode"?: string, readonly "natureSuit"?: string }
export const GetPackagesByDateIssuedQuery = Schema.Struct({ "offsetMark": Schema.optionalKey(Schema.String), "offset": Schema.optionalKey(Schema.Int), "pageSize": Schema.Int.check(Schema.isLessThanOrEqualTo(1000).annotate({ "expected": "a value less than or equal to 1000" })), "collection": Schema.String, "congress": Schema.optionalKey(Schema.String), "docClass": Schema.optionalKey(Schema.String), "billVersion": Schema.optionalKey(Schema.Literals(["as", "ash", "ath", "ats", "cdh", "cds", "cph", "cps", "eah", "eas", "eh", "enr", "eph", "es", "fah", "fph", "fps", "hdh", "hds", "ih", "iph", "ips", "is", "lth", "lts", "nat", "oph", "ops", "pap", "pav", "pch", "pcs", "pp", "pwah", "rah", "ras", "rch", "rcs", "rdh", "rds", "re", "reah", "renr", "res", "rfh", "rfs", "rft", "rh", "rhuc", "rih", "ris", "rs", "rth", "rts", "s_p", "sas", "sc", "mostrecent"])), "modifiedSince": Schema.optionalKey(Schema.String), "courtCode": Schema.optionalKey(Schema.String.check(Schema.isPattern(new RegExp("(?:AL|AK|AS|AZ|AR|CA|CO|CT|DE|DC|FL|GA|GU|HI|ID|IL|IN|IA|KS|KY|LA|ME|MD|MA|MI|MN|MS|MO|MT|NE|NV|NH|NJ|NM|NY|NC|ND|MP|OH|OK|OR|PA|PR|RI|SC|SD|TN|TX|UT|VT|VA|VI|WA|WV|WI|WY)[n|e|w|s]?[d|b|a]|(cofc|jpml)")).annotate({ "expected": "a string matching the RegExp (?:AL|AK|AS|AZ|AR|CA|CO|CT|DE|DC|FL|GA|GU|HI|ID|IL|IN|IA|KS|KY|LA|ME|MD|MA|MI|MN|MS|MO|MT|NE|NV|NH|NJ|NM|NY|NC|ND|MP|OH|OK|OR|PA|PR|RI|SC|SD|TN|TX|UT|VT|VA|VI|WA|WV|WI|WY)[n|e|w|s]?[d|b|a]|(cofc|jpml)" }))), "courtType": Schema.optionalKey(Schema.String.check(Schema.isPattern(new RegExp("District|Bankruptcy|Appellate|National")).annotate({ "expected": "a string matching the RegExp District|Bankruptcy|Appellate|National" }))), "state": Schema.optionalKey(Schema.String.check(Schema.isPattern(new RegExp("AL|AK|AS|AZ|AR|CA|CO|CT|DE|DC|FL|GA|GU|HI|ID|IL|IN|IA|KS|KY|LA|ME|MD|MA|MI|MN|MS|MO|MT|NE|NV|NH|NJ|NM|NY|NC|ND|MP|OH|OK|OR|PA|PR|RI|SC|SD|TN|TX|UT|VT|VA|VI|WA|WV|WI|WY")).annotate({ "expected": "a string matching the RegExp AL|AK|AS|AZ|AR|CA|CO|CT|DE|DC|FL|GA|GU|HI|ID|IL|IN|IA|KS|KY|LA|ME|MD|MA|MI|MN|MS|MO|MT|NE|NV|NH|NJ|NM|NY|NC|ND|MP|OH|OK|OR|PA|PR|RI|SC|SD|TN|TX|UT|VT|VA|VI|WA|WV|WI|WY" }))), "topic": Schema.optionalKey(Schema.String), "isGLP": Schema.optionalKey(Schema.Boolean), "natureSuitCode": Schema.optionalKey(Schema.String), "natureSuit": Schema.optionalKey(Schema.String) })
export type GetPackagesByDateIssued200 = CollectionContainer
export const GetPackagesByDateIssued200 = CollectionContainer
export type GetPackagesByDateIssued1Params = { readonly "offsetMark"?: string, readonly "offset"?: number, readonly "pageSize": number, readonly "collection": string, readonly "congress"?: string, readonly "docClass"?: string, readonly "billVersion"?: "as" | "ash" | "ath" | "ats" | "cdh" | "cds" | "cph" | "cps" | "eah" | "eas" | "eh" | "enr" | "eph" | "es" | "fah" | "fph" | "fps" | "hdh" | "hds" | "ih" | "iph" | "ips" | "is" | "lth" | "lts" | "nat" | "oph" | "ops" | "pap" | "pav" | "pch" | "pcs" | "pp" | "pwah" | "rah" | "ras" | "rch" | "rcs" | "rdh" | "rds" | "re" | "reah" | "renr" | "res" | "rfh" | "rfs" | "rft" | "rh" | "rhuc" | "rih" | "ris" | "rs" | "rth" | "rts" | "s_p" | "sas" | "sc" | "mostrecent", readonly "modifiedSince"?: string, readonly "courtCode"?: string, readonly "courtType"?: string, readonly "state"?: string, readonly "topic"?: string, readonly "natureSuitCode"?: string, readonly "natureSuit"?: string, readonly "isGLP"?: boolean }
export const GetPackagesByDateIssued1Params = Schema.Struct({ "offsetMark": Schema.optionalKey(Schema.String), "offset": Schema.optionalKey(Schema.Int), "pageSize": Schema.Int.check(Schema.isLessThanOrEqualTo(1000).annotate({ "expected": "a value less than or equal to 1000" })), "collection": Schema.String, "congress": Schema.optionalKey(Schema.String), "docClass": Schema.optionalKey(Schema.String), "billVersion": Schema.optionalKey(Schema.Literals(["as", "ash", "ath", "ats", "cdh", "cds", "cph", "cps", "eah", "eas", "eh", "enr", "eph", "es", "fah", "fph", "fps", "hdh", "hds", "ih", "iph", "ips", "is", "lth", "lts", "nat", "oph", "ops", "pap", "pav", "pch", "pcs", "pp", "pwah", "rah", "ras", "rch", "rcs", "rdh", "rds", "re", "reah", "renr", "res", "rfh", "rfs", "rft", "rh", "rhuc", "rih", "ris", "rs", "rth", "rts", "s_p", "sas", "sc", "mostrecent"])), "modifiedSince": Schema.optionalKey(Schema.String), "courtCode": Schema.optionalKey(Schema.String.check(Schema.isPattern(new RegExp("(?:AL|AK|AS|AZ|AR|CA|CO|CT|DE|DC|FL|GA|GU|HI|ID|IL|IN|IA|KS|KY|LA|ME|MD|MA|MI|MN|MS|MO|MT|NE|NV|NH|NJ|NM|NY|NC|ND|MP|OH|OK|OR|PA|PR|RI|SC|SD|TN|TX|UT|VT|VA|VI|WA|WV|WI|WY)[n|e|w|s]?[d|b|a]|(cofc|jpml)")).annotate({ "expected": "a string matching the RegExp (?:AL|AK|AS|AZ|AR|CA|CO|CT|DE|DC|FL|GA|GU|HI|ID|IL|IN|IA|KS|KY|LA|ME|MD|MA|MI|MN|MS|MO|MT|NE|NV|NH|NJ|NM|NY|NC|ND|MP|OH|OK|OR|PA|PR|RI|SC|SD|TN|TX|UT|VT|VA|VI|WA|WV|WI|WY)[n|e|w|s]?[d|b|a]|(cofc|jpml)" }))), "courtType": Schema.optionalKey(Schema.String.check(Schema.isPattern(new RegExp("District|Bankruptcy|Appellate|National")).annotate({ "expected": "a string matching the RegExp District|Bankruptcy|Appellate|National" }))), "state": Schema.optionalKey(Schema.String.check(Schema.isPattern(new RegExp("AL|AK|AS|AZ|AR|CA|CO|CT|DE|DC|FL|GA|GU|HI|ID|IL|IN|IA|KS|KY|LA|ME|MD|MA|MI|MN|MS|MO|MT|NE|NV|NH|NJ|NM|NY|NC|ND|MP|OH|OK|OR|PA|PR|RI|SC|SD|TN|TX|UT|VT|VA|VI|WA|WV|WI|WY")).annotate({ "expected": "a string matching the RegExp AL|AK|AS|AZ|AR|CA|CO|CT|DE|DC|FL|GA|GU|HI|ID|IL|IN|IA|KS|KY|LA|ME|MD|MA|MI|MN|MS|MO|MT|NE|NV|NH|NJ|NM|NY|NC|ND|MP|OH|OK|OR|PA|PR|RI|SC|SD|TN|TX|UT|VT|VA|VI|WA|WV|WI|WY" }))), "topic": Schema.optionalKey(Schema.String), "natureSuitCode": Schema.optionalKey(Schema.String), "natureSuit": Schema.optionalKey(Schema.String), "isGLP": Schema.optionalKey(Schema.Boolean) })
export type GetPackagesByDateIssued1PathParams = { readonly "dateIssuedStartDate": string, readonly "dateIssuedEndDate": string }
export const GetPackagesByDateIssued1PathParams = Schema.Struct({ "dateIssuedStartDate": Schema.String.check(Schema.isPattern(new RegExp("\\d{4}-\\d{1,2}-\\d{1,2}")).annotate({ "expected": "a string matching the RegExp \\d{4}-\\d{1,2}-\\d{1,2}" })), "dateIssuedEndDate": Schema.String.check(Schema.isPattern(new RegExp("\\d{4}-\\d{1,2}-\\d{1,2}")).annotate({ "expected": "a string matching the RegExp \\d{4}-\\d{1,2}-\\d{1,2}" })) })
export type GetPackagesByDateIssued1Query = { readonly "offsetMark"?: string, readonly "offset"?: number, readonly "pageSize": number, readonly "collection": string, readonly "congress"?: string, readonly "docClass"?: string, readonly "billVersion"?: "as" | "ash" | "ath" | "ats" | "cdh" | "cds" | "cph" | "cps" | "eah" | "eas" | "eh" | "enr" | "eph" | "es" | "fah" | "fph" | "fps" | "hdh" | "hds" | "ih" | "iph" | "ips" | "is" | "lth" | "lts" | "nat" | "oph" | "ops" | "pap" | "pav" | "pch" | "pcs" | "pp" | "pwah" | "rah" | "ras" | "rch" | "rcs" | "rdh" | "rds" | "re" | "reah" | "renr" | "res" | "rfh" | "rfs" | "rft" | "rh" | "rhuc" | "rih" | "ris" | "rs" | "rth" | "rts" | "s_p" | "sas" | "sc" | "mostrecent", readonly "modifiedSince"?: string, readonly "courtCode"?: string, readonly "courtType"?: string, readonly "state"?: string, readonly "topic"?: string, readonly "natureSuitCode"?: string, readonly "natureSuit"?: string, readonly "isGLP"?: boolean }
export const GetPackagesByDateIssued1Query = Schema.Struct({ "offsetMark": Schema.optionalKey(Schema.String), "offset": Schema.optionalKey(Schema.Int), "pageSize": Schema.Int.check(Schema.isLessThanOrEqualTo(1000).annotate({ "expected": "a value less than or equal to 1000" })), "collection": Schema.String, "congress": Schema.optionalKey(Schema.String), "docClass": Schema.optionalKey(Schema.String), "billVersion": Schema.optionalKey(Schema.Literals(["as", "ash", "ath", "ats", "cdh", "cds", "cph", "cps", "eah", "eas", "eh", "enr", "eph", "es", "fah", "fph", "fps", "hdh", "hds", "ih", "iph", "ips", "is", "lth", "lts", "nat", "oph", "ops", "pap", "pav", "pch", "pcs", "pp", "pwah", "rah", "ras", "rch", "rcs", "rdh", "rds", "re", "reah", "renr", "res", "rfh", "rfs", "rft", "rh", "rhuc", "rih", "ris", "rs", "rth", "rts", "s_p", "sas", "sc", "mostrecent"])), "modifiedSince": Schema.optionalKey(Schema.String), "courtCode": Schema.optionalKey(Schema.String.check(Schema.isPattern(new RegExp("(?:AL|AK|AS|AZ|AR|CA|CO|CT|DE|DC|FL|GA|GU|HI|ID|IL|IN|IA|KS|KY|LA|ME|MD|MA|MI|MN|MS|MO|MT|NE|NV|NH|NJ|NM|NY|NC|ND|MP|OH|OK|OR|PA|PR|RI|SC|SD|TN|TX|UT|VT|VA|VI|WA|WV|WI|WY)[n|e|w|s]?[d|b|a]|(cofc|jpml)")).annotate({ "expected": "a string matching the RegExp (?:AL|AK|AS|AZ|AR|CA|CO|CT|DE|DC|FL|GA|GU|HI|ID|IL|IN|IA|KS|KY|LA|ME|MD|MA|MI|MN|MS|MO|MT|NE|NV|NH|NJ|NM|NY|NC|ND|MP|OH|OK|OR|PA|PR|RI|SC|SD|TN|TX|UT|VT|VA|VI|WA|WV|WI|WY)[n|e|w|s]?[d|b|a]|(cofc|jpml)" }))), "courtType": Schema.optionalKey(Schema.String.check(Schema.isPattern(new RegExp("District|Bankruptcy|Appellate|National")).annotate({ "expected": "a string matching the RegExp District|Bankruptcy|Appellate|National" }))), "state": Schema.optionalKey(Schema.String.check(Schema.isPattern(new RegExp("AL|AK|AS|AZ|AR|CA|CO|CT|DE|DC|FL|GA|GU|HI|ID|IL|IN|IA|KS|KY|LA|ME|MD|MA|MI|MN|MS|MO|MT|NE|NV|NH|NJ|NM|NY|NC|ND|MP|OH|OK|OR|PA|PR|RI|SC|SD|TN|TX|UT|VT|VA|VI|WA|WV|WI|WY")).annotate({ "expected": "a string matching the RegExp AL|AK|AS|AZ|AR|CA|CO|CT|DE|DC|FL|GA|GU|HI|ID|IL|IN|IA|KS|KY|LA|ME|MD|MA|MI|MN|MS|MO|MT|NE|NV|NH|NJ|NM|NY|NC|ND|MP|OH|OK|OR|PA|PR|RI|SC|SD|TN|TX|UT|VT|VA|VI|WA|WV|WI|WY" }))), "topic": Schema.optionalKey(Schema.String), "natureSuitCode": Schema.optionalKey(Schema.String), "natureSuit": Schema.optionalKey(Schema.String), "isGLP": Schema.optionalKey(Schema.Boolean) })
export type GetPackagesByDateIssued1200 = CollectionContainer
export const GetPackagesByDateIssued1200 = CollectionContainer
export type PackageDetailsPathParams = { readonly "packageId": string }
export const PackageDetailsPathParams = Schema.Struct({ "packageId": Schema.String })
export type GetGranulesForPackageParams = { readonly "offsetMark"?: string, readonly "offset"?: number, readonly "pageSize": number, readonly "md5"?: string, readonly "granuleClass"?: string }
export const GetGranulesForPackageParams = Schema.Struct({ "offsetMark": Schema.optionalKey(Schema.String), "offset": Schema.optionalKey(Schema.Int), "pageSize": Schema.Int.check(Schema.isLessThanOrEqualTo(1000).annotate({ "expected": "a value less than or equal to 1000" })), "md5": Schema.optionalKey(Schema.String), "granuleClass": Schema.optionalKey(Schema.String) })
export type GetGranulesForPackagePathParams = { readonly "packageId": string }
export const GetGranulesForPackagePathParams = Schema.Struct({ "packageId": Schema.String })
export type GetGranulesForPackageQuery = { readonly "offsetMark"?: string, readonly "offset"?: number, readonly "pageSize": number, readonly "md5"?: string, readonly "granuleClass"?: string }
export const GetGranulesForPackageQuery = Schema.Struct({ "offsetMark": Schema.optionalKey(Schema.String), "offset": Schema.optionalKey(Schema.Int), "pageSize": Schema.Int.check(Schema.isLessThanOrEqualTo(1000).annotate({ "expected": "a value less than or equal to 1000" })), "md5": Schema.optionalKey(Schema.String), "granuleClass": Schema.optionalKey(Schema.String) })
export type GetGranulesForPackage200 = GranuleContainer
export const GetGranulesForPackage200 = GranuleContainer
export type GetGranuleContentDetailPathParams = { readonly "packageId": string, readonly "granuleId": string }
export const GetGranuleContentDetailPathParams = Schema.Struct({ "packageId": Schema.String, "granuleId": Schema.String })
export type GetGranuleContentDetail200 = string
export const GetGranuleContentDetail200 = Schema.String
export type GetCollectionSummary200 = CollectionSummary
export const GetCollectionSummary200 = CollectionSummary
export type GetModifiedCollectionsParams = { readonly "offsetMark"?: string, readonly "offset"?: number, readonly "pageSize": number, readonly "congress"?: number, readonly "docClass"?: string, readonly "billVersion"?: "as" | "ash" | "ath" | "ats" | "cdh" | "cds" | "cph" | "cps" | "eah" | "eas" | "eh" | "enr" | "eph" | "es" | "fah" | "fph" | "fps" | "hdh" | "hds" | "ih" | "iph" | "ips" | "is" | "lth" | "lts" | "nat" | "oph" | "ops" | "pap" | "pav" | "pch" | "pcs" | "pp" | "pwah" | "rah" | "ras" | "rch" | "rcs" | "rdh" | "rds" | "re" | "reah" | "renr" | "res" | "rfh" | "rfs" | "rft" | "rh" | "rhuc" | "rih" | "ris" | "rs" | "rth" | "rts" | "s_p" | "sas" | "sc" | "mostrecent", readonly "courtCode"?: string, readonly "courtType"?: string, readonly "state"?: string, readonly "topic"?: string, readonly "isGLP"?: boolean, readonly "natureSuitCode"?: string, readonly "natureSuit"?: string }
export const GetModifiedCollectionsParams = Schema.Struct({ "offsetMark": Schema.optionalKey(Schema.String), "offset": Schema.optionalKey(Schema.Int), "pageSize": Schema.Int.check(Schema.isLessThanOrEqualTo(1000).annotate({ "expected": "a value less than or equal to 1000" })), "congress": Schema.optionalKey(Schema.Int), "docClass": Schema.optionalKey(Schema.String), "billVersion": Schema.optionalKey(Schema.Literals(["as", "ash", "ath", "ats", "cdh", "cds", "cph", "cps", "eah", "eas", "eh", "enr", "eph", "es", "fah", "fph", "fps", "hdh", "hds", "ih", "iph", "ips", "is", "lth", "lts", "nat", "oph", "ops", "pap", "pav", "pch", "pcs", "pp", "pwah", "rah", "ras", "rch", "rcs", "rdh", "rds", "re", "reah", "renr", "res", "rfh", "rfs", "rft", "rh", "rhuc", "rih", "ris", "rs", "rth", "rts", "s_p", "sas", "sc", "mostrecent"])), "courtCode": Schema.optionalKey(Schema.String.check(Schema.isPattern(new RegExp("(?:(?:al|ak|as|az|ar|ca|co|ct|de|dc|fl|ga|gu|hi|id|il|in|ia|ks|ky|la|me|md|ma|mi|mn|ms|mo|mt|ne|nv|nh|nj|nm|ny|nc|nd|mp|oh|ok|or|pa|pr|ri|sc|sd|tn|tx|ut|vt|va|vi|wa|wv|wi|wy)[n|e|w|s]?[d|b|a])|(cit|ca\\d{1,2})|(cofc|jpml)")).annotate({ "expected": "a string matching the RegExp (?:(?:al|ak|as|az|ar|ca|co|ct|de|dc|fl|ga|gu|hi|id|il|in|ia|ks|ky|la|me|md|ma|mi|mn|ms|mo|mt|ne|nv|nh|nj|nm|ny|nc|nd|mp|oh|ok|or|pa|pr|ri|sc|sd|tn|tx|ut|vt|va|vi|wa|wv|wi|wy)[n|e|w|s]?[d|b|a])|(cit|ca\\d{1,2})|(cofc|jpml)" }))), "courtType": Schema.optionalKey(Schema.String.check(Schema.isPattern(new RegExp("District|Bankruptcy|Appellate|National")).annotate({ "expected": "a string matching the RegExp District|Bankruptcy|Appellate|National" }))), "state": Schema.optionalKey(Schema.String.check(Schema.isPattern(new RegExp("AL|AK|AS|AZ|AR|CA|CO|CT|DE|DC|FL|GA|GU|HI|ID|IL|IN|IA|KS|KY|LA|ME|MD|MA|MI|MN|MS|MO|MT|NE|NV|NH|NJ|NM|NY|NC|ND|MP|OH|OK|OR|PA|PR|RI|SC|SD|TN|TX|UT|VT|VA|VI|WA|WV|WI|WY")).annotate({ "expected": "a string matching the RegExp AL|AK|AS|AZ|AR|CA|CO|CT|DE|DC|FL|GA|GU|HI|ID|IL|IN|IA|KS|KY|LA|ME|MD|MA|MI|MN|MS|MO|MT|NE|NV|NH|NJ|NM|NY|NC|ND|MP|OH|OK|OR|PA|PR|RI|SC|SD|TN|TX|UT|VT|VA|VI|WA|WV|WI|WY" }))), "topic": Schema.optionalKey(Schema.String), "isGLP": Schema.optionalKey(Schema.Boolean), "natureSuitCode": Schema.optionalKey(Schema.String), "natureSuit": Schema.optionalKey(Schema.String) })
export type GetModifiedCollectionsPathParams = { readonly "collection": "BILLS" | "BILLSTATUS" | "BUDGET" | "CCAL" | "CDIR" | "CDOC" | "CFR" | "CHRG" | "CMR" | "COMPS" | "CPD" | "CPRT" | "CREC" | "CRECB" | "CRI" | "CRPT" | "CZIC" | "ECFR" | "ECONI" | "ERIC" | "ERP" | "FR" | "GAOREPORTS" | "GOVMAN" | "GOVPUB" | "GPO" | "HJOURNAL" | "HMAN" | "HOB" | "LSA" | "PAI" | "PLAW" | "PPP" | "SERIALSET" | "SJOURNAL" | "SMAN" | "STATUTE" | "USCODE" | "USCOURTS" | "USREPORTS", readonly "lastModifiedStartDate": string }
export const GetModifiedCollectionsPathParams = Schema.Struct({ "collection": Schema.Literals(["BILLS", "BILLSTATUS", "BUDGET", "CCAL", "CDIR", "CDOC", "CFR", "CHRG", "CMR", "COMPS", "CPD", "CPRT", "CREC", "CRECB", "CRI", "CRPT", "CZIC", "ECFR", "ECONI", "ERIC", "ERP", "FR", "GAOREPORTS", "GOVMAN", "GOVPUB", "GPO", "HJOURNAL", "HMAN", "HOB", "LSA", "PAI", "PLAW", "PPP", "SERIALSET", "SJOURNAL", "SMAN", "STATUTE", "USCODE", "USCOURTS", "USREPORTS"]), "lastModifiedStartDate": Schema.String.check(Schema.isPattern(new RegExp("\\d{4}-\\d{1,2}-\\d{1,2}T\\d{1,2}:\\d{1,2}:\\d{1,2}Z")).annotate({ "expected": "a string matching the RegExp \\d{4}-\\d{1,2}-\\d{1,2}T\\d{1,2}:\\d{1,2}:\\d{1,2}Z" })) })
export type GetModifiedCollectionsQuery = { readonly "offsetMark"?: string, readonly "offset"?: number, readonly "pageSize": number, readonly "congress"?: number, readonly "docClass"?: string, readonly "billVersion"?: "as" | "ash" | "ath" | "ats" | "cdh" | "cds" | "cph" | "cps" | "eah" | "eas" | "eh" | "enr" | "eph" | "es" | "fah" | "fph" | "fps" | "hdh" | "hds" | "ih" | "iph" | "ips" | "is" | "lth" | "lts" | "nat" | "oph" | "ops" | "pap" | "pav" | "pch" | "pcs" | "pp" | "pwah" | "rah" | "ras" | "rch" | "rcs" | "rdh" | "rds" | "re" | "reah" | "renr" | "res" | "rfh" | "rfs" | "rft" | "rh" | "rhuc" | "rih" | "ris" | "rs" | "rth" | "rts" | "s_p" | "sas" | "sc" | "mostrecent", readonly "courtCode"?: string, readonly "courtType"?: string, readonly "state"?: string, readonly "topic"?: string, readonly "isGLP"?: boolean, readonly "natureSuitCode"?: string, readonly "natureSuit"?: string }
export const GetModifiedCollectionsQuery = Schema.Struct({ "offsetMark": Schema.optionalKey(Schema.String), "offset": Schema.optionalKey(Schema.Int), "pageSize": Schema.Int.check(Schema.isLessThanOrEqualTo(1000).annotate({ "expected": "a value less than or equal to 1000" })), "congress": Schema.optionalKey(Schema.Int), "docClass": Schema.optionalKey(Schema.String), "billVersion": Schema.optionalKey(Schema.Literals(["as", "ash", "ath", "ats", "cdh", "cds", "cph", "cps", "eah", "eas", "eh", "enr", "eph", "es", "fah", "fph", "fps", "hdh", "hds", "ih", "iph", "ips", "is", "lth", "lts", "nat", "oph", "ops", "pap", "pav", "pch", "pcs", "pp", "pwah", "rah", "ras", "rch", "rcs", "rdh", "rds", "re", "reah", "renr", "res", "rfh", "rfs", "rft", "rh", "rhuc", "rih", "ris", "rs", "rth", "rts", "s_p", "sas", "sc", "mostrecent"])), "courtCode": Schema.optionalKey(Schema.String.check(Schema.isPattern(new RegExp("(?:(?:al|ak|as|az|ar|ca|co|ct|de|dc|fl|ga|gu|hi|id|il|in|ia|ks|ky|la|me|md|ma|mi|mn|ms|mo|mt|ne|nv|nh|nj|nm|ny|nc|nd|mp|oh|ok|or|pa|pr|ri|sc|sd|tn|tx|ut|vt|va|vi|wa|wv|wi|wy)[n|e|w|s]?[d|b|a])|(cit|ca\\d{1,2})|(cofc|jpml)")).annotate({ "expected": "a string matching the RegExp (?:(?:al|ak|as|az|ar|ca|co|ct|de|dc|fl|ga|gu|hi|id|il|in|ia|ks|ky|la|me|md|ma|mi|mn|ms|mo|mt|ne|nv|nh|nj|nm|ny|nc|nd|mp|oh|ok|or|pa|pr|ri|sc|sd|tn|tx|ut|vt|va|vi|wa|wv|wi|wy)[n|e|w|s]?[d|b|a])|(cit|ca\\d{1,2})|(cofc|jpml)" }))), "courtType": Schema.optionalKey(Schema.String.check(Schema.isPattern(new RegExp("District|Bankruptcy|Appellate|National")).annotate({ "expected": "a string matching the RegExp District|Bankruptcy|Appellate|National" }))), "state": Schema.optionalKey(Schema.String.check(Schema.isPattern(new RegExp("AL|AK|AS|AZ|AR|CA|CO|CT|DE|DC|FL|GA|GU|HI|ID|IL|IN|IA|KS|KY|LA|ME|MD|MA|MI|MN|MS|MO|MT|NE|NV|NH|NJ|NM|NY|NC|ND|MP|OH|OK|OR|PA|PR|RI|SC|SD|TN|TX|UT|VT|VA|VI|WA|WV|WI|WY")).annotate({ "expected": "a string matching the RegExp AL|AK|AS|AZ|AR|CA|CO|CT|DE|DC|FL|GA|GU|HI|ID|IL|IN|IA|KS|KY|LA|ME|MD|MA|MI|MN|MS|MO|MT|NE|NV|NH|NJ|NM|NY|NC|ND|MP|OH|OK|OR|PA|PR|RI|SC|SD|TN|TX|UT|VT|VA|VI|WA|WV|WI|WY" }))), "topic": Schema.optionalKey(Schema.String), "isGLP": Schema.optionalKey(Schema.Boolean), "natureSuitCode": Schema.optionalKey(Schema.String), "natureSuit": Schema.optionalKey(Schema.String) })
export type GetModifiedCollections200 = CollectionContainer
export const GetModifiedCollections200 = CollectionContainer
export type GetModifiedCollections1Params = { readonly "offsetMark"?: string, readonly "offset"?: number, readonly "pageSize": number, readonly "docClass"?: string, readonly "congress"?: number, readonly "billVersion"?: "as" | "ash" | "ath" | "ats" | "cdh" | "cds" | "cph" | "cps" | "eah" | "eas" | "eh" | "enr" | "eph" | "es" | "fah" | "fph" | "fps" | "hdh" | "hds" | "ih" | "iph" | "ips" | "is" | "lth" | "lts" | "nat" | "oph" | "ops" | "pap" | "pav" | "pch" | "pcs" | "pp" | "pwah" | "rah" | "ras" | "rch" | "rcs" | "rdh" | "rds" | "re" | "reah" | "renr" | "res" | "rfh" | "rfs" | "rft" | "rh" | "rhuc" | "rih" | "ris" | "rs" | "rth" | "rts" | "s_p" | "sas" | "sc" | "mostrecent", readonly "courtCode"?: string, readonly "courtType"?: string, readonly "state"?: string, readonly "topic"?: string, readonly "isGLP"?: boolean, readonly "natureSuitCode"?: string, readonly "natureSuit"?: string }
export const GetModifiedCollections1Params = Schema.Struct({ "offsetMark": Schema.optionalKey(Schema.String), "offset": Schema.optionalKey(Schema.Int), "pageSize": Schema.Int.check(Schema.isLessThanOrEqualTo(1000).annotate({ "expected": "a value less than or equal to 1000" })), "docClass": Schema.optionalKey(Schema.String), "congress": Schema.optionalKey(Schema.Int), "billVersion": Schema.optionalKey(Schema.Literals(["as", "ash", "ath", "ats", "cdh", "cds", "cph", "cps", "eah", "eas", "eh", "enr", "eph", "es", "fah", "fph", "fps", "hdh", "hds", "ih", "iph", "ips", "is", "lth", "lts", "nat", "oph", "ops", "pap", "pav", "pch", "pcs", "pp", "pwah", "rah", "ras", "rch", "rcs", "rdh", "rds", "re", "reah", "renr", "res", "rfh", "rfs", "rft", "rh", "rhuc", "rih", "ris", "rs", "rth", "rts", "s_p", "sas", "sc", "mostrecent"])), "courtCode": Schema.optionalKey(Schema.String.check(Schema.isPattern(new RegExp("(?:(?:al|ak|as|az|ar|ca|co|ct|de|dc|fl|ga|gu|hi|id|il|in|ia|ks|ky|la|me|md|ma|mi|mn|ms|mo|mt|ne|nv|nh|nj|nm|ny|nc|nd|mp|oh|ok|or|pa|pr|ri|sc|sd|tn|tx|ut|vt|va|vi|wa|wv|wi|wy)[n|e|w|s]?[d|b|a])|(cit|ca\\d{1,2})|(cofc|jpml)")).annotate({ "expected": "a string matching the RegExp (?:(?:al|ak|as|az|ar|ca|co|ct|de|dc|fl|ga|gu|hi|id|il|in|ia|ks|ky|la|me|md|ma|mi|mn|ms|mo|mt|ne|nv|nh|nj|nm|ny|nc|nd|mp|oh|ok|or|pa|pr|ri|sc|sd|tn|tx|ut|vt|va|vi|wa|wv|wi|wy)[n|e|w|s]?[d|b|a])|(cit|ca\\d{1,2})|(cofc|jpml)" }))), "courtType": Schema.optionalKey(Schema.String.check(Schema.isPattern(new RegExp("District|Bankruptcy|Appellate|National")).annotate({ "expected": "a string matching the RegExp District|Bankruptcy|Appellate|National" }))), "state": Schema.optionalKey(Schema.String.check(Schema.isPattern(new RegExp("AL|AK|AS|AZ|AR|CA|CO|CT|DE|DC|FL|GA|GU|HI|ID|IL|IN|IA|KS|KY|LA|ME|MD|MA|MI|MN|MS|MO|MT|NE|NV|NH|NJ|NM|NY|NC|ND|MP|OH|OK|OR|PA|PR|RI|SC|SD|TN|TX|UT|VT|VA|VI|WA|WV|WI|WY")).annotate({ "expected": "a string matching the RegExp AL|AK|AS|AZ|AR|CA|CO|CT|DE|DC|FL|GA|GU|HI|ID|IL|IN|IA|KS|KY|LA|ME|MD|MA|MI|MN|MS|MO|MT|NE|NV|NH|NJ|NM|NY|NC|ND|MP|OH|OK|OR|PA|PR|RI|SC|SD|TN|TX|UT|VT|VA|VI|WA|WV|WI|WY" }))), "topic": Schema.optionalKey(Schema.String), "isGLP": Schema.optionalKey(Schema.Boolean), "natureSuitCode": Schema.optionalKey(Schema.String), "natureSuit": Schema.optionalKey(Schema.String) })
export type GetModifiedCollections1PathParams = { readonly "collection": "BILLS" | "BILLSTATUS" | "BUDGET" | "CCAL" | "CDIR" | "CDOC" | "CFR" | "CHRG" | "CMR" | "COMPS" | "CPD" | "CPRT" | "CREC" | "CRECB" | "CRI" | "CRPT" | "CZIC" | "ECFR" | "ECONI" | "ERIC" | "ERP" | "FR" | "GAOREPORTS" | "GOVMAN" | "GOVPUB" | "GPO" | "HJOURNAL" | "HMAN" | "HOB" | "LSA" | "PAI" | "PLAW" | "PPP" | "SERIALSET" | "SJOURNAL" | "SMAN" | "STATUTE" | "USCODE" | "USCOURTS" | "USREPORTS", readonly "lastModifiedStartDate": string, readonly "lastModifiedEndDate": string }
export const GetModifiedCollections1PathParams = Schema.Struct({ "collection": Schema.Literals(["BILLS", "BILLSTATUS", "BUDGET", "CCAL", "CDIR", "CDOC", "CFR", "CHRG", "CMR", "COMPS", "CPD", "CPRT", "CREC", "CRECB", "CRI", "CRPT", "CZIC", "ECFR", "ECONI", "ERIC", "ERP", "FR", "GAOREPORTS", "GOVMAN", "GOVPUB", "GPO", "HJOURNAL", "HMAN", "HOB", "LSA", "PAI", "PLAW", "PPP", "SERIALSET", "SJOURNAL", "SMAN", "STATUTE", "USCODE", "USCOURTS", "USREPORTS"]), "lastModifiedStartDate": Schema.String.check(Schema.isPattern(new RegExp("\\d{4}-\\d{1,2}-\\d{1,2}T\\d{1,2}:\\d{1,2}:\\d{1,2}Z")).annotate({ "expected": "a string matching the RegExp \\d{4}-\\d{1,2}-\\d{1,2}T\\d{1,2}:\\d{1,2}:\\d{1,2}Z" })), "lastModifiedEndDate": Schema.String.check(Schema.isPattern(new RegExp("\\d{4}-\\d{1,2}-\\d{1,2}T\\d{1,2}:\\d{1,2}:\\d{1,2}Z")).annotate({ "expected": "a string matching the RegExp \\d{4}-\\d{1,2}-\\d{1,2}T\\d{1,2}:\\d{1,2}:\\d{1,2}Z" })) })
export type GetModifiedCollections1Query = { readonly "offsetMark"?: string, readonly "offset"?: number, readonly "pageSize": number, readonly "docClass"?: string, readonly "congress"?: number, readonly "billVersion"?: "as" | "ash" | "ath" | "ats" | "cdh" | "cds" | "cph" | "cps" | "eah" | "eas" | "eh" | "enr" | "eph" | "es" | "fah" | "fph" | "fps" | "hdh" | "hds" | "ih" | "iph" | "ips" | "is" | "lth" | "lts" | "nat" | "oph" | "ops" | "pap" | "pav" | "pch" | "pcs" | "pp" | "pwah" | "rah" | "ras" | "rch" | "rcs" | "rdh" | "rds" | "re" | "reah" | "renr" | "res" | "rfh" | "rfs" | "rft" | "rh" | "rhuc" | "rih" | "ris" | "rs" | "rth" | "rts" | "s_p" | "sas" | "sc" | "mostrecent", readonly "courtCode"?: string, readonly "courtType"?: string, readonly "state"?: string, readonly "topic"?: string, readonly "isGLP"?: boolean, readonly "natureSuitCode"?: string, readonly "natureSuit"?: string }
export const GetModifiedCollections1Query = Schema.Struct({ "offsetMark": Schema.optionalKey(Schema.String), "offset": Schema.optionalKey(Schema.Int), "pageSize": Schema.Int.check(Schema.isLessThanOrEqualTo(1000).annotate({ "expected": "a value less than or equal to 1000" })), "docClass": Schema.optionalKey(Schema.String), "congress": Schema.optionalKey(Schema.Int), "billVersion": Schema.optionalKey(Schema.Literals(["as", "ash", "ath", "ats", "cdh", "cds", "cph", "cps", "eah", "eas", "eh", "enr", "eph", "es", "fah", "fph", "fps", "hdh", "hds", "ih", "iph", "ips", "is", "lth", "lts", "nat", "oph", "ops", "pap", "pav", "pch", "pcs", "pp", "pwah", "rah", "ras", "rch", "rcs", "rdh", "rds", "re", "reah", "renr", "res", "rfh", "rfs", "rft", "rh", "rhuc", "rih", "ris", "rs", "rth", "rts", "s_p", "sas", "sc", "mostrecent"])), "courtCode": Schema.optionalKey(Schema.String.check(Schema.isPattern(new RegExp("(?:(?:al|ak|as|az|ar|ca|co|ct|de|dc|fl|ga|gu|hi|id|il|in|ia|ks|ky|la|me|md|ma|mi|mn|ms|mo|mt|ne|nv|nh|nj|nm|ny|nc|nd|mp|oh|ok|or|pa|pr|ri|sc|sd|tn|tx|ut|vt|va|vi|wa|wv|wi|wy)[n|e|w|s]?[d|b|a])|(cit|ca\\d{1,2})|(cofc|jpml)")).annotate({ "expected": "a string matching the RegExp (?:(?:al|ak|as|az|ar|ca|co|ct|de|dc|fl|ga|gu|hi|id|il|in|ia|ks|ky|la|me|md|ma|mi|mn|ms|mo|mt|ne|nv|nh|nj|nm|ny|nc|nd|mp|oh|ok|or|pa|pr|ri|sc|sd|tn|tx|ut|vt|va|vi|wa|wv|wi|wy)[n|e|w|s]?[d|b|a])|(cit|ca\\d{1,2})|(cofc|jpml)" }))), "courtType": Schema.optionalKey(Schema.String.check(Schema.isPattern(new RegExp("District|Bankruptcy|Appellate|National")).annotate({ "expected": "a string matching the RegExp District|Bankruptcy|Appellate|National" }))), "state": Schema.optionalKey(Schema.String.check(Schema.isPattern(new RegExp("AL|AK|AS|AZ|AR|CA|CO|CT|DE|DC|FL|GA|GU|HI|ID|IL|IN|IA|KS|KY|LA|ME|MD|MA|MI|MN|MS|MO|MT|NE|NV|NH|NJ|NM|NY|NC|ND|MP|OH|OK|OR|PA|PR|RI|SC|SD|TN|TX|UT|VT|VA|VI|WA|WV|WI|WY")).annotate({ "expected": "a string matching the RegExp AL|AK|AS|AZ|AR|CA|CO|CT|DE|DC|FL|GA|GU|HI|ID|IL|IN|IA|KS|KY|LA|ME|MD|MA|MI|MN|MS|MO|MT|NE|NV|NH|NJ|NM|NY|NC|ND|MP|OH|OK|OR|PA|PR|RI|SC|SD|TN|TX|UT|VT|VA|VI|WA|WV|WI|WY" }))), "topic": Schema.optionalKey(Schema.String), "isGLP": Schema.optionalKey(Schema.Boolean), "natureSuitCode": Schema.optionalKey(Schema.String), "natureSuit": Schema.optionalKey(Schema.String) })
export type GetModifiedCollections1200 = CollectionContainer
export const GetModifiedCollections1200 = CollectionContainer

export const ApiKeySchemeSecurity = HttpApiSecurity.apiKey({ key: "api_key", in: "query" })

export class ApiKeySchemeSecurityMiddleware extends HttpApiMiddleware.Service<ApiKeySchemeSecurityMiddleware>()("apiKeyScheme security", { security: { "apiKeyScheme": ApiKeySchemeSecurity } }) {}

class SearchGroup extends HttpApiGroup.make("Search")
  .add(HttpApiEndpoint.post("search", "/search", { payload: SearchRequestJson, success: Search200, error: [HttpApiSchema.Empty(400), HttpApiSchema.Empty(404), HttpApiSchema.Empty(500)] })
      .middleware(ApiKeySchemeSecurityMiddleware)
      .annotate(OpenApi.Identifier, "search")
      .annotate(OpenApi.Description, "This service can be used to query the GovInfo search engine and return results that are the equivalent to what is returned by the main user interface. You can use field operators, such as congress, publishdate, branch, and others to construct complex queries that will return only matching documents. For additional information, please see our <a href='https://www.govinfo.gov/features/search-service-overview' target='blank' style='text-decoration:underline'>search service overview</a>."))
  .annotate(OpenApi.Description, "Discover documents on GovInfo using search queries and field operators available in the GovInfo UI") {}

class RelatedGroup extends HttpApiGroup.make("Related")
  .add(HttpApiEndpoint.get("relatedPackageDetails", "/related/:accessId", { params: RelatedPackageDetailsPathParams })
      .middleware(ApiKeySchemeSecurityMiddleware)
      .annotate(OpenApi.Identifier, "relatedPackageDetails")
      .annotate(OpenApi.Summary, "Get a list of relationships for a given accessId"), 
    HttpApiEndpoint.get("relatedVersionsDetails", "/related/:accessId/:collection", { params: RelatedVersionsDetailsPathParams, query: RelatedVersionsDetailsQuery })
      .middleware(ApiKeySchemeSecurityMiddleware)
      .annotate(OpenApi.Identifier, "relatedVersionsDetails")
      .annotate(OpenApi.Summary, "Get a list of relationships for a given accessId"))
  .annotate(OpenApi.Description, "Discover relationships between documents available on GovInfo") {}

class PublishedGroup extends HttpApiGroup.make("Published")
  .add(HttpApiEndpoint.get("getPackagesByDateIssued", "/published/:dateIssuedStartDate", { params: GetPackagesByDateIssuedPathParams, query: GetPackagesByDateIssuedQuery, success: GetPackagesByDateIssued200 })
      .middleware(ApiKeySchemeSecurityMiddleware)
      .annotate(OpenApi.Identifier, "getPackagesByDateIssued")
      .annotate(OpenApi.Summary, "Retrieve list of packages based on dateIssued value"), 
    HttpApiEndpoint.get("getPackagesByDateIssued1", "/published/:dateIssuedStartDate/:dateIssuedEndDate", { params: GetPackagesByDateIssued1PathParams, query: GetPackagesByDateIssued1Query, success: GetPackagesByDateIssued1200 })
      .middleware(ApiKeySchemeSecurityMiddleware)
      .annotate(OpenApi.Identifier, "getPackagesByDateIssued_1")
      .annotate(OpenApi.Summary, "Retrieve list of packages based on dateIssued value range"))
  .annotate(OpenApi.Description, "Discover documents on GovInfo based on official publication date") {}

class PackagesGroup extends HttpApiGroup.make("Packages")
  .add(HttpApiEndpoint.get("packageDetails", "/packages/:packageId/summary", { params: PackageDetailsPathParams })
      .middleware(ApiKeySchemeSecurityMiddleware)
      .annotate(OpenApi.Identifier, "packageDetails")
      .annotate(OpenApi.Summary, "Return json summary for specified package"), 
    HttpApiEndpoint.get("getGranulesForPackage", "/packages/:packageId/granules", { params: GetGranulesForPackagePathParams, query: GetGranulesForPackageQuery, success: GetGranulesForPackage200 })
      .middleware(ApiKeySchemeSecurityMiddleware)
      .annotate(OpenApi.Identifier, "getGranulesForPackage")
      .annotate(OpenApi.Summary, "Get a list of granules associated with a package"), 
    HttpApiEndpoint.get("getGranuleContentDetail", "/packages/:packageId/granules/:granuleId/summary", { params: GetGranuleContentDetailPathParams, success: GetGranuleContentDetail200 })
      .middleware(ApiKeySchemeSecurityMiddleware)
      .annotate(OpenApi.Identifier, "getGranuleContentDetail")
      .annotate(OpenApi.Summary, "Return json summary for specified granule"))
  .annotate(OpenApi.Description, "Return content and metadata for individual packages") {}

class CollectionsGroup extends HttpApiGroup.make("Collections")
  .add(HttpApiEndpoint.get("getCollectionSummary", "/collections", { success: GetCollectionSummary200 })
      .middleware(ApiKeySchemeSecurityMiddleware)
      .annotate(OpenApi.Identifier, "getCollectionSummary")
      .annotate(OpenApi.Summary, "Request list of collections. Response includes collectionCode,collectionName, package and granule counts"), 
    HttpApiEndpoint.get("getModifiedCollections", "/collections/:collection/:lastModifiedStartDate", { params: GetModifiedCollectionsPathParams, query: GetModifiedCollectionsQuery, success: GetModifiedCollections200 })
      .middleware(ApiKeySchemeSecurityMiddleware)
      .annotate(OpenApi.Identifier, "getModifiedCollections")
      .annotate(OpenApi.Summary, "Retrieve new or updated packages for a collection given a start date and time"), 
    HttpApiEndpoint.get("getModifiedCollections1", "/collections/:collection/:lastModifiedStartDate/:lastModifiedEndDate", { params: GetModifiedCollections1PathParams, query: GetModifiedCollections1Query, success: GetModifiedCollections1200 })
      .middleware(ApiKeySchemeSecurityMiddleware)
      .annotate(OpenApi.Identifier, "getModifiedCollections_1")
      .annotate(OpenApi.Summary, "Retrieve new or updated packages for a collection within a date range"))
  .annotate(OpenApi.Description, "Discover new and updated documents based on GovInfo lastModified date/time") {}

export class Govinfo extends HttpApi.make("Govinfo")
  .annotate(OpenApi.Title, "GovInfo API")
  .annotate(OpenApi.Version, "2.0")
  .annotate(OpenApi.Description, "<p>The GovInfo API provides services for developers and webmasters to access GovInfo content and metadata. For more information on other developer resources, see our <a href=\"https://www.govinfo.gov/developers\" target=\"blank\"> developer hub</a>. If you have feedback or would like to learn more about plans for the API, please see our <a href=\"https://www.github.com/usgpo/api\" target=\"blank\">GitHub repository<i class=\"bi bi-github\"></i></a>.</p><p>This API requires the use of an <a href=\"https://api.data.gov\" target=\"blank\">API.data.gov</a> key - <a href=\"https://www.govinfo.gov/api-signup\" target=\"blank\">signup here</a>. If you already have one, click on Authorize and enter your key. Then you can make all the requests via this page. For information about copyright, please see our <a href=\"https://www.govinfo.gov/about/policies#copyright\" target=\"blank\">Public Domain & Copyright Notice</a>.")
  .annotate(OpenApi.License, {"name":"License","url":"https://github.com/usgpo/api/blob/master/LICENSE.md"})
  .annotate(OpenApi.Servers, [{"url":""}])
  .add(SearchGroup, RelatedGroup, PublishedGroup, PackagesGroup, CollectionsGroup) {}