"""Shared deterministic helpers for the S6 A-Box generators.

The helpers are deliberately small: path resolution, pinned-commit lookup,
digesting, and the house YAML writer.  Individual ETLs retain their own domain
logic.  Run the public scripts with the commands in s6-abox-contract.md.
"""

from __future__ import annotations

import hashlib
import subprocess
from pathlib import Path
from typing import Any

import yaml

S6 = Path(__file__).resolve().parents[1]
PACKET = S6.parents[2]
REPO = PACKET.parents[1]
S5 = S6.parent / "s5"
S4 = S6.parent / "s4"
TESTS = PACKET / "ontology/tests"
DOCS = PACKET / "ontology/docs"


class _NoAliasSafeDumper(yaml.SafeDumper):
    """Keep generated YAML human-diffable by expanding repeated mappings."""

    def ignore_aliases(self, data: Any) -> bool:
        return True


def load_yaml(path: Path) -> Any:
    """Load one packet YAML file."""

    return yaml.safe_load(path.read_text())


def corpus_commit() -> str:
    """Return the exact checkout commit that pins generated corpus facts."""

    return subprocess.run(
        ["git", "-C", str(REPO), "rev-parse", "HEAD"],
        check=True,
        capture_output=True,
        text=True,
    ).stdout.strip()


def sha256_12(data: bytes) -> str:
    """Return the packet's canonical twelve-hex SHA-256 receipt."""

    return hashlib.sha256(data).hexdigest()[:12]


def repo_path(path: Path) -> str:
    """Render a path relative to the repository root."""

    return path.resolve().relative_to(REPO.resolve()).as_posix()


def write_generated_yaml(
    path: Path,
    data: Any,
    script_name: str,
    *header_lines: str,
) -> None:
    """Write deterministic generated YAML with the S5 house banner."""

    header = f"# GENERATED by scripts/{script_name} — do not hand-edit.\n"
    header += "".join(f"# {line}\n" for line in header_lines)
    body = yaml.dump(
        data,
        Dumper=_NoAliasSafeDumper,
        sort_keys=False,
        allow_unicode=True,
        width=100,
    )
    path.write_text(header + body)
