"""etl_census — enumerate the root-workspace @beep/* package A-Box.

Workspace roots come only from package.json's workspaces globs.  The generated
census keeps one provisional WorkspacePackage individual per matching @beep/*
manifest and one dependsOnWorkspace edge per distinct workspace dependency from
dependencies, devDependencies, or peerDependencies.  Deterministic and
idempotent.

Run: uv run --with pyyaml python etl_census.py
"""

from __future__ import annotations

import glob
import json
from pathlib import Path

from _common import REPO, S6, corpus_commit, repo_path, write_generated_yaml

DEPENDENCY_SECTIONS = ("dependencies", "devDependencies", "peerDependencies")
PROV_IRI = "https://oip.law/ontology/ci-ops-prov#"


def local_name(package_name: str) -> str:
    """Apply the ratified S6 package-local IRI rule."""

    if not package_name.startswith("@beep/"):
        raise ValueError(package_name)
    return package_name.removeprefix("@beep/").replace("/", "--")


def main() -> None:
    root_manifest = json.loads((REPO / "package.json").read_text())
    workspaces = root_manifest.get("workspaces")
    if not isinstance(workspaces, list) or not all(isinstance(item, str) for item in workspaces):
        raise SystemExit("root package.json workspaces must be a string array")

    manifest_paths = set()
    for pattern in workspaces:
        for match in glob.glob(str(REPO / pattern)):
            manifest = Path(match) / "package.json"
            if manifest.is_file():
                manifest_paths.add(manifest.resolve())

    raw_packages = []
    for manifest in sorted(manifest_paths):
        data = json.loads(manifest.read_text())
        name = data.get("name")
        if isinstance(name, str) and name.startswith("@beep/"):
            raw_packages.append((name, manifest, data))
    names = [name for name, _, _ in raw_packages]
    if len(names) != len(set(names)):
        duplicates = sorted(name for name in set(names) if names.count(name) > 1)
        raise SystemExit(f"duplicate @beep workspace package names: {duplicates}")

    workspace_names = set(names)
    packages = []
    edges = set()
    iri_names = set()
    for name, manifest, data in sorted(raw_packages):
        local = local_name(name)
        if local in iri_names:
            raise SystemExit(f"package IRI local-name collision at {local}")
        iri_names.add(local)
        dependencies = set()
        for section in DEPENDENCY_SECTIONS:
            values = data.get(section) or {}
            if not isinstance(values, dict):
                raise SystemExit(f"{repo_path(manifest)} {section} is not an object")
            dependencies.update(dep for dep in values if dep in workspace_names)
        for dependency in dependencies:
            edges.add((name, dependency))
        packages.append(
            {
                "name": name,
                "iri": f"ciops-prov:{local}",
                "manifest": repo_path(manifest),
                "depends_on_workspace": sorted(dependencies),
            }
        )

    out = {
        "generated_by": "scripts/etl_census.py",
        "corpus_commit": corpus_commit(),
        "count": len(packages),
        "edge_count": len(edges),
        "packages": packages,
    }
    write_generated_yaml(
        S6 / "CENSUS.yaml",
        out,
        "etl_census.py",
        "PROVISIONAL census; closure OPEN; excluded from negation and ratified typing.",
        "Workspace membership derives only from root package.json workspaces globs.",
    )

    lines = [
        "# GENERATED by scripts/etl_census.py — do not hand-edit.",
        "# PROVISIONAL GRAPH — closure OPEN; excluded from negation and ratified typing.",
        f"@prefix ciops-prov: <{PROV_IRI}> .",
        "@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .",
        "",
    ]
    for package in packages:
        lines.append(
            f"{package['iri']} rdf:type ciops-prov:WorkspacePackage ."
        )
    if packages and edges:
        lines.append("")
    for source, target in sorted(edges):
        lines.append(
            f"ciops-prov:{local_name(source)} ciops-prov:dependsOnWorkspace "
            f"ciops-prov:{local_name(target)} ."
        )
    (S6 / "graphs/census.ttl").write_text("\n".join(lines) + "\n")
    print(f"census: {len(packages)} packages / {len(edges)} workspace dependency edges")


if __name__ == "__main__":
    main()
