/** Effect Vitest inventory, census, and JSONL persistence. @packageDocumentation @since 0.0.0 */

import { A, Str } from "@beep/utils";
import { Effect, FileSystem, Inspectable, Order, Path } from "effect";
import * as O from "effect/Option";
import * as R from "effect/Record";
import { formatJsonc, readArtifact, writeArtifact } from "../../../internal/artifacts/index.ts";
import { repoRunSafeArtifactName } from "../../../internal/repo-run/RepoRunArtifacts.ts";
import { EffectVitestLintError } from "../Lint.errors.ts";
import {
  decodeEffectVitestFindingJson,
  EffectVitestCensusPath,
  EffectVitestInventoryPath,
  encodeEffectVitestFindingJson,
  encodeEffectVitestInventoryDocument,
  EffectVitestInventoryDocument as InventoryDocument,
} from "../Lint.schemas.ts";
import type { EffectVitestCensusRow, EffectVitestFinding, EffectVitestInventoryDocument } from "../Lint.schemas.ts";

const storageError = (action: string, target: string, cause: unknown): EffectVitestLintError =>
  EffectVitestLintError.new(`${action} ${target}: ${Inspectable.toStringUnknown(cause, 0)}`);

const isOwnedRowsFile = Effect.fn("EffectVitestStore.isOwnedRowsFile")(function* (
  outputRoot: string,
  fileName: string
) {
  if (!Str.endsWith(".jsonl")(fileName)) return false;
  const fs = yield* FileSystem.FileSystem;
  const path = yield* Path.Path;
  const content = yield* fs.readFileString(path.join(outputRoot, fileName)).pipe(Effect.orElseSucceed(() => ""));
  const lines = A.filter(Str.split("\n")(content), (line) => Str.isNonEmpty(Str.trim(line)));
  return (
    !A.isReadonlyArrayEmpty(lines) &&
    A.every(lines, (line) =>
      O.exists(
        decodeEffectVitestFindingJson(line),
        (finding) => `${repoRunSafeArtifactName(finding.package)}.jsonl` === fileName
      )
    )
  );
});

/**
 * Read and schema-decode the optional committed Effect Vitest baseline.
 *
 * **Details**
 *
 * A missing file succeeds with `O.none()`; malformed content fails with the
 * lane's typed storage error.
 *
 * **Example** (Build a baseline read effect)
 *
 * ```ts
 * import { readEffectVitestInventory } from "@beep/repo-cli/commands/Lint"
 * import { Effect } from "effect"
 *
 * console.log(Effect.isEffect(readEffectVitestInventory(process.cwd()))) // true
 * ```
 *
 * @category resources
 * @since 0.0.0
 */
export const readEffectVitestInventory = Effect.fn("EffectVitestStore.readInventory")(function* (root: string) {
  const fs = yield* FileSystem.FileSystem;
  const path = yield* Path.Path;
  const absolute = path.resolve(root, EffectVitestInventoryPath);
  if (!(yield* fs.exists(absolute))) return O.none<EffectVitestInventoryDocument>();
  const document = yield* readArtifact({
    path: absolute,
    schema: InventoryDocument,
    onReadError: (cause) => storageError("Unable to read", EffectVitestInventoryPath, cause),
    onDecodeError: (cause) => storageError("Unable to decode", EffectVitestInventoryPath, cause),
  });
  return O.some(document);
});

/**
 * Encode, format, and write a validated full-scan baseline beneath a repository root.
 *
 * **Example** (Build a baseline write effect)
 *
 * ```ts
 * import { EffectVitestInventoryDocument } from "@beep/repo-cli/commands/Lint"
 * import { writeEffectVitestInventory } from "@beep/repo-cli/commands/Lint"
 * import { Effect } from "effect"
 *
 * const document = EffectVitestInventoryDocument.make({
 *   schemaVersion: "effect-vitest-inventory/v1",
 *   effectVitestVersion: "4.0.0-rc.113",
 *   scope: [],
 *   findings: []
 * })
 * console.log(Effect.isEffect(writeEffectVitestInventory(process.cwd(), document))) // true
 * ```
 *
 * @category resources
 * @since 0.0.0
 */
export const writeEffectVitestInventory = Effect.fn("EffectVitestStore.writeInventory")(function* (
  root: string,
  document: EffectVitestInventoryDocument
) {
  const path = yield* Path.Path;
  const encoded = yield* encodeEffectVitestInventoryDocument(document).pipe(
    Effect.mapError((cause) => storageError("Unable to encode", EffectVitestInventoryPath, cause))
  );
  const body = yield* formatJsonc(encoded).pipe(
    Effect.mapError((cause) => storageError("Unable to format", EffectVitestInventoryPath, cause))
  );
  yield* writeArtifact({
    path: path.resolve(root, EffectVitestInventoryPath),
    header: "// Generated by `bun run beep lint effect-vitest --write`; exceptions require a reason.\n",
    body,
    onError: (cause) => storageError("Unable to write", EffectVitestInventoryPath, cause),
  });
});

/**
 * Format and replace the authoritative D9 census array.
 *
 * **Example** (Build an empty census write effect)
 *
 * ```ts
 * import { writeEffectVitestCensus } from "@beep/repo-cli/commands/Lint"
 * import { Effect } from "effect"
 *
 * console.log(Effect.isEffect(writeEffectVitestCensus(process.cwd(), []))) // true
 * ```
 *
 * @category resources
 * @since 0.0.0
 */
export const writeEffectVitestCensus = Effect.fn("EffectVitestStore.writeCensus")(function* (
  root: string,
  rows: ReadonlyArray<EffectVitestCensusRow>
) {
  const path = yield* Path.Path;
  const body = yield* formatJsonc(rows).pipe(
    Effect.mapError((cause) => storageError("Unable to format", EffectVitestCensusPath, cause))
  );
  yield* writeArtifact({
    path: path.resolve(root, EffectVitestCensusPath),
    body,
    onError: (cause) => storageError("Unable to write", EffectVitestCensusPath, cause),
  });
});

/**
 * Replace deterministic per-package JSONL owned by this command beneath a requested directory.
 *
 * **Details**
 *
 * Owner names pass through the shared artifact-name sanitizer. Stale files are
 * deleted only when every record decodes as this finding schema and names the
 * same safe owner; unrelated files, including other JSONL, remain untouched.
 *
 * **Example** (Build an empty rows export effect)
 *
 * ```ts
 * import { writeEffectVitestRows } from "@beep/repo-cli/commands/Lint"
 * import { Effect } from "effect"
 *
 * console.log(Effect.isEffect(writeEffectVitestRows(process.cwd(), "detector-rows", []))) // true
 * ```
 *
 * @category resources
 * @since 0.0.0
 */
export const writeEffectVitestRows = Effect.fn("EffectVitestStore.writeRows")(function* (
  root: string,
  outputDirectory: string,
  findings: ReadonlyArray<EffectVitestFinding>
) {
  const fs = yield* FileSystem.FileSystem;
  const path = yield* Path.Path;
  const grouped = A.groupBy(findings, (finding) => finding.package);
  const outputRoot = path.resolve(root, outputDirectory);
  type OwnerEntry = readonly [owner: string, findings: ReadonlyArray<EffectVitestFinding>];
  const ownerOrder = Order.mapInput(Order.String, (entry: OwnerEntry) => entry[0]);
  const ownerEntries: ReadonlyArray<OwnerEntry> = A.sort(R.toEntries(grouped), ownerOrder);
  const expectedFiles = A.map(ownerEntries, ([owner]) => `${repoRunSafeArtifactName(owner)}.jsonl`);
  for (const [owner, ownerFindings] of ownerEntries) {
    const sortedFindings = A.sort(
      ownerFindings,
      Order.mapInput(Order.String, (finding: EffectVitestFinding) => finding.id)
    );
    const lines = yield* Effect.forEach(sortedFindings, (finding) => encodeEffectVitestFindingJson(finding), {
      concurrency: 1,
    }).pipe(Effect.mapError((cause) => storageError("Unable to encode rows for", owner, cause)));
    const fileName = `${repoRunSafeArtifactName(owner)}.jsonl`;
    yield* writeArtifact({
      path: path.join(outputRoot, fileName),
      body: `${A.join(lines, "\n")}\n`,
      onError: (cause) => storageError("Unable to write", fileName, cause),
    });
  }
  const previousFiles = yield* fs.readDirectory(outputRoot).pipe(Effect.orElseSucceed(A.empty<string>));
  yield* Effect.forEach(
    previousFiles,
    Effect.fnUntraced(function* (fileName) {
      if (A.contains(expectedFiles, fileName) || !(yield* isOwnedRowsFile(outputRoot, fileName))) return;
      yield* fs
        .remove(path.join(outputRoot, fileName), { force: true })
        .pipe(Effect.mapError((cause) => storageError("Unable to remove stale rows file", fileName, cause)));
    }),
    { concurrency: 1, discard: true }
  );
});
