/**
 * Generate the eCFR HttpApi contract from the checked-in Swagger document.
 *
 * @since 0.0.0
 */

import { $EcfrId } from "@beep/identity";
import * as OpenApiGenerator from "@effect/openapi-generator/OpenApiGenerator";
import { BunRuntime } from "@effect/platform-bun";
import * as BunServices from "@effect/platform-bun/BunServices";
import { Effect, FileSystem, Layer, MutableList, Path, pipe } from "effect";
import * as A from "effect/Array";
import * as S from "effect/Schema";
import * as Str from "effect/String";
import { Command, Flag } from "effect/unstable/cli";
import * as ChildProcess from "effect/unstable/process/ChildProcess";
import * as ChildProcessSpawner from "effect/unstable/process/ChildProcessSpawner";
import type { OpenAPISpec } from "effect/unstable/httpapi/OpenApi";

const $I = $EcfrId.create("scripts/generate");
const generatedHeader = `/**
 * Generated eCFR HttpApi contract. Do not edit this file by hand.
 *
 * Run \`bun run generate\` after changing \`openapi.json\`.
 *
 * @packageDocumentation
 * @since 0.0.0
 */

`;
const integerSchemaPattern =
  /Schema\.Number(\.annotate\(\{[^\n]*?\}\))?\.check\(Schema\.isInt\(\)\.annotate\(\{[^\n]*?\}\)\)/g;

class GenerateError extends S.TaggedError<GenerateError>($I`GenerateError`)(
  "GenerateError",
  { message: S.String },
  $I.annoteError<GenerateError>("GenerateError", {
    description: "Failure while generating or checking the eCFR HttpApi contract.",
  })
) {}

const fail = (message: string): Effect.Effect<never, GenerateError> => Effect.fail(GenerateError.make({ message }));

const postProcess = (source: string): string =>
  pipe(
    source,
    Str.replaceAll(integerSchemaPattern, "Schema.Int$1"),
    Str.replaceAll(/\bSchema\.Number\b/g, "Schema.Finite"),
    Str.replaceAll(", HttpApiMiddleware", ""),
    Str.replaceAll(", HttpApiSecurity", ""),
    Str.replaceAll(
      "Schema.optionalKey(Schema.Array(Schema.String))",
      "Schema.Array(Schema.String).pipe(Schema.optionalKey)"
    ),
    (generated) => `${generatedHeader}${generated}`
  );

const formatWarning = (warning: OpenApiGenerator.OpenApiGeneratorWarning): string =>
  `[${warning.code}] ${warning.method ?? ""} ${warning.path ?? ""} ${warning.operationId ?? ""}: ${warning.message}`;

// The generator supports Swagger 2.0 at runtime, but its public input type only
// describes the OpenAPI 3.1 documents emitted by HttpApi.
const asGeneratorInput = (spec: S.Json): OpenAPISpec => spec as unknown as OpenAPISpec;

const runCommand = Effect.fnUntraced(function* (command: ChildProcess.Command, failureMessage: string) {
  const spawner = yield* ChildProcessSpawner.ChildProcessSpawner;
  const exitCode = yield* spawner.exitCode(command);
  if (exitCode !== 0) {
    return yield* fail(`${failureMessage} Exit code: ${exitCode}.`);
  }
});

const generate = Effect.fnUntraced(function* (check: boolean) {
  const fs = yield* FileSystem.FileSystem;
  const path = yield* Path.Path;
  const scriptPath = yield* path.fromFileUrl(new URL(import.meta.url));
  const packageRoot = path.dirname(path.dirname(scriptPath));
  const repoRoot = path.resolve(packageRoot, "../../..");
  const generatedDir = path.join(packageRoot, "src", "_generated");
  const outputPath = path.join(generatedDir, "Ecfr.gen.ts");
  const specPath = path.join(packageRoot, "openapi.json");
  const biomePath = path.join(repoRoot, "node_modules", ".bin", "biome");

  const specText = yield* fs.readFileString(specPath);
  const spec = yield* S.decodeEffect(S.fromJsonString(S.Json))(specText).pipe(
    Effect.mapError((cause) => GenerateError.make({ message: `Invalid openapi.json: ${cause.message}` }))
  );
  const generator = yield* OpenApiGenerator.OpenApiGenerator;
  const warnings = MutableList.make<OpenApiGenerator.OpenApiGeneratorWarning>();
  const rawSource = yield* generator.generate(asGeneratorInput(spec), {
    name: "Ecfr",
    format: "httpapi",
    onWarning: (warning) => MutableList.append(warnings, warning),
  });
  yield* A.match(MutableList.toArray(warnings), {
    onEmpty: () => Effect.void,
    onNonEmpty: (items) => fail(`OpenAPI generation warnings:\n${pipe(items, A.map(formatWarning), A.join("\n"))}`),
  });

  const temporaryPath = yield* fs.makeTempFileScoped({
    directory: generatedDir,
    prefix: "ecfr-generate-",
    suffix: ".generated.ts",
  });
  yield* fs.writeFileString(temporaryPath, postProcess(rawSource));
  yield* runCommand(
    ChildProcess.make(biomePath, ["check", "--write", "--unsafe", temporaryPath], {
      cwd: packageRoot,
      stderr: "inherit",
      stdout: "inherit",
    }),
    "Biome failed while formatting generated eCFR output."
  );
  const formattedSource = yield* fs.readFileString(temporaryPath);

  if (!check) {
    yield* fs.writeFileString(outputPath, formattedSource);
    return yield* Effect.log("Generated src/_generated/Ecfr.gen.ts from openapi.json.");
  }

  const outputExists = yield* fs.exists(outputPath);
  const diffSource = outputExists ? outputPath : "/dev/null";
  const spawner = yield* ChildProcessSpawner.ChildProcessSpawner;
  const diffExitCode = yield* spawner.exitCode(
    ChildProcess.make(
      "diff",
      ["-u", "--label", "src/_generated/Ecfr.gen.ts", "--label", "generated", diffSource, temporaryPath],
      {
        cwd: packageRoot,
        stderr: "inherit",
        stdout: "inherit",
      }
    )
  );
  if (diffExitCode !== 0) {
    return yield* fail("Generated eCFR output differs from src/_generated/Ecfr.gen.ts.");
  }
  return yield* Effect.log("Generated eCFR output is current.");
});

const generateCommand = Command.make(
  "generate",
  {
    check: Flag.boolean("check").pipe(Flag.withDefault(false)),
  },
  ({ check }) => generate(check)
).pipe(Command.withDescription("Generate or check the eCFR HttpApi contract."));

const runtimeLayer = Layer.mergeAll(BunServices.layer, OpenApiGenerator.layerTransformerSchema);
const program = Effect.scoped(
  Layer.build(runtimeLayer).pipe(
    Effect.flatMap(
      Effect.fnUntraced(function* (context) {
        return yield* Command.run(generateCommand, { version: "0.0.0" }).pipe(Effect.provide(context));
      })
    )
  )
);

BunRuntime.runMain(program);
