/**
 * Static schema catalog generator for the crispened schema surface.
 *
 * @packageDocumentation
 * @since 0.0.0
 */

import { $RepoCliId } from "@beep/identity/packages";
import { FsUtils } from "@beep/repo-utils/FsUtils";
import { findRepoRoot } from "@beep/repo-utils/Root";
import { isExcludedTypeScriptSourcePath, toPosixPath } from "@beep/repo-utils/schemas/TypeScriptSourceExclusions";
import { LiteralKit } from "@beep/schema";
import { A, Str, thunkEmptyStr } from "@beep/utils";
import { Console, Effect, FileSystem, Order, Path, pipe, SchemaGetter } from "effect";
import * as O from "effect/Option";
import * as S from "effect/Schema";
import { Command, Flag } from "effect/unstable/cli";
import { Node, Project, SyntaxKind } from "ts-morph";
import { failWithReportedExit } from "../../internal/cli/ExitCodeError.js";
import { optionalProp } from "../../internal/cli/OptionRecord.js";
import { literalMemberEquals, makeSchemaFirstOwnerResolver, SchemaFirstIncludedGlobs } from "./SchemaFirst.ts";
import type {
  CallExpression,
  ClassDeclaration,
  Expression,
  Identifier,
  PropertyAssignment,
  SourceFile,
  VariableDeclaration,
} from "ts-morph";

const $I = $RepoCliId.create("commands/Lint/SchemaCatalog");
const SCHEMA_CATALOG_PATH = "standards/schema-catalog.generated.jsonc";
const SCHEMA_CATALOG_GENERATED_BY = "bun run beep lint schema-catalog --write";
const SCHEMA_CATALOG_HEADER = `// Generated by ${SCHEMA_CATALOG_GENERATED_BY}. Do not edit manually.`;
const stringifyJsonPretty = SchemaGetter.stringifyJson({ space: 2 });

/**
 * Static schema declaration kinds emitted by the generated schema catalog.
 *
 * @example
 * ```ts
 * import { SchemaCatalogEntryKind } from "@beep/repo-cli/commands/Lint"
 * import * as S from "effect/Schema"
 *
 * const value = "schema-class"
 * console.log(S.is(SchemaCatalogEntryKind)(value)) // true
 * ```
 * @category schema
 * @since 0.0.0
 */
export const SchemaCatalogEntryKind = LiteralKit([
  "schema-class",
  "tagged-class",
  "error-class",
  "tagged-error",
  "struct-const",
  "tagged-struct",
  "literal-kit",
  "brand",
  "union",
  "tagged-union",
  "codec",
  "schema-const",
]).pipe(
  $I.annoteSchema("SchemaCatalogEntryKind", {
    description: "Static schema declaration kinds emitted by the generated schema catalog.",
  })
);

/**
 * Static schema declaration kind for one generated schema catalog entry.
 *
 * @example
 * ```ts
 * import type { SchemaCatalogEntryKind } from "@beep/repo-cli/commands/Lint"
 *
 * const kind: SchemaCatalogEntryKind = "schema-class"
 * console.log(kind)
 * ```
 * @category schema
 * @since 0.0.0
 */
export type SchemaCatalogEntryKind = typeof SchemaCatalogEntryKind.Type;

/**
 * Single static schema declaration catalog entry.
 *
 * @example
 * ```ts
 * import { SchemaCatalogEntry } from "@beep/repo-cli/commands/Lint"
 * import * as S from "effect/Schema"
 *
 * const candidate = { file: "packages/example/src/Foo.ts", name: "Foo", kind: "class" }
 * console.log(S.is(SchemaCatalogEntry)(candidate)) // true
 * ```
 * @category models
 * @since 0.0.0
 */
export class SchemaCatalogEntry extends S.Class<SchemaCatalogEntry>($I`SchemaCatalogEntry`)(
  {
    file: S.String,
    symbol: S.String,
    kind: SchemaCatalogEntryKind,
    owner: S.String,
    identity: S.optionalKey(S.String),
    description: S.optionalKey(S.String),
  },
  $I.annote("SchemaCatalogEntry", {
    description: "Single static schema declaration catalog entry.",
  })
) {}

/**
 * Generated schema catalog document committed under standards.
 *
 * @example
 * ```ts
 * import { SchemaCatalogDocument } from "@beep/repo-cli/commands/Lint"
 * import * as S from "effect/Schema"
 *
 * const candidate = { entries: [] }
 * console.log(S.is(SchemaCatalogDocument)(candidate)) // true
 * ```
 * @category models
 * @since 0.0.0
 */
export class SchemaCatalogDocument extends S.Class<SchemaCatalogDocument>($I`SchemaCatalogDocument`)(
  {
    schemaVersion: S.Literal("schema-catalog/v1"),
    generatedBy: S.Literal(SCHEMA_CATALOG_GENERATED_BY),
    entries: S.Array(SchemaCatalogEntry),
  },
  $I.annote("SchemaCatalogDocument", {
    description: "Generated schema catalog document committed under standards.",
  })
) {}

/**
 * CLI options for schema catalog generation.
 *
 * @example
 * ```ts
 * import { SchemaCatalogOptions } from "@beep/repo-cli/commands/Lint"
 * import * as S from "effect/Schema"
 *
 * const candidate = { check: true, write: false }
 * console.log(S.is(SchemaCatalogOptions)(candidate)) // true
 * ```
 * @category models
 * @since 0.0.0
 */
export class SchemaCatalogOptions extends S.Class<SchemaCatalogOptions>($I`SchemaCatalogOptions`)(
  {
    write: S.Boolean.pipe(
      S.withConstructorDefault(Effect.succeed(false)),
      S.withDecodingDefault(Effect.succeed(false))
    ),
  },
  $I.annote("SchemaCatalogOptions", {
    description: "CLI options for schema catalog generation.",
  })
) {}

/**
 * Summary emitted after a schema catalog run.
 *
 * @example
 * ```ts
 * import { SchemaCatalogSummary } from "@beep/repo-cli/commands/Lint"
 * import * as S from "effect/Schema"
 *
 * const candidate = { entryCount: 1, written: false }
 * console.log(S.is(SchemaCatalogSummary)(candidate)) // true
 * ```
 * @category models
 * @since 0.0.0
 */
export class SchemaCatalogSummary extends S.Class<SchemaCatalogSummary>($I`SchemaCatalogSummary`)(
  {
    entries: S.Finite,
    wroteCatalog: S.Boolean,
  },
  $I.annote("SchemaCatalogSummary", {
    description: "Summary emitted after a schema catalog run.",
  })
) {}

type SchemaCatalogMetadata = {
  readonly identity: O.Option<string>;
  readonly description: O.Option<string>;
};

const encodeSchemaCatalogDocument = S.encodeUnknownEffect(SchemaCatalogDocument);

const isExcludedFile = isExcludedTypeScriptSourcePath;

const makeEntryKey = (entry: SchemaCatalogEntry): string => `${entry.file}::${entry.symbol}`;

const byEntryPathAndSymbolAscending: Order.Order<SchemaCatalogEntry> = Order.mapInput(Order.String, makeEntryKey);

const sortCatalogEntries: (entries: ReadonlyArray<SchemaCatalogEntry>) => ReadonlyArray<SchemaCatalogEntry> =
  A.sort(byEntryPathAndSymbolAscending);

const literalTextFromNode = (node: Node | undefined): O.Option<string> => {
  if (node === undefined) {
    return O.none();
  }
  if (Node.isStringLiteral(node)) {
    return O.some(node.getLiteralText());
  }
  if (Node.isNoSubstitutionTemplateLiteral(node)) {
    return O.some(node.getLiteralValue());
  }
  return O.none();
};

const callExpressionsIn = (node: Node): ReadonlyArray<CallExpression> => {
  const calls = A.empty<CallExpression>();
  if (Node.isCallExpression(node)) {
    A.appendInPlace(calls, node);
  }
  for (const callExpression of node.getDescendantsOfKind(SyntaxKind.CallExpression)) {
    A.appendInPlace(calls, callExpression);
  }
  return calls;
};

const isPropertyAccessCallMember = <const T extends string>(
  callExpression: CallExpression,
  namespaceName: string,
  memberNames: readonly T[]
): boolean => {
  const expression = callExpression.getExpression();
  return (
    Node.isPropertyAccessExpression(expression) &&
    Str.Equivalence(expression.getExpression().getText(), namespaceName) &&
    literalMemberEquals(memberNames, expression.getName())
  );
};

const isIdentifierCall = <const T extends string>(
  callExpression: CallExpression,
  identifiers: readonly T[]
): boolean => {
  const expression = callExpression.getExpression();
  return Node.isIdentifier(expression) && literalMemberEquals(identifiers, expression.getText());
};

const hasPropertyAccessCall = <const T extends string>(
  calls: ReadonlyArray<CallExpression>,
  namespaceName: string,
  memberNames: readonly T[]
): boolean => A.some(calls, (callExpression) => isPropertyAccessCallMember(callExpression, namespaceName, memberNames));

const hasIdentifierCall = <const T extends string>(
  calls: ReadonlyArray<CallExpression>,
  identifiers: readonly T[]
): boolean => A.some(calls, (callExpression) => isIdentifierCall(callExpression, identifiers));

const SCHEMA_PRIMITIVE_PROPERTY_NAMES = [
  "Boolean",
  "Finite",
  "Int",
  "Null",
  "Number",
  "NumberFromString",
  "String",
  "Undefined",
  "Unknown",
  "UnknownFromJsonString",
] as const;

const isSchemaPrimitivePropertyAccess = (node: Node): boolean =>
  Node.isPropertyAccessExpression(node) &&
  Str.Equivalence(node.getExpression().getText(), "S") &&
  literalMemberEquals(SCHEMA_PRIMITIVE_PROPERTY_NAMES, node.getName());

const expressionStartsWithSchemaPrimitive = (node: Node): boolean => {
  if (isSchemaPrimitivePropertyAccess(node)) {
    return true;
  }
  if (!Node.isCallExpression(node)) {
    return false;
  }
  const callTarget = node.getExpression();
  if (!Node.isPropertyAccessExpression(callTarget) || !Str.Equivalence(callTarget.getName(), "pipe")) {
    return false;
  }
  return isSchemaPrimitivePropertyAccess(callTarget.getExpression());
};

const SCHEMA_CONST_MEMBER_NAMES = [
  "Array",
  "Boolean",
  "Finite",
  "Int",
  "Literal",
  "Null",
  "Number",
  "NumberFromString",
  "OptionFromNullOr",
  "OptionFromNullishOr",
  "OptionFromOptional",
  "OptionFromOptionalKey",
  "Record",
  "String",
  "TemplateLiteral",
  "Tuple",
  "Undefined",
  "Unknown",
  "UnknownFromJsonString",
] as const;

const SCHEMA_TRANSFORMATION_MEMBER_NAMES = [
  "transform",
  "transformOrFail",
  "transformOptional",
  "fromJsonString",
] as const;

type SchemaKindRule = {
  readonly kind: SchemaCatalogEntryKind;
  readonly matches: (calls: ReadonlyArray<CallExpression>, node: Node) => boolean;
};

// Ordered classification rules: the first matching rule wins, so the more
// specific declaration shapes stay ahead of the broad schema-const fallback.
const SCHEMA_KIND_RULES: ReadonlyArray<SchemaKindRule> = [
  {
    kind: "tagged-error",
    matches: (calls) =>
      hasIdentifierCall(calls, ["TaggedErrorClass", "StatusCauseTaggedErrorClass"]) ||
      hasPropertyAccessCall(calls, "S", ["TaggedErrorClass"]),
  },
  { kind: "error-class", matches: (calls) => hasPropertyAccessCall(calls, "S", ["ErrorClass"]) },
  { kind: "tagged-class", matches: (calls) => hasPropertyAccessCall(calls, "S", ["TaggedClass"]) },
  { kind: "schema-class", matches: (calls) => hasPropertyAccessCall(calls, "S", ["Class"]) },
  { kind: "literal-kit", matches: (calls) => hasIdentifierCall(calls, ["LiteralKit", "MappedLiteralKit"]) },
  { kind: "tagged-union", matches: (calls) => hasPropertyAccessCall(calls, "S", ["TaggedUnion", "toTaggedUnion"]) },
  { kind: "union", matches: (calls) => hasPropertyAccessCall(calls, "S", ["Union"]) },
  { kind: "tagged-struct", matches: (calls) => hasPropertyAccessCall(calls, "S", ["TaggedStruct"]) },
  { kind: "struct-const", matches: (calls) => hasPropertyAccessCall(calls, "S", ["Struct"]) },
  { kind: "brand", matches: (calls) => hasPropertyAccessCall(calls, "S", ["brand", "fromBrand"]) },
  {
    kind: "codec",
    matches: (calls) =>
      hasPropertyAccessCall(calls, "S", ["decodeTo", "encodeTo", "fromJsonString"]) ||
      hasPropertyAccessCall(calls, "SchemaTransformation", SCHEMA_TRANSFORMATION_MEMBER_NAMES),
  },
  {
    kind: "schema-const",
    matches: (calls, node) =>
      hasPropertyAccessCall(calls, "S", SCHEMA_CONST_MEMBER_NAMES) || expressionStartsWithSchemaPrimitive(node),
  },
];

const schemaKindFromCalls = (calls: ReadonlyArray<CallExpression>, node: Node): O.Option<SchemaCatalogEntryKind> =>
  pipe(
    A.findFirst(SCHEMA_KIND_RULES, (rule) => rule.matches(calls, node)),
    O.map((rule) => rule.kind)
  );

const initializerFromIdentifier = (identifier: Identifier): O.Option<Expression> => {
  const declarations = identifier.getSymbol()?.getDeclarations() ?? A.empty<Node>();
  for (const declaration of declarations) {
    if (Node.isVariableDeclaration(declaration)) {
      return O.fromNullishOr(declaration.getInitializer());
    }
  }
  return O.none();
};

const pipeReceiverExpression = (expression: Expression): O.Option<Expression> => {
  if (!Node.isCallExpression(expression)) {
    return O.none();
  }
  const callTarget = expression.getExpression();
  if (!Node.isPropertyAccessExpression(callTarget) || !Str.Equivalence(callTarget.getName(), "pipe")) {
    return O.none();
  }
  return O.some(callTarget.getExpression());
};

const schemaKindFromExpression = (expression: Expression, depth = 0): O.Option<SchemaCatalogEntryKind> => {
  const directKind = schemaKindFromCalls(callExpressionsIn(expression), expression);
  if (O.isSome(directKind)) {
    return directKind;
  }
  if (depth > 2) {
    return O.none();
  }

  const receiver = pipeReceiverExpression(expression);
  if (O.isSome(receiver) && Node.isIdentifier(receiver.value)) {
    return pipe(
      initializerFromIdentifier(receiver.value),
      O.flatMap((initializer) => schemaKindFromExpression(initializer, depth + 1))
    );
  }

  if (Node.isIdentifier(expression)) {
    return pipe(
      initializerFromIdentifier(expression),
      O.flatMap((initializer) => schemaKindFromExpression(initializer, depth + 1))
    );
  }

  return O.none();
};

const propertyNameText = (property: PropertyAssignment): O.Option<string> => {
  const nameNode = property.getNameNode();
  if (Node.isIdentifier(nameNode)) {
    return O.some(nameNode.getText());
  }
  if (Node.isStringLiteral(nameNode)) {
    return O.some(nameNode.getLiteralText());
  }
  return O.none();
};

const descriptionFromAnnotationOptions = (optionsNode: Node | undefined): O.Option<string> => {
  if (!Node.isObjectLiteralExpression(optionsNode)) {
    return O.none();
  }

  for (const property of optionsNode.getProperties()) {
    if (!Node.isPropertyAssignment(property)) {
      continue;
    }
    const name = propertyNameText(property);
    if (O.isNone(name) || !Str.Equivalence(name.value, "description")) {
      continue;
    }
    return literalTextFromNode(property.getInitializer());
  }

  return O.none();
};

const isIdentityAnnotationCall = (callExpression: CallExpression): boolean => {
  const expression = callExpression.getExpression();
  return (
    Node.isPropertyAccessExpression(expression) &&
    Str.Equivalence(expression.getExpression().getText(), "$I") &&
    literalMemberEquals(["annote", "annoteSchema"], expression.getName())
  );
};

const metadataFromAnnotationCalls = (node: Node): SchemaCatalogMetadata => {
  let identity = O.none<string>();
  let description = O.none<string>();

  for (const callExpression of callExpressionsIn(node)) {
    if (!isIdentityAnnotationCall(callExpression)) {
      continue;
    }
    const args = callExpression.getArguments();
    if (O.isNone(identity)) {
      identity = pipe(O.fromNullishOr(args[0]), O.flatMap(literalTextFromNode));
    }
    if (O.isNone(description)) {
      description = descriptionFromAnnotationOptions(args[1]);
    }
    if (O.isSome(identity) && O.isSome(description)) {
      return { identity, description };
    }
  }

  return { identity, description };
};

const identityFromTaggedTemplate = (node: Node): O.Option<string> => {
  for (const expression of node.getDescendantsOfKind(SyntaxKind.TaggedTemplateExpression)) {
    if (!Str.Equivalence(expression.getTag().getText(), "$I")) {
      continue;
    }
    const template = expression.getTemplate();
    if (Node.isNoSubstitutionTemplateLiteral(template)) {
      return O.some(template.getLiteralValue());
    }
  }
  return O.none();
};

const metadataFromNode = (node: Node): SchemaCatalogMetadata => {
  const fromAnnotation = metadataFromAnnotationCalls(node);
  return {
    identity: pipe(
      fromAnnotation.identity,
      O.orElse(() => identityFromTaggedTemplate(node))
    ),
    description: fromAnnotation.description,
  };
};

const makeCatalogEntry = (
  file: string,
  symbol: string,
  kind: SchemaCatalogEntryKind,
  owner: string,
  node: Node
): SchemaCatalogEntry => {
  const metadata = metadataFromNode(node);
  return SchemaCatalogEntry.make({
    file,
    symbol,
    kind,
    owner,
    ...optionalProp("identity", metadata.identity),
    ...optionalProp("description", metadata.description),
  });
};

const catalogEntryFromClassDeclaration = (
  declaration: ClassDeclaration,
  file: string,
  owner: string
): O.Option<SchemaCatalogEntry> => {
  // The catalog is the exported crispened surface; private helper schemas
  // (module-local bases, internal codecs) stay out of it.
  if (!declaration.isExported()) {
    return O.none();
  }
  const symbol = declaration.getName();
  const heritageExpression = declaration.getExtends()?.getExpression();
  if (symbol === undefined || heritageExpression === undefined) {
    return O.none();
  }

  return pipe(
    schemaKindFromExpression(heritageExpression),
    O.map((kind) => makeCatalogEntry(file, symbol, kind, owner, declaration))
  );
};

const catalogEntryFromVariableDeclaration = (
  declaration: VariableDeclaration,
  file: string,
  owner: string
): O.Option<SchemaCatalogEntry> =>
  pipe(
    O.fromNullishOr(declaration.getInitializer()),
    O.filter((initializer) => !Node.isArrowFunction(initializer) && !Node.isFunctionExpression(initializer)),
    O.flatMap((initializer) =>
      pipe(
        schemaKindFromExpression(initializer),
        O.map((kind) => makeCatalogEntry(file, declaration.getName(), kind, owner, initializer))
      )
    )
  );

const collectCatalogEntriesFromSourceFile = (
  sourceFile: SourceFile,
  file: string,
  owner: string
): ReadonlyArray<SchemaCatalogEntry> => {
  const entries = A.empty<SchemaCatalogEntry>();

  for (const declaration of sourceFile.getClasses()) {
    const entry = catalogEntryFromClassDeclaration(declaration, file, owner);
    if (O.isSome(entry)) {
      A.appendInPlace(entries, entry.value);
    }
  }

  for (const variableStatement of sourceFile.getVariableStatements()) {
    if (!variableStatement.isExported()) {
      continue;
    }
    for (const declaration of variableStatement.getDeclarations()) {
      const entry = catalogEntryFromVariableDeclaration(declaration, file, owner);
      if (O.isSome(entry)) {
        A.appendInPlace(entries, entry.value);
      }
    }
  }

  return entries;
};

/**
 * Generate the static schema catalog document from the schema-first scan scope.
 *
 * @example
 * ```ts
 * import { generateSchemaCatalogDocument } from "@beep/repo-cli/commands/Lint"
 * import { Effect } from "effect"
 *
 * const program = Effect.succeed(generateSchemaCatalogDocument)
 * console.log(Effect.isEffect(program)) // true
 * ```
 * @category use-cases
 * @since 0.0.0
 */
export const generateSchemaCatalogDocument = Effect.fn("SchemaCatalog.generateDocument")(function* () {
  return yield* Effect.gen(function* () {
    const path = yield* Path.Path;
    const fsUtils = yield* FsUtils;
    const repoRoot = yield* findRepoRoot();
    const ownerResolver = yield* makeSchemaFirstOwnerResolver(repoRoot);
    // Enumerate through FsUtils so the scan is anchored at the repo root even
    // when the command runs from a workspace subdirectory (ts-morph resolves
    // relative globs against the process cwd).
    const sourcePaths = yield* fsUtils.globFiles(SchemaFirstIncludedGlobs, {
      absolute: true,
      cwd: repoRoot,
      ignore: "**/docs/**",
    });
    const project = new Project({
      skipAddingFilesFromTsConfig: true,
      tsConfigFilePath: path.join(repoRoot, "tsconfig.json"),
    });
    for (const sourcePath of sourcePaths) {
      project.addSourceFileAtPath(sourcePath);
    }
    const entries = A.empty<SchemaCatalogEntry>();

    for (const sourceFile of project.getSourceFiles()) {
      const filePath = toPosixPath(path.relative(repoRoot, sourceFile.getFilePath()));
      if (isExcludedFile(filePath)) {
        continue;
      }
      const owner = ownerResolver(sourceFile.getFilePath());
      A.appendAllInPlace(entries, collectCatalogEntriesFromSourceFile(sourceFile, filePath, owner));
    }

    return SchemaCatalogDocument.make({
      schemaVersion: "schema-catalog/v1",
      generatedBy: SCHEMA_CATALOG_GENERATED_BY,
      entries: sortCatalogEntries(A.dedupeWith(entries, (left, right) => makeEntryKey(left) === makeEntryKey(right))),
    });
  }).pipe(Effect.withSpan("SchemaCatalog.generateDocument"));
});

/**
 * Render a schema catalog document as deterministic JSONC text.
 *
 * @example
 * ```ts
 * import { renderSchemaCatalogDocument } from "@beep/repo-cli/commands/Lint"
 * import { Effect } from "effect"
 *
 * const program = Effect.succeed(renderSchemaCatalogDocument)
 * console.log(Effect.isEffect(program)) // true
 * ```
 * @category formatting
 * @since 0.0.0
 */
export const renderSchemaCatalogDocument = Effect.fn("SchemaCatalog.renderDocument")(function* (
  document: SchemaCatalogDocument
) {
  const encodedDocument = yield* encodeSchemaCatalogDocument(document);
  const rendered = yield* stringifyJsonPretty.run(O.some(encodedDocument), {});
  const serialized = O.getOrElse(rendered, thunkEmptyStr);
  return `${SCHEMA_CATALOG_HEADER}\n${serialized}\n`;
});

/**
 * Generate deterministic JSONC text for the schema catalog.
 *
 * @example
 * ```ts
 * import { generateSchemaCatalogText } from "@beep/repo-cli/commands/Lint"
 * import { Effect } from "effect"
 *
 * const program = Effect.succeed(generateSchemaCatalogText)
 * console.log(Effect.isEffect(program)) // true
 * ```
 * @category use-cases
 * @since 0.0.0
 */
export const generateSchemaCatalogText = Effect.fn("SchemaCatalog.generateText")(function* () {
  const document = yield* generateSchemaCatalogDocument();
  return yield* renderSchemaCatalogDocument(document);
});

const schemaCatalogPath = Effect.fn("SchemaCatalog.path")(function* () {
  const path = yield* Path.Path;
  const repoRoot = yield* findRepoRoot();
  return path.resolve(repoRoot, SCHEMA_CATALOG_PATH);
});

const writeSchemaCatalog = Effect.fn("SchemaCatalog.write")(function* (content: string) {
  const fs = yield* FileSystem.FileSystem;
  const path = yield* Path.Path;
  const absolutePath = yield* schemaCatalogPath();
  yield* fs.makeDirectory(path.dirname(absolutePath), { recursive: true });
  yield* fs.writeFileString(absolutePath, content);
});

const checkSchemaCatalog = Effect.fn("SchemaCatalog.check")(function* (content: string) {
  const fs = yield* FileSystem.FileSystem;
  const absolutePath = yield* schemaCatalogPath();
  const exists = yield* fs.exists(absolutePath);

  if (!exists) {
    yield* Console.error(`[schema-catalog] missing ${SCHEMA_CATALOG_PATH}`);
    return yield* failWithReportedExit(
      `schema-catalog: ${SCHEMA_CATALOG_PATH} is missing; run ${SCHEMA_CATALOG_GENERATED_BY}.`
    );
  }

  const current = yield* fs.readFileString(absolutePath);
  if (current !== content) {
    yield* Console.error(`[schema-catalog] stale ${SCHEMA_CATALOG_PATH}`);
    return yield* failWithReportedExit(
      `schema-catalog: ${SCHEMA_CATALOG_PATH} is stale; run ${SCHEMA_CATALOG_GENERATED_BY}.`
    );
  }
});

/**
 * Run schema catalog write/check mode.
 *
 * @example
 * ```ts
 * import { runSchemaCatalog } from "@beep/repo-cli/commands/Lint"
 * import { Effect } from "effect"
 *
 * const program = Effect.succeed(runSchemaCatalog)
 * console.log(Effect.isEffect(program)) // true
 * ```
 * @category use-cases
 * @since 0.0.0
 */
export const runSchemaCatalog = Effect.fn("SchemaCatalog.run")(function* (options: SchemaCatalogOptions) {
  return yield* Effect.gen(function* () {
    const document = yield* generateSchemaCatalogDocument();
    const content = yield* renderSchemaCatalogDocument(document);

    if (options.write) {
      yield* writeSchemaCatalog(content);
      yield* Console.log(`[schema-catalog] wrote ${SCHEMA_CATALOG_PATH}`);
    } else {
      yield* checkSchemaCatalog(content);
      yield* Console.log(`[schema-catalog] ${SCHEMA_CATALOG_PATH} is current`);
    }

    const summary = SchemaCatalogSummary.make({
      entries: A.length(document.entries),
      wroteCatalog: options.write,
    });
    yield* Console.log(`[schema-catalog] entries=${summary.entries}`);
    return summary;
  }).pipe(Effect.withSpan("SchemaCatalog.run"));
});

/**
 * Repo-wide schema catalog generation command.
 *
 * @example
 * ```ts
 * import { lintSchemaCatalogCommand } from "@beep/repo-cli/commands/Lint"
 * import { Command } from "effect/unstable/cli"
 * import { Effect } from "effect"
 *
 * const run = Command.run(lintSchemaCatalogCommand, { version: "0.0.0" })
 * console.log(Effect.isEffect(run)) // true
 * ```
 * @category cli-commands
 * @since 0.0.0
 */
export const lintSchemaCatalogCommand = Command.make(
  "schema-catalog",
  {
    write: Flag.boolean("write").pipe(Flag.withDescription(`Refresh ${SCHEMA_CATALOG_PATH}`)),
  },
  Effect.fn(function* ({ write }) {
    yield* runSchemaCatalog(SchemaCatalogOptions.make({ write }));
  })
).pipe(Command.withDescription(`Verify or refresh ${SCHEMA_CATALOG_PATH}`));
