/**
 * Generated Runpod REST request models and operation descriptors.
 * Do not edit this file by hand.
 *
 * @packageDocumentation
 * @since 0.1.0
 */

import type { Effect } from "effect";
import * as S from "effect/Schema";

import { $RunpodId } from "@beep/identity";
import { LiteralKit, SchemaUtils } from "@beep/schema";
import * as Models from "./Runpod.models.gen.ts";

const $I = $RunpodId.create("Runpod.generated");

/**
 * Advisory allowedCudaVersions values observed in the checked-in Runpod OpenAPI document.
 *
 * **Example** (Read the RUNPOD_ALLOWED_CUDA_VERSIONS_VALUES values)
 *
 * ```ts
 * import { RUNPOD_ALLOWED_CUDA_VERSIONS_VALUES } from "@beep/runpod"
 *
 * console.log(RUNPOD_ALLOWED_CUDA_VERSIONS_VALUES)
 * ```
 *
 * @category constants
 * @since 0.1.0
 */
export const RUNPOD_ALLOWED_CUDA_VERSIONS_VALUES = [
  "13.0",
  "12.9",
  "12.8",
  "12.7",
  "12.6",
  "12.5",
  "12.4",
  "12.3",
  "12.2",
  "12.1",
  "12.0",
  "11.8",
] as const;

/**
 * Advisory cpuFlavorIds values observed in the checked-in Runpod OpenAPI document.
 *
 * **Example** (Read the RUNPOD_CPU_FLAVOR_IDS_VALUES values)
 *
 * ```ts
 * import { RUNPOD_CPU_FLAVOR_IDS_VALUES } from "@beep/runpod"
 *
 * console.log(RUNPOD_CPU_FLAVOR_IDS_VALUES)
 * ```
 *
 * @category constants
 * @since 0.1.0
 */
export const RUNPOD_CPU_FLAVOR_IDS_VALUES = [
  "cpu3c",
  "cpu3g",
  "cpu5c",
  "cpu5g",
] as const;

/**
 * Advisory cpuFlavorPriority values observed in the checked-in Runpod OpenAPI document.
 *
 * **Example** (Read the RUNPOD_CPU_FLAVOR_PRIORITY_VALUES values)
 *
 * ```ts
 * import { RUNPOD_CPU_FLAVOR_PRIORITY_VALUES } from "@beep/runpod"
 *
 * console.log(RUNPOD_CPU_FLAVOR_PRIORITY_VALUES)
 * ```
 *
 * @category constants
 * @since 0.1.0
 */
export const RUNPOD_CPU_FLAVOR_PRIORITY_VALUES = [
  "availability",
  "custom",
] as const;

/**
 * Advisory cudaVersions values observed in the checked-in Runpod OpenAPI document.
 *
 * **Example** (Read the RUNPOD_CUDA_VERSIONS_VALUES values)
 *
 * ```ts
 * import { RUNPOD_CUDA_VERSIONS_VALUES } from "@beep/runpod"
 *
 * console.log(RUNPOD_CUDA_VERSIONS_VALUES)
 * ```
 *
 * @category constants
 * @since 0.1.0
 */
export const RUNPOD_CUDA_VERSIONS_VALUES = [
  "12.4",
  "12.3",
  "12.2",
  "12.1",
  "12.0",
  "11.8",
] as const;

/**
 * Advisory dataCenterId values observed in the checked-in Runpod OpenAPI document.
 *
 * **Example** (Read the RUNPOD_DATA_CENTER_ID_VALUES values)
 *
 * ```ts
 * import { RUNPOD_DATA_CENTER_ID_VALUES } from "@beep/runpod"
 *
 * console.log(RUNPOD_DATA_CENTER_ID_VALUES)
 * ```
 *
 * @category constants
 * @since 0.1.0
 */
export const RUNPOD_DATA_CENTER_ID_VALUES = [
  "EU-RO-1",
  "CA-MTL-1",
  "EU-SE-1",
  "US-IL-1",
  "EUR-IS-1",
  "EU-CZ-1",
  "US-TX-3",
  "EUR-IS-2",
  "US-KS-2",
  "US-GA-2",
  "US-WA-1",
  "US-TX-1",
  "CA-MTL-3",
  "EU-NL-1",
  "US-TX-4",
  "US-CA-2",
  "US-NC-1",
  "OC-AU-1",
  "US-DE-1",
  "EUR-IS-3",
  "CA-MTL-2",
  "AP-JP-1",
  "EUR-NO-1",
  "EU-FR-1",
  "US-KS-3",
  "US-GA-1",
] as const;

/**
 * Advisory dataCenterIds values observed in the checked-in Runpod OpenAPI document.
 *
 * **Example** (Read the RUNPOD_DATA_CENTER_IDS_VALUES values)
 *
 * ```ts
 * import { RUNPOD_DATA_CENTER_IDS_VALUES } from "@beep/runpod"
 *
 * console.log(RUNPOD_DATA_CENTER_IDS_VALUES)
 * ```
 *
 * @category constants
 * @since 0.1.0
 */
export const RUNPOD_DATA_CENTER_IDS_VALUES = [
  "EU-RO-1",
  "CA-MTL-1",
  "EU-SE-1",
  "US-IL-1",
  "EUR-IS-1",
  "EU-CZ-1",
  "US-TX-3",
  "EUR-IS-2",
  "US-KS-2",
  "US-GA-2",
  "US-WA-1",
  "US-TX-1",
  "CA-MTL-3",
  "EU-NL-1",
  "US-TX-4",
  "US-CA-2",
  "US-NC-1",
  "OC-AU-1",
  "US-DE-1",
  "EUR-IS-3",
  "CA-MTL-2",
  "AP-JP-1",
  "EUR-NO-1",
  "EU-FR-1",
  "US-KS-3",
  "US-GA-1",
] as const;

/**
 * Advisory dataCenterPriority values observed in the checked-in Runpod OpenAPI document.
 *
 * **Example** (Read the RUNPOD_DATA_CENTER_PRIORITY_VALUES values)
 *
 * ```ts
 * import { RUNPOD_DATA_CENTER_PRIORITY_VALUES } from "@beep/runpod"
 *
 * console.log(RUNPOD_DATA_CENTER_PRIORITY_VALUES)
 * ```
 *
 * @category constants
 * @since 0.1.0
 */
export const RUNPOD_DATA_CENTER_PRIORITY_VALUES = [
  "availability",
  "custom",
] as const;

/**
 * Advisory gpuTypeId values observed in the checked-in Runpod OpenAPI document.
 *
 * **Example** (Read the RUNPOD_GPU_TYPE_ID_VALUES values)
 *
 * ```ts
 * import { RUNPOD_GPU_TYPE_ID_VALUES } from "@beep/runpod"
 *
 * console.log(RUNPOD_GPU_TYPE_ID_VALUES)
 * ```
 *
 * @category constants
 * @since 0.1.0
 */
export const RUNPOD_GPU_TYPE_ID_VALUES = [
  "NVIDIA GeForce RTX 4090",
  "NVIDIA RTX A5000",
  "NVIDIA RTX A4000",
  "NVIDIA GeForce RTX 3090",
  "NVIDIA RTX A6000",
  "NVIDIA A40",
  "NVIDIA RTX A4500",
  "NVIDIA A100 80GB PCIe",
  "NVIDIA L4",
  "NVIDIA RTX 4000 Ada Generation",
  "NVIDIA RTX 6000 Ada Generation",
  "NVIDIA A100-SXM4-80GB",
  "NVIDIA H100 80GB HBM3",
  "NVIDIA L40",
  "NVIDIA H100 PCIe",
  "NVIDIA L40S",
  "NVIDIA GeForce RTX 3080",
  "NVIDIA GeForce RTX 3070",
  "NVIDIA GeForce RTX 3080 Ti",
  "NVIDIA A30",
  "NVIDIA GeForce RTX 4080",
  "NVIDIA RTX A2000",
  "NVIDIA GeForce RTX 3090 Ti",
  "Tesla V100-SXM2-32GB",
  "NVIDIA GeForce RTX 4070 Ti",
  "NVIDIA RTX 4000 SFF Ada Generation",
  "NVIDIA RTX 5000 Ada Generation",
  "Tesla V100-SXM2-16GB",
  "Tesla V100-FHHL-16GB",
  "Tesla V100-PCIE-16GB",
  "NVIDIA RTX 2000 Ada Generation",
  "NVIDIA H100 NVL",
  "AMD Instinct MI300X OAM",
  "NVIDIA A100-SXM4-40GB",
] as const;

/**
 * Advisory gpuTypeIds values observed in the checked-in Runpod OpenAPI document.
 *
 * **Example** (Read the RUNPOD_GPU_TYPE_IDS_VALUES values)
 *
 * ```ts
 * import { RUNPOD_GPU_TYPE_IDS_VALUES } from "@beep/runpod"
 *
 * console.log(RUNPOD_GPU_TYPE_IDS_VALUES)
 * ```
 *
 * @category constants
 * @since 0.1.0
 */
export const RUNPOD_GPU_TYPE_IDS_VALUES = [
  "NVIDIA GeForce RTX 4090",
  "NVIDIA A40",
  "NVIDIA RTX A5000",
  "NVIDIA GeForce RTX 5090",
  "NVIDIA H100 80GB HBM3",
  "NVIDIA GeForce RTX 3090",
  "NVIDIA RTX A4500",
  "NVIDIA L40S",
  "NVIDIA H200",
  "NVIDIA L4",
  "NVIDIA RTX 6000 Ada Generation",
  "NVIDIA A100-SXM4-80GB",
  "NVIDIA RTX 4000 Ada Generation",
  "NVIDIA RTX A6000",
  "NVIDIA A100 80GB PCIe",
  "NVIDIA RTX 2000 Ada Generation",
  "NVIDIA RTX A4000",
  "NVIDIA RTX PRO 6000 Blackwell Server Edition",
  "NVIDIA H100 PCIe",
  "NVIDIA H100 NVL",
  "NVIDIA L40",
  "NVIDIA B200",
  "NVIDIA GeForce RTX 3080 Ti",
  "NVIDIA RTX PRO 6000 Blackwell Workstation Edition",
  "NVIDIA GeForce RTX 3080",
  "NVIDIA GeForce RTX 3070",
  "AMD Instinct MI300X OAM",
  "NVIDIA GeForce RTX 4080 SUPER",
  "Tesla V100-PCIE-16GB",
  "Tesla V100-SXM2-32GB",
  "NVIDIA RTX 5000 Ada Generation",
  "NVIDIA GeForce RTX 4070 Ti",
  "NVIDIA RTX 4000 SFF Ada Generation",
  "NVIDIA GeForce RTX 3090 Ti",
  "NVIDIA RTX A2000",
  "NVIDIA GeForce RTX 4080",
  "NVIDIA A30",
  "NVIDIA GeForce RTX 5080",
  "Tesla V100-FHHL-16GB",
  "NVIDIA H200 NVL",
  "Tesla V100-SXM2-16GB",
  "NVIDIA RTX PRO 6000 Blackwell Max-Q Workstation Edition",
  "NVIDIA A5000 Ada",
  "Tesla V100-PCIE-32GB",
  "NVIDIA  RTX A4500",
  "NVIDIA  A30",
  "NVIDIA GeForce RTX 3080TI",
  "Tesla T4",
  "NVIDIA RTX A30",
] as const;

/**
 * Advisory gpuTypePriority values observed in the checked-in Runpod OpenAPI document.
 *
 * **Example** (Read the RUNPOD_GPU_TYPE_PRIORITY_VALUES values)
 *
 * ```ts
 * import { RUNPOD_GPU_TYPE_PRIORITY_VALUES } from "@beep/runpod"
 *
 * console.log(RUNPOD_GPU_TYPE_PRIORITY_VALUES)
 * ```
 *
 * @category constants
 * @since 0.1.0
 */
export const RUNPOD_GPU_TYPE_PRIORITY_VALUES = [
  "availability",
  "custom",
] as const;

/**
 * Advisory minCudaVersion values observed in the checked-in Runpod OpenAPI document.
 *
 * **Example** (Read the RUNPOD_MIN_CUDA_VERSION_VALUES values)
 *
 * ```ts
 * import { RUNPOD_MIN_CUDA_VERSION_VALUES } from "@beep/runpod"
 *
 * console.log(RUNPOD_MIN_CUDA_VERSION_VALUES)
 * ```
 *
 * @category constants
 * @since 0.1.0
 */
export const RUNPOD_MIN_CUDA_VERSION_VALUES = [
  "13.0",
  "12.9",
  "12.8",
  "12.7",
  "12.6",
  "12.5",
  "12.4",
  "12.3",
  "12.2",
  "12.1",
  "12.0",
  "11.8",
] as const;

/**
 * GetOpenAPIStatus200Response schema generated from the Runpod OpenAPI document.
 *
 * **Example** (Inspect the GetOpenAPIStatus200Response schema)
 *
 * ```ts
 * import { GetOpenAPIStatus200Response } from "@beep/runpod"
 *
 * console.log(GetOpenAPIStatus200Response.ast)
 * ```
 *
 * @category schemas
 * @since 0.1.0
 */

export const GetOpenAPIStatus200Response = S.Record(S.String, S.Unknown).pipe(
  $I.annoteSchema("GetOpenAPIStatus200Response", {
    description:
      "GetOpenAPIStatus200Response schema generated from the Runpod OpenAPI document.",
  }),
);

/**
 * GetOpenAPIStatus200Response value generated from the Runpod OpenAPI document.
 *
 * **Example** (Reference the GetOpenAPIStatus200Response type)
 *
 * ```ts
 * import type { GetOpenAPIStatus200Response } from "@beep/runpod"
 *
 * type GetOpenAPIStatus200ResponseValue = GetOpenAPIStatus200Response
 * ```
 *
 * @category type-level
 * @since 0.1.0
 */
export type GetOpenAPIStatus200Response =
  typeof GetOpenAPIStatus200Response.Type;

/**
 * GetDocsStatus200TextResponse schema generated from the Runpod OpenAPI document.
 *
 * **Example** (Inspect the GetDocsStatus200TextResponse schema)
 *
 * ```ts
 * import { GetDocsStatus200TextResponse } from "@beep/runpod"
 *
 * console.log(GetDocsStatus200TextResponse.ast)
 * ```
 *
 * @category schemas
 * @since 0.1.0
 */

export const GetDocsStatus200TextResponse = S.String.pipe(
  $I.annoteSchema("GetDocsStatus200TextResponse", {
    description:
      "GetDocsStatus200TextResponse schema generated from the Runpod OpenAPI document.",
  }),
);

/**
 * GetDocsStatus200TextResponse value generated from the Runpod OpenAPI document.
 *
 * **Example** (Reference the GetDocsStatus200TextResponse type)
 *
 * ```ts
 * import type { GetDocsStatus200TextResponse } from "@beep/runpod"
 *
 * type GetDocsStatus200TextResponseValue = GetDocsStatus200TextResponse
 * ```
 *
 * @category type-level
 * @since 0.1.0
 */
export type GetDocsStatus200TextResponse =
  typeof GetDocsStatus200TextResponse.Type;

/**
 * Request input for GetOpenAPI.
 *
 * **Example** (Inspect the GetOpenAPIRequest schema)
 *
 * ```ts
 * import { GetOpenAPIRequest } from "@beep/runpod"
 *
 * console.log(GetOpenAPIRequest.ast)
 * ```
 *
 * @category dtos
 * @since 0.1.0
 */
export class GetOpenAPIRequest extends S.Class<GetOpenAPIRequest>(
  $I`GetOpenAPIRequest`,
)(
  {},
  $I.annote("GetOpenAPIRequest", {
    description: "Request input for GetOpenAPI.",
  }),
) {}

/**
 * Request input for GetDocs.
 *
 * **Example** (Inspect the GetDocsRequest schema)
 *
 * ```ts
 * import { GetDocsRequest } from "@beep/runpod"
 *
 * console.log(GetDocsRequest.ast)
 * ```
 *
 * @category dtos
 * @since 0.1.0
 */
export class GetDocsRequest extends S.Class<GetDocsRequest>($I`GetDocsRequest`)(
  {},
  $I.annote("GetDocsRequest", {
    description: "Request input for GetDocs.",
  }),
) {}

/**
 * Request input for ListPods.
 *
 * **Example** (Inspect the ListPodsRequest schema)
 *
 * ```ts
 * import { ListPodsRequest } from "@beep/runpod"
 *
 * console.log(ListPodsRequest.ast)
 * ```
 *
 * @category dtos
 * @since 0.1.0
 */
export class ListPodsRequest extends S.Class<ListPodsRequest>(
  $I`ListPodsRequest`,
)(
  {
    computeType: LiteralKit(["GPU", "CPU"]).pipe(S.optionalKey),
    cpuFlavorId: S.String.pipe(S.Array, S.optionalKey),
    dataCenterId: S.String.pipe(S.Array, S.optionalKey),
    desiredStatus: LiteralKit(["RUNNING", "EXITED", "TERMINATED"]).pipe(
      S.optionalKey,
    ),
    endpointId: S.String.pipe(S.optionalKey),
    gpuTypeId: S.String.pipe(S.Array, S.optionalKey),
    id: S.String.pipe(S.optionalKey),
    imageName: S.String.pipe(S.optionalKey),
    includeMachine: S.Boolean.pipe(S.optionalKey),
    includeNetworkVolume: S.Boolean.pipe(S.optionalKey),
    includeSavingsPlans: S.Boolean.pipe(S.optionalKey),
    includeTemplate: S.Boolean.pipe(S.optionalKey),
    includeWorkers: S.Boolean.pipe(S.optionalKey),
    name: S.String.pipe(S.optionalKey),
    networkVolumeId: S.String.pipe(S.optionalKey),
    templateId: S.String.pipe(S.optionalKey),
  },
  $I.annote("ListPodsRequest", {
    description: "Request input for ListPods.",
  }),
) {}

/**
 * Request input for CreatePod.
 *
 * **Example** (Inspect the CreatePodRequest schema)
 *
 * ```ts
 * import { CreatePodRequest } from "@beep/runpod"
 *
 * console.log(CreatePodRequest.ast)
 * ```
 *
 * @category dtos
 * @since 0.1.0
 */
export class CreatePodRequest extends S.Class<CreatePodRequest>(
  $I`CreatePodRequest`,
)(
  {
    body: S.suspend(() => Models.PodCreateInput),
  },
  $I.annote("CreatePodRequest", {
    description: "Request input for CreatePod.",
  }),
) {}

/**
 * Request input for GetPod.
 *
 * **Example** (Inspect the GetPodRequest schema)
 *
 * ```ts
 * import { GetPodRequest } from "@beep/runpod"
 *
 * console.log(GetPodRequest.ast)
 * ```
 *
 * @category dtos
 * @since 0.1.0
 */
export class GetPodRequest extends S.Class<GetPodRequest>($I`GetPodRequest`)(
  {
    includeMachine: S.Boolean.pipe(S.optionalKey),
    includeNetworkVolume: S.Boolean.pipe(S.optionalKey),
    includeSavingsPlans: S.Boolean.pipe(S.optionalKey),
    includeTemplate: S.Boolean.pipe(S.optionalKey),
    includeWorkers: S.Boolean.pipe(S.optionalKey),
    podId: S.String,
  },
  $I.annote("GetPodRequest", {
    description: "Request input for GetPod.",
  }),
) {}

/**
 * Request input for UpdatePod.
 *
 * **Example** (Inspect the UpdatePodRequest schema)
 *
 * ```ts
 * import { UpdatePodRequest } from "@beep/runpod"
 *
 * console.log(UpdatePodRequest.ast)
 * ```
 *
 * @category dtos
 * @since 0.1.0
 */
export class UpdatePodRequest extends S.Class<UpdatePodRequest>(
  $I`UpdatePodRequest`,
)(
  {
    podId: S.String,
    body: S.suspend(() => Models.PodUpdateInput),
  },
  $I.annote("UpdatePodRequest", {
    description: "Request input for UpdatePod.",
  }),
) {}

/**
 * Request input for DeletePod.
 *
 * **Example** (Inspect the DeletePodRequest schema)
 *
 * ```ts
 * import { DeletePodRequest } from "@beep/runpod"
 *
 * console.log(DeletePodRequest.ast)
 * ```
 *
 * @category dtos
 * @since 0.1.0
 */
export class DeletePodRequest extends S.Class<DeletePodRequest>(
  $I`DeletePodRequest`,
)(
  {
    podId: S.String,
  },
  $I.annote("DeletePodRequest", {
    description: "Request input for DeletePod.",
  }),
) {}

/**
 * Request input for UpdatePod.
 *
 * **Example** (Inspect the UpdatePodViaPostRequest schema)
 *
 * ```ts
 * import { UpdatePodViaPostRequest } from "@beep/runpod"
 *
 * console.log(UpdatePodViaPostRequest.ast)
 * ```
 *
 * @category dtos
 * @since 0.1.0
 */
export class UpdatePodViaPostRequest extends S.Class<UpdatePodViaPostRequest>(
  $I`UpdatePodViaPostRequest`,
)(
  {
    podId: S.String,
    body: S.suspend(() => Models.PodUpdateInput),
  },
  $I.annote("UpdatePodViaPostRequest", {
    description: "Request input for UpdatePod.",
  }),
) {}

/**
 * Request input for StartPod.
 *
 * **Example** (Inspect the StartPodRequest schema)
 *
 * ```ts
 * import { StartPodRequest } from "@beep/runpod"
 *
 * console.log(StartPodRequest.ast)
 * ```
 *
 * @category dtos
 * @since 0.1.0
 */
export class StartPodRequest extends S.Class<StartPodRequest>(
  $I`StartPodRequest`,
)(
  {
    podId: S.String,
  },
  $I.annote("StartPodRequest", {
    description: "Request input for StartPod.",
  }),
) {}

/**
 * Request input for StopPod.
 *
 * **Example** (Inspect the StopPodRequest schema)
 *
 * ```ts
 * import { StopPodRequest } from "@beep/runpod"
 *
 * console.log(StopPodRequest.ast)
 * ```
 *
 * @category dtos
 * @since 0.1.0
 */
export class StopPodRequest extends S.Class<StopPodRequest>($I`StopPodRequest`)(
  {
    podId: S.String,
  },
  $I.annote("StopPodRequest", {
    description: "Request input for StopPod.",
  }),
) {}

/**
 * Request input for ResetPod.
 *
 * **Example** (Inspect the ResetPodRequest schema)
 *
 * ```ts
 * import { ResetPodRequest } from "@beep/runpod"
 *
 * console.log(ResetPodRequest.ast)
 * ```
 *
 * @category dtos
 * @since 0.1.0
 */
export class ResetPodRequest extends S.Class<ResetPodRequest>(
  $I`ResetPodRequest`,
)(
  {
    podId: S.String,
  },
  $I.annote("ResetPodRequest", {
    description: "Request input for ResetPod.",
  }),
) {}

/**
 * Request input for RestartPod.
 *
 * **Example** (Inspect the RestartPodRequest schema)
 *
 * ```ts
 * import { RestartPodRequest } from "@beep/runpod"
 *
 * console.log(RestartPodRequest.ast)
 * ```
 *
 * @category dtos
 * @since 0.1.0
 */
export class RestartPodRequest extends S.Class<RestartPodRequest>(
  $I`RestartPodRequest`,
)(
  {
    podId: S.String,
  },
  $I.annote("RestartPodRequest", {
    description: "Request input for RestartPod.",
  }),
) {}

/**
 * Request input for ListEndpoints.
 *
 * **Example** (Inspect the ListEndpointsRequest schema)
 *
 * ```ts
 * import { ListEndpointsRequest } from "@beep/runpod"
 *
 * console.log(ListEndpointsRequest.ast)
 * ```
 *
 * @category dtos
 * @since 0.1.0
 */
export class ListEndpointsRequest extends S.Class<ListEndpointsRequest>(
  $I`ListEndpointsRequest`,
)(
  {
    includeTemplate: S.Boolean.pipe(S.optionalKey),
    includeWorkers: S.Boolean.pipe(S.optionalKey),
  },
  $I.annote("ListEndpointsRequest", {
    description: "Request input for ListEndpoints.",
  }),
) {}

/**
 * Request input for CreateEndpoint.
 *
 * **Example** (Inspect the CreateEndpointRequest schema)
 *
 * ```ts
 * import { CreateEndpointRequest } from "@beep/runpod"
 *
 * console.log(CreateEndpointRequest.ast)
 * ```
 *
 * @category dtos
 * @since 0.1.0
 */
export class CreateEndpointRequest extends S.Class<CreateEndpointRequest>(
  $I`CreateEndpointRequest`,
)(
  {
    body: S.suspend(() => Models.EndpointCreateInput),
  },
  $I.annote("CreateEndpointRequest", {
    description: "Request input for CreateEndpoint.",
  }),
) {}

/**
 * Request input for GetEndpoint.
 *
 * **Example** (Inspect the GetEndpointRequest schema)
 *
 * ```ts
 * import { GetEndpointRequest } from "@beep/runpod"
 *
 * console.log(GetEndpointRequest.ast)
 * ```
 *
 * @category dtos
 * @since 0.1.0
 */
export class GetEndpointRequest extends S.Class<GetEndpointRequest>(
  $I`GetEndpointRequest`,
)(
  {
    endpointId: S.String,
    includeTemplate: S.Boolean.pipe(S.optionalKey),
    includeWorkers: S.Boolean.pipe(S.optionalKey),
  },
  $I.annote("GetEndpointRequest", {
    description: "Request input for GetEndpoint.",
  }),
) {}

/**
 * Request input for UpdateEndpoint.
 *
 * **Example** (Inspect the UpdateEndpointRequest schema)
 *
 * ```ts
 * import { UpdateEndpointRequest } from "@beep/runpod"
 *
 * console.log(UpdateEndpointRequest.ast)
 * ```
 *
 * @category dtos
 * @since 0.1.0
 */
export class UpdateEndpointRequest extends S.Class<UpdateEndpointRequest>(
  $I`UpdateEndpointRequest`,
)(
  {
    endpointId: S.String,
    body: S.suspend(() => Models.EndpointUpdateInput),
  },
  $I.annote("UpdateEndpointRequest", {
    description: "Request input for UpdateEndpoint.",
  }),
) {}

/**
 * Request input for DeleteEndpoint.
 *
 * **Example** (Inspect the DeleteEndpointRequest schema)
 *
 * ```ts
 * import { DeleteEndpointRequest } from "@beep/runpod"
 *
 * console.log(DeleteEndpointRequest.ast)
 * ```
 *
 * @category dtos
 * @since 0.1.0
 */
export class DeleteEndpointRequest extends S.Class<DeleteEndpointRequest>(
  $I`DeleteEndpointRequest`,
)(
  {
    endpointId: S.String,
  },
  $I.annote("DeleteEndpointRequest", {
    description: "Request input for DeleteEndpoint.",
  }),
) {}

/**
 * Request input for UpdateEndpoint.
 *
 * **Example** (Inspect the UpdateEndpointViaPostRequest schema)
 *
 * ```ts
 * import { UpdateEndpointViaPostRequest } from "@beep/runpod"
 *
 * console.log(UpdateEndpointViaPostRequest.ast)
 * ```
 *
 * @category dtos
 * @since 0.1.0
 */
export class UpdateEndpointViaPostRequest extends S.Class<UpdateEndpointViaPostRequest>(
  $I`UpdateEndpointViaPostRequest`,
)(
  {
    endpointId: S.String,
    body: S.suspend(() => Models.EndpointUpdateInput),
  },
  $I.annote("UpdateEndpointViaPostRequest", {
    description: "Request input for UpdateEndpoint.",
  }),
) {}

/**
 * Request input for ListTemplates.
 *
 * **Example** (Inspect the ListTemplatesRequest schema)
 *
 * ```ts
 * import { ListTemplatesRequest } from "@beep/runpod"
 *
 * console.log(ListTemplatesRequest.ast)
 * ```
 *
 * @category dtos
 * @since 0.1.0
 */
export class ListTemplatesRequest extends S.Class<ListTemplatesRequest>(
  $I`ListTemplatesRequest`,
)(
  {
    includeEndpointBoundTemplates: S.Boolean.pipe(S.optionalKey),
    includePublicTemplates: S.Boolean.pipe(S.optionalKey),
    includeRunpodTemplates: S.Boolean.pipe(S.optionalKey),
  },
  $I.annote("ListTemplatesRequest", {
    description: "Request input for ListTemplates.",
  }),
) {}

/**
 * Request input for CreateTemplate.
 *
 * **Example** (Inspect the CreateTemplateRequest schema)
 *
 * ```ts
 * import { CreateTemplateRequest } from "@beep/runpod"
 *
 * console.log(CreateTemplateRequest.ast)
 * ```
 *
 * @category dtos
 * @since 0.1.0
 */
export class CreateTemplateRequest extends S.Class<CreateTemplateRequest>(
  $I`CreateTemplateRequest`,
)(
  {
    body: S.suspend(() => Models.TemplateCreateInput),
  },
  $I.annote("CreateTemplateRequest", {
    description: "Request input for CreateTemplate.",
  }),
) {}

/**
 * Request input for GetTemplate.
 *
 * **Example** (Inspect the GetTemplateRequest schema)
 *
 * ```ts
 * import { GetTemplateRequest } from "@beep/runpod"
 *
 * console.log(GetTemplateRequest.ast)
 * ```
 *
 * @category dtos
 * @since 0.1.0
 */
export class GetTemplateRequest extends S.Class<GetTemplateRequest>(
  $I`GetTemplateRequest`,
)(
  {
    includeEndpointBoundTemplates: S.Boolean.pipe(S.optionalKey),
    includePublicTemplates: S.Boolean.pipe(S.optionalKey),
    includeRunpodTemplates: S.Boolean.pipe(S.optionalKey),
    templateId: S.String,
  },
  $I.annote("GetTemplateRequest", {
    description: "Request input for GetTemplate.",
  }),
) {}

/**
 * Request input for UpdateTemplate.
 *
 * **Example** (Inspect the UpdateTemplateRequest schema)
 *
 * ```ts
 * import { UpdateTemplateRequest } from "@beep/runpod"
 *
 * console.log(UpdateTemplateRequest.ast)
 * ```
 *
 * @category dtos
 * @since 0.1.0
 */
export class UpdateTemplateRequest extends S.Class<UpdateTemplateRequest>(
  $I`UpdateTemplateRequest`,
)(
  {
    templateId: S.String,
    body: S.suspend(() => Models.TemplateUpdateInput),
  },
  $I.annote("UpdateTemplateRequest", {
    description: "Request input for UpdateTemplate.",
  }),
) {}

/**
 * Request input for DeleteTemplate.
 *
 * **Example** (Inspect the DeleteTemplateRequest schema)
 *
 * ```ts
 * import { DeleteTemplateRequest } from "@beep/runpod"
 *
 * console.log(DeleteTemplateRequest.ast)
 * ```
 *
 * @category dtos
 * @since 0.1.0
 */
export class DeleteTemplateRequest extends S.Class<DeleteTemplateRequest>(
  $I`DeleteTemplateRequest`,
)(
  {
    templateId: S.String,
  },
  $I.annote("DeleteTemplateRequest", {
    description: "Request input for DeleteTemplate.",
  }),
) {}

/**
 * Request input for UpdateTemplate.
 *
 * **Example** (Inspect the UpdateTemplateViaPostRequest schema)
 *
 * ```ts
 * import { UpdateTemplateViaPostRequest } from "@beep/runpod"
 *
 * console.log(UpdateTemplateViaPostRequest.ast)
 * ```
 *
 * @category dtos
 * @since 0.1.0
 */
export class UpdateTemplateViaPostRequest extends S.Class<UpdateTemplateViaPostRequest>(
  $I`UpdateTemplateViaPostRequest`,
)(
  {
    templateId: S.String,
    body: S.suspend(() => Models.TemplateUpdateInput),
  },
  $I.annote("UpdateTemplateViaPostRequest", {
    description: "Request input for UpdateTemplate.",
  }),
) {}

/**
 * Request input for ListNetworkVolumes.
 *
 * **Example** (Inspect the ListNetworkVolumesRequest schema)
 *
 * ```ts
 * import { ListNetworkVolumesRequest } from "@beep/runpod"
 *
 * console.log(ListNetworkVolumesRequest.ast)
 * ```
 *
 * @category dtos
 * @since 0.1.0
 */
export class ListNetworkVolumesRequest extends S.Class<ListNetworkVolumesRequest>(
  $I`ListNetworkVolumesRequest`,
)(
  {},
  $I.annote("ListNetworkVolumesRequest", {
    description: "Request input for ListNetworkVolumes.",
  }),
) {}

/**
 * Request input for CreateNetworkVolume.
 *
 * **Example** (Inspect the CreateNetworkVolumeRequest schema)
 *
 * ```ts
 * import { CreateNetworkVolumeRequest } from "@beep/runpod"
 *
 * console.log(CreateNetworkVolumeRequest.ast)
 * ```
 *
 * @category dtos
 * @since 0.1.0
 */
export class CreateNetworkVolumeRequest extends S.Class<CreateNetworkVolumeRequest>(
  $I`CreateNetworkVolumeRequest`,
)(
  {
    body: S.suspend(() => Models.NetworkVolumeCreateInput),
  },
  $I.annote("CreateNetworkVolumeRequest", {
    description: "Request input for CreateNetworkVolume.",
  }),
) {}

/**
 * Request input for GetNetworkVolume.
 *
 * **Example** (Inspect the GetNetworkVolumeRequest schema)
 *
 * ```ts
 * import { GetNetworkVolumeRequest } from "@beep/runpod"
 *
 * console.log(GetNetworkVolumeRequest.ast)
 * ```
 *
 * @category dtos
 * @since 0.1.0
 */
export class GetNetworkVolumeRequest extends S.Class<GetNetworkVolumeRequest>(
  $I`GetNetworkVolumeRequest`,
)(
  {
    networkVolumeId: S.String,
  },
  $I.annote("GetNetworkVolumeRequest", {
    description: "Request input for GetNetworkVolume.",
  }),
) {}

/**
 * Request input for UpdateNetworkVolume.
 *
 * **Example** (Inspect the UpdateNetworkVolumeRequest schema)
 *
 * ```ts
 * import { UpdateNetworkVolumeRequest } from "@beep/runpod"
 *
 * console.log(UpdateNetworkVolumeRequest.ast)
 * ```
 *
 * @category dtos
 * @since 0.1.0
 */
export class UpdateNetworkVolumeRequest extends S.Class<UpdateNetworkVolumeRequest>(
  $I`UpdateNetworkVolumeRequest`,
)(
  {
    networkVolumeId: S.String,
    body: S.suspend(() => Models.NetworkVolumeUpdateInput),
  },
  $I.annote("UpdateNetworkVolumeRequest", {
    description: "Request input for UpdateNetworkVolume.",
  }),
) {}

/**
 * Request input for DeleteNetworkVolume.
 *
 * **Example** (Inspect the DeleteNetworkVolumeRequest schema)
 *
 * ```ts
 * import { DeleteNetworkVolumeRequest } from "@beep/runpod"
 *
 * console.log(DeleteNetworkVolumeRequest.ast)
 * ```
 *
 * @category dtos
 * @since 0.1.0
 */
export class DeleteNetworkVolumeRequest extends S.Class<DeleteNetworkVolumeRequest>(
  $I`DeleteNetworkVolumeRequest`,
)(
  {
    networkVolumeId: S.String,
  },
  $I.annote("DeleteNetworkVolumeRequest", {
    description: "Request input for DeleteNetworkVolume.",
  }),
) {}

/**
 * Request input for UpdateNetworkVolume.
 *
 * **Example** (Inspect the UpdateNetworkVolumeViaPostRequest schema)
 *
 * ```ts
 * import { UpdateNetworkVolumeViaPostRequest } from "@beep/runpod"
 *
 * console.log(UpdateNetworkVolumeViaPostRequest.ast)
 * ```
 *
 * @category dtos
 * @since 0.1.0
 */
export class UpdateNetworkVolumeViaPostRequest extends S.Class<UpdateNetworkVolumeViaPostRequest>(
  $I`UpdateNetworkVolumeViaPostRequest`,
)(
  {
    networkVolumeId: S.String,
    body: S.suspend(() => Models.NetworkVolumeUpdateInput),
  },
  $I.annote("UpdateNetworkVolumeViaPostRequest", {
    description: "Request input for UpdateNetworkVolume.",
  }),
) {}

/**
 * Request input for ListContainerRegistryAuths.
 *
 * **Example** (Inspect the ListContainerRegistryAuthsRequest schema)
 *
 * ```ts
 * import { ListContainerRegistryAuthsRequest } from "@beep/runpod"
 *
 * console.log(ListContainerRegistryAuthsRequest.ast)
 * ```
 *
 * @category dtos
 * @since 0.1.0
 */
export class ListContainerRegistryAuthsRequest extends S.Class<ListContainerRegistryAuthsRequest>(
  $I`ListContainerRegistryAuthsRequest`,
)(
  {},
  $I.annote("ListContainerRegistryAuthsRequest", {
    description: "Request input for ListContainerRegistryAuths.",
  }),
) {}

/**
 * Request input for CreateContainerRegistryAuth.
 *
 * **Example** (Inspect the CreateContainerRegistryAuthRequest schema)
 *
 * ```ts
 * import { CreateContainerRegistryAuthRequest } from "@beep/runpod"
 *
 * console.log(CreateContainerRegistryAuthRequest.ast)
 * ```
 *
 * @category dtos
 * @since 0.1.0
 */
export class CreateContainerRegistryAuthRequest extends S.Class<CreateContainerRegistryAuthRequest>(
  $I`CreateContainerRegistryAuthRequest`,
)(
  {
    body: S.suspend(() => Models.ContainerRegistryAuthCreateInput),
  },
  $I.annote("CreateContainerRegistryAuthRequest", {
    description: "Request input for CreateContainerRegistryAuth.",
  }),
) {}

/**
 * Request input for GetContainerRegistryAuth.
 *
 * **Example** (Inspect the GetContainerRegistryAuthRequest schema)
 *
 * ```ts
 * import { GetContainerRegistryAuthRequest } from "@beep/runpod"
 *
 * console.log(GetContainerRegistryAuthRequest.ast)
 * ```
 *
 * @category dtos
 * @since 0.1.0
 */
export class GetContainerRegistryAuthRequest extends S.Class<GetContainerRegistryAuthRequest>(
  $I`GetContainerRegistryAuthRequest`,
)(
  {
    containerRegistryAuthId: S.String,
  },
  $I.annote("GetContainerRegistryAuthRequest", {
    description: "Request input for GetContainerRegistryAuth.",
  }),
) {}

/**
 * Request input for DeleteContainerRegistryAuth.
 *
 * **Example** (Inspect the DeleteContainerRegistryAuthRequest schema)
 *
 * ```ts
 * import { DeleteContainerRegistryAuthRequest } from "@beep/runpod"
 *
 * console.log(DeleteContainerRegistryAuthRequest.ast)
 * ```
 *
 * @category dtos
 * @since 0.1.0
 */
export class DeleteContainerRegistryAuthRequest extends S.Class<DeleteContainerRegistryAuthRequest>(
  $I`DeleteContainerRegistryAuthRequest`,
)(
  {
    containerRegistryAuthId: S.String,
  },
  $I.annote("DeleteContainerRegistryAuthRequest", {
    description: "Request input for DeleteContainerRegistryAuth.",
  }),
) {}

/**
 * Request input for PodBilling.
 *
 * **Example** (Inspect the PodBillingRequest schema)
 *
 * ```ts
 * import { PodBillingRequest } from "@beep/runpod"
 *
 * console.log(PodBillingRequest.ast)
 * ```
 *
 * @category dtos
 * @since 0.1.0
 */
export class PodBillingRequest extends S.Class<PodBillingRequest>(
  $I`PodBillingRequest`,
)(
  {
    bucketSize: LiteralKit(["hour", "day", "week", "month", "year"]).pipe(
      S.optionalKey,
    ),
    endTime: S.String.pipe(S.optionalKey),
    gpuTypeId: S.String.pipe(S.optionalKey),
    grouping: LiteralKit(["podId", "gpuTypeId"]).pipe(S.optionalKey),
    podId: S.String.pipe(S.optionalKey),
    startTime: S.String.pipe(S.optionalKey),
  },
  $I.annote("PodBillingRequest", {
    description: "Request input for PodBilling.",
  }),
) {}

/**
 * Request input for EndpointBilling.
 *
 * **Example** (Inspect the EndpointBillingRequest schema)
 *
 * ```ts
 * import { EndpointBillingRequest } from "@beep/runpod"
 *
 * console.log(EndpointBillingRequest.ast)
 * ```
 *
 * @category dtos
 * @since 0.1.0
 */
export class EndpointBillingRequest extends S.Class<EndpointBillingRequest>(
  $I`EndpointBillingRequest`,
)(
  {
    bucketSize: LiteralKit(["hour", "day", "week", "month", "year"]).pipe(
      S.optionalKey,
    ),
    dataCenterId: S.String.pipe(S.Array, S.optionalKey),
    endpointId: S.String.pipe(S.optionalKey),
    endTime: S.String.pipe(S.optionalKey),
    gpuTypeId: S.String.pipe(S.Array, S.optionalKey),
    grouping: LiteralKit(["endpointId", "podId", "gpuTypeId"]).pipe(
      S.optionalKey,
    ),
    imageName: S.String.pipe(S.optionalKey),
    startTime: S.String.pipe(S.optionalKey),
    templateId: S.String.pipe(S.optionalKey),
  },
  $I.annote("EndpointBillingRequest", {
    description: "Request input for EndpointBilling.",
  }),
) {}

/**
 * Request input for NetworkVolumeBilling.
 *
 * **Example** (Inspect the NetworkVolumeBillingRequest schema)
 *
 * ```ts
 * import { NetworkVolumeBillingRequest } from "@beep/runpod"
 *
 * console.log(NetworkVolumeBillingRequest.ast)
 * ```
 *
 * @category dtos
 * @since 0.1.0
 */
export class NetworkVolumeBillingRequest extends S.Class<NetworkVolumeBillingRequest>(
  $I`NetworkVolumeBillingRequest`,
)(
  {
    bucketSize: LiteralKit(["hour", "day", "week", "month", "year"]).pipe(
      S.optionalKey,
    ),
    endTime: S.String.pipe(S.optionalKey),
    startTime: S.String.pipe(S.optionalKey),
  },
  $I.annote("NetworkVolumeBillingRequest", {
    description: "Request input for NetworkVolumeBilling.",
  }),
) {}

const RunpodHttpMethodBase = LiteralKit(["GET", "POST", "PATCH", "DELETE"]);
/**
 * Supported Runpod HTTP methods.
 *
 * **Example** (Inspect the RunpodHttpMethod schema)
 *
 * ```ts
 * import { RunpodHttpMethod } from "@beep/runpod"
 *
 * console.log(RunpodHttpMethod.ast)
 * ```
 *
 * @category schemas
 * @since 0.0.0
 */
export const RunpodHttpMethod = RunpodHttpMethodBase.pipe(
  $I.annoteSchema("RunpodHttpMethod", {
    description: "Supported Runpod HTTP methods.",
  }),
  SchemaUtils.withLiteralKitStatics(RunpodHttpMethodBase),
  SchemaUtils.withStatics((schema) => ({
    decodeOption: S.decodeUnknownOption(schema),
    fromUnknown: S.decodeUnknownSync(schema),
  })),
);

/**
 * Supported Runpod HTTP method.
 *
 * **Example** (Reference the RunpodHttpMethod type)
 *
 * ```ts
 * import type { RunpodHttpMethod } from "@beep/runpod"
 *
 * type Method = RunpodHttpMethod
 * ```
 *
 * @category type-level
 * @since 0.1.0
 */
export type RunpodHttpMethod = typeof RunpodHttpMethod.Type;

const RunpodOperationIdBase = LiteralKit([
  "GetOpenAPI",
  "GetDocs",
  "ListPods",
  "CreatePod",
  "GetPod",
  "UpdatePod",
  "DeletePod",
  "StartPod",
  "StopPod",
  "ResetPod",
  "RestartPod",
  "ListEndpoints",
  "CreateEndpoint",
  "GetEndpoint",
  "UpdateEndpoint",
  "DeleteEndpoint",
  "ListTemplates",
  "CreateTemplate",
  "GetTemplate",
  "UpdateTemplate",
  "DeleteTemplate",
  "ListNetworkVolumes",
  "CreateNetworkVolume",
  "GetNetworkVolume",
  "UpdateNetworkVolume",
  "DeleteNetworkVolume",
  "ListContainerRegistryAuths",
  "CreateContainerRegistryAuth",
  "GetContainerRegistryAuth",
  "DeleteContainerRegistryAuth",
  "PodBilling",
  "EndpointBilling",
  "NetworkVolumeBilling",
]);
/**
 * Operation ids exposed by Runpod REST API v1.
 *
 * **Example** (Inspect the RunpodOperationId schema)
 *
 * ```ts
 * import { RunpodOperationId } from "@beep/runpod"
 *
 * console.log(RunpodOperationId.ast)
 * ```
 *
 * @category schemas
 * @since 0.0.0
 */
export const RunpodOperationId = RunpodOperationIdBase.pipe(
  $I.annoteSchema("RunpodOperationId", {
    description: "Operation ids exposed by Runpod REST API v1.",
  }),
  SchemaUtils.withLiteralKitStatics(RunpodOperationIdBase),
  SchemaUtils.withStatics((schema) => ({
    decodeOption: S.decodeUnknownOption(schema),
    fromUnknown: S.decodeUnknownSync(schema),
  })),
);

/**
 * Operation id exposed by Runpod REST API v1.
 *
 * **Example** (Reference the RunpodOperationId type)
 *
 * ```ts
 * import type { RunpodOperationId } from "@beep/runpod"
 *
 * type OperationId = RunpodOperationId
 * ```
 *
 * @category type-level
 * @since 0.1.0
 */
export type RunpodOperationId = typeof RunpodOperationId.Type;

const RunpodRequestBodyKindBase = LiteralKit(["json", "none"]);
/**
 * Request body encoding used by a Runpod operation.
 *
 * **Example** (Inspect the RunpodRequestBodyKind schema)
 *
 * ```ts
 * import { RunpodRequestBodyKind } from "@beep/runpod"
 *
 * console.log(RunpodRequestBodyKind.ast)
 * ```
 *
 * @category schemas
 * @since 0.0.0
 */
export const RunpodRequestBodyKind = RunpodRequestBodyKindBase.pipe(
  $I.annoteSchema("RunpodRequestBodyKind", {
    description: "Request body encoding used by a Runpod operation.",
  }),
  SchemaUtils.withLiteralKitStatics(RunpodRequestBodyKindBase),
  SchemaUtils.withStatics((schema) => ({
    decodeOption: S.decodeUnknownOption(schema),
    fromUnknown: S.decodeUnknownSync(schema),
  })),
);

/**
 * Request body encoding used by a Runpod operation.
 *
 * **Example** (Reference the RunpodRequestBodyKind type)
 *
 * ```ts
 * import type { RunpodRequestBodyKind } from "@beep/runpod"
 *
 * type RequestBodyKind = RunpodRequestBodyKind
 * ```
 *
 * @category type-level
 * @since 0.1.0
 */
export type RunpodRequestBodyKind = typeof RunpodRequestBodyKind.Type;

const RunpodResponseBodyKindBase = LiteralKit(["json", "none", "text"]);
/**
 * Response body decoding used by a Runpod operation.
 *
 * **Example** (Inspect the RunpodResponseBodyKind schema)
 *
 * ```ts
 * import { RunpodResponseBodyKind } from "@beep/runpod"
 *
 * console.log(RunpodResponseBodyKind.ast)
 * ```
 *
 * @category schemas
 * @since 0.0.0
 */
export const RunpodResponseBodyKind = RunpodResponseBodyKindBase.pipe(
  $I.annoteSchema("RunpodResponseBodyKind", {
    description: "Response body decoding used by a Runpod operation.",
  }),
  SchemaUtils.withLiteralKitStatics(RunpodResponseBodyKindBase),
  SchemaUtils.withStatics((schema) => ({
    decodeOption: S.decodeUnknownOption(schema),
    fromUnknown: S.decodeUnknownSync(schema),
  })),
);

/**
 * Response body decoding used by a Runpod operation.
 *
 * **Example** (Reference the RunpodResponseBodyKind type)
 *
 * ```ts
 * import type { RunpodResponseBodyKind } from "@beep/runpod"
 *
 * type ResponseBodyKind = RunpodResponseBodyKind
 * ```
 *
 * @category type-level
 * @since 0.1.0
 */
export type RunpodResponseBodyKind = typeof RunpodResponseBodyKind.Type;

/**
 * Static metadata for one Runpod REST operation.
 *
 * **Example** (Inspect the RunpodOperationDescriptor schema)
 *
 * ```ts
 * import { RunpodOperationDescriptor } from "@beep/runpod"
 *
 * console.log(RunpodOperationDescriptor.ast)
 * ```
 *
 * @category models
 * @since 0.1.0
 */
export class RunpodOperationDescriptor extends S.Class<RunpodOperationDescriptor>(
  $I`RunpodOperationDescriptor`,
)(
  {
    authenticated: S.Boolean,
    method: RunpodHttpMethod,
    methodName: S.String,
    operationId: RunpodOperationId,
    path: S.String,
    pathParams: S.Array(S.String),
    queryParams: S.Array(S.String),
    requestBody: RunpodRequestBodyKind,
    requestBodyRequired: S.Boolean,
    responseBody: RunpodResponseBodyKind,
    status: S.String,
  },
  $I.annote("RunpodOperationDescriptor", {
    description: "Static metadata for one Runpod REST operation.",
  }),
) {
  static readonly is = S.is(RunpodOperationDescriptor);
}

/**
 * Descriptor for GetOpenAPI.
 *
 * **Example** (Read the getOpenAPIOperation path)
 *
 * ```ts
 * import { getOpenAPIOperation } from "@beep/runpod"
 *
 * console.log(getOpenAPIOperation.path)
 * ```
 *
 * @category constants
 * @since 0.1.0
 */
export const getOpenAPIOperation = RunpodOperationDescriptor.make({
  authenticated: false,
  method: "GET",
  methodName: "getOpenAPI",
  operationId: "GetOpenAPI",
  path: "/openapi.json",
  pathParams: [],
  queryParams: [],
  requestBody: "none",
  requestBodyRequired: false,
  responseBody: "json",
  status: "200",
});

/**
 * Descriptor for GetDocs.
 *
 * **Example** (Read the getDocsOperation path)
 *
 * ```ts
 * import { getDocsOperation } from "@beep/runpod"
 *
 * console.log(getDocsOperation.path)
 * ```
 *
 * @category constants
 * @since 0.1.0
 */
export const getDocsOperation = RunpodOperationDescriptor.make({
  authenticated: false,
  method: "GET",
  methodName: "getDocs",
  operationId: "GetDocs",
  path: "/docs",
  pathParams: [],
  queryParams: [],
  requestBody: "none",
  requestBodyRequired: false,
  responseBody: "text",
  status: "200",
});

/**
 * Descriptor for ListPods.
 *
 * **Example** (Read the listPodsOperation path)
 *
 * ```ts
 * import { listPodsOperation } from "@beep/runpod"
 *
 * console.log(listPodsOperation.path)
 * ```
 *
 * @category constants
 * @since 0.1.0
 */
export const listPodsOperation = RunpodOperationDescriptor.make({
  authenticated: true,
  method: "GET",
  methodName: "listPods",
  operationId: "ListPods",
  path: "/pods",
  pathParams: [],
  queryParams: [
    "computeType",
    "cpuFlavorId",
    "dataCenterId",
    "desiredStatus",
    "endpointId",
    "gpuTypeId",
    "id",
    "imageName",
    "includeMachine",
    "includeNetworkVolume",
    "includeSavingsPlans",
    "includeTemplate",
    "includeWorkers",
    "name",
    "networkVolumeId",
    "templateId",
  ],
  requestBody: "none",
  requestBodyRequired: false,
  responseBody: "json",
  status: "200",
});

/**
 * Descriptor for CreatePod.
 *
 * **Example** (Read the createPodOperation path)
 *
 * ```ts
 * import { createPodOperation } from "@beep/runpod"
 *
 * console.log(createPodOperation.path)
 * ```
 *
 * @category constants
 * @since 0.1.0
 */
export const createPodOperation = RunpodOperationDescriptor.make({
  authenticated: true,
  method: "POST",
  methodName: "createPod",
  operationId: "CreatePod",
  path: "/pods",
  pathParams: [],
  queryParams: [],
  requestBody: "json",
  requestBodyRequired: true,
  responseBody: "json",
  status: "201",
});

/**
 * Descriptor for GetPod.
 *
 * **Example** (Read the getPodOperation path)
 *
 * ```ts
 * import { getPodOperation } from "@beep/runpod"
 *
 * console.log(getPodOperation.path)
 * ```
 *
 * @category constants
 * @since 0.1.0
 */
export const getPodOperation = RunpodOperationDescriptor.make({
  authenticated: true,
  method: "GET",
  methodName: "getPod",
  operationId: "GetPod",
  path: "/pods/{podId}",
  pathParams: ["podId"],
  queryParams: [
    "includeMachine",
    "includeNetworkVolume",
    "includeSavingsPlans",
    "includeTemplate",
    "includeWorkers",
  ],
  requestBody: "none",
  requestBodyRequired: false,
  responseBody: "json",
  status: "200",
});

/**
 * Descriptor for UpdatePod.
 *
 * **Example** (Read the updatePodOperation path)
 *
 * ```ts
 * import { updatePodOperation } from "@beep/runpod"
 *
 * console.log(updatePodOperation.path)
 * ```
 *
 * @category constants
 * @since 0.1.0
 */
export const updatePodOperation = RunpodOperationDescriptor.make({
  authenticated: true,
  method: "PATCH",
  methodName: "updatePod",
  operationId: "UpdatePod",
  path: "/pods/{podId}",
  pathParams: ["podId"],
  queryParams: [],
  requestBody: "json",
  requestBodyRequired: true,
  responseBody: "json",
  status: "200",
});

/**
 * Descriptor for DeletePod.
 *
 * **Example** (Read the deletePodOperation path)
 *
 * ```ts
 * import { deletePodOperation } from "@beep/runpod"
 *
 * console.log(deletePodOperation.path)
 * ```
 *
 * @category constants
 * @since 0.1.0
 */
export const deletePodOperation = RunpodOperationDescriptor.make({
  authenticated: true,
  method: "DELETE",
  methodName: "deletePod",
  operationId: "DeletePod",
  path: "/pods/{podId}",
  pathParams: ["podId"],
  queryParams: [],
  requestBody: "none",
  requestBodyRequired: false,
  responseBody: "none",
  status: "204",
});

/**
 * Descriptor for UpdatePod.
 *
 * **Example** (Read the updatePodViaPostOperation path)
 *
 * ```ts
 * import { updatePodViaPostOperation } from "@beep/runpod"
 *
 * console.log(updatePodViaPostOperation.path)
 * ```
 *
 * @category constants
 * @since 0.1.0
 */
export const updatePodViaPostOperation = RunpodOperationDescriptor.make({
  authenticated: true,
  method: "POST",
  methodName: "updatePodViaPost",
  operationId: "UpdatePod",
  path: "/pods/{podId}/update",
  pathParams: ["podId"],
  queryParams: [],
  requestBody: "json",
  requestBodyRequired: true,
  responseBody: "json",
  status: "200",
});

/**
 * Descriptor for StartPod.
 *
 * **Example** (Read the startPodOperation path)
 *
 * ```ts
 * import { startPodOperation } from "@beep/runpod"
 *
 * console.log(startPodOperation.path)
 * ```
 *
 * @category constants
 * @since 0.1.0
 */
export const startPodOperation = RunpodOperationDescriptor.make({
  authenticated: true,
  method: "POST",
  methodName: "startPod",
  operationId: "StartPod",
  path: "/pods/{podId}/start",
  pathParams: ["podId"],
  queryParams: [],
  requestBody: "none",
  requestBodyRequired: false,
  responseBody: "none",
  status: "200",
});

/**
 * Descriptor for StopPod.
 *
 * **Example** (Read the stopPodOperation path)
 *
 * ```ts
 * import { stopPodOperation } from "@beep/runpod"
 *
 * console.log(stopPodOperation.path)
 * ```
 *
 * @category constants
 * @since 0.1.0
 */
export const stopPodOperation = RunpodOperationDescriptor.make({
  authenticated: true,
  method: "POST",
  methodName: "stopPod",
  operationId: "StopPod",
  path: "/pods/{podId}/stop",
  pathParams: ["podId"],
  queryParams: [],
  requestBody: "none",
  requestBodyRequired: false,
  responseBody: "none",
  status: "200",
});

/**
 * Descriptor for ResetPod.
 *
 * **Example** (Read the resetPodOperation path)
 *
 * ```ts
 * import { resetPodOperation } from "@beep/runpod"
 *
 * console.log(resetPodOperation.path)
 * ```
 *
 * @category constants
 * @since 0.1.0
 */
export const resetPodOperation = RunpodOperationDescriptor.make({
  authenticated: true,
  method: "POST",
  methodName: "resetPod",
  operationId: "ResetPod",
  path: "/pods/{podId}/reset",
  pathParams: ["podId"],
  queryParams: [],
  requestBody: "none",
  requestBodyRequired: false,
  responseBody: "none",
  status: "200",
});

/**
 * Descriptor for RestartPod.
 *
 * **Example** (Read the restartPodOperation path)
 *
 * ```ts
 * import { restartPodOperation } from "@beep/runpod"
 *
 * console.log(restartPodOperation.path)
 * ```
 *
 * @category constants
 * @since 0.1.0
 */
export const restartPodOperation = RunpodOperationDescriptor.make({
  authenticated: true,
  method: "POST",
  methodName: "restartPod",
  operationId: "RestartPod",
  path: "/pods/{podId}/restart",
  pathParams: ["podId"],
  queryParams: [],
  requestBody: "none",
  requestBodyRequired: false,
  responseBody: "none",
  status: "400",
});

/**
 * Descriptor for ListEndpoints.
 *
 * **Example** (Read the listEndpointsOperation path)
 *
 * ```ts
 * import { listEndpointsOperation } from "@beep/runpod"
 *
 * console.log(listEndpointsOperation.path)
 * ```
 *
 * @category constants
 * @since 0.1.0
 */
export const listEndpointsOperation = RunpodOperationDescriptor.make({
  authenticated: true,
  method: "GET",
  methodName: "listEndpoints",
  operationId: "ListEndpoints",
  path: "/endpoints",
  pathParams: [],
  queryParams: ["includeTemplate", "includeWorkers"],
  requestBody: "none",
  requestBodyRequired: false,
  responseBody: "json",
  status: "200",
});

/**
 * Descriptor for CreateEndpoint.
 *
 * **Example** (Read the createEndpointOperation path)
 *
 * ```ts
 * import { createEndpointOperation } from "@beep/runpod"
 *
 * console.log(createEndpointOperation.path)
 * ```
 *
 * @category constants
 * @since 0.1.0
 */
export const createEndpointOperation = RunpodOperationDescriptor.make({
  authenticated: true,
  method: "POST",
  methodName: "createEndpoint",
  operationId: "CreateEndpoint",
  path: "/endpoints",
  pathParams: [],
  queryParams: [],
  requestBody: "json",
  requestBodyRequired: true,
  responseBody: "json",
  status: "200",
});

/**
 * Descriptor for GetEndpoint.
 *
 * **Example** (Read the getEndpointOperation path)
 *
 * ```ts
 * import { getEndpointOperation } from "@beep/runpod"
 *
 * console.log(getEndpointOperation.path)
 * ```
 *
 * @category constants
 * @since 0.1.0
 */
export const getEndpointOperation = RunpodOperationDescriptor.make({
  authenticated: true,
  method: "GET",
  methodName: "getEndpoint",
  operationId: "GetEndpoint",
  path: "/endpoints/{endpointId}",
  pathParams: ["endpointId"],
  queryParams: ["includeTemplate", "includeWorkers"],
  requestBody: "none",
  requestBodyRequired: false,
  responseBody: "json",
  status: "200",
});

/**
 * Descriptor for UpdateEndpoint.
 *
 * **Example** (Read the updateEndpointOperation path)
 *
 * ```ts
 * import { updateEndpointOperation } from "@beep/runpod"
 *
 * console.log(updateEndpointOperation.path)
 * ```
 *
 * @category constants
 * @since 0.1.0
 */
export const updateEndpointOperation = RunpodOperationDescriptor.make({
  authenticated: true,
  method: "PATCH",
  methodName: "updateEndpoint",
  operationId: "UpdateEndpoint",
  path: "/endpoints/{endpointId}",
  pathParams: ["endpointId"],
  queryParams: [],
  requestBody: "json",
  requestBodyRequired: true,
  responseBody: "json",
  status: "200",
});

/**
 * Descriptor for DeleteEndpoint.
 *
 * **Example** (Read the deleteEndpointOperation path)
 *
 * ```ts
 * import { deleteEndpointOperation } from "@beep/runpod"
 *
 * console.log(deleteEndpointOperation.path)
 * ```
 *
 * @category constants
 * @since 0.1.0
 */
export const deleteEndpointOperation = RunpodOperationDescriptor.make({
  authenticated: true,
  method: "DELETE",
  methodName: "deleteEndpoint",
  operationId: "DeleteEndpoint",
  path: "/endpoints/{endpointId}",
  pathParams: ["endpointId"],
  queryParams: [],
  requestBody: "none",
  requestBodyRequired: false,
  responseBody: "none",
  status: "204",
});

/**
 * Descriptor for UpdateEndpoint.
 *
 * **Example** (Read the updateEndpointViaPostOperation path)
 *
 * ```ts
 * import { updateEndpointViaPostOperation } from "@beep/runpod"
 *
 * console.log(updateEndpointViaPostOperation.path)
 * ```
 *
 * @category constants
 * @since 0.1.0
 */
export const updateEndpointViaPostOperation = RunpodOperationDescriptor.make({
  authenticated: true,
  method: "POST",
  methodName: "updateEndpointViaPost",
  operationId: "UpdateEndpoint",
  path: "/endpoints/{endpointId}/update",
  pathParams: ["endpointId"],
  queryParams: [],
  requestBody: "json",
  requestBodyRequired: true,
  responseBody: "json",
  status: "200",
});

/**
 * Descriptor for ListTemplates.
 *
 * **Example** (Read the listTemplatesOperation path)
 *
 * ```ts
 * import { listTemplatesOperation } from "@beep/runpod"
 *
 * console.log(listTemplatesOperation.path)
 * ```
 *
 * @category constants
 * @since 0.1.0
 */
export const listTemplatesOperation = RunpodOperationDescriptor.make({
  authenticated: true,
  method: "GET",
  methodName: "listTemplates",
  operationId: "ListTemplates",
  path: "/templates",
  pathParams: [],
  queryParams: [
    "includeEndpointBoundTemplates",
    "includePublicTemplates",
    "includeRunpodTemplates",
  ],
  requestBody: "none",
  requestBodyRequired: false,
  responseBody: "json",
  status: "200",
});

/**
 * Descriptor for CreateTemplate.
 *
 * **Example** (Read the createTemplateOperation path)
 *
 * ```ts
 * import { createTemplateOperation } from "@beep/runpod"
 *
 * console.log(createTemplateOperation.path)
 * ```
 *
 * @category constants
 * @since 0.1.0
 */
export const createTemplateOperation = RunpodOperationDescriptor.make({
  authenticated: true,
  method: "POST",
  methodName: "createTemplate",
  operationId: "CreateTemplate",
  path: "/templates",
  pathParams: [],
  queryParams: [],
  requestBody: "json",
  requestBodyRequired: true,
  responseBody: "json",
  status: "200",
});

/**
 * Descriptor for GetTemplate.
 *
 * **Example** (Read the getTemplateOperation path)
 *
 * ```ts
 * import { getTemplateOperation } from "@beep/runpod"
 *
 * console.log(getTemplateOperation.path)
 * ```
 *
 * @category constants
 * @since 0.1.0
 */
export const getTemplateOperation = RunpodOperationDescriptor.make({
  authenticated: true,
  method: "GET",
  methodName: "getTemplate",
  operationId: "GetTemplate",
  path: "/templates/{templateId}",
  pathParams: ["templateId"],
  queryParams: [
    "includeEndpointBoundTemplates",
    "includePublicTemplates",
    "includeRunpodTemplates",
  ],
  requestBody: "none",
  requestBodyRequired: false,
  responseBody: "json",
  status: "200",
});

/**
 * Descriptor for UpdateTemplate.
 *
 * **Example** (Read the updateTemplateOperation path)
 *
 * ```ts
 * import { updateTemplateOperation } from "@beep/runpod"
 *
 * console.log(updateTemplateOperation.path)
 * ```
 *
 * @category constants
 * @since 0.1.0
 */
export const updateTemplateOperation = RunpodOperationDescriptor.make({
  authenticated: true,
  method: "PATCH",
  methodName: "updateTemplate",
  operationId: "UpdateTemplate",
  path: "/templates/{templateId}",
  pathParams: ["templateId"],
  queryParams: [],
  requestBody: "json",
  requestBodyRequired: true,
  responseBody: "json",
  status: "200",
});

/**
 * Descriptor for DeleteTemplate.
 *
 * **Example** (Read the deleteTemplateOperation path)
 *
 * ```ts
 * import { deleteTemplateOperation } from "@beep/runpod"
 *
 * console.log(deleteTemplateOperation.path)
 * ```
 *
 * @category constants
 * @since 0.1.0
 */
export const deleteTemplateOperation = RunpodOperationDescriptor.make({
  authenticated: true,
  method: "DELETE",
  methodName: "deleteTemplate",
  operationId: "DeleteTemplate",
  path: "/templates/{templateId}",
  pathParams: ["templateId"],
  queryParams: [],
  requestBody: "none",
  requestBodyRequired: false,
  responseBody: "none",
  status: "204",
});

/**
 * Descriptor for UpdateTemplate.
 *
 * **Example** (Read the updateTemplateViaPostOperation path)
 *
 * ```ts
 * import { updateTemplateViaPostOperation } from "@beep/runpod"
 *
 * console.log(updateTemplateViaPostOperation.path)
 * ```
 *
 * @category constants
 * @since 0.1.0
 */
export const updateTemplateViaPostOperation = RunpodOperationDescriptor.make({
  authenticated: true,
  method: "POST",
  methodName: "updateTemplateViaPost",
  operationId: "UpdateTemplate",
  path: "/templates/{templateId}/update",
  pathParams: ["templateId"],
  queryParams: [],
  requestBody: "json",
  requestBodyRequired: true,
  responseBody: "json",
  status: "200",
});

/**
 * Descriptor for ListNetworkVolumes.
 *
 * **Example** (Read the listNetworkVolumesOperation path)
 *
 * ```ts
 * import { listNetworkVolumesOperation } from "@beep/runpod"
 *
 * console.log(listNetworkVolumesOperation.path)
 * ```
 *
 * @category constants
 * @since 0.1.0
 */
export const listNetworkVolumesOperation = RunpodOperationDescriptor.make({
  authenticated: true,
  method: "GET",
  methodName: "listNetworkVolumes",
  operationId: "ListNetworkVolumes",
  path: "/networkvolumes",
  pathParams: [],
  queryParams: [],
  requestBody: "none",
  requestBodyRequired: false,
  responseBody: "json",
  status: "200",
});

/**
 * Descriptor for CreateNetworkVolume.
 *
 * **Example** (Read the createNetworkVolumeOperation path)
 *
 * ```ts
 * import { createNetworkVolumeOperation } from "@beep/runpod"
 *
 * console.log(createNetworkVolumeOperation.path)
 * ```
 *
 * @category constants
 * @since 0.1.0
 */
export const createNetworkVolumeOperation = RunpodOperationDescriptor.make({
  authenticated: true,
  method: "POST",
  methodName: "createNetworkVolume",
  operationId: "CreateNetworkVolume",
  path: "/networkvolumes",
  pathParams: [],
  queryParams: [],
  requestBody: "json",
  requestBodyRequired: true,
  responseBody: "json",
  status: "200",
});

/**
 * Descriptor for GetNetworkVolume.
 *
 * **Example** (Read the getNetworkVolumeOperation path)
 *
 * ```ts
 * import { getNetworkVolumeOperation } from "@beep/runpod"
 *
 * console.log(getNetworkVolumeOperation.path)
 * ```
 *
 * @category constants
 * @since 0.1.0
 */
export const getNetworkVolumeOperation = RunpodOperationDescriptor.make({
  authenticated: true,
  method: "GET",
  methodName: "getNetworkVolume",
  operationId: "GetNetworkVolume",
  path: "/networkvolumes/{networkVolumeId}",
  pathParams: ["networkVolumeId"],
  queryParams: [],
  requestBody: "none",
  requestBodyRequired: false,
  responseBody: "json",
  status: "200",
});

/**
 * Descriptor for UpdateNetworkVolume.
 *
 * **Example** (Read the updateNetworkVolumeOperation path)
 *
 * ```ts
 * import { updateNetworkVolumeOperation } from "@beep/runpod"
 *
 * console.log(updateNetworkVolumeOperation.path)
 * ```
 *
 * @category constants
 * @since 0.1.0
 */
export const updateNetworkVolumeOperation = RunpodOperationDescriptor.make({
  authenticated: true,
  method: "PATCH",
  methodName: "updateNetworkVolume",
  operationId: "UpdateNetworkVolume",
  path: "/networkvolumes/{networkVolumeId}",
  pathParams: ["networkVolumeId"],
  queryParams: [],
  requestBody: "json",
  requestBodyRequired: true,
  responseBody: "json",
  status: "200",
});

/**
 * Descriptor for DeleteNetworkVolume.
 *
 * **Example** (Read the deleteNetworkVolumeOperation path)
 *
 * ```ts
 * import { deleteNetworkVolumeOperation } from "@beep/runpod"
 *
 * console.log(deleteNetworkVolumeOperation.path)
 * ```
 *
 * @category constants
 * @since 0.1.0
 */
export const deleteNetworkVolumeOperation = RunpodOperationDescriptor.make({
  authenticated: true,
  method: "DELETE",
  methodName: "deleteNetworkVolume",
  operationId: "DeleteNetworkVolume",
  path: "/networkvolumes/{networkVolumeId}",
  pathParams: ["networkVolumeId"],
  queryParams: [],
  requestBody: "none",
  requestBodyRequired: false,
  responseBody: "none",
  status: "204",
});

/**
 * Descriptor for UpdateNetworkVolume.
 *
 * **Example** (Read the updateNetworkVolumeViaPostOperation path)
 *
 * ```ts
 * import { updateNetworkVolumeViaPostOperation } from "@beep/runpod"
 *
 * console.log(updateNetworkVolumeViaPostOperation.path)
 * ```
 *
 * @category constants
 * @since 0.1.0
 */
export const updateNetworkVolumeViaPostOperation =
  RunpodOperationDescriptor.make({
    authenticated: true,
    method: "POST",
    methodName: "updateNetworkVolumeViaPost",
    operationId: "UpdateNetworkVolume",
    path: "/networkvolumes/{networkVolumeId}/update",
    pathParams: ["networkVolumeId"],
    queryParams: [],
    requestBody: "json",
    requestBodyRequired: true,
    responseBody: "json",
    status: "200",
  });

/**
 * Descriptor for ListContainerRegistryAuths.
 *
 * **Example** (Read the listContainerRegistryAuthsOperation path)
 *
 * ```ts
 * import { listContainerRegistryAuthsOperation } from "@beep/runpod"
 *
 * console.log(listContainerRegistryAuthsOperation.path)
 * ```
 *
 * @category constants
 * @since 0.1.0
 */
export const listContainerRegistryAuthsOperation =
  RunpodOperationDescriptor.make({
    authenticated: true,
    method: "GET",
    methodName: "listContainerRegistryAuths",
    operationId: "ListContainerRegistryAuths",
    path: "/containerregistryauth",
    pathParams: [],
    queryParams: [],
    requestBody: "none",
    requestBodyRequired: false,
    responseBody: "json",
    status: "200",
  });

/**
 * Descriptor for CreateContainerRegistryAuth.
 *
 * **Example** (Read the createContainerRegistryAuthOperation path)
 *
 * ```ts
 * import { createContainerRegistryAuthOperation } from "@beep/runpod"
 *
 * console.log(createContainerRegistryAuthOperation.path)
 * ```
 *
 * @category constants
 * @since 0.1.0
 */
export const createContainerRegistryAuthOperation =
  RunpodOperationDescriptor.make({
    authenticated: true,
    method: "POST",
    methodName: "createContainerRegistryAuth",
    operationId: "CreateContainerRegistryAuth",
    path: "/containerregistryauth",
    pathParams: [],
    queryParams: [],
    requestBody: "json",
    requestBodyRequired: true,
    responseBody: "json",
    status: "200",
  });

/**
 * Descriptor for GetContainerRegistryAuth.
 *
 * **Example** (Read the getContainerRegistryAuthOperation path)
 *
 * ```ts
 * import { getContainerRegistryAuthOperation } from "@beep/runpod"
 *
 * console.log(getContainerRegistryAuthOperation.path)
 * ```
 *
 * @category constants
 * @since 0.1.0
 */
export const getContainerRegistryAuthOperation = RunpodOperationDescriptor.make(
  {
    authenticated: true,
    method: "GET",
    methodName: "getContainerRegistryAuth",
    operationId: "GetContainerRegistryAuth",
    path: "/containerregistryauth/{containerRegistryAuthId}",
    pathParams: ["containerRegistryAuthId"],
    queryParams: [],
    requestBody: "none",
    requestBodyRequired: false,
    responseBody: "json",
    status: "200",
  },
);

/**
 * Descriptor for DeleteContainerRegistryAuth.
 *
 * **Example** (Read the deleteContainerRegistryAuthOperation path)
 *
 * ```ts
 * import { deleteContainerRegistryAuthOperation } from "@beep/runpod"
 *
 * console.log(deleteContainerRegistryAuthOperation.path)
 * ```
 *
 * @category constants
 * @since 0.1.0
 */
export const deleteContainerRegistryAuthOperation =
  RunpodOperationDescriptor.make({
    authenticated: true,
    method: "DELETE",
    methodName: "deleteContainerRegistryAuth",
    operationId: "DeleteContainerRegistryAuth",
    path: "/containerregistryauth/{containerRegistryAuthId}",
    pathParams: ["containerRegistryAuthId"],
    queryParams: [],
    requestBody: "none",
    requestBodyRequired: false,
    responseBody: "none",
    status: "204",
  });

/**
 * Descriptor for PodBilling.
 *
 * **Example** (Read the podBillingOperation path)
 *
 * ```ts
 * import { podBillingOperation } from "@beep/runpod"
 *
 * console.log(podBillingOperation.path)
 * ```
 *
 * @category constants
 * @since 0.1.0
 */
export const podBillingOperation = RunpodOperationDescriptor.make({
  authenticated: true,
  method: "GET",
  methodName: "podBilling",
  operationId: "PodBilling",
  path: "/billing/pods",
  pathParams: [],
  queryParams: [
    "bucketSize",
    "endTime",
    "gpuTypeId",
    "grouping",
    "podId",
    "startTime",
  ],
  requestBody: "none",
  requestBodyRequired: false,
  responseBody: "json",
  status: "200",
});

/**
 * Descriptor for EndpointBilling.
 *
 * **Example** (Read the endpointBillingOperation path)
 *
 * ```ts
 * import { endpointBillingOperation } from "@beep/runpod"
 *
 * console.log(endpointBillingOperation.path)
 * ```
 *
 * @category constants
 * @since 0.1.0
 */
export const endpointBillingOperation = RunpodOperationDescriptor.make({
  authenticated: true,
  method: "GET",
  methodName: "endpointBilling",
  operationId: "EndpointBilling",
  path: "/billing/endpoints",
  pathParams: [],
  queryParams: [
    "bucketSize",
    "dataCenterId",
    "endpointId",
    "endTime",
    "gpuTypeId",
    "grouping",
    "imageName",
    "startTime",
    "templateId",
  ],
  requestBody: "none",
  requestBodyRequired: false,
  responseBody: "json",
  status: "200",
});

/**
 * Descriptor for NetworkVolumeBilling.
 *
 * **Example** (Read the networkVolumeBillingOperation path)
 *
 * ```ts
 * import { networkVolumeBillingOperation } from "@beep/runpod"
 *
 * console.log(networkVolumeBillingOperation.path)
 * ```
 *
 * @category constants
 * @since 0.1.0
 */
export const networkVolumeBillingOperation = RunpodOperationDescriptor.make({
  authenticated: true,
  method: "GET",
  methodName: "networkVolumeBilling",
  operationId: "NetworkVolumeBilling",
  path: "/billing/networkvolumes",
  pathParams: [],
  queryParams: ["bucketSize", "endTime", "startTime"],
  requestBody: "none",
  requestBodyRequired: false,
  responseBody: "json",
  status: "200",
});

/**
 * Generated operation spec table for Runpod service construction.
 *
 * **Example** (List the generated operation spec keys)
 *
 * ```ts
 * import { RUNPOD_OPERATION_SPECS } from "@beep/runpod"
 *
 * console.log(Object.keys(RUNPOD_OPERATION_SPECS))
 * ```
 *
 * @category constants
 * @since 0.1.0
 */
export const RUNPOD_OPERATION_SPECS = {
  getOpenAPI: {
    descriptor: getOpenAPIOperation,
    request: GetOpenAPIRequest,
    response: GetOpenAPIStatus200Response,
  },
  getDocs: {
    descriptor: getDocsOperation,
    request: GetDocsRequest,
    response: GetDocsStatus200TextResponse,
  },
  listPods: {
    descriptor: listPodsOperation,
    request: ListPodsRequest,
    response: Models.Pods,
  },
  createPod: {
    descriptor: createPodOperation,
    request: CreatePodRequest,
    response: Models.Pod,
  },
  getPod: {
    descriptor: getPodOperation,
    request: GetPodRequest,
    response: Models.Pod,
  },
  updatePod: {
    descriptor: updatePodOperation,
    request: UpdatePodRequest,
    response: Models.Pod,
  },
  deletePod: {
    descriptor: deletePodOperation,
    request: DeletePodRequest,
  },
  updatePodViaPost: {
    descriptor: updatePodViaPostOperation,
    request: UpdatePodViaPostRequest,
    response: Models.Pod,
  },
  startPod: {
    descriptor: startPodOperation,
    request: StartPodRequest,
  },
  stopPod: {
    descriptor: stopPodOperation,
    request: StopPodRequest,
  },
  resetPod: {
    descriptor: resetPodOperation,
    request: ResetPodRequest,
  },
  restartPod: {
    descriptor: restartPodOperation,
    request: RestartPodRequest,
  },
  listEndpoints: {
    descriptor: listEndpointsOperation,
    request: ListEndpointsRequest,
    response: Models.Endpoints,
  },
  createEndpoint: {
    descriptor: createEndpointOperation,
    request: CreateEndpointRequest,
    response: Models.Endpoint,
  },
  getEndpoint: {
    descriptor: getEndpointOperation,
    request: GetEndpointRequest,
    response: Models.Endpoint,
  },
  updateEndpoint: {
    descriptor: updateEndpointOperation,
    request: UpdateEndpointRequest,
    response: Models.Endpoint,
  },
  deleteEndpoint: {
    descriptor: deleteEndpointOperation,
    request: DeleteEndpointRequest,
  },
  updateEndpointViaPost: {
    descriptor: updateEndpointViaPostOperation,
    request: UpdateEndpointViaPostRequest,
    response: Models.Endpoint,
  },
  listTemplates: {
    descriptor: listTemplatesOperation,
    request: ListTemplatesRequest,
    response: Models.Templates,
  },
  createTemplate: {
    descriptor: createTemplateOperation,
    request: CreateTemplateRequest,
    response: Models.Template,
  },
  getTemplate: {
    descriptor: getTemplateOperation,
    request: GetTemplateRequest,
    response: Models.Template,
  },
  updateTemplate: {
    descriptor: updateTemplateOperation,
    request: UpdateTemplateRequest,
    response: Models.Template,
  },
  deleteTemplate: {
    descriptor: deleteTemplateOperation,
    request: DeleteTemplateRequest,
  },
  updateTemplateViaPost: {
    descriptor: updateTemplateViaPostOperation,
    request: UpdateTemplateViaPostRequest,
    response: Models.Template,
  },
  listNetworkVolumes: {
    descriptor: listNetworkVolumesOperation,
    request: ListNetworkVolumesRequest,
    response: Models.NetworkVolumes,
  },
  createNetworkVolume: {
    descriptor: createNetworkVolumeOperation,
    request: CreateNetworkVolumeRequest,
    response: Models.NetworkVolume,
  },
  getNetworkVolume: {
    descriptor: getNetworkVolumeOperation,
    request: GetNetworkVolumeRequest,
    response: Models.NetworkVolume,
  },
  updateNetworkVolume: {
    descriptor: updateNetworkVolumeOperation,
    request: UpdateNetworkVolumeRequest,
    response: Models.NetworkVolume,
  },
  deleteNetworkVolume: {
    descriptor: deleteNetworkVolumeOperation,
    request: DeleteNetworkVolumeRequest,
  },
  updateNetworkVolumeViaPost: {
    descriptor: updateNetworkVolumeViaPostOperation,
    request: UpdateNetworkVolumeViaPostRequest,
    response: Models.NetworkVolume,
  },
  listContainerRegistryAuths: {
    descriptor: listContainerRegistryAuthsOperation,
    request: ListContainerRegistryAuthsRequest,
    response: Models.ContainerRegistryAuths,
  },
  createContainerRegistryAuth: {
    descriptor: createContainerRegistryAuthOperation,
    request: CreateContainerRegistryAuthRequest,
    response: Models.ContainerRegistryAuth,
  },
  getContainerRegistryAuth: {
    descriptor: getContainerRegistryAuthOperation,
    request: GetContainerRegistryAuthRequest,
    response: Models.ContainerRegistryAuth,
  },
  deleteContainerRegistryAuth: {
    descriptor: deleteContainerRegistryAuthOperation,
    request: DeleteContainerRegistryAuthRequest,
  },
  podBilling: {
    descriptor: podBillingOperation,
    request: PodBillingRequest,
    response: Models.BillingRecords,
  },
  endpointBilling: {
    descriptor: endpointBillingOperation,
    request: EndpointBillingRequest,
    response: Models.BillingRecords,
  },
  networkVolumeBilling: {
    descriptor: networkVolumeBillingOperation,
    request: NetworkVolumeBillingRequest,
    response: Models.NetworkVolumeBillingRecords,
  },
};

/**
 * Typed method surface generated from Runpod REST API v1.
 *
 * **Example** (Reference the RunpodOperationsShape type)
 *
 * ```ts
 * import type { RunpodOperationsShape } from "@beep/runpod"
 *
 * type Operations = RunpodOperationsShape<never>
 * ```
 *
 * @category services
 * @since 0.1.0
 */
export interface RunpodOperationsShape<E> {
  readonly getOpenAPI: (
    request?: GetOpenAPIRequest,
  ) => Effect.Effect<GetOpenAPIStatus200Response, E>;
  readonly getDocs: (request?: GetDocsRequest) => Effect.Effect<string, E>;
  readonly listPods: (
    request?: ListPodsRequest,
  ) => Effect.Effect<Models.Pods, E>;
  readonly createPod: (
    request: CreatePodRequest,
  ) => Effect.Effect<Models.Pod, E>;
  readonly getPod: (request: GetPodRequest) => Effect.Effect<Models.Pod, E>;
  readonly updatePod: (
    request: UpdatePodRequest,
  ) => Effect.Effect<Models.Pod, E>;
  readonly deletePod: (request: DeletePodRequest) => Effect.Effect<void, E>;
  readonly updatePodViaPost: (
    request: UpdatePodViaPostRequest,
  ) => Effect.Effect<Models.Pod, E>;
  readonly startPod: (request: StartPodRequest) => Effect.Effect<void, E>;
  readonly stopPod: (request: StopPodRequest) => Effect.Effect<void, E>;
  readonly resetPod: (request: ResetPodRequest) => Effect.Effect<void, E>;
  readonly restartPod: (request: RestartPodRequest) => Effect.Effect<void, E>;
  readonly listEndpoints: (
    request?: ListEndpointsRequest,
  ) => Effect.Effect<Models.Endpoints, E>;
  readonly createEndpoint: (
    request: CreateEndpointRequest,
  ) => Effect.Effect<Models.Endpoint, E>;
  readonly getEndpoint: (
    request: GetEndpointRequest,
  ) => Effect.Effect<Models.Endpoint, E>;
  readonly updateEndpoint: (
    request: UpdateEndpointRequest,
  ) => Effect.Effect<Models.Endpoint, E>;
  readonly deleteEndpoint: (
    request: DeleteEndpointRequest,
  ) => Effect.Effect<void, E>;
  readonly updateEndpointViaPost: (
    request: UpdateEndpointViaPostRequest,
  ) => Effect.Effect<Models.Endpoint, E>;
  readonly listTemplates: (
    request?: ListTemplatesRequest,
  ) => Effect.Effect<Models.Templates, E>;
  readonly createTemplate: (
    request: CreateTemplateRequest,
  ) => Effect.Effect<Models.Template, E>;
  readonly getTemplate: (
    request: GetTemplateRequest,
  ) => Effect.Effect<Models.Template, E>;
  readonly updateTemplate: (
    request: UpdateTemplateRequest,
  ) => Effect.Effect<Models.Template, E>;
  readonly deleteTemplate: (
    request: DeleteTemplateRequest,
  ) => Effect.Effect<void, E>;
  readonly updateTemplateViaPost: (
    request: UpdateTemplateViaPostRequest,
  ) => Effect.Effect<Models.Template, E>;
  readonly listNetworkVolumes: (
    request?: ListNetworkVolumesRequest,
  ) => Effect.Effect<Models.NetworkVolumes, E>;
  readonly createNetworkVolume: (
    request: CreateNetworkVolumeRequest,
  ) => Effect.Effect<Models.NetworkVolume, E>;
  readonly getNetworkVolume: (
    request: GetNetworkVolumeRequest,
  ) => Effect.Effect<Models.NetworkVolume, E>;
  readonly updateNetworkVolume: (
    request: UpdateNetworkVolumeRequest,
  ) => Effect.Effect<Models.NetworkVolume, E>;
  readonly deleteNetworkVolume: (
    request: DeleteNetworkVolumeRequest,
  ) => Effect.Effect<void, E>;
  readonly updateNetworkVolumeViaPost: (
    request: UpdateNetworkVolumeViaPostRequest,
  ) => Effect.Effect<Models.NetworkVolume, E>;
  readonly listContainerRegistryAuths: (
    request?: ListContainerRegistryAuthsRequest,
  ) => Effect.Effect<Models.ContainerRegistryAuths, E>;
  readonly createContainerRegistryAuth: (
    request: CreateContainerRegistryAuthRequest,
  ) => Effect.Effect<Models.ContainerRegistryAuth, E>;
  readonly getContainerRegistryAuth: (
    request: GetContainerRegistryAuthRequest,
  ) => Effect.Effect<Models.ContainerRegistryAuth, E>;
  readonly deleteContainerRegistryAuth: (
    request: DeleteContainerRegistryAuthRequest,
  ) => Effect.Effect<void, E>;
  readonly podBilling: (
    request?: PodBillingRequest,
  ) => Effect.Effect<Models.BillingRecords, E>;
  readonly endpointBilling: (
    request?: EndpointBillingRequest,
  ) => Effect.Effect<Models.BillingRecords, E>;
  readonly networkVolumeBilling: (
    request?: NetworkVolumeBillingRequest,
  ) => Effect.Effect<Models.NetworkVolumeBillingRecords, E>;
}
