// Structural JSONC modification: compute the edits needed to set, replace or
// delete a value at a path, without mutating the source.
//
// Navigation goes through the scanner-based `internal/navigate.ts`; this
// module owns only edit synthesis and the `JsoncModificationError` it raises
// on a navigation miss.
import { $ScratchpadId } from "@beep/identity/packages";
import * as R from "effect/Record";
import * as A from "effect/Array";
import * as Effect from "effect/Effect";
import * as O from "effect/Option";
import * as P from "effect/Predicate";
import * as S from "effect/Schema";
import * as Str from "effect/String";
import { navigate, NavigateContainer, NavigateResult } from "./internal/navigate.ts";
import {
  Jsonc,
  type JsoncStringifyError,
  JsoncStringifyOptions,
} from "./Jsonc.ts";
import {
  JsoncEdit,
  JsoncFormattingOptions,
  JsoncFormattingOptionsLike,
} from "./JsoncEdit.ts";
import { JsoncPath } from "./JsoncNode.ts";

const $I = $ScratchpadId.create("effected/jsonc/JsoncModifier");

/**
 * Raised when `JsoncModifier.modify` cannot navigate the requested path: the
 * value at `depth` is not the container kind the next segment requires.
 *
 * **Details**
 *
 * - `path`: the full path passed to `JsoncModifier.modify`.
 * - `expected`: the container kind the segment at `depth` required.
 * - `depth`: the 1-based index into `path` where navigation failed.
 * - `offset`: reserved for a source-position annotation. `modify` reports the
 *   mismatch structurally and never sets it; when present, the message names it.
 *
 * The mismatch is carried as typed fields rather than a prose reason.
 *
 * **Example** (Inspect a structural mismatch)
 *
 * ```ts
 * import * as Effect from "effect/Effect"
 * import { JsoncModifier } from "@beep/scratchpad/effected/jsonc/index"
 *
 * const error = Effect.runSync(Effect.flip(JsoncModifier.modify('{ "a": 1 }', ["a", "b"], 2)))
 *
 * console.log(error._tag) // "JsoncModificationError"
 * console.log(error.message) // "Modification failed at path [a, b]: expected object at depth 2"
 * ```
 *
 * @category errors
 * @since 0.0.0
 */
export class JsoncModificationError extends S.TaggedError<JsoncModificationError>($I.make("JsoncModificationError"))(
  "JsoncModificationError",
  {
    path: JsoncPath,
    expected: NavigateContainer,
    depth: S.Natural,
    offset: S.optionalKey(S.Finite),
  },
  $I.annoteError<JsoncModificationError>("JsoncModificationError", {
    description: "A path could not be navigated because a value was not the required container kind.",
  }),
) {
  /**
   * Render the path, the optional source offset, the expected container kind
   * and the failing depth.
   *
   * **Example** (Read the rendered message)
   *
   * ```ts
   * import { JsoncModificationError } from "@beep/scratchpad/effected/jsonc/index"
   *
   * const error = JsoncModificationError.make({ path: ["a", 0], expected: "array", depth: 2 })
   * const located = JsoncModificationError.make({ path: ["a", 0], expected: "array", depth: 2, offset: 7 })
   *
   * console.log(error.message) // "Modification failed at path [a, 0]: expected array at depth 2"
   * console.log(located.message) // "Modification failed at path [a, 0] (offset 7): expected array at depth 2"
   * ```
   */
  override get message(): string {
    const at = O.match(O.fromUndefinedOr(this.offset), {
      onNone: () => Str.empty,
      onSome: (offset) => ` (offset ${offset})`,
    });
    return `Modification failed at path [${A.join(A.map(this.path, String), ", ")}]${at}: expected ${this.expected} at depth ${this.depth}`;
  }
}

/**
 * Options for `JsoncModifier.modify`: formatting controls for generated text.
 *
 * **Details**
 *
 * `formattingOptions` accepts a {@link JsoncFormattingOptions} instance or a
 * plain literal; only `tabSize`, `insertSpaces` and `eol` affect generated
 * content. Modelled as a struct so callers pass a literal at the boundary.
 *
 * **Example** (Insert with tabs)
 *
 * ```ts
 * import * as Effect from "effect/Effect"
 * import { JsoncEdit, JsoncModifier } from "@beep/scratchpad/effected/jsonc/index"
 *
 * const edits = Effect.runSync(JsoncModifier.modify("{}", ["a"], { b: 1 }, { formattingOptions: { insertSpaces: false } }))
 *
 * console.log(JsoncEdit.applyAll("{}", edits)) // '{\n\t"a": {\n\t\t"b": 1\n\t}\n}'
 * ```
 *
 * @category schemas
 * @since 0.0.0
 */
export const JsoncModifyOptions = S.Struct({
  formattingOptions: S.optionalKey(JsoncFormattingOptionsLike),
}).pipe(
  $I.annoteSchema("JsoncModifyOptions", {
    description: "Formatting controls for content generated by JsoncModifier.modify.",
  }),
);

/**
 * The decoded shape of {@link JsoncModifyOptions}.
 *
 * @see {@link JsoncModifyOptions} for the runtime schema.
 * @category type-level
 * @since 0.0.0
 */
export type JsoncModifyOptions = typeof JsoncModifyOptions.Type;

const edits = (...items: ReadonlyArray<JsoncEdit>): ReadonlyArray<JsoncEdit> => items;

type Modify = Effect.Effect<ReadonlyArray<JsoncEdit>, JsoncStringifyError | JsoncModificationError>;

/**
 * Sets, replaces or deletes a value at a path in JSONC text, as byte-minimal
 * edits that leave comments and formatting elsewhere untouched. Not
 * instantiable.
 *
 * **Example** (Change one value and keep the comment)
 *
 * ```ts
 * import * as Effect from "effect/Effect"
 * import { JsoncEdit, JsoncModifier } from "@beep/scratchpad/effected/jsonc/index"
 *
 * const text = '{\n  // dev port\n  "port": 3000\n}'
 * const edits = Effect.runSync(JsoncModifier.modify(text, ["port"], 8080))
 *
 * console.log(JsoncEdit.applyAll(text, edits)) // '{\n  // dev port\n  "port": 8080\n}'
 * ```
 *
 * @category services
 * @since 0.0.0
 */
export abstract class JsoncModifier {
  /**
   * Compute the edits that set, replace or delete `value` at `path` in `text`.
   *
   * **Details**
   *
   * Passing `value === undefined` deletes the target property or element,
   * including its surrounding comma. A missing insertion target appends after
   * the last property or element, with multi-line values re-indented to the
   * insertion depth. Line breaks inside a generated value stay `\n`, as
   * `JSON.stringify` writes them; the configured `eol` applies only to the
   * line breaks around an inserted entry. The empty path replaces the whole
   * document.
   * Fails with {@link JsoncModificationError} on a structural mismatch and
   * with `JsoncStringifyError` when `value` cannot be serialized.
   *
   * @param text - The JSONC source to modify.
   * @param path - The location to set, replace or delete.
   * @param value - The plain JavaScript value to write; `undefined` deletes.
   * @param options - Formatting controls for generated content.
   * @returns The edits to apply with `JsoncEdit.applyAll`.
   */
  static readonly modify = Effect.fn("JsoncModifier.modify")(function* (
    text: string,
    path: JsoncPath,
    value: unknown,
    options?: JsoncModifyOptions,
  ) {
    const fmt = JsoncFormattingOptions.make(options?.formattingOptions ?? R.empty());
    const indentUnit = fmt.insertSpaces ? Str.repeat(fmt.tabSize)(" ") : "\t";
    const stringifyOptions = JsoncStringifyOptions.make({
      tabSize: fmt.tabSize,
      insertSpaces: fmt.insertSpaces,
    });
    const serialize = (): Effect.Effect<string, JsoncStringifyError> => Jsonc.stringify(value, stringifyOptions);
    const deleting = P.isUndefined(value);

    if (!A.isReadonlyArrayNonEmpty(path)) {
      const content = deleting ? Str.empty : yield* serialize();
      return edits(JsoncEdit.make({ offset: 0, length: text.length, content }));
    }

    return yield* NavigateResult.match(navigate(text, path), {
      Mismatch: (
        {
          depth,
          expected,
        }): Modify => Effect.fail(JsoncModificationError.make({
        path,
        expected,
        depth,
      })),
      NoOp: (): Modify => Effect.succeed(edits()),
      Located: (located): Modify => {
        if (!deleting) {
          return Effect.map(serialize(), (content) =>
            edits(JsoncEdit.make({
              offset: located.valueStart,
              length: located.valueEnd - located.valueStart,
              content,
            })),
          );
        }
        // Comma positions come from scanner tokens, never from searching the
        // raw text, so commas inside comments are invisible here. The entry
        // takes its preceding comma with it, or its following comma when it
        // is the first entry.
        const removeStart = O.getOrElse(located.commaBefore, () => located.keyStart);
        const removeEnd =
          O.isNone(located.commaBefore) && O.isSome(located.commaAfter) ? located.commaAfter.value + 1 : located.valueEnd;
        return Effect.succeed(edits(JsoncEdit.make({
          offset: removeStart,
          length: removeEnd - removeStart,
          content: "",
        })));
      },
      Insert: (insert): Modify =>
        deleting
          ? Effect.succeed(edits())
          : Effect.gen(function* () {
            const indent = Str.repeat(insert.depth)(indentUnit);
            const outdent = Str.repeat(insert.depth - 1)(indentUnit);
            // Generated multi-line values are re-indented to the insertion
            // depth so a nested object lands at the same column as its siblings.
            // The value keeps JSON.stringify's own "\n" line breaks (upstream);
            // `eol` belongs to the wrapper around the entry only.
            const serialized = Str.replaceAll("\n", `\n${indent}`)(yield* serialize());
            const entry =
              NavigateContainer.is.object(insert.container)
                ? `${yield* Jsonc.stringify(String(A.lastNonEmpty(path)))}: ${serialized}`
                : serialized;
            const content = insert.isFirst ? `${fmt.eol}${indent}${entry}${fmt.eol}${outdent}` : `,${fmt.eol}${indent}${entry}`;
            return edits(JsoncEdit.make({
              offset: insert.at,
              length: 0,
              content,
            }));
          }),
    });
  });
}
