/**
 * The demand-scoped Box SDK manager surface generated by `scripts/generate.ts`.
 *
 * `@beep/box` wraps only the SDK managers this repo actually calls, not the full
 * 85-manager `BoxClient` surface. The full surface costs ~4.8M TypeScript type
 * instantiations in `_generated/Box.models.gen.ts` alone, which is the mass that
 * keeps exposing the no-location TS2589 native-compiler flake in full proofs.
 *
 * See `goals/box-typecheck-cost/SPEC.md` for the decisions this file implements.
 *
 * ## Adding a manager
 *
 * 1. Add its `BoxClient` property name below, keeping the list sorted.
 * 2. Run `bun run generate` from `packages/drivers/box`.
 * 3. Re-measure per `goals/box-typecheck-cost/research/measurements.md` and
 *    record the numbers in the PR. Budget: `750K` marginal instantiations for
 *    any single generated file (total minus the schema-import floor, currently
 *    ~1.65M) and `3M` absolute package-wide.
 *
 * A manager outside this list has no generated operations, so calling it is a
 * compile error rather than a runtime failure.
 *
 * @packageDocumentation
 * @since 0.0.0
 */

/**
 * `BoxClient` manager property names wrapped as generated JSON operations.
 *
 * Each entry names the demand that keeps it: removing a manager whose demand
 * disappears is as valid as adding one, and both require a re-measurement.
 *
 * **Example** (Filter discovered managers to the wrapped surface)
 *
 * ```ts
 * import { GENERATED_MANAGERS } from "./box.surface.ts"
 * import * as A from "effect/Array"
 * import * as MutableHashSet from "effect/MutableHashSet"
 *
 * // How `generate.ts` filters the SDK's 85 `BoxClient` managers down to the
 * // wrapped surface, and reports what it dropped.
 * const allowed = MutableHashSet.fromIterable(GENERATED_MANAGERS)
 * const discovered = ["files", "folders", "retentionPolicies"]
 *
 * const wrapped = A.filter(discovered, (name) => MutableHashSet.has(allowed, name))
 * const dropped = A.filter(discovered, (name) => !MutableHashSet.has(allowed, name))
 *
 * console.log(wrapped) // ["files", "folders"]
 * console.log(dropped) // ["retentionPolicies"]
 * ```
 *
 * @category constants
 * @since 0.0.0
 */
export const GENERATED_MANAGERS: ReadonlyArray<string> = [
  // Box.streaming.ts — getUserAvatar / createUserAvatar payload + success models.
  "avatars",
  // Box.streaming.ts — chunked upload session lifecycle.
  "chunkedUploads",
  // Box.streaming.ts — byte downloads; test surface.
  "downloads",
  // DmsMirrorBox.ts (event polling); Box.streaming.ts (event stream); tests.
  "events",
  // DmsMirrorBox.ts (file metadata, move, delete); Box.streaming.ts thumbnails.
  "files",
  // DmsMirrorBox.ts (ensure/rename/move folder, list items).
  "folders",
  // DmsMirrorBox.ts (upload, upload new version); Box.streaming.ts; tests.
  "uploads",
  // goals/box-driver `live-smokes-read-only`: users.getUserMe is the live probe.
  "users",
  // Box.streaming.ts — zip download request/status models.
  "zipDownloads",
];
