/**
 * The demand-scoped Box SDK manager surface generated by `scripts/generate.ts`.
 *
 * `@beep/box` wraps only the SDK operations this repo actually calls, not the
 * full 86-manager installed `BoxClient` surface. The full surface costs ~4.8M TypeScript type
 * instantiations in `_generated/Box.models.gen.ts` alone, which is the mass that
 * keeps exposing the no-location TS2589 native-compiler flake in full proofs.
 *
 * See `goals/box-typecheck-cost/SPEC.md` for the decisions this file implements.
 *
 * ## Adding demand
 *
 * 1. Add a full `BoxClient` property name or an individual `manager.method`
 *    name below, keeping the selected list sorted by manager.
 * 2. Run `bun run generate` from `packages/drivers/box`.
 * 3. Re-measure per `goals/box-typecheck-cost/research/measurements.md` and
 *    record the numbers in the PR. Budget: `750K` marginal instantiations for
 *    any single generated file (total minus the schema-import floor, currently
 *    ~1.65M) and `3M` absolute package-wide.
 *
 * A method outside both lists has no generated operation, so calling it is a
 * compile error rather than a runtime failure.
 *
 * @packageDocumentation
 * @since 0.0.0
 */

/**
 * `BoxClient` manager property names wrapped as generated JSON operations.
 *
 * Each entry names the demand that keeps it: removing a manager whose demand
 * disappears is as valid as adding one, and both require a re-measurement.
 *
 * **Example** (Filter discovered managers to the wrapped surface)
 *
 * ```ts
 * import { GENERATED_MANAGERS } from "./box.surface.ts"
 * import * as A from "effect/Array"
 * import * as MutableHashSet from "effect/MutableHashSet"
 *
 * // How `generate.ts` filters the SDK's 85 `BoxClient` managers down to the
 * // wrapped surface, and reports what it dropped.
 * const allowed = MutableHashSet.fromIterable(GENERATED_MANAGERS)
 * const discovered = ["files", "folders", "retentionPolicies"]
 *
 * const wrapped = A.filter(discovered, (name) => MutableHashSet.has(allowed, name))
 * const dropped = A.filter(discovered, (name) => !MutableHashSet.has(allowed, name))
 *
 * console.log(wrapped) // ["files", "folders"]
 * console.log(dropped) // ["retentionPolicies"]
 * ```
 *
 * @category constants
 * @since 0.0.0
 */
export const GENERATED_MANAGERS: ReadonlyArray<string> = [
  // Box.streaming.ts — getUserAvatar / createUserAvatar payload + success models.
  "avatars",
  // Box.streaming.ts — chunked upload session lifecycle.
  "chunkedUploads",
  // Box.streaming.ts — byte downloads; test surface.
  "downloads",
  // DmsMirrorBox.ts (event polling); Box.streaming.ts (event stream); tests.
  "events",
  // DmsMirrorBox.ts (file metadata, move, delete); Box.streaming.ts thumbnails.
  "files",
  // DmsMirrorBox.ts (ensure/rename/move folder, list items).
  "folders",
  // practice-box-provisioning — inventory collaborations attached to folders.
  "listCollaborations",
  // DmsMirrorBox.ts (upload, upload new version); Box.streaming.ts; tests.
  "uploads",
  // practice-box-provisioning — create, inspect, update, and remove collaborations.
  "userCollaborations",
  // goals/box-driver `live-smokes-read-only`: users.getUserMe is the live probe.
  "users",
  // practice-box-provisioning — discover and manage V2 webhooks.
  "webhooks",
  // Box.streaming.ts — zip download request/status models.
  "zipDownloads",
];

/**
 * Individual Box SDK operations admitted without wrapping their whole manager.
 *
 * Use this surface for manager families whose unused operations would exceed
 * the type-instantiation budget or publish mutations that the current product
 * entitlement deliberately blocks. Entries use `manager.method` names from
 * the installed SDK declarations.
 *
 * **Example** (Check an individually admitted operation)
 *
 * ```ts
 * import { GENERATED_OPERATIONS } from "./box.surface.ts"
 * import * as A from "effect/Array"
 *
 * const admitsRetentionReads = A.contains(
 *   GENERATED_OPERATIONS,
 *   "retentionPolicies.getRetentionPolicies"
 * )
 *
 * console.log(admitsRetentionReads) // true
 * ```
 *
 * @category constants
 * @since 0.0.0
 */
export const GENERATED_OPERATIONS: ReadonlyArray<string> = [
  // practice-box-provisioning — metadata and retention discovery only on Business.
  "folderMetadata.getFolderMetadata",
  "folderMetadata.getFolderMetadataById",
  "metadataCascadePolicies.getMetadataCascadePolicies",
  "metadataCascadePolicies.getMetadataCascadePolicyById",
  "metadataTemplates.getEnterpriseMetadataTemplates",
  "metadataTemplates.getGlobalMetadataTemplates",
  "metadataTemplates.getMetadataTemplate",
  "metadataTemplates.getMetadataTemplateById",
  "metadataTemplates.getMetadataTemplatesByInstanceId",
  "retentionPolicies.getRetentionPolicies",
  "retentionPolicies.getRetentionPolicyById",
  "retentionPolicyAssignments.getFilesUnderRetentionPolicyAssignment",
  "retentionPolicyAssignments.getRetentionPolicyAssignmentById",
  "retentionPolicyAssignments.getRetentionPolicyAssignments",
  // practice-box-provisioning — Box Sign's complete request/template manager surface.
  "signRequests.cancelSignRequest",
  "signRequests.createSignRequest",
  "signRequests.getSignRequestById",
  "signRequests.getSignRequests",
  "signRequests.resendSignRequest",
  "signTemplates.getSignTemplateById",
  "signTemplates.getSignTemplates",
];
