"""build_ledger_docket — classify all 104 LEDGER entries under the four-ruling
policy the steward approved 2026-08-30 (DECISIONS.md, S5 sitting 3):

  run-2-obligation    subject vocabulary parked, or the suggestion needs the
                      runtime corpus / a CQ-suite extension
  standing-constraint keep-domains-distinct / no-alignment-without-mapping —
                      binds the S5 taxonomy assembly
  taxonomy-input      parameterization facts about ACCEPTED terms — fed to the
                      seat round and the gate via CONSTRAINTS.yaml
  moot                the subject was rejected as A-Box material

Deterministic and reviewable: ordered rules + an explicit override table (the
steward-flagged six and any hand-corrections). Emits LEDGER-DOCKET.yaml and
CONSTRAINTS.yaml. Run: uv run --with pyyaml python build_ledger_docket.py
"""
import re
from pathlib import Path

import yaml

S5 = Path(__file__).resolve().parents[1]
S4 = S5.parent / "s4"
BC = S4 / "beep-ci-ops"

# Steward rulings for the flagged six (sitting 3, approved verbatim).
OVERRIDES = {
    "fallow-laws-I02": ("standing-constraint",
                        "result-attribution scope != execution scope binds every hasScope assertion"),
    "literalkits-I04": ("standing-constraint",
                        "FallowQualityFeatureFamily and FallowFeatureFamily stay separate source domains; "
                        "matrix-row denotation is a named run-2 leg"),
    "turbo-tasks-I04": ("run-2-obligation", "future-flag denotation needs the pinned Turbo schema corpus"),
    "turbo-tasks-I01": ("run-2-obligation", "task-vs-VerificationLane proof needs yeet/CI runtime use"),
    "fallow-laws-I01": ("run-2-obligation", "ScriptLane/CollectedGateLane facts ratify against runtime corpus"),
    "literalkits-I08": ("run-2-obligation", "environment bearer model only if run-2 cost calibration requires it"),
    # census/topology subjects were rejected as A-Box ETL material (sitting 1b/2d)
    "package-topology-I05": ("moot", "numeric topology indexes belong to the rejected A-Box census"),
}


def main() -> None:
    ledger = yaml.safe_load((S4 / "LEDGER.yaml").read_text())
    ratified = set()
    for f in sorted((BC / "work/proposals").glob("otp-*.yaml")):
        if "review" in f.name:
            continue
        ratified.add(yaml.safe_load(f.read_text())["term"]["local_name"])
    # accepted candidate spellings too (join buckets accepted-via)
    join = yaml.safe_load((S5 / "JOIN.yaml").read_text())
    for r in join["rows"]:
        if r["bucket"] in ("accepted-via", "leaf-of-ratified-domain"):
            ratified.add(r["candidate"])
    token = re.compile(r"[A-Za-z][A-Za-z0-9]+")

    def mentions_accepted(text: str) -> list:
        return sorted({t for t in token.findall(text) if t in ratified})

    rows, constraints = [], []
    for e in ledger:
        eid, kind = e["id"], e["kind"]
        sugg = (e.get("suggested_disposition") or "")
        low = sugg.lower()
        if eid in OVERRIDES:
            ruling, reason = OVERRIDES[eid]
        elif kind == "missing-cq":
            ruling, reason = "run-2-obligation", "CQ-suite extension is run-2 S2 authority; the suggestion becomes a named CQ obligation"
        elif ("distinct" in low or "separate" in low) and ("keep" in low or "preserve" in low or "source domain" in low):
            ruling, reason = "standing-constraint", "source domains stay distinct (sittings 1a/2c precedent)"
        elif "mapping" in low or "alignment" in low:
            ruling, reason = "standing-constraint", "no cross-domain alignment without an explicit steward-ratified mapping"
        else:
            hits = mentions_accepted(e.get("claim", "") + " " + sugg)
            if hits:
                ruling, reason = "taxonomy-input", f"parameterization fact about accepted term(s): {', '.join(hits[:4])}"
            else:
                ruling, reason = "run-2-obligation", "subject vocabulary is parked; the suggestion joins the run-2 queue"
        row = {"id": eid, "kind": kind, "ruling": ruling, "reason": reason}
        rows.append(row)
        if ruling in ("standing-constraint", "taxonomy-input"):
            constraints.append({
                "id": f"con:{eid}", "source": eid, "class": ruling,
                "text": sugg or e.get("claim", ""),
            })
    counts = {}
    for r in rows:
        counts[r["ruling"]] = counts.get(r["ruling"], 0) + 1
    header = ("# GENERATED by scripts/build_ledger_docket.py — do not hand-edit.\n"
              "# Policy: DECISIONS.md 2026-08-30 S5 sitting 3 (four rulings).\n")
    (S5 / "LEDGER-DOCKET.yaml").write_text(header + yaml.safe_dump(
        {"generated_by": "scripts/build_ledger_docket.py", "entry_count": len(rows),
         "ruling_counts": dict(sorted(counts.items())), "rows": rows},
        sort_keys=False, allow_unicode=True, width=100))
    (S5 / "CONSTRAINTS.yaml").write_text(header + yaml.safe_dump(
        {"generated_by": "scripts/build_ledger_docket.py", "constraint_count": len(constraints),
         "constraints": constraints}, sort_keys=False, allow_unicode=True, width=100))
    print(f"docket: {len(rows)} entries -> {counts}; constraints: {len(constraints)}")


if __name__ == "__main__":
    main()
