"""join_s4b — the S5 mechanical join pass (s5-taxonomy-contract.md §3.1).

Deterministically buckets every S4 candidate against the ratified §4b outcome
surface. Exact normalized-name joins to ratified term local names and
source-domain joins to ratified domains ONLY — merge pairings are steward
rulings and are never guessed here. Output: ontology/extraction/s5/JOIN.yaml,
one row per candidate, totality asserted.

Run: uv run --with pyyaml python join_s4b.py
"""
import collections
import re
from pathlib import Path

import yaml

S5 = Path(__file__).resolve().parents[1]
S4 = S5.parent / "s4"
BC = S4 / "beep-ci-ops"

norm = lambda s: re.sub(r"[^a-z0-9]", "", str(s).lower())


def main() -> None:
    cands = yaml.safe_load((S4 / "CANDIDATES.yaml").read_text())
    rat_by_otp = {}
    for f in sorted((BC / "governance/ratifications").glob("rat-*.yaml")):
        d = yaml.safe_load(f.read_text())
        rat_by_otp[d["proposal_ref"]] = f.stem
    term_index = {}
    for f in sorted((BC / "work/proposals").glob("otp-*.yaml")):
        if "review" in f.name:
            continue
        d = yaml.safe_load(f.read_text())
        term_index[norm(d["term"]["local_name"])] = {
            "term": d["term"]["local_name"],
            "otp": d["id"],
            "rat": rat_by_otp[d["id"]],
        }
    rows, counts = [], collections.Counter()
    for c in cands:
        key = norm(c["candidate"])
        row = {"candidate": c["candidate"], "kind": c["kind"],
               "admission_kind": c.get("admission_kind")}
        if key in term_index:
            hit = term_index[key]
            row |= {"bucket": "accepted-via", "term": hit["term"], "join_ref": hit["rat"]}
        elif c["kind"] == "literal-domain-member" and norm(c.get("source_domain", "")) in term_index:
            hit = term_index[norm(c["source_domain"])]
            row |= {"bucket": "leaf-of-ratified-domain", "term": hit["term"], "join_ref": hit["rat"]}
        else:
            row |= {"bucket": "open"}
            if c["kind"] == "literal-domain-member":
                row["source_domain"] = c.get("source_domain")
        rows.append(row)
        counts[row["bucket"]] += 1
    assert len(rows) == len(cands), "totality: one row per candidate"
    out = {
        "generated_by": "scripts/join_s4b.py",
        "contract": "ontology/docs/s5-taxonomy-contract.md",
        "candidate_count": len(rows),
        "bucket_counts": dict(sorted(counts.items())),
        "rows": rows,
    }
    (S5 / "JOIN.yaml").write_text(
        "# GENERATED by scripts/join_s4b.py — do not hand-edit. Contract:\n"
        "# s5-taxonomy-contract.md §2. Steward rulings land in DISPOSITIONS.yaml.\n"
        + yaml.safe_dump(out, sort_keys=False, allow_unicode=True, width=100))
    print(f"join_s4b: {len(rows)} rows -> {dict(counts)}")


if __name__ == "__main__":
    main()
