import { fcRuns } from "@beep/fc-runs/FastCheckRuns";
import { assert, it } from "@effect/vitest";
import * as Arbitrary from "effect/Arbitrary";
import * as Effect from "effect/Effect";
import * as S from "effect/Schema";
import type { Counter } from "../../../effected/cli/Doc.ts";
import { columnLabel, counterLabel, countsTableOf, totalOf, visibleCountersOf } from "../../../effected/cli/internal/counts.ts";
const runs = { arbitrary: fcRuns(100) };
const count = S.Int.check(S.isBetween({ minimum: 0, maximum: 100000 }));
const counter = (n: number): Counter => ({ key: "repos", label: { one: "repo", other: "repos" }, n, status: { name: "ok", def: { glyph: "+", ascii: "+", token: "success", rank: 0 } } });
it.effect.prop("counter labels preserve singular/plural semantics and number cells round-trip", [Arbitrary.schema(count)], ([n]) => Effect.sync(() => {
  const c = counter(n);
  assert.strictEqual(counterLabel(c), n === 1 ? "repo" : "repos");
  assert.strictEqual(counterLabel(n)(c), counterLabel(c));
  assert.strictEqual(columnLabel(c), "repos");
  const block = { _tag: "Counts" as const, layout: "inline" as const, counters: [c] };
  assert.strictEqual(totalOf(block), n);
  const visible = visibleCountersOf(block);
  assert.deepStrictEqual(visible, n === 0 ? [] : [c]);
  assert.deepStrictEqual(visibleCountersOf({ ...block, counters: visible }), visible);
  const table = countsTableOf({ _tag: "CountsTable", rows: [{ label: [], counters: [c] }] });
  assert.deepStrictEqual(table.rows, [[[], [{ _tag: "Text", value: String(n), token: "success" }]]]);
  assert.strictEqual(Number(String(n)), n);
  assert.deepStrictEqual(countsTableOf({ _tag: "CountsTable", rows: [{ label: [], counters: [counter(Number(String(n)))] }] }), table);
}), runs);
